### ISSUE TITLE
Multiple tabs support on iPhone / iPad

### ISSUE THREAD

**Issue by snk33** [isontheline/pro.webssh.net#101]
Like Terminal native App on MacOS, multiple tabs support would be very nice to have, especially when using app on iPad.

Specs :
- tab name : hostname of server
- add tab : a "+" menu button, a keyboard shortcut Cmd + T would be awesome too
- switch between tab : single tap on tab and a gesture like 3 fingers + left/right (like I use on MacOS)

I often use the app on my iPad when I do not want to go back to my Mac, the app is very nice to use and would be close to perfection for my daily usage (as Linux sysadmin).
It could even justify some in-app purchase for this feature only (like some other apps) :)

PS : À dispo afin d'en discuter plus longuement si besoin d'éclaircir !

**Comment by isontheline** [comment]
Bonjour @snk33 de Bordeaux !

You're right it could be a great addition 😁

[Termius](https://apps.apple.com/us/app/termius-ssh-client/id549039908) also use tabs :
![image](https://user-images.githubusercontent.com/44212923/98987196-3b5f0500-2526-11eb-8e9f-0fa96faff1ae.png)

I dislike "tabs" because at least 2 rows are used and thus this is 2 lines less for the terminal 😕

Right now WebSSH supports multiple "windows" (when enabled in settings : "Allow multiple features at the same time") but to use it we need to exit fullscreen 😕

@snk33 and folks, what would be the best solution?
* Enable tabs like Termius?
* Enable "Allow multiple features at the same time" even in fullscreen mode?
* Another ideas?

Merci encore pour votre issue @snk33🇫🇷

**Comment by snk33** [comment]
I would say the best approach would be like MacOS Terminal app :
- only one tab opened -> no tab menu on top (so maximum space for a single session)
- multiple tabs -> tabs with title

The tab name doesn’t have to be big, just need to distinguish tab names to be able to switch to the desired one easily.

Height would be an issue when using virtual keyboard, I don’t think it would be a problem when using an iPad Pro with Magic Keyboard (or any bluetooth keyboard).

Termius does it quite right but the rest of the App is just full of useless features, with an expensive monthly fee, which is quite another philosophy than WebSSH and finally WebSSH does the SSH part much better (better visibility, better support of Mac layout, easy menu, etc).

For me having multiple tabs with gesture switch is app killer for power users like me that love to do parallel tasks : 
- parallel sessions on the same server (like htop on one, typing command on another one)
- parallel sessions on servers that work together (ex : web / sql servers)
- parallel sessions on servers that do the same thing to switch copy/paste a set of commands to apply to each one of them

I forgot one thing, adding a tab (by a « + » button or Cmd + T shortcut) could show some quick list of favorites servers with a search form already selected to type the name quickly.

And maybe a support for « ssh user@host » command that would use a default SSH key that we can select but I’m not sure how to keep it simple.

J’espère que ce sera + clair :)

**Comment by isontheline** [comment]
Oui c'est bien plus clair et j'adhère, merci également pour votre soutien face aux alternatives à WebSSH ;)

I will enhance the current multiple windows system in order to be more efficient and to be more "macOS" like (because iOS apps will be on the Mac App Store soon too).

Thank you a lot again for the description of your need, I will come back to you as soon as possible.

Have a nice day ☀️

**Comment by AInteriorB** [comment]
Hey. Is there already a fast way to switch between multiple sessions, I haven‘t found out yet? ;-) Thanks a lot for your great tool!

**Comment by isontheline** [comment]
Hello @AInteriorB 👋

Thank you a lot for your support 🙏

Yes you're right the current implementation of window switching is "bad".
The only option - yet - to switch between windows is like you have done 👍

**Comment by isontheline** [comment]
* On iPad WebSSH will use iOS "scenes" in order to be able to switch between windows. Available on alpha release TestFlight.

* On macOS WebSSH will use "native tabs". Available on alpha release TestFlight.

* On iPhone WebSSH will implement "tabs" buttons. Planned for 17.X

**Comment by isontheline** [comment]
On iPad "scenes" are already available.

On iPhone I need to implement tabs.

**Comment by snk33** [comment]
Thanks for these updates. I've tested on iPad and it works well.

Is there any shortcut to open a scene and switch between scenes ?

**Comment by isontheline** [comment]
Shortcuts on hardware keyboard?

I've already implemented them but only inside macOS release (18.0)

**Comment by snk33** [comment]
Indeed I meant shortcuts Magic Keyboard and/or trackpad.

For example on MacOS, the terminal app allows to switch between tabs with 3 fingers swipe left/right on trackpad. I guess some Cmd + left/right would be ok aswell.

**Comment by isontheline** [comment]
Thank you, I'm checking for availability under iOS

**Comment by isontheline** [comment]
@snk33 @AInteriorB @jarrah31

WebSSH 18.1 for iPhone / iPad is near :
![Simulator Screen Shot - iPad mini (6th generation) - 2022-05-20 at 22 36 32](https://user-images.githubusercontent.com/44212923/169607287-5bbe426a-d639-4c1f-a2a7-e63162a15ff6.png)

**Comment by isontheline** [comment]
Now available inside WebSSH 18.1 :
https://testflight.apple.com/join/QSrBK59z

**Comment by jarrah31** [comment]
The new sidebar layout on the iPad looks so much better, thank you Arnaud!

**Comment by jarrah31** [comment]
hmm, it's been niggling me for a while so I should mention that I find the term "multiple tabs" on the iPad a little confusing.

e.g.
I see that tabs on macOS looks like this:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/3072303/170125706-b9a5182e-0aa2-4589-84d9-3f34e21ca748.png">

Tabs on iOS (which look great btw!) are like this:
![image](https://user-images.githubusercontent.com/3072303/170127259-14f8aa02-474e-4ccd-9266-750f7f9d1c8d.png)

Tabs on Safari on the iPad look like this:
![image](https://user-images.githubusercontent.com/3072303/170127743-d4b70bab-9761-4304-a2c9-f627d34cbb89.png)

Windows on Safari on the iPad look like this:
![image](https://user-images.githubusercontent.com/3072303/170127990-5210be4c-8251-440e-a21c-d263f5721f2c.png)

But "tabs" on WebSSH on the iPad are basically "Windows":
![image](https://user-images.githubusercontent.com/3072303/170128364-563971c6-c35d-40e7-9019-477f58c721d1.png)

I imagine this is just the way that different OSs work and can't be helped. I see in the comments above that you mention iPad uses "Scenes" which I guess means there's no easy or native way to implement tabs on the iPad in the same way that Safari on iPad and WebSSH on macOS works? 

I'm sorry to be a pain but if there is a way to implement tabs on the iPad it would feel so much more intuitive and easier to use than the "Windows" method. This is only a suggestion and I understand if it isn't possible with the native iPad SDK.

**Comment by jarrah31** [comment]
In hindsight, the new Sessions section on the iPad is basically "tabs" because I can easily swap between them just like tabs. Maybe this is all that's needed on the iPad and this could be described as a tab alternative in the docs?
![image](https://user-images.githubusercontent.com/3072303/170131426-e3af5622-170d-4538-ab94-3bd7ab10407e.png)

**Comment by isontheline** [comment]
> In hindsight, the new Sessions section on the iPad is basically "tabs" because I can easily swap between them just like tabs. Maybe this is all that's needed on the iPad and this could be described as a tab alternative in the docs?
> ![image](https://user-images.githubusercontent.com/3072303/170131426-e3af5622-170d-4538-ab94-3bd7ab10407e.png)

No problem I will update the documentation : https://github.com/isontheline/pro.webssh.net/issues/628

**Comment by isontheline** [comment]
> hmm, it's been niggling me for a while so I should mention that I find the term "multiple tabs" on the iPad a little confusing.
> 
> e.g. I see that tabs on macOS looks like this: <img alt="image" width="606" src="https://user-images.githubusercontent.com/3072303/170125706-b9a5182e-0aa2-4589-84d9-3f34e21ca748.png">
> 
> Tabs on iOS (which look great btw!) are like this: ![image](https://user-images.githubusercontent.com/3072303/170127259-14f8aa02-474e-4ccd-9266-750f7f9d1c8d.png)

iPhone OS doesn't provide "tabs" out of the box (or I don't found them).
I'm waiting for iPhone OS 16 and I hope that easier multi-tasking will be available.

> Tabs on Safari on the iPad look like this: ![image](https://user-images.githubusercontent.com/3072303/170127743-d4b70bab-9761-4304-a2c9-f627d34cbb89.png)

I think that tabs on Safari iPad OS are "hand made" by Apple. 
I didn't found any "native" implementation inside the SDK.
Hope iPad OS 16 will fix the gap.

> Windows on Safari on the iPad look like this: ![image](https://user-images.githubusercontent.com/3072303/170127990-5210be4c-8251-440e-a21c-d263f5721f2c.png)
> 
> But "tabs" on WebSSH on the iPad are basically "Windows": ![image](https://user-images.githubusercontent.com/3072303/170128364-563971c6-c35d-40e7-9019-477f58c721d1.png)

Yes you're right, only windows are available inside WebSSH.
"Fake" tabs are implemented through the sidebar.

> I imagine this is just the way that different OSs work and can't be helped. I see in the comments above that you mention iPad uses "Scenes" which I guess means there's no easy or native way to implement tabs on the iPad in the same way that Safari on iPad and WebSSH on macOS works?

The "source code" of tabs implemented on macOS and iPad OS are the same inside WebSSH and the OS render them differently. 
I cross my fingers to have a better implementation on iPad on the next major iOS release.
Yet I need to wait in order to don't implement things that should be broken on a future iOS update.
 
> I'm sorry to be a pain but if there is a way to implement tabs on the iPad it would feel so much more intuitive and easier to use than the "Windows" method. This is only a suggestion and I understand if it isn't possible with the native iPad SDK.

Everything is possible, I just would like to don't implement things which will be broken soon.
Don't worry, WebSSH will be improved over the next few months with the help of iOS 16 🤞

**Comment by AInteriorB** [comment]
Yeah @isontheline , looks good at first glance. 😄 🥳 

Two suggestions:

1) The keyboard should be available after switching the session. Currently, I need to touch the ipad screen to activate the keyboard after switching the session. 

2) Autohide sidebar after switch: The console is the area where I work. After switching the session, the new sidebar uses still lots of space and I have to manually hide it. In my optinion it would be better to autohide the sidebar after switching the session 😄 


Then a strange behaviour: When I have opened two Tabs (basically Windows) on iPad  and I close one of it, the sessions of the other window are gone.

**Comment by isontheline** [comment]
> Yeah @isontheline , looks good at first glance. 😄 🥳

🙏

> Two suggestions:
> 
> 1. The keyboard should be available after switching the session. Currently, I need to touch the ipad screen to activate the keyboard after switching the session.

I have created an issue : https://github.com/isontheline/pro.webssh.net/issues/629

> 2. Autohide sidebar after switch: The console is the area where I work. After switching the session, the new sidebar uses still lots of space and I have to hide it manually. In my opinion it would be better to autohide the sidebar after switching the session 😄

I have created an issue :

> Then a strange behaviour: When I have opened two Tabs (basically Windows) on iPad and I close one of it, the sessions of the other window are gone.

When you are using the iPad three "..." dots and dropping one window?
I'm opening a bug issue :

**Comment by jarrah31** [comment]
> Don't worry, WebSSH will be improved over the next few months with the help of iOS 16

Very happy to wait, I understand the limitations you're having to deal with and I appreciate all you do to improve your useful app.
