### ISSUE TITLE
Please Support Older OS Versions

### ISSUE THREAD

**Issue by marienmare** [isontheline/pro.webssh.net#1013]
I am currently using an older Intel MacBook, which runs macOS 12.7.1 Monterey. I'm really interested in the new interface and additional features that have been introduced in the recent update of WebSSH. However, I've noticed that the App Store only supports these updates for macOS 13 and later versions.

Is there a possible solution for this? If it's feasible to develop a version that runs on Monterey, it would be great if you could distribute the latest version as a .dmg file. This would allow users like me, who are on older macOS versions, to benefit from the new features and improvements.

Thank you for considering this request. I look forward to any updates you might have on this matter.

![image](https://github.com/isontheline/pro.webssh.net/assets/73532293/e7385bd9-f65f-47b0-8050-d991c71a4233)
![image](https://github.com/isontheline/pro.webssh.net/assets/73532293/2cddbbf9-6229-4fe4-a9b1-0adcd226d878)

**Comment by isontheline** [comment]
Hello @marienmare 👋

Thank you so much for reaching me out 🙏

Some new features requires at least macOS 13, I will try to identify them and take a look I I can produce a binary which could be run on macOS 12.

Sorry for the trouble.

I wish you a nice day ☀️

**Comment by isontheline** [comment]
@marienmare I'm sorry I'm unable to run WebSSH before iOS 16 / macOS 13
There are two much libraries which require newer OS version
