### ISSUE TITLE
Missing magical word * in "Port Forwarding"

### ISSUE THREAD

**Issue by bigboyq** [isontheline/pro.webssh.net#102]
I am happy to see the VPN feature from the version 14.6
But quite incovient for me, as I used tunnel as a bastion, instead of VPN.
As I have at least 10 machines to connect through the bastion tunnel.
Under this new feature, I must set up at least 10 tunnels to forward connections.
In the past, just magical word "*" should resolve the problem.
I am happy to have system VPN features instead of in-app feature, but please keep the magical word "*" enabled.
If VPN feature supported, magical word "*" keep also, would be quite convient for every users.

**Comment by isontheline** [comment]
Hello @bigboyq 👋

Magical word `*` have been only removed from documentation not from the code itself.

Do you experience any problem with the dynamic port forwarding (aka bastion?)

**Comment by bigboyq** [comment]
Yup, I have downloaded TF version, and make up connection through tunnel successful, with the configuration "*"
I could see VPN logo on top of screen, but every connection I made, no matter in-app or out-app, all through the default wifi or celluar, no as expected through the tunnel

**Comment by isontheline** [comment]
Thank you a lot for your quick feedback!

So I will fix it as soon as possible.

I will come back to you shortly I think.

Have a nice day ☀️

**Comment by isontheline** [comment]
Perhaps you could download an older version (before 14.6) in order to use bastion again while I'm working on a fix.

**Comment by bigboyq** [comment]
That's ok, it seems that you have reproduced the problem, happy to see you online

**Comment by isontheline** [comment]
- [ ] Update documentation about Dynamic Port Forwarding

**Comment by isontheline** [comment]
@bigboyq TestFlight update will be available tomorrow

Have a nice day ☀️

**Comment by isontheline** [comment]
![image](https://user-images.githubusercontent.com/44212923/99115927-8430bf80-25f3-11eb-94ec-03dc9684b973.png)

Always waiting for review... I'm impatient 😇

**Comment by isontheline** [comment]
Apple are you watching me?

![image](https://user-images.githubusercontent.com/44212923/99116438-513afb80-25f4-11eb-8d82-0b7f91819410.png)

@bigboyq Could you try this beta release please?

**Comment by bigboyq** [comment]
Sorry, just wake up, I am living in EST-8
Have tested.
As the implementation is legacy, in-app test passed, work properly, out-app test failed, as all traffic implemented inside app, not through vpn.

**Comment by isontheline** [comment]
Hello @bigboyq, thanks for your feedback!

The magical word `*` can only be used inside the app yet.

I will implement outside app traffic later as a lot of work is required.

If you need outside traffic to pas through the port forwarding please use :
* Socks V4 server : 127.0.0.1
* Socks V4 port : 1985

Your outside apps need socks support of course yet.

**Comment by isontheline** [comment]
@bigboyq Have you used "Web" connections in the past?

**Comment by bigboyq** [comment]
I have seen the Web connection in the past, but don't know how to use, no documentation as good as now :)
If I am your product manager, I would suggest:

1. in-app tunnel should be a native feature
2. out-app tunnel(iOS VPN style) could be a in-app-purchase, and more work could be done, just as route table, route list, local port mapping should be a route rule. magical word maybe the default rule, hoho

I think much more users should be interested in this feature, as using SSH server is much easier than buildindg any other VPN server.

**Comment by isontheline** [comment]
> I think much more users should be interested in this feature, as using SSH server is much easier than buildindg any other VPN server.

I agree!

I have added issue #104 in order to track progress of VPN Over SSH outside WebSSH.

Thank you again for your feedback @bigboyq
