### ISSUE TITLE
Ability to change Cursor Keys Mode globally

### ISSUE THREAD

**Issue by pc-support65** [isontheline/pro.webssh.net#1021]
# Bug description
Pressing up / down arrow keys does nothing while connected to remote machine. Does not show previous commands executed  history.

**Comment by isontheline** [comment]
Could you share some information about your server (os, etc)?

**Comment by isontheline** [comment]
Feel free to reopen this issue as soon as needed

**Comment by pc-support65** [comment]
SSH’ing from Mac to both Windows and Mac machines, various OS versions. 

It seems to be Windows machines (using powershell as default shell) where the up arrow command execution history doesn’t work (both Win 10 and 11).

**Comment by isontheline** [comment]
Thank you so much for your feedback 🙏

Could you try to edit your connection terminal settings and update "Cursor Keys Mode" to "Normal" value?

I wish you a nice day ☀️

**Comment by pc-support65** [comment]
You’re up early!

Done and working. Can this be set globally?


---
Richard Burt

PC Support Services
Edinburgh.

W:  https://pc-support.uk.com
Phone: +44 (0)131 208 8977

Book an appointment <https://app.simplymeet.me/pc-support>

**Comment by isontheline** [comment]
You're Welcome 😉 

I will add an option tonight to set it globally.

The update should be available by the end of year (7-10 days)

**Comment by isontheline** [comment]
Now available on TestFlight : https://testflight.apple.com/join/QSrBK59z

You will need to edit ssh_config file : https://webssh.net/documentation/help/SSH/ssh-config-file/#special-features

Example :
```
HOST *
    #!CursorKeysMode normal
```

Have a nice day ☀️

**Comment by pc-support65** [comment]
Appears to be working as intended :)
