### ISSUE TITLE
in iPad OS freezing commandline, like up/down arrows show precedent commands, but impossible to type via keyboard or display keyboard. 

### ISSUE THREAD

**Issue by cturpel** [isontheline/pro.webssh.net#1023]
# Bug description

iPad OS 17.1.2, ipad Pro 2022 12.9“
in SSH connection to server
typing from HW Keyboard or screen does not work.
Hitting Enter no reaction
Arrow up/down is showing precedent commands.

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. connect to server (tried here 2 different vps, 1 local ssh server (qnap nas))
2. seeing behaviour as in Bug Description
3. after a while it works, then gets stuck again
4. and so on. reconecting to server does not seem to have a big effect

EDIT:

IF clicking in command line itself, gets stuck, if i click on the left pane on the server session it gets unstuck.
Biggest problem when clicking in the terminal window to paste code -> hangs

**Comment by isontheline** [comment]
Could you share more information about what you were doing?

Inside SSH or mashREPL?

Thank you

**Comment by cturpel** [comment]
Hey Thanks for quick Reply. I updated the Bug Description to something „usable“ :)

**Comment by isontheline** [comment]
Thanks for updating the issue 🙏

I'm not able to reproduce, both virtual and hardware keyboard seem to be working as wanted :
![image](https://github.com/isontheline/pro.webssh.net/assets/44212923/ca89ec50-438c-4263-856d-c3492cd5be1f)

When using your hardware keyboard could you confirm that this line is shown above the bottom of the screen?
<img width="755" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/f0bf3d39-005e-4a2f-860d-aebc63ce6a9a">

**Comment by isontheline** [comment]
Feel free @cturpel to reopen this issue as soon as you need

I wish you a nice day ☀️
