### ISSUE TITLE
Terrapin-attack / webssh vulnerable

### ISSUE THREAD

**Issue by bettercom** [isontheline/pro.webssh.net#1028]
According to the terrapin-scanner running as "server" (in listen-mode) webssh is vulnerable to Terrapin. More info about this may be found on https://terrapin-attack.com/

It would be great if you could fix this issue in the next release. 

Thanks in advance!

```
% ./go/bin/Terrapin-Scanner -listen 192.168.168.7:2222
Listening for incoming client connection on 192.168.168.7:2222
================================================================================
==================================== Report ====================================
================================================================================

Remote Banner: SSH-2.0-WebSSH_24.4

ChaCha20-Poly1305 support:   true
CBC-EtM support:             true

Strict key exchange support: false

The scanned peer is VULNERABLE to Terrapin.

Note: This tool is provided as is, with no warranty whatsoever. It determines
      the vulnerability of a peer by checking the supported algorithms and
      support for strict key exchange. It may falsely claim a peer to be
      vulnerable if the vendor supports countermeasures other than strict key
      exchange.

For more details visit our website available at https://terrapin-attack.com
```

**Comment by isontheline** [comment]
Hello @bettercom 👋

I'm aware about the Terrapin attack vector and I will provide a new binary with safe default settings.

I can't give you any ETA yet

**Comment by isontheline** [comment]
I think I will be able to provide a safe binary within hours (high hope)

**Comment by isontheline** [comment]
I'm facing some backend issues but I'm in progress :
<img width="617" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/eed9a226-142b-414c-b016-1a222e364382">

**Comment by isontheline** [comment]
Latest alpha release is now OK with Terrapin-attack :

<img width="590" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/4af0601e-ce6f-411d-b6de-f1489f176dd6">

I need to do more checks and will provide an ETA asap

**Comment by isontheline** [comment]
Beta release will be available in a few hours today

**Comment by isontheline** [comment]
Fix now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
