### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by md347** [isontheline/pro.webssh.net#103]
**Describe the feature**
_A clear and concise description of what the feature is. Be warned : I will refuse requests with no or little informations_

**Screenshots / Draws**
_If applicable, add screenshots and/or draws to help explain your feature request._

**Comment by isontheline** [comment]
Hello @ 👋 
Thanks for your issue! 
But...

...Every time someone does not respect the issue's template, a little mouse dies.

<details> 
<summary>Learn how</summary>

![little-mouse-dies-or-not-it-depends-on-you](https://user-images.githubusercontent.com/44212923/91720843-10584c80-eb98-11ea-80b8-fdc48f92392c.gif)
</details>

Please edit your issue description to respect the issue template as much as possible :
* https://github.com/isontheline/pro.webssh.net/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
* https://github.com/isontheline/pro.webssh.net/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by isontheline** [comment]
Duplicate, already planned in #7
