### ISSUE TITLE
Bad DNS servers used since 24.6+

### ISSUE THREAD

**Issue by MrFly72** [isontheline/pro.webssh.net#1030]
# Bug description
Connections I have used for ages (authorization by key+password) do not connect anymore.

# Screenshots
![image](https://github.com/isontheline/pro.webssh.net/assets/65505278/4b5fd40f-0483-42c8-913f-2bc01df4065c)

**Comment by MrFly72** [comment]
Oh, and rolling back to 25.x lets the same connections work again

**Comment by bbjunkie** [comment]
Same here.

**Comment by isontheline** [comment]
@MrFly72 Could be a collateral effect of this fix : #1028

Could you extract the verbose logs please?

@bbjunkie Could you put screenshots about the ping issue?

**Comment by isontheline** [comment]
@MrFly72 It's not 25.x, do you mean 24.5?

**Comment by MrFly72** [comment]
Yes you are right.

**Comment by isontheline** [comment]
@MrFly72 Please share any data you may have (verbose logs of WebSSH, your server version and custom settings)

**Comment by MrFly72** [comment]
Will send later. First view in the log. You seem to use Google dns instead of mine. Very bad for local addresses.

**Comment by MrFly72** [comment]
`2024/01/10 07:06:13:198 [INFO] Thank you so much for using WebSSH 24.7.1239 on iOS
2024/01/10 07:06:13:198 [INFO] WebSSH Setting Log Level : VERBOSE
2024/01/10 07:06:13:199 [INFO] Launching Data Migration...
2024/01/10 07:06:13:199 [INFO] Checking if settings need to be migrated...
2024/01/10 07:06:13:203 [INFO] Data Migration Done!
2024/01/10 07:06:13:203 [DEBUG] Launch_APP_Count_24.7 : 3
2024/01/10 07:06:13:203 [DEBUG] Launch_APP_Count : 214
2024/01/10 07:06:13:203 [DEBUG] Launching Vacuum on the local database...
2024/01/10 07:06:13:204 [DEBUG] 0 objects have been vacuumed
2024/01/10 07:06:13:212 [VERBOSE] Performing vacuum on old deleted iCloud objects...
2024/01/10 07:06:13:230 [DEBUG] Device language : de
2024/01/10 07:06:13:230 [INFO] Language bundle is not loaded. Will load this bundle : de
2024/01/10 07:06:13:285 [VERBOSE] Will notify when setting 'WEBSSH_SETTING_CONNECTION_LIST_ROW_DETAILS' will change
2024/01/10 07:06:13:307 [INFO] WebSSH should be locked after delay (secs) : 60
2024/01/10 07:06:13:658 [DEBUG] Application did become active
2024/01/10 07:06:13:662 [DEBUG] No pin code set. WebSSH won't be locked.
2024/01/10 07:06:13:765 [DEBUG] Application will resign active
2024/01/10 07:06:13:849 [VERBOSE] No objects to be vacuumed on iCloud.
2024/01/10 07:06:14:210 [DEBUG] Fetching from iCloud with a change token
2024/01/10 07:06:14:288 [VERBOSE] Updating host statuses...
2024/01/10 07:06:14:308 [VERBOSE] Host raspi4.fritz.box:22 changed. Is up : 1
2024/01/10 07:06:14:314 [VERBOSE] Host bbbbb.aaaaaaaa.de:24472 changed. Is up : 1
2024/01/10 07:06:14:492 [DEBUG] iCloud data fetched with success.
2024/01/10 07:06:15:330 [VERBOSE] Host raspi4b.fritz.box:22 changed. Is up : 0
2024/01/10 07:06:15:371 [VERBOSE] Host raspizero2.fritz.box:22 changed. Is up : 1
2024/01/10 07:06:16:385 [VERBOSE] Host synologynas.fritz.box:22 changed. Is up : 0
2024/01/10 07:06:16:434 [VERBOSE] Host jjjjjjjjjjj.myfritz.net:2404 changed. Is up : 1
2024/01/10 07:06:16:434 [VERBOSE] Updating of host statuses done.
2024/01/10 07:06:16:435 [VERBOSE] Need to refresh hosts list because at least one host status have been updated
2024/01/10 07:06:16:435 [VERBOSE] Fresh requested for connection list...
2024/01/10 07:06:16:595 [DEBUG] Application did become active
2024/01/10 07:06:16:595 [DEBUG] Can't lock WebSSH because delay not elapsed : 2 < 60
2024/01/10 07:06:17:594 [DEBUG] A custom SSH Config File will overwrite this connection settings : (
    "_keyboardaccessoryview"
)
2024/01/10 07:06:17:594 [VERBOSE] Want to connect with a Private Key
2024/01/10 07:06:17:599 [VERBOSE] Private Key is encrypted because user have set a passphrase inside WebSSH.
2024/01/10 07:06:17:599 [DEBUG] Private Key is encrypted : 1
2024/01/10 07:06:17:600 [VERBOSE] Load Private Key in PuTTY Format
2024/01/10 07:06:17:603 [VERBOSE] Launching connection (SSH)...
2024/01/10 07:06:17:604 [VERBOSE] Connecting to SSH...
2024/01/10 07:06:17:604 [VERBOSE] Launching connection with block...
2024/01/10 07:06:17:604 [VERBOSE] Won't dismiss prompt because no one is displayed.
2024/01/10 07:06:17:619 [INFO] IP Strategy is set to 'ipv4'. Does IPv6 is prefered over IPv4? => 0
2024/01/10 07:06:17:620 [DEBUG] No SOCKS Tunnel launched. SSH connection will be established without any SOCKS hostname.
2024/01/10 07:06:17:640 [VERBOSE] <EngineLog>
  <Connect_Ssh>
    <EngineVersion>9.5.0.97</EngineVersion>
    <EngineStatus>2</EngineStatus>
    <connectInner>
      <hostname>raspi4.fritz.box</hostname>
      <port>22</port>
      <sshConnect>
        <connectSocket_v2>
          <connect_domain>
            <ckDnsResolveDomainIPv4_n>
              <dnsHostsFileLookup>
                <domainName>raspi4.fritz.box</domainName>
              </dnsHostsFileLookup>
              <namservers>
                <ip>8.8.8.8</ip>
                <ip>1.1.1.1</ip>
              </namservers>
              <error>No valid DNS answer..</error>
            </ckDnsResolveDomainIPv4_n>
          </connect_domain>
        </connectSocket_v2>
        <error>Failed to establish initial TCP/IP connection</error>
        <hostname>raspi4.fritz.box</hostname>
        <port>22</port>
      </sshConnect>
    </connectInner>
    <error>Failed.</error>
  </Connect_Ssh>
</EngineLog>
2024/01/10 07:06:17:740 [DEBUG] Dismissing prompt...
2024/01/10 07:06:17:948 [VERBOSE] Updating host statuses...
2024/01/10 07:06:20:016 [VERBOSE] Error : Es kann keine Verbindung zu raspi4.fritz.box hergestellt werden
2024/01/10 07:06:20:043 [VERBOSE] Updating of host statuses done.
2024/01/10 07:06:23:899 [VERBOSE] IAP already purchased (device) : com.webssh.pro.unlimited
2024/01/10 07:06:29:212 [DEBUG] Fetching from iCloud with a change token
2024/01/10 07:06:29:512 [DEBUG] iCloud data fetched with success.
2024/01/10 07:06:32:282 [DEBUG] Application will resign active
`

**Comment by MrFly72** [comment]
Sorry, hope it is readable.  iPad does not give a lot of options to format in the GitHub app

**Comment by isontheline** [comment]
@MrFly72 I will provide a fix asap.

Google DNS shouldn't be used as default. I'm searching why it's now by default.

**Comment by bbjunkie** [comment]
> @MrFly72 Could be a collateral effect of this fix : #1028
> 
> Could you extract the verbose logs please?
> 
> @bbjunkie Could you put screenshots about the ping issue?

![image](https://github.com/isontheline/pro.webssh.net/assets/35636055/d919bd46-b197-4f24-8de3-6da03550825f)

**Comment by isontheline** [comment]
Thanks @bbjunkie 

Seems not related to this issue.
Could you extract these information please :
1. Launch mashREPL
2. What's the output of : ifconfig

**Comment by isontheline** [comment]
@MrFly72 Please try WebSSH 24.7.1240 : https://testflight.apple.com/join/QSrBK59z

I have fixed the default DNS resolver trouble.
Your defined DNS servers inside your OS will be used instead.

**Comment by MrFly72** [comment]
I can connect again.
The big change you wanted to does to present the keys again, right? Because that's the difference that alleys are presented once again.

**Comment by isontheline** [comment]
Yes @MrFly72 I have added a warning about it to support page :

<img width="970" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/1ff6b10b-daca-49f4-9633-2143f8faf68e">

I now use different host fingerprint keys when available

I will add another on the App Store.

Sorry for the trouble

**Comment by ash34** [comment]
This fixed for me now with version 24.7.1240

**Comment by isontheline** [comment]
@ash34 Many thanks for your feedback 🙏

**Comment by MrFly72** [comment]
> 
> Sorry for the trouble

No worries. That's what beta testing (TestFlight) is for. Glad that we could find it before a release!
Thanks for reacting that fast! Awesome support!
