### ISSUE TITLE
Session won't launch on latest MacOS Ventura update

### ISSUE THREAD

**Issue by sbrooke** [isontheline/pro.webssh.net#1041]
After upgrading an older MacBook to MacOS 13.6.4 and WebSSH to 24.8 (1244) I can no longer launch a session, most of the time. The item flashes briefly but nothing else happens. Oddly, a few of the servers will launch, but it's only about a third in my list. The rest just flash like they've been "activated" and nothing happens. It seems like the WebSSH window does pause (like it's trying to do something) as I'm not able to scroll for 2-3 seconds after clicking on the server.

I've rebooted several times and checked for additional updates. 

I also tried opening a second tab and launching from there. Same behavior on the same servers.

Everything works fine on my iPad. I haven't tested on my Sonoma Mac mini yet.

**Comment by sbrooke** [comment]
Just discovered my iPad is behaving the same. I must have tested on an older version of WebSSH yesterday, on the iPad.

Is it getting hung up on the cert reissue?

**Comment by sbrooke** [comment]
I built a new entry for one of the failing servers. All the same settings. That worked and prompted me for the cert.

After doing this, the old entry still does not work. I didn't expect it to. Just letting you know.

**Comment by isontheline** [comment]
Hello @sbrooke Please upgrade to 24.9 release

**Comment by isontheline** [comment]
@sbrooke May I closd this issue?

**Comment by sbrooke** [comment]
Apple hasn't granted me with the update yet. If you're confident it fixes the issue that's fine. I can open another ticket if it's still not working.

**Comment by isontheline** [comment]
You can reopen this one.

Current workaround with the 24.8 release : 
1. Edit your connection
2. Set roles with SSH + SFTP
3. Save your connection

You'll be able to use them as expected
