### ISSUE TITLE
中国区ios端下架了这个app，之前购买过pro版本的，换了手机后怎么下载恢复

### ISSUE THREAD

**Issue by fuzengjie** [isontheline/pro.webssh.net#1045]
我曾经买过webssh这个软件，现在换了手机后国服下载不了了，换到美服，下载到手机上怎么恢复购买？盼回

**Comment by isontheline** [comment]
Hello @fuzengjie 👋

Thank you so much for reaching me out 🙏

Unfortunately WebSSH isn't available anymore inside China App Store.
Please send me your original purchase receipt on : team [AT} webssh (DOT] net

I wish you a nice day ☀️
