### ISSUE TITLE
App crashing when notes are open

### ISSUE THREAD

**Issue by Dave-W** [isontheline/pro.webssh.net#1058]
# Bug description
Application crashes when notes open

# Steps to reproduce
1. Connect to an ssh server
2. Open Notes from icon
3. Click on ssh session in left hand bar
4. App crashes

**Comment by isontheline** [comment]
Hello @Dave-W 👋 

Thank you so much for your feedback 🙏

Are you using macOS or iPadOS?

When you say "click on session on the left hand bar", are you referring to the sidebar?

**Comment by Dave-W** [comment]
Sorry, yes, the sidebar.
It's Mac OS Sonoma 14.1.2 running on an M1 Mac Mini

https://github.com/isontheline/pro.webssh.net/assets/3381755/2eeeb57d-211d-42ac-9bbf-d3f1c94fe95d

**Comment by isontheline** [comment]
Many thanks @Dave-W 🙏

I'll provide a fix (very) soon

**Comment by isontheline** [comment]
I'm now working on it.

Expecting a fix before end of February.

**Comment by isontheline** [comment]
Hello @Dave-W 👋

Could you try latest WebSSH release 25.4.1289?
https://testflight.apple.com/join/QSrBK59z
