### ISSUE TITLE
Purchase moving across MacOS to iOS not working 

### ISSUE THREAD

**Issue by EagleDTW** [isontheline/pro.webssh.net#1059]
# Bug description

Purchase moving across MacOS to iOS not working

# no Screenshots
Error message in red that says contact support if help needed 

# Steps to reproduce
1. Had app originally on purchased iOS but also had to purchase for MacOS too
2. Do the WebRCL (sp?) screen and type web ssh store sync on both devices and nothing!
3. App Store on iPhone doesn’t show purchased
4. When trying to hit restore purchase on iPhone an Error is thrown

**Comment by isontheline** [comment]
Hello @EagleDTW 👋 

Sorry that you are encountering a bad experience about purchasing WebSSH.

Could you please contact me through email?

team [AT} webssh (DOT] net

I will help you as much as you need.

I wish you a nice day ☀️

**Comment by isontheline** [comment]
@EagleDTW Thanks for reaching me through email.

I'm closing this issue and continue to help you as much as needed on the other channel.
