### ISSUE TITLE
How to delete an invalid known-host ssh key

### ISSUE THREAD

**Issue by yblake** [isontheline/pro.webssh.net#106]
**How to**
Hi, I did a complete rebuilt of my remote computer, flashing a fresh new Ubuntu image on an sd card.
After reboot, the remote computer with same name and IP address is no more reachable, as remote ssh key changed.
In my pc using windows, I had to remove it from ssh known-host file in order to access again the new installation.
I was unable to achieve this with webssh. Deleting and Recreating the connection didn’t work.
I had to delete the whole application from iPhone, reinstall it from App Store and then it worked.
So how to delete a known-host that has changed his ssh key, without reinstalling webssh ?
May be I missed something,
Thanks for support

**Comment by isontheline** [comment]
Hello @yblake 👋

Didn't the "Continue anyway" button was working?
![image](https://user-images.githubusercontent.com/44212923/99155946-0afd9f00-26bd-11eb-9af7-b960e13b197f.png)

**Comment by yblake** [comment]
No it didn't, got a connection failed red banner.
(But I got a similar message in Windows, which leaded me to manually delete the known-host entry cause I knew the man in the middle was myself...)

**Comment by yblake** [comment]
I can try to reproduce switching to previous sdcard

**Comment by isontheline** [comment]
Bonsoir Yves 👋

The [above popup](https://github.com/isontheline/pro.webssh.net/issues/106#issuecomment-727258758) should be displayed when MitM is detected 😕

If you can reproduce this bug 🐛  I will be happy to fix it.
Please come back as soon as you want and I will reopen this issue instantly.

A très bientôt Yves 🇫🇷

**Comment by yblake** [comment]
I couldn't reproduce, and the "bad remote host fingerprint" action shows correctly.
I think I previously tried to reconnect from 4G network instead of local wifi, pls apologize for my mistake.

**Comment by isontheline** [comment]
No problem, you're Welcome 👍
