### ISSUE TITLE
Check if Pro

### ISSUE THREAD

**Issue by CyberMew** [isontheline/pro.webssh.net#1063]
Not sure how I can check if I am pro. Attach a screenshot can you help me understand what it says?
![IMG_6924](https://github.com/isontheline/pro.webssh.net/assets/4715911/9e2274fa-4d07-421e-b8e7-b8fe18504226)

**Comment by isontheline** [comment]
Hello @CyberMew 👋

It says you are using the PRO :
<img width="570" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/4830546d-912d-4068-83e3-0cbbb63c1a3a">

Are you encountering any error?

**Comment by CyberMew** [comment]
No error but I see the restore purchase button as if I am not on PRO. Is there a command line I can type to check properly?

**Comment by isontheline** [comment]
@CyberMew Yes this button is here in order to retry the restore purchase if something is wrong within the app
