### ISSUE TITLE
Ping results layout not helpful on error

### ISSUE THREAD

**Issue by ash34** [isontheline/pro.webssh.net#1067]
# Bug description
Using an iPad the ping results are formatted/ aligned so that successful ping results are Ok but unsuccessful results only show part of the error message. This not helpful. 

# Screenshots
![IMG_0953](https://github.com/isontheline/pro.webssh.net/assets/56022918/5522cb49-1d23-4401-8573-1c3e50c5b6d8)
![IMG_0952](https://github.com/isontheline/pro.webssh.net/assets/56022918/ee8e4e0b-2095-43b2-b83e-4fce8dfbb7d4)

# Steps to reproduce
1. Use the ping tool to ping a known reachable host
2. Use the ping tool to ping a known unreachable host
3. Compare the outputs

**Comment by isontheline** [comment]
Hello @ash34 👋

Thanks for your feedback!
I will release an enhancement before the end of the week ;)

**Comment by isontheline** [comment]
A first attempt is available on WebSSH 25.4.1291 : https://testflight.apple.com/join/QSrBK59z

**Comment by ash34** [comment]
The change has made the error easily readable.
