### ISSUE TITLE
Terminal is hidden behind the keyboard on iOS

### ISSUE THREAD

**Issue by gpelouze** [isontheline/pro.webssh.net#1074]
# Bug description

When starting a new SSH connection, the bottom part of the terminal is hidden by the keyboard on iOS (see screenshots). As a result, it is impossible to see what you are typing at the bottom of the screen. This means the app is unusable in the current state. 

In previous versions (probably before 25.0), the terminal was moved upon opening the keyboard, such that the last line would appear above the the keyboard. 

# Screenshots

![IMG_3731](https://github.com/isontheline/pro.webssh.net/assets/9514702/86074fb3-b700-4a82-991b-e7550e06d04e)
![IMG_3732](https://github.com/isontheline/pro.webssh.net/assets/9514702/85b8929d-6c0d-4efc-acbe-20273f4d3d0d)

# Steps to reproduce

1. Open a SSH connection to a saved server
2. Notice that the bottom part of the terminal is hidden behind the keyboard

**Comment by isontheline** [comment]
Hello @gpelouze 👋

Many thanks for your strong feedback 🙏

Strange behavior not encountered - yet - on my side.

Does a screen rotation (portrait - landscape - portrait) fixes the trouble?

**Comment by gpelouze** [comment]
Thanks for the quick followup! Unfortunately the issue is still present after the screen rotation (it appears both in landscape mode, and in portrait mode after the rotation cycle).

**Comment by isontheline** [comment]
Thanks for your feedback @gpelouze 🙏

When you press "return" key : doesn't the screen resizing?

**Comment by isontheline** [comment]
Does a host with less "Message Of The Day" at the beginning of the shell works better?

**Comment by gpelouze** [comment]
I have the same issue with servers that have a shorter motd. The prompt is initially above the keyboard, but disappears behind it after running a few commands. 

Can you please advise a way to fully reset the app settings to make the issue disappear? I would hate to have to pay for another ssh client.

**Comment by isontheline** [comment]
> Can you please advise a way to fully reset the app settings to make the issue disappear?

Have you set any setting inside the ssh_config of WebSSH?

**Comment by gpelouze** [comment]
I had. Removing them does not fix the issue either.

**Comment by gpelouze** [comment]
Sure, here are the logs (with private info removed): https://gist.github.com/gpelouze/c12abe276ca5f7bd894c5192ff288dbb

During this session, I connected to some host, hid the keyboard and brought it up again.

**Comment by isontheline** [comment]
I suspect this line : 
Keyboard Mode = Floating 

I will try to make a fix tonight

**Comment by isontheline** [comment]
A fix is on its way

**Comment by isontheline** [comment]
WebSSH 25.7.1305 is now available for beta testing : https://testflight.apple.com/join/QSrBK59z
