### ISSUE TITLE
SFTP : File edit on iPadOS floating keyboard issues

### ISSUE THREAD

**Issue by janwiesemann** [isontheline/pro.webssh.net#1083]
# Bug description
_Put here a clear and concise description of what the bug is_

The floating keyboard on the file edit page of the SFT feature on iPadOS does not seam to be handled properly.

If you unpin the keyboard and switch to the floating version, about half of the screen is turning gray. If you start moving it around, the whole screen turns gray.

Also there isn’t a real way to close the keyboard.

# Screenshots
_If applicable, add screenshots to help explain your problem_

![IMG_0070](https://github.com/isontheline/pro.webssh.net/assets/1347201/3a5e99d1-796f-47db-8e3d-735f7ed8c57f)
![IMG_0068](https://github.com/isontheline/pro.webssh.net/assets/1347201/df8cb9ee-a959-41b2-8fca-3b52e0689a52)
![IMG_0069](https://github.com/isontheline/pro.webssh.net/assets/1347201/8e67618d-b35d-4738-a158-85f8decb1484)

# Steps to reproduce
1. open a file over SFTP
2. switch to the floating keyboard

thank you for your development and your app <3

**Comment by isontheline** [comment]
Hello @janwiesemann 👋
Thank you so much for all your three issues 🙏

I will enhance SFTP File Editor in the next milestone so your issue will be fixed as well

**Comment by isontheline** [comment]
Now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z

**Comment by janwiesemann** [comment]
Thanks 🙏🏻
