### ISSUE TITLE
Stuck in terminal when after coming back from another application or desktop

### ISSUE THREAD

**Issue by B1aSst** [isontheline/pro.webssh.net#1088]
# Bug description
When switching from desktop or full screen application, I got stuck in the terminal. I can't write anything anymore. I need to close the terminal and open another one. It's very annoying when doing debugging.
_Put here a clear and concise description of what the bug is_

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. Open a ssh connection
2. Switch to another desktop or full screen application
3. Come back to the previously opened ssh connection
5. Error is thrown

**Comment by isontheline** [comment]
Thank you @B1aSst for your feedback

I'm searching the root issue.

I'm merging your issue with this one : https://github.com/isontheline/pro.webssh.net/issues/1025

**Comment by isontheline** [comment]
Hello @B1aSst 👋 

Could you try the latest beta release please?

https://testflight.apple.com/join/QSrBK59z

**Comment by B1aSst** [comment]
Hello
Just tested the beta version 27.2 and I do not encounter the issue anymore.
Thanks you for your action and for developping this app.
Have a good day !

**Comment by isontheline** [comment]
Hello @B1aSst 👋

You're Welcome!
Thank you so much for your feedback 🙏
