### ISSUE TITLE
.local unsupported?

### ISSUE THREAD

**Issue by DDoS** [isontheline/pro.webssh.net#1091]
# Bug description
I'm trying to connect to a device on my local network using a ".local" address. I can ping it (from the app), but connections fail on DNS resolution. Is this unsupported?

# Steps to reproduce
1. Add a connect to a ".local" host
2. Try to connect
4. Error is thrown
5. Try to ping
6. No error

**Comment by isontheline** [comment]
Hello @DDoS 👋 

Good catch!
If will check it and make a fix asap

**Comment by isontheline** [comment]
Hello @DDoS 👋

I'm able to connect to .local address out of the box (mba3arnaud.local) :

![Image](https://github.com/isontheline/pro.webssh.net/assets/44212923/e8ce8633-c30e-4856-b8db-5e1a812141d7)

Could you send me your fail logs of WebSSH?
I would like to see it it's related to IPv6 please

**Comment by isontheline** [comment]
IPv6 over IPv4 could be changed inside settings :


![Image](https://github.com/isontheline/pro.webssh.net/assets/44212923/44b62b28-22ca-4f19-9ba0-8645707b0925)

**Comment by DDoS** [comment]
Changing to IPv4 first fixed it.

**Comment by isontheline** [comment]
Thanks for your feedback @DDoS 🙏
