### ISSUE TITLE
Unable to agree up client server  MAC algorithm/ Failed to read Kex init response

### ISSUE THREAD

**Issue by naseemr** [isontheline/pro.webssh.net#1093]
# Bug description
Not able to ssh

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. added server 
2. added ssh key
3. connection failed
4. Error is thrown
Unable to agree up client server  MAC algorithm/ Failed to read Kex init response

**Comment by isontheline** [comment]
Hello @naseemr 👋 

Please post error log about the problem you encountered as it seems to be about : 

https://webssh.net/documentation/help/SSH/terrapin-attack/

**Comment by naseemr** [comment]
[2024-04-07 16:01:37 +0000] [INFO] Thank you so much for using WebSSH
25.7.1306 on iOS 17.4.1 🙏 [2024-04-07 16:02:18 +0000] [INFO] Private Key
(id_rsa_putt.ppk) need to be upgraded [2024-04-07 16:02:18 +0000] [INFO]
Private Key (id_rsa_putt.ppk) has been upgraded [2024-04-07 16:02:35 +0000]
[ERROR] <EngineLog> <Connect_Ssh> <EngineVersion>9.5.0.97</EngineVersion>
<EngineStatus>2</EngineStatus> <connectInner>
<hostname>192.168.86.245</hostname> <port>22</port> <sshConnect>
</sshConnect> <sshSetupConnection>
<clientIdentifier>SSH-2.0-WebSSH_25.7</clientIdentifier>
<initialDataFromSshServer><![CDATA[SSH-2.0-OpenSSH_9.6
]]></initialDataFromSshServer>
<serverVersion>SSH-2.0-OpenSSH_9.6</serverVersion> <serverKex>
<KeyExchangeAlgs> ***@***.***</algorithm>
<algorithm>curve25519-sha256</algorithm> <algorithm>
***@***.***</algorithm>
<algorithm>diffie-hellman-group-exchange-sha256</algorithm>
<algorithm>diffie-hellman-group16-sha512</algorithm>
<algorithm>diffie-hellman-group18-sha512</algorithm>
<algorithm>ext-info-s</algorithm>
***@***.***</algorithm>
</KeyExchangeAlgs> <HostKeyAlgs> <algorithm>rsa-sha2-512</algorithm>
<algorithm>rsa-sha2-256</algorithm> <algorithm>ssh-ed25519</algorithm>
</HostKeyAlgs> <EncCS> ***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncCS> <EncSC> <algorithm>
***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncSC> <MacCS> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacCS> <MacSC> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacSC> <CompCS>
<algorithm>none</algorithm> ***@***.***</algorithm>
</CompCS> <CompSC> <algorithm>none</algorithm>
***@***.***</algorithm>
</CompSC> <ChosenIncomingEncryption>aes128-ctr</ChosenIncomingEncryption>
<ChosenOutgoingEncryptoin>aes128-ctr</ChosenOutgoingEncryptoin> <error>No
matching mac algorithms supported.</error> <error>Unable to agree upon
server-to-client MAC algorithm.</error> <error>No matching mac algorithms
supported.</error> <error>Unable to agree upon client-to-server MAC
algorithm.</error>
<ChosenIncomingCompression>none</ChosenIncomingCompression>
<ChosenOutgoingCompression>none</ChosenOutgoingCompression>
<ChosenKexAlgorithm>curve25519-sha256</ChosenKexAlgorithm>
<ChosenHostKeyAlgorithm>ssh-ed25519</ChosenHostKeyAlgorithm> </serverKex>
<sshRawPacket>Socket connection closed.</sshRawPacket>
<sshKexInitResponse>Socket connection closed.</sshKexInitResponse>
<error>Failed to read KEX init response</error> </sshSetupConnection>
<sshConnect> </sshConnect> <sshSetupConnection>
<clientIdentifier>SSH-2.0-WebSSH_25.7</clientIdentifier>
<initialDataFromSshServer><![CDATA[SSH-2.0-OpenSSH_9.6
]]></initialDataFromSshServer>
<serverVersion>SSH-2.0-OpenSSH_9.6</serverVersion> <serverKex>
<KeyExchangeAlgs> ***@***.***</algorithm>
<algorithm>curve25519-sha256</algorithm> <algorithm>
***@***.***</algorithm>
<algorithm>diffie-hellman-group-exchange-sha256</algorithm>
<algorithm>diffie-hellman-group16-sha512</algorithm>
<algorithm>diffie-hellman-group18-sha512</algorithm>
<algorithm>ext-info-s</algorithm>
***@***.***</algorithm>
</KeyExchangeAlgs> <HostKeyAlgs> <algorithm>rsa-sha2-512</algorithm>
<algorithm>rsa-sha2-256</algorithm> <algorithm>ssh-ed25519</algorithm>
</HostKeyAlgs> <EncCS> ***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncCS> <EncSC> <algorithm>
***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncSC> <MacCS> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacCS> <MacSC> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacSC> <CompCS>
<algorithm>none</algorithm> ***@***.***</algorithm>
</CompCS> <CompSC> <algorithm>none</algorithm>
***@***.***</algorithm>
</CompSC> <ChosenIncomingEncryption>aes128-ctr</ChosenIncomingEncryption>
<ChosenOutgoingEncryptoin>aes128-ctr</ChosenOutgoingEncryptoin> <error>No
matching mac algorithms supported.</error> <error>Unable to agree upon
server-to-client MAC algorithm.</error> <error>No matching mac algorithms
supported.</error> <error>Unable to agree upon client-to-server MAC
algorithm.</error>
<ChosenIncomingCompression>none</ChosenIncomingCompression>
<ChosenOutgoingCompression>none</ChosenOutgoingCompression>
<ChosenKexAlgorithm>curve25519-sha256</ChosenKexAlgorithm>
<ChosenHostKeyAlgorithm>ssh-ed25519</ChosenHostKeyAlgorithm> </serverKex>
<sshRawPacket>Socket connection closed.</sshRawPacket>
<sshKexInitResponse>Socket connection closed.</sshKexInitResponse>
<error>Failed to read KEX init response</error> </sshSetupConnection>
</connectInner> <error>Failed.</error> </Connect_Ssh> </EngineLog>
[2024-04-07 16:02:36 +0000] [ERROR] Error : Can not establish connection to
192.168.86.245 [2024-04-07 16:18:34 +0000] [ERROR] <EngineLog>
<Connect_Ssh> <EngineVersion>9.5.0.97</EngineVersion>
<EngineStatus>2</EngineStatus> <connectInner>
<hostname>192.168.86.245</hostname> <port>22</port> <sshConnect>
</sshConnect> <sshSetupConnection>
<clientIdentifier>SSH-2.0-WebSSH_25.7</clientIdentifier>
<initialDataFromSshServer><![CDATA[SSH-2.0-OpenSSH_9.6
]]></initialDataFromSshServer>
<serverVersion>SSH-2.0-OpenSSH_9.6</serverVersion> <serverKex>
<KeyExchangeAlgs> ***@***.***</algorithm>
<algorithm>curve25519-sha256</algorithm> <algorithm>
***@***.***</algorithm>
<algorithm>diffie-hellman-group-exchange-sha256</algorithm>
<algorithm>diffie-hellman-group16-sha512</algorithm>
<algorithm>diffie-hellman-group18-sha512</algorithm>
<algorithm>ext-info-s</algorithm>
***@***.***</algorithm>
</KeyExchangeAlgs> <HostKeyAlgs> <algorithm>rsa-sha2-512</algorithm>
<algorithm>rsa-sha2-256</algorithm> <algorithm>ssh-ed25519</algorithm>
</HostKeyAlgs> <EncCS> ***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncCS> <EncSC> <algorithm>
***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncSC> <MacCS> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacCS> <MacSC> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacSC> <CompCS>
<algorithm>none</algorithm> ***@***.***</algorithm>
</CompCS> <CompSC> <algorithm>none</algorithm>
***@***.***</algorithm>
</CompSC> <ChosenIncomingEncryption>aes128-ctr</ChosenIncomingEncryption>
<ChosenOutgoingEncryptoin>aes128-ctr</ChosenOutgoingEncryptoin> <error>No
matching mac algorithms supported.</error> <error>Unable to agree upon
server-to-client MAC algorithm.</error> <error>No matching mac algorithms
supported.</error> <error>Unable to agree upon client-to-server MAC
algorithm.</error>
<ChosenIncomingCompression>none</ChosenIncomingCompression>
<ChosenOutgoingCompression>none</ChosenOutgoingCompression>
<ChosenKexAlgorithm>curve25519-sha256</ChosenKexAlgorithm>
<ChosenHostKeyAlgorithm>ssh-ed25519</ChosenHostKeyAlgorithm> </serverKex>
<sshRawPacket>Socket connection closed.</sshRawPacket>
<sshKexInitResponse>Socket connection closed.</sshKexInitResponse>
<error>Failed to read KEX init response</error> </sshSetupConnection>
<sshConnect> </sshConnect> <sshSetupConnection>
<clientIdentifier>SSH-2.0-WebSSH_25.7</clientIdentifier>
<initialDataFromSshServer><![CDATA[SSH-2.0-OpenSSH_9.6
]]></initialDataFromSshServer>
<serverVersion>SSH-2.0-OpenSSH_9.6</serverVersion> <serverKex>
<KeyExchangeAlgs> ***@***.***</algorithm>
<algorithm>curve25519-sha256</algorithm> <algorithm>
***@***.***</algorithm>
<algorithm>diffie-hellman-group-exchange-sha256</algorithm>
<algorithm>diffie-hellman-group16-sha512</algorithm>
<algorithm>diffie-hellman-group18-sha512</algorithm>
<algorithm>ext-info-s</algorithm>
***@***.***</algorithm>
</KeyExchangeAlgs> <HostKeyAlgs> <algorithm>rsa-sha2-512</algorithm>
<algorithm>rsa-sha2-256</algorithm> <algorithm>ssh-ed25519</algorithm>
</HostKeyAlgs> <EncCS> ***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncCS> <EncSC> <algorithm>
***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncSC> <MacCS> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacCS> <MacSC> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacSC> <CompCS>
<algorithm>none</algorithm> ***@***.***</algorithm>
</CompCS> <CompSC> <algorithm>none</algorithm>
***@***.***</algorithm>
</CompSC> <ChosenIncomingEncryption>aes128-ctr</ChosenIncomingEncryption>
<ChosenOutgoingEncryptoin>aes128-ctr</ChosenOutgoingEncryptoin> <error>No
matching mac algorithms supported.</error> <error>Unable to agree upon
server-to-client MAC algorithm.</error> <error>No matching mac algorithms
supported.</error> <error>Unable to agree upon client-to-server MAC
algorithm.</error>
<ChosenIncomingCompression>none</ChosenIncomingCompression>
<ChosenOutgoingCompression>none</ChosenOutgoingCompression>
<ChosenKexAlgorithm>curve25519-sha256</ChosenKexAlgorithm>
<ChosenHostKeyAlgorithm>ssh-ed25519</ChosenHostKeyAlgorithm> </serverKex>
<sshRawPacket>Socket connection closed.</sshRawPacket>
<sshKexInitResponse>Socket connection closed.</sshKexInitResponse>
<error>Failed to read KEX init response</error> </sshSetupConnection>
</connectInner> <error>Failed.</error> </Connect_Ssh> </EngineLog>
[2024-04-07 16:18:35 +0000] [ERROR] Error : Can not establish connection to
192.168.86.245 [2024-04-07 16:18:46 +0000] [ERROR] <EngineLog>
<Connect_Ssh> <EngineVersion>9.5.0.97</EngineVersion>
<EngineStatus>2</EngineStatus> <connectInner>
<hostname>192.168.86.245</hostname> <port>22</port> <sshConnect>
</sshConnect> <sshSetupConnection>
<clientIdentifier>SSH-2.0-WebSSH_25.7</clientIdentifier>
<initialDataFromSshServer><![CDATA[SSH-2.0-OpenSSH_9.6
]]></initialDataFromSshServer>
<serverVersion>SSH-2.0-OpenSSH_9.6</serverVersion> <serverKex>
<KeyExchangeAlgs> ***@***.***</algorithm>
<algorithm>curve25519-sha256</algorithm> <algorithm>
***@***.***</algorithm>
<algorithm>diffie-hellman-group-exchange-sha256</algorithm>
<algorithm>diffie-hellman-group16-sha512</algorithm>
<algorithm>diffie-hellman-group18-sha512</algorithm>
<algorithm>ext-info-s</algorithm>
***@***.***</algorithm>
</KeyExchangeAlgs> <HostKeyAlgs> <algorithm>rsa-sha2-512</algorithm>
<algorithm>rsa-sha2-256</algorithm> <algorithm>ssh-ed25519</algorithm>
</HostKeyAlgs> <EncCS> ***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncCS> <EncSC> <algorithm>
***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncSC> <MacCS> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacCS> <MacSC> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacSC> <CompCS>
<algorithm>none</algorithm> ***@***.***</algorithm>
</CompCS> <CompSC> <algorithm>none</algorithm>
***@***.***</algorithm>
</CompSC> <ChosenIncomingEncryption>aes128-ctr</ChosenIncomingEncryption>
<ChosenOutgoingEncryptoin>aes128-ctr</ChosenOutgoingEncryptoin> <error>No
matching mac algorithms supported.</error> <error>Unable to agree upon
server-to-client MAC algorithm.</error> <error>No matching mac algorithms
supported.</error> <error>Unable to agree upon client-to-server MAC
algorithm.</error>
<ChosenIncomingCompression>none</ChosenIncomingCompression>
<ChosenOutgoingCompression>none</ChosenOutgoingCompression>
<ChosenKexAlgorithm>curve25519-sha256</ChosenKexAlgorithm>
<ChosenHostKeyAlgorithm>ssh-ed25519</ChosenHostKeyAlgorithm> </serverKex>
<sshRawPacket>Socket connection closed.</sshRawPacket>
<sshKexInitResponse>Socket connection closed.</sshKexInitResponse>
<error>Failed to read KEX init response</error> </sshSetupConnection>
<sshConnect> </sshConnect> <sshSetupConnection>
<clientIdentifier>SSH-2.0-WebSSH_25.7</clientIdentifier>
<initialDataFromSshServer><![CDATA[SSH-2.0-OpenSSH_9.6
]]></initialDataFromSshServer>
<serverVersion>SSH-2.0-OpenSSH_9.6</serverVersion> <serverKex>
<KeyExchangeAlgs> ***@***.***</algorithm>
<algorithm>curve25519-sha256</algorithm> <algorithm>
***@***.***</algorithm>
<algorithm>diffie-hellman-group-exchange-sha256</algorithm>
<algorithm>diffie-hellman-group16-sha512</algorithm>
<algorithm>diffie-hellman-group18-sha512</algorithm>
<algorithm>ext-info-s</algorithm>
***@***.***</algorithm>
</KeyExchangeAlgs> <HostKeyAlgs> <algorithm>rsa-sha2-512</algorithm>
<algorithm>rsa-sha2-256</algorithm> <algorithm>ssh-ed25519</algorithm>
</HostKeyAlgs> <EncCS> ***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncCS> <EncSC> <algorithm>
***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncSC> <MacCS> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacCS> <MacSC> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacSC> <CompCS>
<algorithm>none</algorithm> ***@***.***</algorithm>
</CompCS> <CompSC> <algorithm>none</algorithm>
***@***.***</algorithm>
</CompSC> <ChosenIncomingEncryption>aes128-ctr</ChosenIncomingEncryption>
<ChosenOutgoingEncryptoin>aes128-ctr</ChosenOutgoingEncryptoin> <error>No
matching mac algorithms supported.</error> <error>Unable to agree upon
server-to-client MAC algorithm.</error> <error>No matching mac algorithms
supported.</error> <error>Unable to agree upon client-to-server MAC
algorithm.</error>
<ChosenIncomingCompression>none</ChosenIncomingCompression>
<ChosenOutgoingCompression>none</ChosenOutgoingCompression>
<ChosenKexAlgorithm>curve25519-sha256</ChosenKexAlgorithm>
<ChosenHostKeyAlgorithm>ssh-ed25519</ChosenHostKeyAlgorithm> </serverKex>
<sshRawPacket>Socket connection closed.</sshRawPacket>
<sshKexInitResponse>Socket connection closed.</sshKexInitResponse>
<error>Failed to read KEX init response</error> </sshSetupConnection>
</connectInner> <error>Failed.</error> </Connect_Ssh> </EngineLog>
[2024-04-07 16:18:47 +0000] [ERROR] Error : Can not establish connection to
192.168.86.245 [2024-04-07 18:24:11 +0000] [INFO] Want to save SFTP Editor
state [2024-04-07 18:25:11 +0000] [INFO] Want to save SFTP Editor state
[2024-04-07 18:25:55 +0000] [ERROR] <EngineLog> <Connect_Ssh>
<EngineVersion>9.5.0.97</EngineVersion> <EngineStatus>2</EngineStatus>
<connectInner> <hostname>192.168.86.245</hostname> <port>22</port>
<sshConnect> </sshConnect> <sshSetupConnection>
<clientIdentifier>SSH-2.0-WebSSH_25.7</clientIdentifier>
<initialDataFromSshServer><![CDATA[SSH-2.0-OpenSSH_9.6
]]></initialDataFromSshServer>
<serverVersion>SSH-2.0-OpenSSH_9.6</serverVersion> <serverKex>
<KeyExchangeAlgs> ***@***.***</algorithm>
<algorithm>curve25519-sha256</algorithm> <algorithm>
***@***.***</algorithm>
<algorithm>diffie-hellman-group-exchange-sha256</algorithm>
<algorithm>diffie-hellman-group16-sha512</algorithm>
<algorithm>diffie-hellman-group18-sha512</algorithm>
<algorithm>ext-info-s</algorithm>
***@***.***</algorithm>
</KeyExchangeAlgs> <HostKeyAlgs> <algorithm>rsa-sha2-512</algorithm>
<algorithm>rsa-sha2-256</algorithm> <algorithm>ssh-ed25519</algorithm>
</HostKeyAlgs> <EncCS> ***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncCS> <EncSC> <algorithm>
***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncSC> <MacCS> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacCS> <MacSC> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacSC> <CompCS>
<algorithm>none</algorithm> ***@***.***</algorithm>
</CompCS> <CompSC> <algorithm>none</algorithm>
***@***.***</algorithm>
</CompSC> <ChosenIncomingEncryption>aes128-ctr</ChosenIncomingEncryption>
<ChosenOutgoingEncryptoin>aes128-ctr</ChosenOutgoingEncryptoin> <error>No
matching mac algorithms supported.</error> <error>Unable to agree upon
server-to-client MAC algorithm.</error> <error>No matching mac algorithms
supported.</error> <error>Unable to agree upon client-to-server MAC
algorithm.</error>
<ChosenIncomingCompression>none</ChosenIncomingCompression>
<ChosenOutgoingCompression>none</ChosenOutgoingCompression>
<ChosenKexAlgorithm>curve25519-sha256</ChosenKexAlgorithm>
<ChosenHostKeyAlgorithm>ssh-ed25519</ChosenHostKeyAlgorithm> </serverKex>
<sshRawPacket>Socket connection closed.</sshRawPacket>
<sshKexInitResponse>Socket connection closed.</sshKexInitResponse>
<error>Failed to read KEX init response</error> </sshSetupConnection>
<sshConnect> </sshConnect> <sshSetupConnection>
<clientIdentifier>SSH-2.0-WebSSH_25.7</clientIdentifier>
<initialDataFromSshServer><![CDATA[SSH-2.0-OpenSSH_9.6
]]></initialDataFromSshServer>
<serverVersion>SSH-2.0-OpenSSH_9.6</serverVersion> <serverKex>
<KeyExchangeAlgs> ***@***.***</algorithm>
<algorithm>curve25519-sha256</algorithm> <algorithm>
***@***.***</algorithm>
<algorithm>diffie-hellman-group-exchange-sha256</algorithm>
<algorithm>diffie-hellman-group16-sha512</algorithm>
<algorithm>diffie-hellman-group18-sha512</algorithm>
<algorithm>ext-info-s</algorithm>
***@***.***</algorithm>
</KeyExchangeAlgs> <HostKeyAlgs> <algorithm>rsa-sha2-512</algorithm>
<algorithm>rsa-sha2-256</algorithm> <algorithm>ssh-ed25519</algorithm>
</HostKeyAlgs> <EncCS> ***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncCS> <EncSC> <algorithm>
***@***.***</algorithm>
***@***.***</algorithm>
<algorithm>aes256-ctr</algorithm> <algorithm>aes192-ctr</algorithm>
<algorithm>aes128-ctr</algorithm> </EncSC> <MacCS> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacCS> <MacSC> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> <algorithm>
***@***.***</algorithm> </MacSC> <CompCS>
<algorithm>none</algorithm> ***@***.***</algorithm>
</CompCS> <CompSC> <algorithm>none</algorithm>
***@***.***</algorithm>
</CompSC> <ChosenIncomingEncryption>aes128-ctr</ChosenIncomingEncryption>
<ChosenOutgoingEncryptoin>aes128-ctr</ChosenOutgoingEncryptoin> <error>No
matching mac algorithms supported.</error> <error>Unable to agree upon
server-to-client MAC algorithm.</error> <error>No matching mac algorithms
supported.</error> <error>Unable to agree upon client-to-server MAC
algorithm.</error>
<ChosenIncomingCompression>none</ChosenIncomingCompression>
<ChosenOutgoingCompression>none</ChosenOutgoingCompression>
<ChosenKexAlgorithm>curve25519-sha256</ChosenKexAlgorithm>
<ChosenHostKeyAlgorithm>ssh-ed25519</ChosenHostKeyAlgorithm> </serverKex>
<sshRawPacket>Socket connection closed.</sshRawPacket>
<sshKexInitResponse>Socket connection closed.</sshKexInitResponse>
<error>Failed to read KEX init response</error> </sshSetupConnection>
</connectInner> <error>Failed.</error> </Connect_Ssh> </EngineLog>
[2024-04-07 18:25:56 +0000] [ERROR] Error : Can not establish connection to
192.168.86.245 [2024-04-07 18:26:11 +0000] [INFO] Want to save SFTP Editor
state [2024-04-07 18:27:12 +0000] [INFO] Want to save SFTP Editor state
[2024-04-07 18:28:12 +0000] [INFO] Want to save SFTP Editor state
[2024-04-07 18:29:12 +0000] [INFO] Want to save SFTP Editor state
[2024-04-07 18:41:36 +0000] [INFO] Want to save SFTP Editor state


Naseem R.

**Comment by isontheline** [comment]
Please enable again the MAC algorithms :
https://webssh.net/documentation/help/SSH/terrapin-attack/#re-enable-etm-mac-algorithms
