### ISSUE TITLE
locked / unlock loop

### ISSUE THREAD

**Issue by stuntsman** [isontheline/pro.webssh.net#1101]
# Bug description
WebSSH 25.8 on iPadOS 17.3.1 is stuck in an unlock loop. A small dialog appears including "Locked" and an Unlock button. Clicking the button makes the dialog go away for a second then it comes back.

# Screenshots
![IMG_0154](https://github.com/isontheline/pro.webssh.net/assets/2482177/58c59fad-d040-4078-af8d-7e8cb8c03913)

# Steps to reproduce
1. Start app
2. Locked dialog appears, click Unlock
3. Dialog goes away for a second. Go to step 2.

Tried but didn't help:

- killing the app (swipe up from bottom for app cards, swipe WebSSH card up to end process)
- changing lock settings under Settings/WebSSH
- disabling FaceID under Settings/WebSSH
- restarting iPad

**Comment by isontheline** [comment]
Hello @stuntsman 👋 

Does Face ID is enrolled on the device?

**Comment by stuntsman** [comment]
Thanks for the tip, I've found that FaceID was disabled:

- a few days earlier I had to disable Passcode on the device temporarily, but then forgot about that
- however disabling Passcode also automatically disabled FaceID (I didn't notice that until now)
- since then WebSSH stuck in an unlock loop
- re-enabling FaceID systemwide solved the issue (iPadOS required setting a passcode too)

Suggestion: the WebSSH unlock dialog could show a message if FaceID and/or passcode is disabled systemwide, as it seems to make unlocking impossible.

**Comment by isontheline** [comment]
Thanks for your strong feedback about your resolution 🙏

I will check if I can retrieve Face ID (full) enrollment from the Apple SDK and so improve WebSSH as well in order to avoid this check loop

**Comment by isontheline** [comment]
Merging this issue with this old one : https://github.com/isontheline/pro.webssh.net/issues/1101#issuecomment-2061731451

**Comment by isontheline** [comment]
Fixed inside the latest beta release : 
https://testflight.apple.com/join/QSrBK59z
