### ISSUE TITLE
Checking roles for stored servers with the same hostname

### ISSUE THREAD

**Issue by casaschi** [isontheline/pro.webssh.net#1106]
# Bug description
in my list of stored servers, I have two entries with the same hostname, for example myhost.example.com
- first entry has server myhost.example.com and allows for SSH and SFTP roles
- second entry has server myhost.example.com, allows only for SSH role, and execute a custom command
The first entry correctly shows in both the SSH and the SFTP server lists.
However, when I tap on the second entry, the app still prompts me to chose between SSH and SFTP, while only the SSH role is configured and SFTP should not be offered.

I have other servers configured with the SSH role only and tapping those the app does not offer an SFTP option, what makes the error case unique is the other server stored with the same hostname and both roles.

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by isontheline** [comment]
Thanks for reaching me out @casaschi 🙏

Does saving (top right button) the second connection again (without any change) fix the problem?

**Comment by casaschi** [comment]
@isontheline no, saving the second connection again does not fix the problem.

**Comment by isontheline** [comment]
On the bad behaviour connection, does only one role is showed on screen?
<img width="340" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/b41a2f79-f2fc-4a1a-8e87-addc2a21e10d">

**Comment by isontheline** [comment]
What's about the icon on the list?
When SSH only it should be this one :
<img width="69" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/20bea745-d5f4-49ef-8590-84c6690332e2">

**Comment by casaschi** [comment]
If that matters, I assigned similar labels to the connections:
- the SSH+SFTP connection is labeled with the hostname
- the SSH only connection is labeled with hostname:command where command is the actual command being executed on SSH

**Comment by isontheline** [comment]
I will check on my side why the icon shows as "SSH/SFTP" instead of SSH only :
> <img width="753" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/a3ff3d0f-5350-4bf6-8df5-c18994640a68">

It should explain the bug
I will come back to you tonight

**Comment by casaschi** [comment]
I should have mentioned, I'm using webssh on iOS, both app and operating system at the latest version.

**Comment by isontheline** [comment]
Could you make these steps please?
1. Edit the connection
2. Choose both roles
3. Save the connection
4. Edit the connection
5. Choose only SSH
6. Save the connection

It should fix the bug in database.

I'm pushing a fix to prevent it

**Comment by casaschi** [comment]
Your fix worked!

Thanks.

**Comment by isontheline** [comment]
Many thanks for your feedback and your support about WebSSH 🙏
