### ISSUE TITLE
Paste from other programs only over one line and not multiple

### ISSUE THREAD

**Issue by srvh** [isontheline/pro.webssh.net#1108]
When I copy and paste several commands from another application (Microsoft Word) to WebSSH...
Commands like this:
```
ls -l /etc
systemctl status apache2
```

Then WebSSH will paste all commands in one line like this:
`ls -l /etc systemctl status apache2`

So these commands are not working correctly.
I have servers on Debian 12. I tried to make the same via macOS Terminal, it is working well. So it is not a problem of servers.

Please, fix it.

**Comment by isontheline** [comment]
Hello @srvh 👋

Thanks for reporting this bug of WebSSH 🙏

I'm adding it to the TODO list

**Comment by srvh** [comment]
I install WebSSH from App Store. Version is 26.3 (1357).
I send you a test screenshot. I do not know how to record video. Just made screenshots of each step and combine in one screenshot.
I tried to change Carriage Return to \n and \r\n - no changes.
![webssh](https://github.com/isontheline/pro.webssh.net/assets/45752596/761127e3-3838-4bb6-9ee6-c4d308de7879)

**Comment by isontheline** [comment]
On another host (Ubuntu 16) and TextEdit paste also works :
![paste2](https://github.com/isontheline/pro.webssh.net/assets/44212923/4718f6cc-0c75-4776-9b6f-7706a20bf842)

That's strange.

I'm sure the bug could exists but can't reproduce it :(

**Comment by srvh** [comment]
> I have found an addiction. If I use CMD + V button - then it go to one line as on screenshot higher. But if I use right mouse button in WebSSH and then choose Paste, then working well.

Check this, please

**Comment by isontheline** [comment]
I'm double checking anyway

**Comment by srvh** [comment]
Is there any settings which can lead this situation?

**Comment by isontheline** [comment]
@srvh Please try out WebSSH 26.4.1360 : https://testflight.apple.com/join/QSrBK59z

**Comment by srvh** [comment]
I installed this version. It is working correctly now!
I can paste anything via CMD + V.

**Comment by isontheline** [comment]
Glad to hear that ;)

Thank you for your strong feedback!
