### ISSUE TITLE
Failure to handle switch from landscape to portrait orientation 

### ISSUE THREAD

**Issue by rce1086** [isontheline/pro.webssh.net#1111]
# Bug description
_Put here a clear and concise description of what the bug is_
If I connect to a host via ssh, opening the connection in landscape orientation, and then switch the iPad to normal portrait mode, then the keyboard covers the current input lines
# Screenshots
_If applicable, add screenshots to help explain your problem_
![IMG_0164](https://github.com/isontheline/pro.webssh.net/assets/8218359/71bcf713-eea6-4c71-a3bd-27113331e85f)
![IMG_0163](https://github.com/isontheline/pro.webssh.net/assets/8218359/d6a69359-8638-43ed-879c-ce8ddc6878c7)

# Steps to reproduce
1. Open connect in landscape mode
2. Switch to portrait mode
3. 
4. Problem is apparent, as per screen shots, which were taken immediately one after the other, just switching orientation in between…

**Comment by rce1086** [comment]
Pictures are attached in 2,1 order, not the more logical 1,2: you can see from the presence of the sidebar that this one is landscape.

**Comment by isontheline** [comment]
Hello @rce1086 👋 

Many thanks for your feedback about this issue 🙏

I'm planning it for a fix

I wish you a nice day ☀️

**Comment by isontheline** [comment]
I'm able to reproduce every time when launching the connection in landscape (as you described above).
Will work on it asap

**Comment by isontheline** [comment]
A fix should be available tomorrow

**Comment by isontheline** [comment]
@rce1086 Please try the latest beta release : https://testflight.apple.com/join/QSrBK59z
