### ISSUE TITLE
Unlock with Apple Watch

### ISSUE THREAD

**Issue by tonvan-entrepid** [isontheline/pro.webssh.net#1119]
# Bug description
I use WebSSH Pro version on Macbook 
I turn on "Password Authentication" in settings
and everytime WebSSH open, it will require password to unlock
and I use apple watch(AW) to unlock instead input password
when WebSSH appear, the popup notice can use AW to unlock, I can feel AW vibrate 2 times as everytime use AW to unlock on macbook
but the confirm screen do not show to AW as usually

Device model
1.Macbook  : Sonoma 14.4.1 (23E224) , M1 pro 14inch
2.AW :  Watch OS 10.4(21T216) , SE 2022 Model

# Screenshots
Screen to unlock by AW on macbook
<img width="792" alt="Screenshot 2024-05-08 at 15 38 57" src="https://github.com/isontheline/pro.webssh.net/assets/51903508/916e61ad-05e2-4d18-842c-0362d049a19e">
Screen should show on AW (I use another app as example)
![IMG_8523](https://github.com/isontheline/pro.webssh.net/assets/51903508/8c13b2ec-63c5-4b1d-ab70-52160b46bd69)

# Steps to reproduce
1. open WebSSH on macbook
2. Screen use AW to unlock appear
3. On AW vibrate 2 times to notice have request use AW to unlock
4. But no screen request unlock appear on AW

**Comment by isontheline** [comment]
Hello @tonvan-entrepid 👋

Many thanks for your feedback 🙏

I will check it as soon as possible and will come back to you "shortly".

**Comment by isontheline** [comment]
I'm sorry @tonvan-entrepid I've just testes on my MBA and AW and it works as expected -> unlock occurs

<img width="737" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/721f025d-30cd-4dff-9545-497665d25634">
