### ISSUE TITLE
Tool : DNS Lookup

### ISSUE THREAD

**Issue by TCB13** [isontheline/pro.webssh.net#1121]
Hi,

It would be good to have a tool to run DNS queries with options to run the popular record types and the ability to set the DNS server to use. Look at the following example from the [HE Network Tools](https://apps.apple.com/app/id858241710):

![image](https://github.com/isontheline/pro.webssh.net/assets/6315832/529cf060-8bbe-4ae2-b74b-0698bc618cf2)

They've the most common record types and an input field for the DNS server. The field also shows the current server the system has picked from DHCP and still provides the ability to override it.

Clicking on a result should provide two options:

1) Copy - copies the result;
2) ping - only for IP addresses and domain names, should open the ping tool and run a ping to the address

Thanks.

**Comment by isontheline** [comment]
Hi @TCB13 👋

I like this layout!

I'm planning it

**Comment by isontheline** [comment]
I'm working on it and should be alive within 4 weeks

**Comment by isontheline** [comment]
A first attempt is available here : https://testflight.apple.com/join/QSrBK59z
