### ISSUE TITLE
Allow to choose one of the system font(s)

### ISSUE THREAD

**Issue by fpiraneo** [isontheline/pro.webssh.net#1125]
# Feature description
There are some readability hints that every developer / system engineer appreciate; one of them is the possibility to use the favorite font on the console and some typographic settings like letter spacings (that should be wider with small fonts). This will increase readability (and of course productivity).

**Comment by isontheline** [comment]
Are we talking about system fonts already available on the device?

**Comment by fpiraneo** [comment]
> Are we talking about system fonts already available on the device?

Yes of course!

**Comment by isontheline** [comment]
Thank you @fpiraneo for your feedback!
I will enhance WebSSH in this way

**Comment by isontheline** [comment]
I'm merging your issue with #60
