### ISSUE TITLE
Uploading files from iPad / iPhone to server through SFTP

### ISSUE THREAD

**Issue by 9201170** [isontheline/pro.webssh.net#113]
Ability to allow moving and copying files from iPad / iPhone to server

**Comment by isontheline** [comment]
Hello @9201170 👋
Thanks for your issue!

Similar to #87 

Your issue is now planned

Have a nice day☀️

**Comment by isontheline** [comment]
Hello 👋

I'm moving this issue to #114 in order to track all SFTP enhancements needed.

Have a nice day. ☀️

**Comment by isontheline** [comment]
Working on upload from iOS to server through SFTP

**Comment by isontheline** [comment]
Hello @9201170 👋

Will be available on TestFlight in a few minutes : https://testflight.apple.com/join/QSrBK59z

Have a nice day ☀️

**Comment by isontheline** [comment]
Download feature will be inside https://github.com/isontheline/pro.webssh.net/issues/87

**Comment by isontheline** [comment]
Hello @9201170 

Could you try 14.9.3?
