### ISSUE TITLE
Preserve Window Settings Across Sessions

### ISSUE THREAD

**Issue by nilswald** [isontheline/pro.webssh.net#1131]
# Feature description

As a user, I want the application to remember the size and position of its window so that I can maintain a consistent viewing experience across sessions.

**Comment by isontheline** [comment]
Hello Nils 👋

There is a setting inside WebSSH :
<img width="621" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/bfa9227b-a36e-4155-9093-1dc3ef87160f">

Could you try it?

**Comment by nilswald** [comment]
excellent 👍.. sorry, I missed that ... – rtfm, I guess ;)

**Comment by isontheline** [comment]
No problem ;)

(NOT in the FM however)
