### ISSUE TITLE
Consistent Sort Order for Connections in Sidebar

### ISSUE THREAD

**Issue by nilswald** [isontheline/pro.webssh.net#1132]
# Feature description

Connections in the sidebar should be displayed following a specific sort order that is visible and understandable to the user. Possible sorting criteria could include alphabetical, most recently opened, or custom order set by the user.

**Comment by isontheline** [comment]
No problem @nilswald I will it sort alphabetically 

Thanks for your issue 🙏

**Comment by isontheline** [comment]
Sort now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
