### ISSUE TITLE
Web Browser : Ability to share URL

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#1141]
On iOS, the ‘help’ button which opens up a browser window to GitHub, does not open as a ‘session’. This means I can’t easily switch from my ssh session and making a comment here on GitHub. Missed opportunity as lots of room for session n right of screen.

_Originally posted by @JohnCronk79 in https://github.com/isontheline/pro.webssh.net/discussions/992#discussioncomment-9784063_

**Comment by JohnCronk79** [comment]
Thanks,

BTW, rather then open a safari browser window, perhaps it could open ‘the
default browser’, in my case, Chrome (iPad).

John

**Comment by isontheline** [comment]
@JohnCronk79 You can now try the feature on the latest beta release : 
https://testflight.apple.com/join/QSrBK59z
