### ISSUE TITLE
Connections without a name : Ability to launch a favorite server from Home Screen Quick Actions

### ISSUE THREAD

**Issue by akuropka** [isontheline/pro.webssh.net#1142]
# Relevant feature
https://github.com/isontheline/pro.webssh.net/issues/1082

# Bug description
I am trying to use Home Screen Quick Actions to launch a server. I have set up servers as favorite and enabled the menu option but it seems no server appears. Other items such as meshREPL, Ping, Browser do appear if enabled.

# Hard- / Software
iPhone 11 Pro on iOS 17.5.1 with WebSSH 26.4.1360 (App Store)
iPhone 15 Pro Max on iOS 18 DB1 with WebSSH  26.4.1360 (Testflight)

# Screenshots
![Screenshot 2024-06-17 at 17 59 05 jpeg](https://github.com/isontheline/pro.webssh.net/assets/22570574/29114227-a854-445e-9847-37c6b7cff0e1)
![Screenshot 2024-06-17 at 17 59 46 jpeg](https://github.com/isontheline/pro.webssh.net/assets/22570574/c15bb857-f44b-43f2-b575-5a867fdcd124)
![Screenshot 2024-06-17 at 18 00 07 jpeg](https://github.com/isontheline/pro.webssh.net/assets/22570574/483c5093-e1e4-4295-96eb-64f9de1ae226)

**Comment by isontheline** [comment]
Hello @akuropka 👋

Please check that your connections have a "title"

**Comment by akuropka** [comment]
Hello @isontheline, 🙋‍♂️
this does the trick, thank you. 🙏 
Good to know… I do not use names since the connection name (username@host) is clear enough for me. 😉 Maybe this can be implemented as fallback or somewhere a hint placed.
By the way, it would be helpful, too, to be able just to favor one connection type, e.g. SSH, to avoid selection every time. 🧐

**Comment by isontheline** [comment]
Hello Andreas 👋

I'll implement the fallback 😉

> By the way, it would be helpful, too, to be able just to favor one connection type, e.g. SSH, to avoid selection every time. 🧐

Sure but I "don't" know how to do it easily and how to present a clean GUI to the user

**Comment by isontheline** [comment]
> By the way, it would be helpful, too, to be able just to favor one connection type, e.g. SSH, to avoid selection every time. 🧐

@akuropka I will open another issue for this new behaviour

I think I will be able to release the fallback later tomorrow

**Comment by isontheline** [comment]
Fallback now available on beta : https://testflight.apple.com/join/QSrBK59z

**Comment by akuropka** [comment]
@isontheline, works perfect, thanks.

**Comment by isontheline** [comment]
Thanks for your feedback @akuropka !

And thousand warm thanks for your support about my work 🙏 🎉
Thank you!!!
