### ISSUE TITLE
Please help me how to use forward 

### ISSUE THREAD

**Issue by Sharonzhao1** [isontheline/pro.webssh.net#1148]
# Bug description
_Put here a clear and concise description of what the bug is_
Can’t use 
Please help me how to use 
181.215.154.30
41647
# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by isontheline** [comment]
Hello @Sharonzhao1 👋

Documentation about Port Forwarding is available here : https://webssh.net/documentation/help/networking/port-forwarding/
