### ISSUE TITLE
Telnet Support

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#115]
**Describe the feature**
Brilliant app. I bought the paid one now. I just wish it supported Telnet so I can have one app for all my needs. Thx.

By **Chaskayy** on *App Store* (GB)

**Comment by isontheline** [comment]
This app is beautiful, the icon is simplistic, and it’s functional. What more could you ask for? Oh there’s also the ability to port-knock to open various ports built into the connection’s config’s themselves. 

I just have one request, and that’s somewhere down the line, if you could add telnet. I have some old machines that require a separate app for telnet and I much prefer this one.

By **Austen1335** on *App Store* (US)

**Comment by isontheline** [comment]
Dear team,

Why is Telnet not supported ? I know it is less secure and I do not or rarely use it myself.
Nevertheless some public servers like IPv4 or IPv6 BGP route servers, like “[route-server.opentransit.net](http://route-server.opentransit.net/)” are available by Telnet access alone.

NB : I am only using WebSSH on iPad

**Martial**

**Comment by isontheline** [comment]
> Would you ever consider adding a telnet option to WebSSH? Terminus has an option for ssh connections to be telnet instead of ssh (a slider in the connection for telnet)?
>
> Regards Paul

Hello Paul 👋

Telnet support have been requested many years ago : https://github.com/isontheline/pro.webssh.net/issues/115
I need to find some time to implement it properly inside WebSSH.

Are you using it a lot?

Kind regards,

> Hello
>
> I probably use it more for bulletin boards than ssh. I only have one connection with ssh an having a telnet option would mean I would probably only need WebSSH for terminal connections.
>
> Regards Paul

**Comment by jedis00** [comment]
Just bought pro and came here to ask for Telnet support. I am using it daily to manage some Netgear hotspot devices. Please consider adding support including password-less Telnet. Thanks!

**Comment by isontheline** [comment]
Thank you so much for your feedback and for your purchase @jedis00 🙏

I'm adding this issue to the roadmap

**Comment by isontheline** [comment]
For @isontheline work :
* https://hub.docker.com/r/jaredharringtongibbs/telnet-server
* https://github.com/Jared-Harrington-Gibbs/Docker-Files/blob/master/telnet-server/Dockerfile

**Comment by isontheline** [comment]
Hello everybody 👋

Telnet implementation is now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
