### ISSUE TITLE
ed25519 keys on ios 17.5.1 broken?

### ISSUE THREAD

**Issue by DonPablo1010** [isontheline/pro.webssh.net#1154]
# Bug description
Since this morning i‘m not able to ssh into any of my safed host on all ios devices with your app. The ios devoce seeems not be able to use the safed ssh keys. It asks fo passphrase even if there is none (empty) or at keys with known and safed passsphrase the key is no accessable.

# Screenshots
![IMG_0301](https://github.com/user-attachments/assets/8405ff57-5556-47b8-868f-dd007b395b7c)

# Steps to reproduce
1. open webssh
2. try to connect one of saved hosts
3. ssh key is use automaticly
4. Error is thrown

**Comment by isontheline** [comment]
Merging with #1153
