### ISSUE TITLE
unableToGenerate & unableToLoadPrivateKey

### ISSUE THREAD

**Issue by bernhard-roessler** [isontheline/pro.webssh.net#1155]
Since today i have some troubles with generating and loading private keys.

Error Message while generation:
An error has been occured while generating a new Private Key : unableToGenerate

Error while connection:
unable to parse the private key.

Parsing an existing one is also not working since today. (yesterday - it works without any troubles)

Webssh Version: 26.7

**Comment by isontheline** [comment]
Merging with #1153
