### ISSUE TITLE
Serious Problem - WebSSH no longer connects with SSH key - request key passphrase when none is used

### ISSUE THREAD

**Issue by FredK27** [isontheline/pro.webssh.net#1157]
# Bug description
After the last update, WebSSH on macOS is asking for a key passphrase for keys that do not use a passphrase

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. Just try to connect with ssh to a server using a key without a passphrase
2. 
3. 
4. Error is thrown

**Comment by FredK27** [comment]
Standard SSH with same keys works fine from a terminal box on macOS. I suspect that WebSSH is corrupting the iCloud store where its settings are saved. I am seeing the failure in WebSSH on multiple macOS machines here. They all exhibit the same but right now. This problem just manifested itself in the last few days.

**Comment by isontheline** [comment]
Please check https://github.com/isontheline/pro.webssh.net/issues/1153
