### ISSUE TITLE
Unable to Connect to SSH/SFTP if password is blank

### ISSUE THREAD

**Issue by pasutafukurou** [isontheline/pro.webssh.net#1158]
After v26.7 Update: Unable to connect to SSH/SFTP where its password is set to blank/no password. 

Steps to reproduce(Requires an instance with no password)
1. Add SSH key into WebSSH
2. Add Connection to said Instance
3. Attampt to Connect
4. Enter Password pops up, keep the password blank, and click "Connect"
5. Nothing happens.

**Comment by isontheline** [comment]
Hello @pasutafukurou 👋

Sorry for the trouble, please refer to this issue : https://github.com/isontheline/pro.webssh.net/issues/1153
