### ISSUE TITLE
Reconnect w 2FA Not Working on Desktop

### ISSUE THREAD

**Issue by karero** [isontheline/pro.webssh.net#1160]
# Bug description

When SSH connection is lost I cannot enter the verification code upon entering R. Seems like the focus is on the terminal and – even when clicking on the pop-up window I cannot enter the 2FA code.

MacOS 14.5 MacBook Air

# Screenshot attached![image](https://github.com/user-attachments/assets/97550e1a-9826-4684-b8bf-69fce41993da)

# Steps to reproduce
1. Login with 2FA e.g. Google Authenticator
2. Wait until server cuts connection
3. Enter "R" to reconnect: verification code pop-up shows up
4. I cannot enter the code in the pop-up since the "focus" is not on the pop-up. Even clicking on it does not help.

**Comment by isontheline** [comment]
Hello @karero 👋

Many thanks for your report 🙏

I'm planning it for the upcoming minor release.

**Comment by karero** [comment]
Hi @isontheline That's cool. 😎 Thank you. 🙏
Please check the iPhone app as well. I think the same is happening there too.

**Comment by isontheline** [comment]
Hi @karero 👋

Could you please try WebSSH 27.2.1377 ?
https://testflight.apple.com/join/QSrBK59z

**Comment by karero** [comment]
Tested on MAC and iPhone, both work fine now.

**Comment by isontheline** [comment]
Thanks for your feedback @karero 🙏
