### ISSUE TITLE
Even after updating to 27.1 i'm getting password error on private key.

### ISSUE THREAD

**Issue by kmrifat** [isontheline/pro.webssh.net#1161]
# Bug description
it's asking for a password for my private key, but by key does not have a password, the same configuration was working perfectly. 
now it's asking for password

# Screenshots
![Screenshot 2024-07-16 at 3 08 48 AM](https://github.com/user-attachments/assets/17d62b5f-1e11-459d-bd82-b53530ba0b64)

**Comment by isontheline** [comment]
Hello @kmrifat 👋 

In order to troubleshoot, please post the verbose logs : https://webssh.net/documentation/help/howtos/enabling-verbose-logging/

**Comment by isontheline** [comment]
@kmrifat Feel free to reopen this issue if 27.2.1379 doesn't solve your encountered problem
