### ISSUE TITLE
Theme : Purple color should be named Magenta (ANSI)

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#1173]
Just want to start by saying I have been looking for an iOS SSH client that allows both custom ANSI themes + custom system fonts, and your app is the *only* one I could find - a be all, end all! I think this feature should be highlighted more.

That being said, I have found a few bugs with the custom ANSI themes:
1. No matter the color they are set to in a theme, and no matter what theme you choose, Purple and Bright Purple are stuck being the same color scheme as the WebSSH theme. It is pretty easy to see the issue with themes like Desert or Seashells, which intentionally have no purples.

2. In creating a custom theme, I cannot change the Cursor, background, foreground, and selection colors. I have tried everything I can to alter them in all of the tabs (Classic, Grid, RGB), but they just won't budge. I had to find a theme that had close enough values to what I wanted, clone it, and then edit the "other colors" (ansi codes).

3. While I was successful in setting my other ANSI color codes, notably, the hex field in RGB refuses to set the color to that value. When exiting the screen, no changes are ever applied. I had to enter the RGB-256 values to set them correctly.

Thank you again for your app and time!

_Originally posted by @oklopfer in https://github.com/isontheline/pro.webssh.net/discussions/1171_

**Comment by isontheline** [comment]
Hello @oklopfer 👋

Thank you so much for your great and strong feedback about WebSSH 🙏

> 1. No matter the color they are set to in a theme, and no matter what theme you choose, Purple and Bright Purple are stuck being the same color scheme as the WebSSH theme. It is pretty easy to see the issue with themes like Desert or Seashells, which intentionally have no purples.

Very good catch!
I’m using “purple” and “brightPurple” instead of “magenta” and “brightMagenta” :(
I will fix it asap in the next upcoming minor release.

> 2. In creating a custom theme, I cannot change the Cursor, background, foreground, and selection colors. I have tried everything I can to alter them in all of the tabs (Classic, Grid, RGB), but they just won't budge. I had to find a theme that had close enough values to what I wanted, clone it, and then edit the "other colors" (ansi codes).

Oops seems to be a regression, I’m looking at it

> 3. While I was successful in setting my other ANSI color codes, notably, the hex field in RGB refuses to set the color to that value. When exiting the screen, no changes are ever applied. I had to enter the RGB-256 values to set them correctly.

That’s strange I’ve just tested over iOS 17 and macOS 14 and I can apply hex values. The color is even updated when I focus another field.

Sorry @oklopfer for all these troubles
I’m opening an issue to track them all : https://github.com/isontheline/pro.webssh.net/issues/1173

**Comment by isontheline** [comment]
@oklopfer about (2) : when you have made your changes to your custom theme -> please select it again in the list in order to be applied to your connection. Don't forget to save your connection (don't just go back).

Themes are not - yet - applied to your connections when you edit them.

**Comment by oklopfer** [comment]
@isontheline I can select the theme just fine, the problem is just that those 4 colors are uneditable for me.

**Comment by isontheline** [comment]
Many thanks for all your feedbacks!

So just point one (1) needs to be fixed?

**Comment by oklopfer** [comment]
That’s correct - the swiping vs hitting the X is a little clunky without knowing at first, but I can confirm I was able to set all of the colors properly now :)

**Comment by isontheline** [comment]
I admit that's clunky 😓
The library I use seems to have only a delegate about "colorPickerViewControllerDidFinish" and not about dismiss.

I will work on (1) soon

**Comment by isontheline** [comment]
Hello @oklopfer 👋

Please try WebSSH 27.3.1385 about magenta / purple color : https://testflight.apple.com/join/QSrBK59z

**Comment by oklopfer** [comment]
Can confirm it works! Thank you for such a quick fix and once again a perfect app, now my phone and laptop terminals are seamless :D

**Comment by isontheline** [comment]
Many thanks for your strong feedback about WebSSH 🙏
