### ISSUE TITLE
cursor key mode default

### ISSUE THREAD

**Issue by jazzyj123** [isontheline/pro.webssh.net#1185]
# Feature description
I would like the ability to set the default ‘Cursor Key Mode’ (CKM). A lot of the devices I connect do will not show the last entered command when I press the UP arrow so I regularly change the CKM but I usually forget as well. I’d just like to be able to set the default for new connections. Great tool by the way. Thanks. 

# Screenshots / Draws
_If applicable, add screenshots and/or draws to help explain your feature request_

**Comment by isontheline** [comment]
Hello @jazzyj123 👋

Which CKM modes are you talking about?
These ones?

<img width="667" alt="image" src="https://github.com/user-attachments/assets/00790552-2977-4b78-ab00-f8bbb109c768">

**Comment by jazzyj123** [comment]
Correct. I have to changed them to normal when SSH. Thanks

**Comment by isontheline** [comment]
You’re welcome!
