### ISSUE TITLE
How To : Setting up tunnel

### ISSUE THREAD

**Issue by boneda** [isontheline/pro.webssh.net#119]
**How to**
Hi,
 I just download your app on my IOS device and will like to use it for SSH web tunnel. I have added a connection and also allow vpn connection to be created. But i don't know which details to use for port knocking and port forwarding, and because of that my device traffic cant pass through the SSH tunnel. please me right way. I have attached a screenshot of my setup to this message.

![IMG_0048](https://user-images.githubusercontent.com/67591320/101351302-052b5180-3856-11eb-8564-6a175efe954b.jpg)

**Comment by isontheline** [comment]
Hello @boneda 👋

Firstly I need an important thing in order to help you : what do you want to do with port forwarding ?
Could you explain your use case ?

Thank you a lot

Have a nice day☀️

**Comment by boneda** [comment]
Hi @isontheline
To be able to pass all my iphone internet traffic through it. i figure if its possible why not use it. Thank you for the reply.

**Comment by isontheline** [comment]
This is not **YET** possible.

In [documentation](https://webssh.net/documentation/help/networking/port_forwarding/) you will find that statement :
DPF will forward all connections **INSIDE** WebSSH (SSH, SFTP) to a dynamic remote IP and port through your SSH server (aka bastion).

So proxying is done inside WebSSH and not outside **YET**.

**Comment by boneda** [comment]
okay Thank you
