### ISSUE TITLE
Diferente 

### ISSUE THREAD

**Issue by EricFerraz180784** [isontheline/pro.webssh.net#1193]
# Bug description
_Put here a clear and concise description of what the bug is_

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by EricFerraz180784** [comment]
Sim acho que poderia simplificar a adição do snipped ajudante não sei se é
pelo fato de estar tudo em inglês para mim por exemplo , mas não estou
conseguindo add

Em sáb., 31 de ago. de 2024 às 15:47, github-actions[bot] <
***@***.***> escreveu:

**Comment by isontheline** [comment]
Hello @EricFerraz180784 👋

I'm sorry I can only speak English.

Don't hesitate to come back to me if you need any further help.

Have a nice day ☀️
