### ISSUE TITLE
Images missing from website

### ISSUE THREAD

**Issue by ash34** [isontheline/pro.webssh.net#1198]
I just noticed that many images are missing from [https://webssh.net/](https://webssh.net/)

![IMG_0026](https://github.com/user-attachments/assets/c8b608aa-d1be-4bbb-8cb9-f32f498eef00)

**Comment by isontheline** [comment]
A transient problem about jsdeliver ?

<img width="552" alt="image" src="https://github.com/user-attachments/assets/892cb91e-1106-4ca7-b373-03dc5c65756a">
