### ISSUE TITLE
Search bar overlaps lists (ssh, sftp)

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#12]
iOS 13 / 14

**Comment by Dianne087** [comment]
> 1 | ''remote access providing of to business system <Mybox> > 1 | ''remote access providing of to business system 
    |   ^
  2 | <jscriptutility >printIn( )
  3 | remote access technologies,impact cybersecurity 
  4 | dr.converter.file.xml.xmltopdf.xmltocsv. > 1 | *<environment>up<Advancce.Analysising>
    | ^ > 1 | *<environment>up<Advancce.MISCELLANEOUS UTILITY AND INTERFACES similar in spirit to the standard templete Libarary(STL)define by > 1 | *<environment>up<Advancce.Analysising>
    | ^ > 1 | *<environment>up<Advancce.Analysis
Box
