### ISSUE TITLE
Unable to connect over cellular

### ISSUE THREAD

**Issue by ggeers** [isontheline/pro.webssh.net#120]
**Describe the bug**
WebSSH no longer connects to my home system when using mobile data (4G or 5G).

**Informations**
 - Device : iPhone 12 Pro Max
 - OS : iOS 14.2.1
 - WebSSH Pro version : 14.7.4

The log file says the network is unreachable.
I’m connecting directly to my device’s static IPv4 address to avoid IPv6 issues (firewall).

UNIX Reflection on the same device connects flawlessly, so there is a route to the host.

**To Reproduce**
Try to connect

Thanks
Glenn

**Comment by isontheline** [comment]
Hello @ggeers Glenn 👋

Thank for your issue. Strange trouble ☹️

Please attach a screenshot of the error (when you press the "Report" button).

Have a nice day ☀️

**Comment by ggeers** [comment]
Will do when I’m home. Have to remember to turn wifi off 😊

________________________________

**Comment by ggeers** [comment]
Screenshot of the log file in two parts...[Image.jpeg][Image.jpeg]

________________________________

**Comment by isontheline** [comment]
I'm sorry, there are no screenshots attached.

Perhaps you need to upload them through Github and not through email.

**Comment by ggeers** [comment]
Will try again later...

Typed on a small keyboard

Glenn Geers

**Comment by isontheline** [comment]
Hello @ggeers  👋 

You cou-d also try _WebSSH Beta_ from TestFlight app : https://testflight.apple.com/join/QSrBK59z

☀️ Have a nice day

**Comment by isontheline** [comment]
Glenn, any update?
