### ISSUE TITLE
WebSSH closes after selecting a tag for filtering.

### ISSUE THREAD

**Issue by camoralb** [isontheline/pro.webssh.net#1205]
# Bug description
The app exits and ask for sending the error log to apple. I have activated the fingerprint lock feature. When I select tags, the closes.

# Steps to reproduce
1. Select "Servers" at the left column (to list all created server)
2. Select "Tags"
3. Select one tag
4. Error is thrown

**Comment by isontheline** [comment]
Hello @camoralb 👋

Thank you so much for your crash report!

I'm working on a fix and hope to beta release it tonight.
I will come back to you shortly.

**Comment by isontheline** [comment]
Hello Carlos @camoralb 👋

Please find a fix here : https://testflight.apple.com/join/QSrBK59z
