### ISSUE TITLE
Add (again) old arrow keys upside iPad keyboard

### ISSUE THREAD

**Issue by r2ixuz** [isontheline/pro.webssh.net#121]
**Describe the feature**
_A key feature for me over the other ssh ios apps were the seperated arrow keys. Now they are gone and only this dumb virtual arrow key like in any other app is present. Thats is really sad and I am already regret it that I bought your app... 😒 _

Please bring back the separate arrow keys. Thank you.

**Comment by isontheline** [comment]
Please enable it again inside WebSSH settings.

**Comment by r2ixuz** [comment]
There is no option for activating the seperate arrow keys layout from last version again. I can only activate the pad or joystick in the upper right corner.

**Comment by isontheline** [comment]
I'm tired 😔
So you are using iPad ? Your issue description didn't mention it 🙄

**Comment by r2ixuz** [comment]
Sorry, missed that. Yes iPad Pro 12.3" from 2020 with IpadOS 14.2.

In the WebSSH settings there are two lines with version information:
14.7.4 Nov 25 2020 @ 14:44:39
14.6.6 @ 20201114

**Comment by r2ixuz** [comment]
To clarify: I am missing the arrow keys directly on top of the normal virtual iPadOS keyboard (the same row where Esc Tab and the other keys are located).

**Comment by r2ixuz** [comment]
An other solution for me would be if the upper right corner arrow pad would be much larger for easy typing.

**Comment by svenh0** [comment]
Yes in one of the last versions i don't have the different 2 arrow Buttons for Up/Down in the virtual keyboard top right. 
Now i have only the arrow-Button in the virtual keyboard top middle. 

I liked the 2 separate keys better  
The new 4-arrow-button is a bit complicated to use.

**Comment by isontheline** [comment]
Hello @r2ixuz and @svenh0 👋

Could you confirm me that you want this accessory form upside the iPad keyboard again?
![image](https://user-images.githubusercontent.com/44212923/101536469-547a9a80-399a-11eb-88d2-b0b6ed0c36df.png)

Sorry for the trouble

**Comment by svenh0** [comment]
Yes, i mean the first line on the top of the virtual ipad keyboard (on the bottom of the picture). 
This arrows left from "..." i liked better as the new 4-arrow-button in the middle of this line. 
Perhaps you can make a setup option to select the old 4 keys or the new 4-arrow-key

**Comment by isontheline** [comment]
@svenh0 Yes I'm currently implementing a setting in order to switch back to the old behavior.
Thank you for your quick feedback!

It will be available as soon as I can 😉

**Comment by r2ixuz** [comment]
Yes, I want the buttons back (red square). Thank you:

![101536469-547a9a80-399a-11eb-88d2-b0b6ed0c36df](https://user-images.githubusercontent.com/15087554/101537610-12525880-399c-11eb-873d-c3e74a0da5dc.png)

**Comment by isontheline** [comment]
@r2ixuz Thanks for your feedback!

Let's go

**Comment by isontheline** [comment]
Please install _WebSSH Beta_ 14.8.5 from TestFlight : https://testflight.apple.com/join/QSrBK59z

You will then be able to switch back to old special keys :
![image](https://user-images.githubusercontent.com/44212923/101540509-67906900-39a0-11eb-9e15-bebbb1c27d81.png)

@r2ixuz and @svenh0 could you check if this issue is now fixed?

**Comment by svenh0** [comment]
Yes, with 4.8.5 this option works fine. 
Thanks ;)

**Comment by r2ixuz** [comment]
Can confirm, it works. Great, thanks! Do you close this when it is final?

**Comment by isontheline** [comment]
Thanks for your feedback!

I'm closing this issue right now.

Have a nice day ☀️

**Comment by isontheline** [comment]
Hello @r2ixuz 👋

Can I add your nickname to "WebSSH Contributors" page ?

**Comment by r2ixuz** [comment]
> Can I add your nickname to "WebSSH Contributors" page ?

Yes, thanks.

Do you know, when the fixed version will be public released? Don't like this testflight thingy ;)

**Comment by isontheline** [comment]
If no outage there, I think 27-28 December : https://developer.apple.com/news/?id=83m4plrb
