### ISSUE TITLE
Terrapin-protection only on iPad, not on iPhone?

### ISSUE THREAD

**Issue by svenh0** [isontheline/pro.webssh.net#1210]
Since version 27.6 i can't connect to any old servers on iPadPro (IOS18). 
There i have to change the ssh_config to connect to this old servers. 
But on iPhone11 (IOS18) with 27.6 i can connect to this old servers without changing the ssh_config. 
Is the terrapin-protection only activated on iPad and not on iPhone?
Now i use 27.6.1406 on both devices (iPhone and iPad).

**Comment by isontheline** [comment]
Hello @svenh0 👋

Terrapin mitigation is enabled on all devices.

If you change ssh_config on your iPad it will be synced to all other devices.

**Comment by svenh0** [comment]
Yes, after changing the ssh_config on iPad i can connect to the old servers. 
But on iPhone i can connect to this old servers without changing the ssh_config. 
So i think, the new terrapin-protection is not enabled on iPhone.

**Comment by isontheline** [comment]
It’s enable on every devices since 27.4

Any chance your iPhone was running older version?

You can use this tool to check either clients : https://www.ssh-audit.com/

**Comment by svenh0** [comment]
On both device running the version 27.6.1406 with IOS18.
It is curious, that i have to change the ssh_config on iPad but not on iPhone. 

On iPhone i can not connect to audit-client-listener with WebSSH.
I get a connection error. 

For me it is ok. 
I would only inform to this curious behaviour on iPhone. 
How i can check, if the terrapin-protection is activated on iPhone?

**Comment by isontheline** [comment]
Are you able to run this scanner on your computer / server?
https://terrapin-attack.com/#scanner

**Comment by svenh0** [comment]
Sorry, i cant install this scanner on my servers. 
Perhaps the connection-error to audit.com-client-listener show, that the terrapin-protection is active on iPhone ;)
There is only the question because i can connect to old servers on iPhone without changing the ssh_config, but on iPad i must change the ssh_config?

**Comment by isontheline** [comment]
When connecting (both iPad and iPhone), please extract verbose logs : https://webssh.net/documentation/help/howtos/enabling-verbose-logging/

It could help together to find the root cause

**Comment by isontheline** [comment]
@svenh0 I found something, I'm trying to fix

**Comment by isontheline** [comment]
Fix is being pushed to Apple TestFlight.

Before available, please try these steps on the "faulty" device :
1. Edit ssh_config
2. Put these lines :
```
Host *
  RemoteCommand none
```
3. Try connection again

It's not related to "RemoteCommand" but only the fact that the ssh_config is empty.

When fix is available I will ping you.

Many thanks for your report @svenh0 🙏

**Comment by svenh0** [comment]
Ok, if i use the "RemoteCommand none" in the ssh_config on iPhone, then i must also set the other options (MACs ...) to connect to the old server. 
Then the the behaviour on the iPhone is the same as on iPad.

**Comment by isontheline** [comment]
@svenh0 Thanks for your try 🙏

Fix is bing pushed to Staging and Production at same time.

As time of writing the fix is now available inside WebSSH 27.7.1407 : https://testflight.apple.com/join/QSrBK59z

You can download it

**Comment by isontheline** [comment]
Perfect!

Sorry for any trouble
