### ISSUE TITLE
Virtual keyboard backspace deletes sometimes 2 characters 

### ISSUE THREAD

**Issue by berti34** [isontheline/pro.webssh.net#1213]
# Bug description
When editing code on my servers with vim sometimes the backspace delete button erases two characters instead of one as expected.

# Screenshots
None

# Steps to reproduce
1. open (Bash) scripts with vim
2. put some text in and delete it by using the backspace

**Comment by isontheline** [comment]
Hello @berti34 👋

What does this command produces :
`showkey -a`

When doing a backspace sequence?
