### ISSUE TITLE
SSH connection issues after the latest update (with SSH key)

### ISSUE THREAD

**Issue by IMEIICCID** [isontheline/pro.webssh.net#1215]
Title: SSH connection issues after the latest update (with SSH key)

Description:
After the recent update of the WebSSH app (version 27.7, October 8th, 2024), I am experiencing issues connecting to my SSH server using an SSH key. Prior to the update, everything worked smoothly. The connection now fails without providing clear error messages, and I haven’t made any changes to the server-side configuration (using Dropbear as the SSH server on FreshTomato 2023.4). The issue seems to have appeared after the latest app update.

Steps to Reproduce:

	1.	Open WebSSH (version 27.7) on iPad
	2.	Use an SSH key to attempt to connect to an SSH server running Dropbear (v2022.83) on FreshTomato 2023.4
	3.	Connection fails without useful error output

Expected Behavior:
SSH connection with an SSH key should succeed as it did prior to the update, without changes to server configuration.

Actual Behavior:
The connection fails after the update, making the SSH client unusable for the current configuration, particularly when using SSH key authentication.

App Version:
WebSSH version 27.7

Device:

	•	Device: iPad
	•	iOS Version: [your iOS version]
	•	Server: Dropbear SSH (v2022.83) running on FreshTomato firmware version 2023.4

Additional Information:
I’ve tried the following troubleshooting steps:

	•	Verified the server-side SSH configuration
	•	Tested with other SSH clients (e.g., Termius) using the same SSH key, which work fine with the same server
	•	Reinstalled the app, but the issue persists

The issue seems to be directly related to the recent app update and affects SSH key-based authentication.

**Comment by isontheline** [comment]
@IMEIICCID Hello 👋

Terrapin mitigation has been enforced inside WebSSH 27.7 and weaks algorithms disabled by default.

Have you tried this guide?
https://webssh.net/documentation/help/SSH/terrapin-attack/

**Comment by IMEIICCID** [comment]
@isontheline  Thanks for the hint :-) Works! 👍

**Comment by IMEIICCID** [comment]
safe with:
Host *
    Ciphers aes128-gcm@openssh.com,aes256-gcm@openssh.com
    MACs hmac-sha2-256,hmac-sha2-512

**Comment by isontheline** [comment]
Thanks a lot for your feedback @IMEIICCID 🙏

Sorry for any trouble due to this latest release with upgraded security recommandations
