### ISSUE TITLE
Can't scroll anymore in the terminal log in 14.8

### ISSUE THREAD

**Issue by svenh0** [isontheline/pro.webssh.net#122]
With Version 14.8 i can't scroll anymore in the terminal-log-text. 
In Version 14.7 is it ok. 
If more logtext avaible as could show in the terminal window, so i can go down/up with swiping with one finger to scroll in the log-text. 
In 14.8 this dont work anymore. 

 - Device : iPad Pro 11
 - OS : 14.2
 - WebSSH Pro version : 14.8

**To Reproduce**
1. open terminal window
2. start logging
3. wait until logging-text is scrolling down, because it has more text as one page
4. try to scroll up/down the log-text

**Comment by isontheline** [comment]
Woops 🥲

Hello @svenh0 👋

You're right, I will fix this issue asap.

**Comment by isontheline** [comment]
Scroll works on iOS 12, but not iOS 14 :(

**Comment by svenh0** [comment]
In WebSSH Pro 14.7 it works also on IOS 14 ;)

**Comment by isontheline** [comment]
I am still working on this issue, I will fix it, I'm confident 😇
Thank you for your patience

**Comment by isontheline** [comment]
@svenh0 Could you try 14.8.9?

A first attempt to fix this issue
Could you try it?

**Comment by svenh0** [comment]
With 14.8.9 scrolling works again. 
But i think it a little bit to fast. If i swipe only a bit, it is scrolling more if i want.

**Comment by isontheline** [comment]
I think too.

I'm working on velocity now.

**Comment by svenh0** [comment]
And sometimes on swiping is showing the blue select-button.

**Comment by isontheline** [comment]
Yes when long press without movement

Could you try the new velocity on 14.8.10?

**Comment by svenh0** [comment]
14.8.10 is better, but not perfekt ;)
On 14.7x i can scrolling a litte bit smoother specially steps by one row or any rows. 
And on Push and swipe showing the select-button, if the push is a little bit longer. 
On 14.7.x the select button is only showing if the push is longer. 
On short push and swipe there dont show the select button. 
On 14.8.10 i must use a really short push and following swipe to avoid showing the select button.

**Comment by isontheline** [comment]
OK I will improve 14.8 👍

I'm working on a new rendering engine (WKWebView) so some glitches like it can appear.

**Comment by isontheline** [comment]
Could you tell a little more about "smoother scrolling, steps by one row or any rows"?

14.8.10 doesn't let you to scroll slowly or fastly over your rows?

**Comment by svenh0** [comment]
It's difficult to describe;)

On 14.7 the line on this i push/tab ans swipe is fixing under the finger on swiping. 
I move the text by this line with the finger. 

On 14.8 the pushed line is moving outside of the finger on swiping.

**Comment by ash34** [comment]
Fixed in 14.8.11 as far as I can see. Works great for main window scrolling and cursor moving with the 4way arrow key.

**Comment by svenh0** [comment]
Scrolling behavior in 14.8.11 is not like on 14.7x, but it's ok ;)
Only this 2 different things:
- on a little bit longer push and swipe it shows faster the select-button (on 14.7 i can push a litte bit longer without show select button)
- the pushed line is moving outside the finger on swiping on 14.8.x (on 14.7.x is fixing under the finger on swiping)

If is not possible in new rendering engine, then it's ok;)

**Comment by isontheline** [comment]
1. I agree that the push must be longer in order to show select menu
2. I'm not experiencing the same trouble but I think it is there. All I can tell is that now I need to scroll lines by lines instead of pixels by pixels in the new rendering engine. I will do an another try

I will try to fix these to issues as soon as possible. 

Stay tunned in the next days (hours?)☀️

**Comment by isontheline** [comment]
I have added a longer delay for select-button to appear
Inside 14.8.13

**Comment by svenh0** [comment]
Yes, now it's ok ;)

But could it be that now always open the virtual keyboard on showing the select-button?

A single tab to open virtual keyboard is ok, but on longer press for showing select-button also ?

**Comment by isontheline** [comment]
So you have found a new bug 🥲

OK I will fix it asap, thanks for your feedback!

**Comment by svenh0** [comment]
To the other problem: text ist faster scrolling as the finger swipe.

try this:
1. Tap on the top of the display on a line in log. 
2. swipe down with the finger to the middle of the display and look at the line from 1.
3. if you go to the middle, the line is moving to the buttom of the display, but the finger is only move to the middle. 

In 14.7.x the line is always moving with the finger, not faster as the finger.

The scrolling-behavior works on 14.8.13, but is it an other behavior ;)

**Comment by isontheline** [comment]
14.8.14 should fix [keyboard appear after displaying "select" menu](https://github.com/isontheline/pro.webssh.net/issues/122#issuecomment-748307457).

**Comment by svenh0** [comment]
Yes, is fixed ;)
(but now a single tap also do not open the virtual keyboard - is this ok?)

Could you make got to the selected line in the select-text-window?
The select-text-windows is always scroll to the end of the text. 
Also if i selected the first line in the log-windows. So i must go to or search the selected line.

**Comment by isontheline** [comment]
Yes short single tap wasn't support before and I have tried to support it without success now. I will implement short single tap (show/hide keyboard) in a later release.

I have create another issue to track "Could you make got to the selected line in the select-text-window?"

I will now try to implement better scrolling support

**Comment by svenh0** [comment]
> I will now try to implement better scrolling support
But only if it can be done.
The current behavior would be good if you swiped a little faster.
When swiping slowly, the text should be fixed under the finger.

**Comment by isontheline** [comment]
Does 14.8.16 improve the scroll for you?

Thank you again for your feedback 😇

**Comment by svenh0** [comment]
Yes, now is the scroll behavior in 14.8.16 like in 14.7.x ;)
Thanks.

**Comment by isontheline** [comment]
@svenh0 @ash34 

Can I add you nicknames to "Many thanks to" section on https://webssh.net ❓

**Comment by ash34** [comment]
You can use my name “Ash Jones” if you want. 👍🏼

**Comment by svenh0** [comment]
Thanks, you can use my shortname "Sven H", it's better as the nick 😉
