### ISSUE TITLE
all my SSH attempts cannot establish connection

### ISSUE THREAD

**Issue by froche3777** [isontheline/pro.webssh.net#1221]
# Bug description
_Last I used WebSSH last week everything was fine, but now every SSH attempt returns "cannot establish connection", but other SSH clients are working_

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by isontheline** [comment]
Hello @froche3777 👋

Many thanks for your feedback ☀️

You will find all needed information to fix your issue here : https://webssh.net/documentation/help/SSH/terrapin-attack/

Sorry for any trouble

**Comment by froche3777** [comment]
That worked. Thank you!

**Comment by isontheline** [comment]
You're welcome @froche3777
