### ISSUE TITLE
iOS Keyboard bug

### ISSUE THREAD

**Issue by Kritz0** [isontheline/pro.webssh.net#1223]
When I connect to a server with the iOS app via SSH and open the midnight commander and the keyboard is open, the keyboard sometimes disappears when I press on a directory in the midnight commander.

https://github.com/user-attachments/assets/bec22665-f11c-408d-bb9c-65217345a6fa

**Comment by isontheline** [comment]
Hello @Kritz0 👋

Please try to set this option :
iOS Settings > Apps > WebSSH > SSH > Keyboard visibility swap method > On navigation bar button

I wish you a nice day ☀️
