### ISSUE TITLE
Command History

### ISSUE THREAD

**Issue by ThiagoLimahDev** [isontheline/pro.webssh.net#1227]
I would like to check the possibility of having a history of commands executed on the device. This way, when we press the (up) key on the keyboard, we browse the last commands executed, just like in the Linux terminal.

**Comment by isontheline** [comment]
Hello @ThiagoLimahDev 👋

Seems to be related to #1140 ?

I don’t understand because your Linux server already handle the history, isn’t it?

**Comment by ThiagoLimahDev** [comment]
I normally use WebSSH to access Huawei equipment that I work on, and I tend to use several commands that are very similar, such as interface names.

If I have to change several interfaces, I always have to type the entire command, as there is no way to press the up button and the last executed command appears, this way I could press up and just change the name of the interface, you know?

**Comment by isontheline** [comment]
Thanks for clarifying @ThiagoLimahDev 🙏

I need to check how to do that as WebSSH doesn't intercept anything between your device and your server.
But I know what you are describing when I work on switches.

Do you know any terminal that emulates what you are wanting?

**Comment by ThiagoLimahDev** [comment]
Look at how it works in Termius, I'll send you a video that I believe will be easier to understand.

https://github.com/user-attachments/assets/9bd083f0-bcab-4ef2-a7c7-606e29eb2298

**Comment by isontheline** [comment]
Thanks for sharing!
When you use the arrows inside WebSSH, does it produces glitches or nothing?

**Comment by ThiagoLimahDev** [comment]
Nothing

**Comment by isontheline** [comment]
Last thing, have you tried to change this setting?
<img width="506" alt="image" src="https://github.com/user-attachments/assets/d2ddc561-2fc6-4450-8b1e-83c7b797c91a">

**Comment by ThiagoLimahDev** [comment]
Great, I changed it to 'Normal' and it worked perfectly!

Thank you very much!

**Comment by isontheline** [comment]
You're Welcome @ThiagoLimahDev 👍
