### ISSUE TITLE
macOS: Open Sidebar Button Actions to the same tab

### ISSUE THREAD

**Issue by CTRL-panino** [isontheline/pro.webssh.net#1228]
# Feature description
Hi! I'm using WebSSH Pro and I find it very useful and well designed!

I would like to request a feature that allows users to disable the automatic opening of new tabs.
For example, every time I access the settings, a new tab opens, which leads to multiple unnecessary settings tabs.
In my opinion, the automatic opening of new tabs should be disabled by default or, at least, there should be an option to disable it.

Additionally, I’ve noticed that when the "Window Restoration Strategy" is set to "Custom by User," the WebSSH window shifts every time a new tab opens (see the GIF).

Thank you for your help :)
# Screenshots / Draws
![trim F0BF1823-12A6-4DE4-BD38-D0727469F9B1](https://github.com/user-attachments/assets/0e2f40c9-b4a1-4776-aa88-5f1b6d5d20db)

**Comment by isontheline** [comment]
Hello @CTRL-panino 👋

I agree I will take a look at the sidebar top buttons that open new tabs instead of pushing to the current view controller. I’ve done this behavior years ago for a reason I don’t remember, yet.

The « restoration strategy » needs serious work. It’s not trivial as I share the same base code as iPadOS. Will take a look but can’t tell any ETA.

**Comment by isontheline** [comment]
Every feedback is helpful ;) 

I've done some tests and it seems that I can show the content in the same tab instead of opening new ones.
I continue my investigation and will come back to you with a final reply

**Comment by isontheline** [comment]
Hello @CTRL-panino 👋

About sidebar buttons opening in new tabs, please try WebSSH 28.0.1434 : https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
Thanks for your feedback!

Now fixed : https://testflight.apple.com/join/QSrBK59z
