### ISSUE TITLE
Server sync stopped after cloning a server on iphone.

### ISSUE THREAD

**Issue by ElizioRezende** [isontheline/pro.webssh.net#1229]
Server sync was working until I tried to clone a server on the iPhone. 
Now I have 13 servers in the iPhone app and only 2 on the MacBook Pro.

**Comment by isontheline** [comment]
Hello @ElizioRezende 👋

Could you confirm that both devices have iCloud enabled?
https://webssh.net/documentation/help/iCloud/

If so, please check logs for sync errors : https://webssh.net/documentation/help/howtos/enabling-verbose-logging/

**Comment by ElizioRezende** [comment]
Hello,

Yes, Icloud enable on MacBook, Iphone and Ipad.
And on the two devices that were supposed to synchronize the servers, it only synchronized two of the thirteen available on the iPhone.

Sorry, the problem was no disk space on icloud. One suggestion would be to show this message to the user. Now that I freed up space everything worked. Thanks

**Comment by isontheline** [comment]
Thank you a lot for your feedback and resolution tip 🙏

Have a nice day ☀️
