### ISSUE TITLE
Crash on delete

### ISSUE THREAD

**Issue by Dave-W** [isontheline/pro.webssh.net#1230]
# Bug description
When you have a server that you no longer want/need using right-click abd delete on the server crashes the app. (It does remove the server from the list though when you reopen the app !)

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1.  Add a server
2. Assign the server to a group
3. Right click pn the server in the list and select "Delete"
4. Error is thrown

**Comment by isontheline** [comment]
Hello @Dave-W 👋

Thanks for your feedback 🙏

Happens on macOS or iPadOS?

**Comment by isontheline** [comment]
Could you try the latest beta release please? 
https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
I'm able to reproduce, I will make a fix asap

**Comment by isontheline** [comment]
Now fixed inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
