### ISSUE TITLE
Crash on every action on a forwarding when a tag is used in any connection (macOS)

### ISSUE THREAD

**Issue by clns** [isontheline/pro.webssh.net#1231]
# Bug description

The app crashes when trying to connect, save or delete a forwarding record, when a tag is used in any other server connection. This is on latest macOS.

# Steps to reproduce

I have multiple server configurations in different groups, and one forwarding connection with port "*". When I set a tag in a server connection, then the app starts crashing when interacting with the forwarding, as explained above. It may crash in other scenarios as well, but this is my use case that always crashed.

After removing the (single) tag I had, it stopped crashing.

After removing the tag, it stopped working. Now I added the tag back, but the crash doesn't happen. If it happens again, I will post here.

The crash report was sent to Apple (according to the crash report UI).

**Comment by isontheline** [comment]
Big thanks @clns 🙏
As soon as I receive the crash report I will make a fix

Sorry for any trouble

**Comment by isontheline** [comment]
Now fixed inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
