### ISSUE TITLE
Keyboard Covers Up Terminal on iPhone

### ISSUE THREAD

**Issue by pksml85** [isontheline/pro.webssh.net#1235]
# Bug description
In iOS, the keyboard covers up the terminal text. Instead, the terminal text box should resize to exclude the keyboard.
I'm on an iPhone 14 Pro running iOS 16.0.3.

# Screenshots
![image](https://github.com/user-attachments/assets/b1f9d60a-0e01-4898-8f79-d7995be07671)
![image](https://github.com/user-attachments/assets/278c96ce-4551-4850-84fd-656c1cc3f052)

# Steps to reproduce
1. Do anything that outputs approximately 60 lines of text. The keyboard will cover the bottom of the terminal text.

**Comment by isontheline** [comment]
Hello @pksml85 👋

I don’t support iOS 16 anymore, please upgrade your iPhone OS
