### ISSUE TITLE
Session display name (sidebar) : ability to rename

### ISSUE THREAD

**Issue by giulianozor** [isontheline/pro.webssh.net#1238]
Hello,
I often use multiple session to the same server. In the sidebar (at least on iPad) all the sessions have the server name, so it is difficult to navigate between the sessions. It would be very helpful if one can tap and hold on the session and set up an  additional title.

I.e.: I have a server called B2 and all my sessions are displayed as B2. I would like to have B2 – task one, B2 – task two and so on .

thanks

g

**Comment by isontheline** [comment]
Hello @giulianozor 👋

Very good idea!
I'm planing it

**Comment by isontheline** [comment]
Hey @giulianozor 👋

You can now try WebSSH 28.3.1463 with the ability to rename the session on the sidebar : https://testflight.apple.com/join/QSrBK59z

Best wishes,

**Comment by giulianozor** [comment]
@isontheline thanks, it semestre to work great !
