### ISSUE TITLE
The "Full Block" character is no longer the full height of a line

### ISSUE THREAD

**Issue by sky1es** [isontheline/pro.webssh.net#1241]
# Bug description
The Full Block character (https://www.compart.com/en/unicode/U+2588) is no longer printed as a full block. There is missing some of the height.
This have changed to this in one of the latest releases. Before I updated to latest version, the full block was a full block.

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. Print the two Full Block characters, one above the other and you will see that there is a space between.

**Comment by isontheline** [comment]
Hello @sky1es 👋

Thanks for your report!

I have updated both xtermjs library and Nerf Font.
I will check it soon.

**Comment by isontheline** [comment]
Can confirm that the current font doesn't fill the full height
![Image](https://github.com/user-attachments/assets/006f9baf-393a-4cff-9fb6-c9de5fb30fdc)

**Comment by isontheline** [comment]
Does this font break your layout?

**Comment by sky1es** [comment]
HiYes, I have made this script for Raspberry Pi, where I use it to plot graphs. See the image.Best regardsKennyOn 28 Nov 2024, at 20.55, isontheline ***@***.***> wrote:﻿
Does this font break your layout?

**Comment by isontheline** [comment]
Sorry GitHub don’t post images from emails

**Comment by isontheline** [comment]
If you have an example script that you can share in purpose it would be awesome

**Comment by sky1es** [comment]
Sure, it's publicly available here: [https://sye.dk/rpi_motd/](https://sye.dk/rpi_motd/)
The images on that page shows how it looks like in Putty. It used to look the same in WebSSH.
The image here is from my iPad where you can see the result of the missing top of the full block.
![Full_Block_issue](https://github.com/user-attachments/assets/ffecfdee-6651-4754-b046-5c5394e16b79)

Another minor font issue is the underscore that I use in the bottom of the graph, it have a one pixel offset from bottom of the char - would be nice if it was placed all the way down at bottom :-)

**Comment by isontheline** [comment]
Thank you 🙏

I need some days to fix it but I will

**Comment by sky1es** [comment]
Sounds great, thanks 👍On 29 Nov 2024, at 15.35, isontheline ***@***.***> wrote:﻿
Thank you 🙏
I need some days to fix it but I will

**Comment by isontheline** [comment]
I'm near

![Image](https://github.com/user-attachments/assets/c4a3f733-e1a7-4b0e-9ec7-3e899256ca54)

**Comment by isontheline** [comment]
@sky1es You can try out the latest WebSSH beta release 28.3.1453 : https://testflight.apple.com/join/QSrBK59z
