### ISSUE TITLE
Short-code of "Enter" key for `#!KeyboardAccessoryViewLayout`

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#1248]
Is there short-code for the "enter" key to put in my SSH Config File for `#!KeyboardAccessoryViewLayout`?

https://webssh.net/documentation/help/howtos/SSH/customise-keyboard-accessory-view-layout/

I would think it would be useful after pasting a snippet to be able to run it without the need of the full keyboard.

_Originally posted by @GuillaumeHullin in https://github.com/isontheline/pro.webssh.net/discussions/1246_

**Comment by isontheline** [comment]
@GuillaumeHullin 
<img width="355" alt="Image" src="https://github.com/user-attachments/assets/6f322cc1-cc51-46d6-9ab7-f54e5379ab3b" />

Will be available in a few hours ;)

**Comment by isontheline** [comment]
Now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
Documentation has been updated as well : https://webssh.net/documentation/help/howtos/SSH/customise-keyboard-accessory-view-layout/

**Comment by GuillaumeHullin** [comment]
Yup! That works :)
