### ISSUE TITLE
Reorder or copy saved connection-commands

### ISSUE THREAD

**Issue by svenh0** [isontheline/pro.webssh.net#125]
It would be verry useful, if i could reorder the saved commands in a connection. 
(on the top right sideboard on the penultimate menu item with the Setup-Symbol)

And if i could copy a saved command to an other connection would be also helpful. ;)
Now i have saved some complicated commands in one connection. 
This commands i want to have also in an other connection, but creating them again is too time-consuming for me ;)

**Comment by isontheline** [comment]
OK it's now planned, thank you a lot 😉

Did you know also that you can add a command which will be available on all connections?
By unchecking "Only on this connection" box.

**Comment by svenh0** [comment]
Thanks, i didn't know this option before. But some commands should not be available in all connections, which is why copying would be useful. ;)

But it's not in such a hurry. :)

**Comment by isontheline** [comment]
Hello @svenh0 👋

You can assign snippets to one or more connections by using tags

**Comment by svenh0** [comment]
Thanks, I've been using this variant with the tags for a while now

**Comment by isontheline** [comment]
Hello @svenh0 👋

Does this issue is done with ability to use tags?

**Comment by svenh0** [comment]
Yes, now i can use all snippets in all connections. 
To show on top of the snippets-list, i can add the tag of the current connection. 

But i can not reorder/sort the snippets in the list. They sort only by name. 
But now i think, this reorder/sort option is not longer necessary.

**Comment by isontheline** [comment]
Many thanks for your feedback @svenh0 🙏

I will enhance snippets in a few weeks, don't hesitate to come back to me if any other improvement may be done

I wish you a nice day ☀️
