### ISSUE TITLE
Backspace deleting more than one character on single press

### ISSUE THREAD

**Issue by cs-hv** [isontheline/pro.webssh.net#1256]
Sometime hitting the backspace (delete left) button it is "eating" more than one character. Happens mostly when hyphens come into the play. 

Screenshot n/a

# Steps to reproduce
1. Enter some text - shell command with options
2. Try to delete the command line (Note: Repeat still missing for backspace key!)
3. Sometimes one press will delete more than one character
4. Characters deleted by chance have to be entered again

**Comment by isontheline** [comment]
Thank you for your issue 🙏

Can’t reproduce on my side, could you please share a video?

**Comment by cs-hv** [comment]
It's quite easy to reproduce the issue following these steps:

- Open a new session
- Enter some characters, e.g. the word **shell**
- Press the backspace key 5-times to delete the word ("shell" has five letters).
- Now enter **-?**
- Press the backspace key **one time** and both characters will be deleted.

**Comment by isontheline** [comment]
😲

Good catch! 👌
Will check at it.

Awesome!

**Comment by isontheline** [comment]
Could it be related with an Apple Keyboard Settings?
<img width="657" alt="Image" src="https://github.com/user-attachments/assets/faad05b7-1cc8-46aa-8b98-d1a093b928c4" />

<img width="332" alt="Image" src="https://github.com/user-attachments/assets/fd4c91c0-a3c7-476b-97b1-fff20a3b3b92" />

**Comment by cs-hv** [comment]
Checked both macOS and iPadOS version - the setting doesn't matter. However I was not able to reproduce the bug on macOS.
Why that? The problem seems to arise from the hyphen button of the accessory keyboard. If you use the hyphen key from the standard keyboard, the problem does not appear on iPad either. This applies to all buttons that produce visible characters as '*', '/' and so on when followed by a character entered by the standard keyboard.

**Comment by isontheline** [comment]
I'm working on a fix thanks to your reproduce steps 🙏

**Comment by isontheline** [comment]
You can now try WebSSH 28.3.1465 : https://testflight.apple.com/join/QSrBK59z

**Comment by cs-hv** [comment]
That did the job - thank you for your great support!

**Comment by isontheline** [comment]
You're welcome @cs-hv 
Thanks for reporting this issue 👍

**Comment by ryamoo** [comment]
Hey, sorry to revive an old issue, but this still happens for me when using the Microsoft SwiftKey keyboard on iPhone. 
It doesn’t seem to happen on the stock iOS keyboard. 

https://github.com/user-attachments/assets/fdd68dd7-10b0-4ce0-bb6e-fe618ca52307
You can see on my video when I press backspace to delete the 5, it deletes the 5 and 4. Then again for the 3, it deletes the 3 and 2.

**Comment by isontheline** [comment]
Hi @ryamoo 👋 

Just tried and works as expected.
But I believe you that a bug can still be there, just no sure about an third party keyboard
