### ISSUE TITLE
NEVPNErrorDomain error 2

### ISSUE THREAD

**Issue by wynstep** [isontheline/pro.webssh.net#129]
**Describe the bug**
This is the error message I obtain when I try to start a tunnel to external server. Other tunnels have the same error. All of them previously worked on same device, same app.

**Informations**
 - Device : iPad Air 
 - OS : iOS 12
 - WebSSH Pro version : latest (nov 2020)

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**To Reproduce**
1. Go to 'tunnels’
2. Touch on 'any tunnel present in my list’

**Comment by isontheline** [comment]
Hello @wynstep 👋

Could you try to delete "WebSSH VPN Profile" inside your iOS settings?

Thank you

**Comment by isontheline** [comment]
@wynstep Any update on your issue?

**Comment by wynstep** [comment]
Solved, thanks

**Comment by isontheline** [comment]
Thank you for your feedback!

Have a nice day ☀️
