### ISSUE TITLE
settings / servers sync import/export

### ISSUE THREAD

**Issue by kevinrook** [isontheline/pro.webssh.net#133]
is there any way or future plan to enable syncing devices.

so my iPhone & ipad can easily be maintained and both uptodate.

i often find myself needing to use a device to find out i havent added a server to it. and rather than a quick import of settings i have to enter all the details again.

i love the app but i manage many servers and would like them all on webssh

**Comment by isontheline** [comment]
Hello Kevin 👋

You're right this is a big lack of WebSSH.

Export / Import feature is already planned here : #43 

I must speed up on this feature...
