### ISSUE TITLE
Keyboard hidden after select

### ISSUE THREAD

**Issue by ash34** [isontheline/pro.webssh.net#139]
When closing the select screen the keyboard is hidden / closed. The first action after selecting some text would be to use it with the keyboard so to have to open the keyboard every time is a pain in the neck. 

**Informations**
 - Device : iPad 7 generation 
 - OS : iOS 14.2
 - WebSSH Pro version : 14.8.11

**To Reproduce**
1. Long press on the main window
2. Choose “Select” from the pop-up
3. Close the select screen with the X top-right
4. Observe the keyboard is now missing

**Comment by isontheline** [comment]
Hello @ash34 👋

That's a good issue, thank you!

You are right : if keyboard was opened before selecting text it should appear again when exiting selection window

I plan it for this release because I think it should be fixed soon.

Have a nice day ☀️

**Comment by isontheline** [comment]
I'm working on it right now

**Comment by isontheline** [comment]
Hello @ash34 👋

Could you try 14.8.13?

**Comment by ash34** [comment]
Yes, that’s solved it.
