### ISSUE TITLE
Don't scroll terminal content when closing keyboard

### ISSUE THREAD

**Issue by svenh0** [isontheline/pro.webssh.net#145]
If i scrolling up in the terminal log with showing virtual keyboard and close the virtual keyboard (to see more lines) the log is scrolling to the end. 
The text does not stay at the last scroll position. 

On open keyboard is ok to scrolling to the end, but not on close the keyboard. 

**Informations**
 - Device : iPad 11 Pro
 - OS : IOS 14.2
 - WebSSH Pro version : 14.8.16

1. start logging
2. Open virtual keyboard
2. Scrolling up any pages
3. close virtual keyboard
4. Text is scrolling down to the end (leave my scroll position)

**Comment by isontheline** [comment]
Hello @svenh0 👋

I will look on it this night.

Thank you

**Comment by isontheline** [comment]
It's more difficult than expected :(

**Comment by isontheline** [comment]
@svenh0 Seems to be fixed with WebSSH 17.0
https://testflight.apple.com/join/QSrBK59z
