### ISSUE TITLE
Missing Long Output

### ISSUE THREAD

**Issue by ash34** [isontheline/pro.webssh.net#161]
Not all output is shown if the output is more than the screen on-show. The top part of the output is lost when you hide the keyboard. (The part that did not fit onto the half-screen)

 - Device : iPad 7 gen
 - OS : iOS 14.3
 - WebSSH Pro version : 14.9.3

![AB123E96-D206-47FB-927B-C975FB7EA07B](https://user-images.githubusercontent.com/56022918/103456220-59f6a680-4cf4-11eb-80c6-4c61c36fcdd0.png)
![14A00C0B-9BA0-4A00-BDEC-BB1DB5C3096C](https://user-images.githubusercontent.com/56022918/103456224-5cf19700-4cf4-11eb-97a7-de59b2d5081f.png)

Third screenshot shows that the issue is not seen if the second command is repeated.

![E3372CC5-E31C-432A-BA8A-90C3FCD34DF4](https://user-images.githubusercontent.com/56022918/103456222-5c590080-4cf4-11eb-9df9-98e89c5cc5aa.png)

1. Already have a good amount of output from a previous command (apt upgrade was used in the test)
2. Enter a command that is known to give a lot of output (mediainfo was used in the test)
3. Hide the keyboard with the key bottom-right
4. See the top of the second command output is missing

**Comment by isontheline** [comment]
Hello @ash34 👋

Could you check again 14.7 fallback? (It is a new bug or was already there?)

Have a nice day ☀️

**Comment by ash34** [comment]
Cannot reproduce in 14.7.1 or 14.7.4 (OK the hide keyboard key does not work in those versions but scrolling down also showed the issue in the original report.

**Comment by isontheline** [comment]
Please :
1. Edit your connection
2. Edit terminal settings
3. Disable "reverse wrap-around"

The trouble is from https://github.com/isontheline/pro.webssh.net/issues/85 enabled by default
I will disable it by default for 14.9.4

Thank you a lot for your issue @ash34

**Comment by isontheline** [comment]
14.9.4 will also be a release candidate for the App Store

**Comment by ash34** [comment]
Confirmed. Disable the reverse wrap-around solves it.

**Comment by isontheline** [comment]
Thank you a lot @ash34 👍

**Comment by ash34** [comment]
Actually this still happens even when Reverse Wrap-Around is disabled. Screenshot attached from earlier 
![1D6A8E0C-C02F-4F14-82D9-C320DE354D7C](https://user-images.githubusercontent.com/56022918/103567364-f6bb6e80-4ec3-11eb-9344-f733fb727c63.jpeg)
today.

**Comment by isontheline** [comment]
With your provided steps I'm not able to reproduce it with wrap-around disabled :

![Capture d’écran 2021-01-04 à 21 35 52](https://user-images.githubusercontent.com/44212923/103577373-f5df0880-4ed4-11eb-9b7d-35fdb785234b.png)

The history is not "eaten" by the second command on my side :(

**Comment by ash34** [comment]
Try a cat of a complete syslog for example, then another command which produces more than the half-screen of output. It’s repeatable for me this way. Screenshots attached. I think I can prevent it with lots of empty lines.

Not sure if it is a bug or not or related or not but sometimes when exiting nano I find a previous command already on the input line but the cursor is at the start of it. Will raise it separately when it happens again.

![B15B8C6E-63DC-4E1F-A3DC-6523044AB6C2](https://user-images.githubusercontent.com/56022918/103698911-60aa4580-4fa2-11eb-9c46-b67fa1ebfbd9.jpeg)
![AE7A3EF0-1AA5-4F3C-AC23-34C4CCC7F979](https://user-images.githubusercontent.com/56022918/103698916-630c9f80-4fa2-11eb-8d0f-2e635d236519.jpeg)
![5A0F6355-D68C-4571-8C86-2ADB13813F5A](https://user-images.githubusercontent.com/56022918/103698919-643dcc80-4fa2-11eb-8363-2c67534df5b1.jpeg)
![9405AF58-6434-45AB-90D0-EECB9D5F50FF](https://user-images.githubusercontent.com/56022918/103698921-64d66300-4fa2-11eb-8313-1ad77ed6d604.jpeg)
![AA62282A-ED50-4F0A-A938-045F18507630](https://user-images.githubusercontent.com/56022918/103698923-656ef980-4fa2-11eb-8394-a8038fc14ae2.jpeg)
![0B96754E-9712-494C-B977-B7B06E554E37](https://user-images.githubusercontent.com/56022918/103698924-66079000-4fa2-11eb-9ce7-59bf1b5a46fa.jpeg)

**Comment by isontheline** [comment]
Thank you a lot @ash34 for your clear reproduce steps!

I will try as soon as possible and come back to you shortly.

**Comment by isontheline** [comment]
I'm sorry I can't reproduce :(

Even with a very long output of 500KB :
```
wget -O apple.txt "https://fr.wikipedia.org/wiki/Apple"
cat apple.txt
cat /proc/cpuinfo
```

**Comment by isontheline** [comment]
Are you able to reproduce with these commands ?

```
wget -O apple.txt "https://fr.wikipedia.org/wiki/Apple"
cat apple.txt
cat /proc/cpuinfo
```

**Comment by ash34** [comment]
> Are you able to reproduce with these commands ?
> 
> ```
> wget -O apple.txt "https://fr.wikipedia.org/wiki/Apple"
> cat apple.txt
> cat /proc/cpuinfo
> ```

No, cannot reproduce.
