### ISSUE TITLE
Full white screen on ios 14 beta2

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#17]
Full white screen on ios 14 beta2

_Originally posted by @maravtdm in https://github.com/isontheline/pro.webssh.net/issues/7#issuecomment-667425879_

**Comment by isontheline** [comment]
@maravtdm At the launch of the app or only on terminal ?

**Comment by maravtdm** [comment]
- only the term. i could see command on the right and the keyboard 
- ios 14 beta2 on iphone 8 plus 
- yes, of course

**Comment by isontheline** [comment]
@maravtdm Thanks for your feedback

I will download Xcode 12 Beta 3 in order to reproduce the bug.

I will go back to you with beta testing link asap.

**Comment by maravtdm** [comment]
![2020-08-01 17-15-24](https://user-images.githubusercontent.com/11086888/89104622-f0a7fa00-d41a-11ea-809d-daffd1acc328.png)

Here is the screenshot of what it look like

**Comment by isontheline** [comment]
Fix pushed to Apple. 
Waiting for the build beeing accepted.🤞

**Comment by isontheline** [comment]
@maravtdm Fixed by 14.0.4
Could you confirm?

**Comment by maravtdm** [comment]
I'm waiting for the update ...

**Comment by isontheline** [comment]
@maravtdm Sorry, you will find TestFlight link here :
https://testflight.apple.com/join/QSrBK59z

**Comment by maravtdm** [comment]
Well done. parfait !
