### ISSUE TITLE
 Fn key access when in  fullscreen terminal mode

### ISSUE THREAD

**Issue by unnilennium** [isontheline/pro.webssh.net#175]
**Describe the feature**
Currently Fn keys are available only in non fullscreen mode with a small link on the top right corner of screen .

Would be better to have it annexed to the keyboard so we can access it in both mode.
would suggest to add it in the top bar of the keyboard with the other shortcuts

thanks

**Comment by isontheline** [comment]
Hello @unnilennium 👋

#137 is already available on TestFlight

Could you check it?

https://testflight.apple.com/join/QSrBK59z

☀️ Have a nice day
