### ISSUE TITLE
Keyboard : Support of page up / down keys

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#180]
Hello,

thank you for the good ssh-Client. I am very happy with them.

But I have a small problem with a bluetooth keyboard.

I have problem with the page up and page down keys. They are not working. Looks like mostly all iOS ssh clients have here trouble.

I found only „ShellFish“ where I can use Pipe and  Page Up + Down.

Are you have any solution for this problem?

Greetings form Germany
Thomas

_Originally posted by @Supertas in https://github.com/isontheline/pro.webssh.net/discussions/179_

**Comment by isontheline** [comment]
I'm able to map my physical keyboard :
![Capture d’écran 2021-01-29 à 22 31 49](https://user-images.githubusercontent.com/44212923/106329542-e9ef2800-6281-11eb-9258-689143c7349b.png)

So I think BT Keyboard will be the same.

I will try to release a beta as soon as possible

**Comment by Supertas** [comment]
Sounds great, thank you

**Comment by isontheline** [comment]
Hope it will not be rejected by Apple : https://stackoverflow.com/a/44321674/8102448

But it is documented here by Apple : https://developer.apple.com/documentation/uikit/uikeyinputpageup?language=objc

Fingers crossed.

**Comment by isontheline** [comment]
I will publish a beta release in the next days, I need to fix SFTP download before

**Comment by isontheline** [comment]
Hello @Supertas  👋 

Could you install _WebSSH Beta_ from TestFlight app : https://testflight.apple.com/join/QSrBK59z

☀️ Have a nice day

**Comment by Supertas** [comment]
Hi,

yes, Page Up and Down are working know. At the testing I saw three others key which are not working. Sorry I don‘t test it before.
The keys are coming from the keyboard block. They are Pos1, End and Del.

I will test, if I finde more broken keys.

Thank you for the fast support.

**Comment by Supertas** [comment]
HI,

more errors, I don‘t found. It is not easy to find alle keys in iOS. :-)

**Comment by isontheline** [comment]
Thank you a lot for your feedback @Supertas 👍

Pos1, End and Del keys will be in another issue : https://github.com/isontheline/pro.webssh.net/issues/183

Have a nice day ☀️

**Comment by CapableFish** [comment]
Has this fix been released? Or is it still a beta?

**Comment by isontheline** [comment]
Released : https://webssh.net/documentation/changelog/14.10/

**Comment by isontheline** [comment]
Could you try WebSSH 16.1.5 available below?
https://testflight.apple.com/join/QSrBK59z

Please note that an Apple Magic Keyboard may be required though.

**Comment by isontheline** [comment]
@Supertas Does the repetition of the keys are working on your side?

**Comment by Supertas** [comment]
Hi, I make a short test. Yes looks good for me. Letters are not sticky, I am not sure if I want it for letters.
But for spaces, del, remove, Arrow Keys and Page Up/Down the sticky keys are working very good for me.

**Comment by isontheline** [comment]
Hi @Supertas 👋

Thank you again for your feedback 🙏
