### ISSUE TITLE
line up/down left/right key too sensitive

### ISSUE THREAD

**Issue by wpballa** [isontheline/pro.webssh.net#181]
In older versions of this really nice software there were big arrows to hit to move up/down and left/right line by line or character by character respectively. the new single button that does all moves way too fast to just pick the last line and edit a character or two.

*** Never mind, now it is working properly, but a few days ago (maybe before the 14.4 update) it would scroll rapidly through lines.

**Informations**
 - Device : iPhone 11/iPad Air 2
 - OS : iOS 14.4
 - WebSSH Pro version : latest

**Comment by isontheline** [comment]
Hello @wpballa Bill 👋

You can revert to the old behavior, here is how to :
https://webssh.net/documentation/help/howtos/SSH/use-old-special-keys/

Does this fix your trouble?

Have a nice day ☀️

**Comment by wpballa** [comment]
Yes, that solved my problem nicely, thanks.
