### ISSUE TITLE
whois查询错误

### ISSUE THREAD

**Issue by chuan01** [isontheline/pro.webssh.net#19]
whois查询接口错误。
![1724FE76-A156-4312-A949-B6C9CDF7BD2D](https://user-images.githubusercontent.com/43603829/89114890-b3437b00-d4b3-11ea-8ee4-aacb00322c2d.png)

**Comment by chuan01** [comment]
建议使用https://whois.gd/查询接口。
调用规则https://whois.gd/你的域名。

**Comment by chuan01** [comment]
比如说https://whois.gd/baidu.com
查询为baidu.com域名whois信息

**Comment by isontheline** [comment]
Thanks for your bug report @chuan01 !
I will fix'it asap and will send you a beta TestFlight link

**Comment by isontheline** [comment]
Fixed in WebSSH TestFlight 14.1.12 : https://testflight.apple.com/join/QSrBK59z
**Will be available in a few minutes**

☀️ Have a nice day
