### ISSUE TITLE
Connection : popup (launch, edit, delete) only when pressing (i)

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#197]
**Describe the feature**
In order to be user friction less : only show popup (launch, edit, delete) only when pressing (i)

- [x] Remove "launch" menu

**Comment by svenh0** [comment]
Yes, it would better, if show this menu only if i want to show by a special info-button at end of the line.

**Comment by isontheline** [comment]
Enhancement will be available in WebSSH 14.11.2 (in a few hours)

**Comment by isontheline** [comment]
@svenh0 Could you try the beta release please?

**Comment by svenh0** [comment]
Thanks, this works in 14.11.2 👍🏼
