### ISSUE TITLE
UI布局bug

### ISSUE THREAD

**Issue by chuan01** [isontheline/pro.webssh.net#20]
添加新屏幕会出现UI布局的bug。
![772675E9-E4F4-4EE7-869C-A300342447C2](https://user-images.githubusercontent.com/43603829/89114908-f00f7200-d4b3-11ea-80b3-1b86409e8c5d.jpeg)

**Comment by chuan01** [comment]
iPhone11 ios14.0 (18A5332f)

**Comment by isontheline** [comment]
Thanks @chuan01 to have sent UI error with steps to reproduce!
I will fix it and come back to you asap

**Comment by isontheline** [comment]
The bug is also on iOS 13 :
![image](https://user-images.githubusercontent.com/44212923/89218333-27724180-d5ce-11ea-86f1-70ef8dd801ce.png)

**Comment by isontheline** [comment]
Waiting for 14.1.1 to be approved for TestFlight Beta Testing (in one day).

@chuan01 Please install WebSSH 14.0.4 Beta Release here :
https://testflight.apple.com/join/QSrBK59z

You will receive tomorrow a notification for 14.1.1

Have a nice day!

**Comment by isontheline** [comment]
@chuan01 Beta release available on TestFlight, could you check it?

**Comment by avalonix** [comment]
iPhone 11 iOS 13.6; iPad Pro iOS 13.6 displayed correctly(14.1.1)
![722C16EE-9FDB-47BF-8404-7285EEFCA46A](https://user-images.githubusercontent.com/29081475/89373052-e7b47280-d711-11ea-873a-cfb61165386e.jpeg)

**Comment by isontheline** [comment]
Thanks @avalonix 👍
I'm closing this issue right now.

Fixed by 14.1.1

**Comment by chuan01** [comment]
修复之后其他屏幕底部出现线条的问题，颜色不对称。
![5BA5AA05-A2CC-432B-BB74-D415A3933E14](https://user-images.githubusercontent.com/43603829/89623167-baf58c00-d8c6-11ea-9206-64f9319fbd6c.jpeg)
![AB7D5456-0919-4948-856D-52448E21F156](https://user-images.githubusercontent.com/43603829/89623180-bdf07c80-d8c6-11ea-8da2-9319e5498792.jpeg)

**Comment by isontheline** [comment]
Hi @chuan01 

I have translated your comment but I don't see the difference between the two screens.

Perhaps I'm tired 😬

Could you explain me more?

**Comment by chuan01** [comment]
Screen 1 looks like a whole, while the other screens look like a line in the middle, with inconsistent colors up and down.

**Comment by isontheline** [comment]
Nice catch!
I reopen the issue.
Thanks

**Comment by isontheline** [comment]
I have made a fix and I'm currently pushing it to TestFlight so it will available in the next few hours.

**Comment by isontheline** [comment]
@chuan01 The fix is now available on TestFlight.

Could you check it?

☀️ Have a nice day
