### ISSUE TITLE
Improve scrolling

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#201]
**Describe the feature**
Scrolling is very slow when you scoll backward to see precioys commands and output or when you scroll back to continue using the shell. It would be nice if it were much faster.

**Comment by isontheline** [comment]
Hello @mbierman 👋

You're right since three / four releases the scrolling is not user friendly (because of upgrading the rendering engine).

I definitely need to improve it.

**Comment by svenh0** [comment]
Yes, perhaps you can use the user scrolling speed to change your scroll speed (how many tabs and scrolls in a time). 
On slow scrolling (for any rows scroll with only one tab) now it's ok ;)

But if i scroll up any pages, this could be a little faster ;)

**Comment by isontheline** [comment]
Thanks @svenh0 for your feedback 😉

You’re right I will implement a different scrolling based on user velocity

**Comment by mbierman** [comment]
Is this on the horizon yet? I know, you have been busy! (And doing great work.)

**Comment by isontheline** [comment]
Thanks for your support @mbierman Michael 😇

This issue requires an important upgrade of the rendering engine (hterm) and this upgrade must come with a major (15.x) release.

This issue is important also on macOS because on this platform the scroll is so bad with the current engine release 😭

I know that this issue was opened months ago and I will try to make my best efforts to fix it.

**Comment by isontheline** [comment]
Statement from @AInteriorB :
` Also I expect to be „back at the bottom“ as soon as I type any key. This would accelerate a usual workflow, when I have to look what happened above and then continue my work 😉`

**Comment by AInteriorB** [comment]
> 1. Scrolling is very slow when you scoll backward to see precioys commands and output or when you scroll back to continue using the shell. It would be nice if it were much faster.

I absolutely agree like written in dublicate #492

**Comment by isontheline** [comment]
Hello 👋

` Also I expect to be „back at the bottom“ as soon as I type any key. This would accelerate a usual workflow, when I have to look what happened above and then continue my work 😉`

This behavior will be available in a few hours now.

**Comment by AInteriorB** [comment]
This works, but

- No improvements in scrolling up
- Some colors are more matte
- Copy-Paste is no longer possible on iOS, as mentioned in #456 
- Keyboard is not enabled when opening a new session

**Comment by isontheline** [comment]
> * Keyboard is not enabled when opening a new session

Even on 852 build?

**Comment by isontheline** [comment]
> * No improvements in scrolling up

You're right I will improve the momentum

> * Some colors are more matte

I'm using default Xterm.js colors. I will change them. Do you have a wanted palette?

**Comment by AInteriorB** [comment]
> > * Keyboard is not enabled when opening a new session
> 
> Even on 852 build?

Fixed in 852 💪😀

**Comment by isontheline** [comment]
@AInteriorB I will implement a feature to import these color schemes : https://github.com/mbadolato/iTerm2-Color-Schemes

**Comment by isontheline** [comment]
I'm now working on a scrollbar (iOS / macOS / iPadOS) : #599

**Comment by isontheline** [comment]
First attempt of a custom scrollbar available on the latest beta release

**Comment by isontheline** [comment]
Custom scrollbar now available inside the latest beta release
