### ISSUE TITLE
Unified server list for SSH and SFTP

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#202]
A good idea is same list for SSH and FTP. 
In this way, the same server would not have to be registered twice.

_Originally posted by @josemmba in https://github.com/isontheline/pro.webssh.net/discussions/185_

- [x] Host capabilities dropdown select : SSH / SCP (mandatory yet?) / SFTP / ESXi / PVE / Docker

**Comment by josemmba** [comment]
In actual beta option "clone" form ssh to Sftp and Sftp to Ssh is a good option, but only 1 list is more clear for users.

**Comment by isontheline** [comment]
I'm pinning discussion https://github.com/isontheline/pro.webssh.net/discussions/185 in order to collect more feedbacks

**Comment by isontheline** [comment]
Will be available on PRO version only

**Comment by isontheline** [comment]
> I don't understand why we have to create separate connections for SSH, SFTP and tunnels. This is wasteful of resources and redundant. Instead, they should all run over the same connection. The idea is to create one SSH connection to a server. Once the connection is established, the user can toggle between screens for terminal, file transfer and tunneling. These three "views" could be displayed as sub-tabs on a row below the active tab. You could also provide the ability to disable one or more of the views if the user doesn't want to use them. For example, there could be two sub-tabs for just terminal and file transfer. Or, if you just want a terminal session, it would be displayed in the top-level tab without any sub-tabs.

From @bkonia https://github.com/isontheline/pro.webssh.net/discussions/185#discussioncomment-5064987

**Comment by isontheline** [comment]
@josemmba @bkonia

Since many years WebSSH have been used two lists for SSH and SFTP hosts, two list visually but also two list stored on the database.

When both will be unified, which option will less hurt users?
* Keep them both, user will clean itself their clones
* Try to find if clones could be found and delete them in order to keep only one

**Comment by bkonia** [comment]
Probably best to keep them both, since they may have different settings. It's not that hard for users to clean up dups manually and it will continue to work fine even if the user doesn't remove the dups.

**Comment by isontheline** [comment]
A beta release will be available in a few hours

**Comment by isontheline** [comment]
Now available inside the latest beta release 24.0 - Dragon : https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
@josemmba @bkonia

Have you some time to give it a try?

Cheers,

**Comment by gith-cmd** [comment]
> A good idea is same list for SSH and FTP. 
> In this way, the same server would not have to be registered twice.
> 
> _Originally posted by @josemmba in https://github.com/isontheline/pro.webssh.net/discussions/185_
> 
> - [x] Host capabilities dropdown select : SSH / SCP (mandatory yet?) / SFTP / ESXi / PVE / Docker

**Comment by gith-cmd** [comment]
> A good idea is same list for SSH and FTP. 
> In this way, the same server would not have to be registered twice.
> 
> _Originally posted by @josemmba in https://github.com/isontheline/pro.webssh.net/discussions/185_
> 
> - [x] Host capabilities dropdown select : SSH / SCP (mandatory yet?) / SFTP / ESXi / PVE / Docker

**Comment by gith-cmd** [comment]
> > I don't understand why we have to create separate connections for SSH, SFTP and tunnels. This is wasteful of resources and redundant. Instead, they should all run over the same connection. The idea is to create one SSH connection to a server. Once the connection is established, the user can toggle between screens for terminal, file transfer and tunneling. These three "views" could be displayed as sub-tabs on a row below the active tab. You could also provide the ability to disable one or more of the views if the user doesn't want to use them. For example, there could be two sub-tabs for just terminal and file transfer. Or, if you just want a terminal session, it would be displayed in the top-level tab without any sub-tabs.
> 
> 
> 
> From @bkonia https://github.com/isontheline/pro.webssh.net/discussions/185#discussioncomment-5064987

**Comment by Fatma32m** [comment]
https://github.com/isontheline/pro.webssh.net/issues/202

**Comment by mashlp** [comment]
[](url)
