### ISSUE TITLE
Keyboard Accessory Keys : Ability to customise them

### ISSUE THREAD

**Issue by frenschman** [isontheline/pro.webssh.net#215]
**Describe the bug**
thx for answer in the App Store!
I follow you’re instructions change the settings but nothing help. I take some screenshots to understand what I mean. The new arrow a too small and that is why the old 4 separate arrows was perfect ...

thx for help.

pleas bring it back 

**Informations**
 - Device : [iPhone 8]
 - OS : [iOS 14.4]
 - WebSSH Pro version : [last one for iOS ]

**Screenshots**
![CFE9C54F-C75F-4CDE-994B-0586A40F1C0B](https://user-images.githubusercontent.com/77173562/109461148-07bad300-7a62-11eb-80c7-f69b8a8cb840.png)
![2A4750F0-5E15-4FBC-97C7-026EF0A2231B](https://user-images.githubusercontent.com/77173562/109461155-09849680-7a62-11eb-8d19-f06755ada835.png)
![20E80617-D9A4-42D4-85EB-63DBC92C94D2](https://user-images.githubusercontent.com/77173562/109461158-0a1d2d00-7a62-11eb-9790-1f152865f437.jpeg)

**Comment by isontheline** [comment]
Hello @frenschman 👋

I understand you need the old "Virtual Arrow Keys" for iPhone and not the "Use old special keys".

You need to define "Virtual Arrow Keys" to "Pad" and you will have the top left pad appearing.

The down / up / left / right keys above the virtual keyboard is only on the iPadOS.

Could you check?

**Comment by frenschman** [comment]
Hi thx for answer so quick.

I don’t want the Virtual Arrow 
I send you a new Foto how it was in the pass

**Comment by isontheline** [comment]
I’m sorry I don’t understand what is the old arrows you want :/

Have you send me a new screenshot through GitHub?

**Comment by frenschman** [comment]
Hi I send here a new foto !

You get that not ?

**Comment by isontheline** [comment]
Attachments should be uploaded through GitHub website and not through email, I think.

**Comment by frenschman** [comment]
Sorry that you get the Foto not :(

I don’t want the Virtual Arrow :( 
I send you a new Foto how it was in the pass

![C328C12E-CB12-4DE0-94F6-4110F7F566E1](https://user-images.githubusercontent.com/77173562/109547423-a29bc780-7acb-11eb-8a49-329933b9062d.jpeg)


Ps: at the iPad it’s posibel 
Why no more at the iphone

**Comment by isontheline** [comment]
In my memory, please excuse me if I don’t remember, pad keys have « never » been upside the keyboard on the iPhone, only on the iPad.

I’m searching in the history if I’m true or wrong

**Comment by isontheline** [comment]
Here is the WebSSH version as of September 2020 :
![image](https://user-images.githubusercontent.com/44212923/109550774-fe684f80-7acf-11eb-87be-9b94be7eb2b4.png)

You can see that arrows are only on iPad and not on iPhone, so that's why I didn't understand your request.

As the iPhone as so little width space I "can't" add up / down / left / right keys

**Comment by isontheline** [comment]
@frenschman Are you sure that arrows keys was upside the keyboard on iPhone OS ?

**Comment by frenschman** [comment]
Good morning 

Yes I was sure !

That is why I buy it the app!

That was the deferent to other app in the store! Better for the using 

Wen you turn the phone at the Site the Keyboard gehts bigger

Nice greats

**Comment by isontheline** [comment]
![643x0w](https://user-images.githubusercontent.com/44212923/109757441-103e1580-7bea-11eb-8713-fda6d3a18b41.jpg)

Are you OK with these statements ?
* you would like ◀️▶️🔼🔽 buttons above the keyboard as the iPadOS ones
* you will lose four buttons * / | - in order to have the space needed for the arrows

**Comment by frenschman** [comment]
Hi looks not bad :) 

Wen you turn the iphone in the Horizont Position dann the Keyboard it’s much biger and more Space a free at the Screen !

We can use that option whit out lose any buttons ! 

Mit freundlichen Grüßen 
Rößler

**Comment by isontheline** [comment]
If you want a quick fix this arrow buttons I can't implement different buttons layouts.

In the few days I can only develop an option to replace buttons "* / | -" by the arrows ones.

Do you agree with this first attempt of fix?

**Comment by frenschman** [comment]
Hi thx for work !!

Wil that be a fix for all or just for me ?

I don’t what that oder use get miss a button there need 

It’s a bad situation ..

I need arrows 
Some one other need the /*

I thing we wait that you find a better option .! 

A double button line ?

**Comment by isontheline** [comment]
You're Welcome!

No a double lines we will loose precious rows.

I will implement one of these two options :
* Add an WebSSH settings that will allow to switch between arrow keys and /* keys
* Add the ability to slide between keys with the finger

**Comment by frenschman** [comment]
Good morning 

I like the slide option !! 
So we have not to go always back in the settings !  

Thx thx

**Comment by isontheline** [comment]
Perhaps it's time to let users choose their own keys above the keyboard

**Comment by isontheline** [comment]
@isontheline Ability to enable a setting which allow to show a submenu (with directional keys) when pressing the "arrows key" (like F1..F12)

**Comment by isontheline** [comment]
For @isontheline work :
=> Keyboard Customization : Using SSH Config

**Comment by isontheline** [comment]
Now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
