### ISSUE TITLE
Wrong SSH servers getting deleted 

### ISSUE THREAD

**Issue by BertrumUK** [isontheline/pro.webssh.net#217]
**Describe the bug**
I added a new server tonight for testing and when I deleted it the top server was deleted instead. This happened twice and was reproduced on my iPhone. 

**Informations**
 - Device : iPad 7 / iPhone 11
 - OS : iOS 14.4
 - WebSSH Pro version : 13.14.3

**Comment by isontheline** [comment]
Hello @BertrumUK 👋 
Thanks for your issue!

In order to help you as soon as possible :

1. Please install _WebSSH Beta_ from TestFlight app : https://testflight.apple.com/join/QSrBK59z
2. Then reproduce the bug

Does the top server is aways deleted with the TestFligh version?

☀️ Have a nice day

**Comment by isontheline** [comment]
I can reproduce too even on the latest release :(

**Comment by BertrumUK** [comment]
Hello Arnaud, thanks for the beta. It’s best to clone the top server for testing. 

Neil

**Comment by isontheline** [comment]
I'm trying to find why it's wrong

Sorry for the trouble :/

**Comment by BertrumUK** [comment]
That’s ok. Good luck.

**Comment by isontheline** [comment]
OK found 😓

Fix have been sent to Apple and should be approved in a few hours.

**Comment by BertrumUK** [comment]
👍

**Comment by isontheline** [comment]
@BertrumUK have you a few minutes to test my new release?
https://testflight.apple.com/join/QSrBK59z

☀️ Have a nice day

**Comment by BertrumUK** [comment]
Checking it now.

**Comment by isontheline** [comment]
Thank you Neil for your feedback!

Can I add your nickname on the contributors page?
https://webssh.net/documentation/contributors/

**Comment by BertrumUK** [comment]
👍🏻

**Comment by Aftabalamkhan120** [comment]
Volcano
