### ISSUE TITLE
Tunnel :Ability to add multiple ports in the tunnel configuration : VPN-Over-SSH

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#220]
I wish to add multiple ports in the tunnel configuration. 
eg:
8020:gitlab.mycompany.com:8020
8030:buildserver.mycompany.com:8030

this is how many other tools work and what i find a bit limiting in webssh.

thx
tilo

_Originally posted by @bytefactory73 in https://github.com/isontheline/pro.webssh.net/discussions/219_

**Comment by melonsode** [comment]
hello. I appreciate this great app, WebSSH. 
I would like to ask whether multiple port forward configuration is available now or not. Should I wait for a while?
If it’s available, please let me know how to write it. I have upgraded the app to ver. 16.1.

**Comment by isontheline** [comment]
Hello @melonsode 

I'm sorry, you need to wait for a while.
I'm need to fix issues in 16.2 before going to 17.0

Sorry again for the late

**Comment by isontheline** [comment]
Hello @bytefactory73 👋

Could you try 17.3 beta release?
https://testflight.apple.com/join/QSrBK59z

**Comment by bytefactory73** [comment]
Hey great stuff, just tested a settings with 2 forwards. works perfectly.

**Comment by bytefactory73** [comment]
The edit field to enter the "forwards" could be a bit bigger :)

**Comment by isontheline** [comment]
Hello @bytefactory73 👋

Thanks for your feedback!

You're right on iPhone it's too small width.

I will fix that

**Comment by megabot88888** [comment]
> ``

> The edit field to enter the "forwards" could be a bit bigger :)

> #101
