### ISSUE TITLE
Tunnel Failed

### ISSUE THREAD

**Issue by bigboyq** [isontheline/pro.webssh.net#223]
IOS 14.4
Webssh 14.13.1
Add stunnel
While try to start, NEVPNErrorDomain Error 2 Occurs
No matter using ip or hostname in the host field

**Comment by isontheline** [comment]
1. Just go to iOS Settings > VPN > Then remove "VPN-Over-SSH"
2. Launch your tunnel again
3. Approve the installation of the VPN profile

**Comment by isontheline** [comment]
I have also updated the documentation about this error : https://webssh.net/documentation/help/howtos/Tunnel/NEVPNErrorDomain/
