### ISSUE TITLE
Multi-touch events

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#224]
**Describe the feature**
Use multitouch events for editing text instead of the arrows. Imagine using two fingers left or right to move forward and back on text... so much faster than the little arrow keys we have now. 

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html

**Screenshots / Draws**

**Comment by isontheline** [comment]
Hello @mbierman 👋

Good idea!

It has already been planned here though : https://github.com/isontheline/pro.webssh.net/issues/59

**Comment by isontheline** [comment]
You can also have the old big pad again : 
1. WebSSH Settings
2. SSH Settings
3. Virtual Keys : Pad

**Comment by mbierman** [comment]
Sweet! I had missed this.
