### ISSUE TITLE
The back space doesn’t work. It buzzes and goes forward.

### ISSUE THREAD

**Issue by workworksalot** [isontheline/pro.webssh.net#225]
**Describe the bug**
_A clear and concise description of what the bug is. Be warned : We will refuse reports with no or little informations_

**Informations**
 - Device : [e.g. iPhone 6]
 - OS : [e.g. iOS 8.1]
 - WebSSH Pro version : [e.g. 13.16]

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**To Reproduce**
2. Touch on '....'
3. Swipe down to '....'

**Comment by isontheline** [comment]
Hello @workworksalot  👋 
Thanks for your issue! 
But...

...Every time someone does not respect the issue's template, a little mouse dies.

<details> 
<summary>Learn how</summary>

![little-mouse-dies-or-not-it-depends-on-you](https://user-images.githubusercontent.com/44212923/91720843-10584c80-eb98-11ea-80b8-fdc48f92392c.gif)
</details>

Please edit your issue description to respect the issue template as much as possible :
* https://github.com/isontheline/pro.webssh.net/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
* https://github.com/isontheline/pro.webssh.net/blob/master/.github/ISSUE_TEMPLATE/feature_request.md
