### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by mgrossb** [isontheline/pro.webssh.net#235]
**Describe the bug**
I Use WebSSH for iOS for connecting to a remote server. This worked fine for quite a time, since a few weeks the connection doesn't work anymore. No problems to connect via WinSCP (pc). 
Connection needs VPN; I use Standard iOS VPN client
**Informations**
 - Device : [iPad Pro 2019]
 - OS : [e.g. iOS 14.4.1]
 - WebSSH Pro version : [e.g. 14.14]

**Screenshots**
_If applicable, add screenshots to help explain your problem._
screenshot attached:
![IMG_0043](https://user-images.githubusercontent.com/80890367/111612865-3533aa80-87de-11eb-846a-ca3af30ff624.PNG)

**Comment by isontheline** [comment]
Hello @mgrossb 👋

The message "Failed to establish initial TCP/IP connection" seems to indicate that the VPN is not used for the connection.

Please ping the host inside WebSSH and put the screenshot of the ping.

**Comment by isontheline** [comment]
Your screenshot show the ping fails.

Two possibilities :
1. Your VPN doesn't let you to reach your server though your iDevice
2. You haven't allowed WebSSH to access your local network : 
![image](https://user-images.githubusercontent.com/44212923/111623797-27385680-87eb-11eb-953c-04e3376a0f28.png)

**Comment by mgrossb** [comment]
Could you please tell me where would I find this setting? Inside WebSSH? I can't find a screen like this.

**Comment by isontheline** [comment]
1. iOS Settings
2. WebSSH (Bottom of the settings)
3. Allow local access

If local access is granted then I think your VPN could be the wrong part but I'm not sure.
