### ISSUE TITLE
Arrow keys support with hardware not fully terminal compliant

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#236]
The issue affects all ssh sessions I tried. (multiple types of HP switches, aruba wireless access points and fortigate firewalls)

_Originally posted by @CapableFish in https://github.com/isontheline/pro.webssh.net/issues/200#issuecomment-801642003_

**Comment by isontheline** [comment]
@CapableFish

Please :
1. Download WebSSH 14.16.2 : https://testflight.apple.com/join/QSrBK59z
2. Edit your connection terminal settings : set CURSOR KEYS MODE to : "normal"
3. Try to launch your connection and check if arrow keys works

**Comment by CapableFish** [comment]
Hi,

it says I may lose the app data if I use the beta,

![image](https://user-images.githubusercontent.com/79424697/115162943-bd60e480-a0e9-11eb-8f1e-2bb2e9e4c00d.jpeg)

is there anyway I can backup the 100+ terminal sessions I had to manually create and save?

**Comment by isontheline** [comment]
@CapableFish You won’t loose any data.

But a WebSSH database backup is always a good thing to do : https://webssh.net/documentation/help/howtos/mashREPL/database-backup/

**Comment by CapableFish** [comment]
thanks for the backup info.

There is an improvement but the arrow keys still do not always work

I tested 
- WebSSH help screens does not have arrow key support (correcting typos in the help search)
- HP switch - does not have arrow key support
- Aruba Wireless - does not have arrow key support
- Fortigate firewall - arrow keys now working

**Comment by CapableFish** [comment]
sorry forgot to set cursor mode to normal

Tested in "Normal" cursor mode
- HP switch - arrow keys working
- Aruba Wireless - arrow keys working

**Comment by isontheline** [comment]
@CapableFish Thank you a lot for your feedback!

Happy to see that arrow keys are working now for you :)

Yet you can't set "normal" mode by default you need to set it for each connections.
The "normal" mode should / would be the default one in a future release but before I need to check that there is no regression for other users.

**Comment by CapableFish** [comment]
When will this be out of beta

**Comment by isontheline** [comment]
Not before 3-9 may because I've lot of issues in progress
