### ISSUE TITLE
Can't set mark in emacs or tmux

### ISSUE THREAD

**Issue by lethall** [isontheline/pro.webssh.net#238]
**Describe the bug**
WebSSH is a nearly perfect product; but it can't be my favorite because ctrl-<space> is not passed.

**Informations**
 - Device : iPhone 8
 - OS : 14
 - WebSSH Pro version : 14.14

**Screenshots**
Not an error. Just doesn't work.

**To Reproduce**
1. Connect to any host (I tried 2)
2. Edit any file with jove, atto, or any other emacsen... Or use tmux in copy mode
3. Try to set a mark to copy a block
4. No mark set

Other iOS ssh clients (eg remotervnc in ssh connection) work.

**Comment by isontheline** [comment]
Hello @lethall 👋

So I will try to make it your favorite 😇

I'm checking your trouble and come back to you asap.

**Comment by lethall** [comment]
To be clear: the "ctrl-<space>" is ctrl-spacebar. The github iOS app *also* seems to be swallowing the space 😀

**Comment by isontheline** [comment]
And "ctrl-@" is same as "ctrl-spacebar" isn't it ?

**Comment by lethall** [comment]
Yes, ctrl-@ is the same as ctrl-space; but harder to type (and not in muscle memory) - and ctrl-@ doesn't get passed either ☹️

**Comment by isontheline** [comment]
No problem I will implement ctrl-space and ctrl-@ asap

**Comment by isontheline** [comment]
Hello @lethall 👋

I will release WebSSH 14.15.7 in a few hours on TestFlight.
If you are not a beta tester, you can be one : https://webssh.net/documentation/becoming-external-tester/

I have fixed ctrl-@ and ctrl-space, they both work with virtual keyboard

When using a physical keyboard, you must use ctrl-@ because ctrl-space is used by iOS to switch languages.

Have a nice day ☀️

**Comment by isontheline** [comment]
Now available in beta version 14.15.7

**Comment by lethall** [comment]
It works well! Thank you.

Happy Easter!

**Comment by isontheline** [comment]
@lethall Thanks for your feedback 👍

Happy Easter too!

**Comment by lethall** [comment]
It works well! Thank you.

Happy Easter!
