### ISSUE TITLE
VPN over SSH

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#25]
It could be great if a SSH connection can be used as a VPN server like a bastion.

Tunnel inside WebSSH works great, but a VPN feature should work better, isn't it?

* https://github.com/passepartoutvpn/tunnelkit

# In-App Purchase
- [ ] (Tier 3) VPN over SSH #23

**Comment by isontheline** [comment]
Now available for every beta tester through TestFlight

**Comment by worm1271** [comment]
```````
```
~~~~
```
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
