### ISSUE TITLE
[ssh] public key authentication failed

### ISSUE THREAD

**Issue by akuropka** [isontheline/pro.webssh.net#250]
**Describe the bug**
Trying to connect to a ssh server, private key sent, public key authentication failed (where can I set up the public key?).

**Informations**
 - Device : iPhone 12 Pro Max
 - OS : iOS 14.5b6
 - WebSSH Pro version : 14.15.6

**Screenshots**
![IMG_0868](https://user-images.githubusercontent.com/22570574/113502700-3aa72980-952e-11eb-9c58-ed44d8ac3aa6.PNG)
![PNG image](https://user-images.githubusercontent.com/22570574/113502678-13505c80-952e-11eb-8c9b-8dcf95872a3c.png)

**To Reproduce**
1. Open app
2. Touch on server

**Comment by isontheline** [comment]
Hello @akuropka 👋

Please also join the server auth.log in order to see if the public key is missing on your server side.

Have a nice day ☀️

**Comment by akuropka** [comment]
Hi @isontheline,
please find below the relevant part of journal:
[sshd.log.txt](https://github.com/isontheline/pro.webssh.net/files/6255107/sshd.log.txt)
It works with PuTTY (Win10) and Termius (Android11).
Thank you so much...

**Comment by isontheline** [comment]
Thanks @akuropka 

Could you give me the command line used to generated your private key?

**Comment by akuropka** [comment]
Oh, that's a long time ago... since it is a 4096 bit RSA key I guess it was
`ssh-keygen -b 4096`

**Comment by isontheline** [comment]
I'm also using a 4K key and it's working as expected 😢 

* Are you using the same key in Termius and PuTTY?
* Does the user is correct?
* Does your authentication need a password with a key or only a key?

**Comment by akuropka** [comment]
I use the same key-only login everywhere and it works.
One thing to note, I also use DUO 2FA, enabled in sshd_config by
`AuthenticationMethods publickey,keyboard-interactive`
But if I switch on Two Factor Authentication I get an error as well:
![PNG image 2](https://user-images.githubusercontent.com/22570574/113551502-0e0a1500-95f5-11eb-8de2-d76db2c29f14.png)
(btw PuTTY/Termius don't have such 2FA-switch, works there OOTB)
Maybe you have a clue... thx!

**Comment by isontheline** [comment]
OK it's so related to this bug : https://github.com/isontheline/pro.webssh.net/issues/51

I'm closing this issue now

**Comment by akuropka** [comment]
@isontheline, thank you for update and reference. I didn't see that. )-:
Sadly to learn that it doesn't work yet but I will follow up and hope for good news soon...
