### ISSUE TITLE
How do I port forward

### ISSUE THREAD

**Issue by Dog8116** [isontheline/pro.webssh.net#260]
I was attempting to forward port 7777 because I was trying to set up a multiplayer terraria game that isn’t only with local devices, but the I have never done this before and the tutorial I used only said to “forward port 7777”. (please try to explain with simple terms as I have never done this)

**Comment by isontheline** [comment]
Hello @Dog8116 👋

Please put your tutorial link or PDF here.

WebSSH documentation about port forwarding is available here : https://webssh.net/documentation/help/networking/port-forwarding/

Have a nice day ☀️

**Comment by Dog8116** [comment]
https://gaming.stackexchange.com/questions/359746/how-do-i-create-a-terraria-server-on-my-android-phone/360086#360086

**Comment by isontheline** [comment]
I'm sorry you are trying to expose a local port to the Internet and WebSSH can't do that. WebSSH can only do local port forwarding : forwarding a remote port to your iDevice
