### ISSUE TITLE
Tunnel : Proxy Jump Host : VPN-Over-SSH

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#266]
**Describe the feature**
Ability to use a "wildcard" jump host from the tunnel feature. 

**Why?**
Yet the Local Port Forwarding and Dynamic Port Forwarding are using the VPN in order to work.
But if we use a VPN (like Cisco, OpenVPN) then we can't use the LPF / DPF features.

So if we can use a Jump Host without using the VPN it would be great :)

**What to do?**
* Keep LPF / DPF through VPN
* Add a new tunnel feature : Proxy Jump Host (will not use VPN)

**Comment by isontheline** [comment]
# Competitors
## MobaXterm
![image](https://user-images.githubusercontent.com/44212923/119714245-eef46a80-be62-11eb-8fed-7fba6e90c6ed.png)

**Comment by isontheline** [comment]
https://github.com/isontheline/pro.webssh.net/issues/263#issuecomment-860259531

Will this feature allow you to do proxy jumps, such as connecting directly to an ssh client via another ssh client?

The following .ssh/config example illustrates what I mean:
``` 
Host myproxypi
 HostName myurl.com
 Port 8700
 User pi

Host pisrv 
 ProxyJump myproxypi
 HostName 192.168.1.100
 User pi
 Port 22
```

Thanks.

**Comment by admdly** [comment]
It would be great if there was some support for the ProxyJump directive / SSH jump hosts as they are a common method to provide access to LAN servers from the Internet. 

What are the chances of this feature being implemented, and is there anything anyone can do to assist with this? Thanks! 🙏

**Comment by isontheline** [comment]
Chance to have this feature implemented is near 100% because I need it too 😇
The only question is when it will be implemented 😢

It's not a hard task for the backend part but a little harder for the frontend part (connection errors, connection progress bar, etc.)

I would like also to implement a more generic way to customize connections by the use of https://github.com/isontheline/pro.webssh.net/issues/327 an SSH config file

**Comment by isontheline** [comment]
# Manque juste une fonction et ce serait top
> Je l’utilise occasionnellement, c’est très bien. Mais dans mon cas il me manque le proxycommand pour accéder à des hosts derrière un bastion. J’espère que ce commentaire suscitera une réflexion en ce sens. Merci pour le travail..

By **volfoni69** on the *App Store*

**Comment by isontheline** [comment]
@admdly @jarrah31

Have you tried Dynamic Port Forwarding inside WebSSH' Tunnels?

**Comment by jcaude** [comment]
Yes, just give it a try now and it works perfectly (I work differently right now..). The only issue I have now is local DNS entry within the bastion that are not available through the tunnel.. it's not a big deal because these are static @IP. But then everything is working fine (at least ssh). Thx for all ..
btw/ I have enroll to the webssh beta program ..

**Comment by jarrah31** [comment]
Interesting! Thanks for notifying me to try this ProxyJump workaround.

Unfortunately something isn't quite working for me using this method. I can only test this on my Intel Mac version of WebSSH at the moment, so I'll try it on my iPhone/iPad later today.

What I've done so far is create a new Tunnel connection with the following settings:
```
Host: my.domain.com
Port: 3456
User: Pi
Private Key: id_rsa.txt
Port forwarding: *
Name: Proxy
```
After saving the changes, I click on this connection within Tunnel tab, and the status icon goes green.
Within the SSH tab, I have the following connection:
```
Host: 192.168.0.10
Port: 21
User: Pi
Private Key: id_rsa.txt
Name: Docker
```
When I click on this connection, the Connecting... popup window appears, but no connection is established.

My laptop is on a remote connection to home, so the Docker profile can't normally connect. Based on the instructions provided above, and given that the guide says "Dynamic Port Forwarding will forward all connections INSIDE WebSSH (SSH, SFTP) to a dynamic remote IP and port through your SSH server (aka bastion)", am I correctly assuming that Docker should be able to connect to 192.168.0.10 via the established "Proxy" connection? If so then this doesn't seem to work for me.

I'll be happy to try any testing or troubleshooting to help work out the problem.

**Comment by isontheline** [comment]
@jcaude 

> Yes, just give it a try now and it works perfectly (I work differently right now..). 

Thank you a lot for your feedback!

> The only issue I have now is local DNS entry within the bastion that are not available through the tunnel.. it's not a big deal because these are static @ip. 

Your need is to have connection' hostname (child) resolved by your local DNS server?

> But then everything is working fine (at least ssh). Thx for all ..

You're Welcome

> btw/ I have enroll to the webssh beta program ..

Thank you again 🙏

**Comment by isontheline** [comment]
@jarrah31 

> am I correctly assuming that Docker should be able to connect to 192.168.0.10 via the established "Proxy" connection? If so then this doesn't seem to work for me.

Yes the configuration you have shown seems good to me

Could you enable verbose logging in order to check further?

In order to enable verbose logging you can follow the steps :
1. iOS Settings
2. WebSSH
3. Settings
4. Log Level > Verbose
5. Restart WebSSH
6. Reproduce your action
7. Find the log files inside iOS > Files > WebSSH

**Comment by jarrah31** [comment]
Thanks @isontheline - is there an equivalent "Log Level -> Verbose" setting within the Intel Mac version of WebSSH? I can't test this on my phone at the moment.

I see within the app Settings there's "SSH Settings" and WebSSH Settings", but I can't find any verbose option within there.

**Comment by isontheline** [comment]
@jarrah31 Yes you will find it here : Menu bar macOS > WebSSH > Settings

**Comment by jarrah31** [comment]
Ah there it is - WebSSH Menubar -> Preferences. Thanks.

Sorry @isontheline, where are the log files kept? Tried looking within my home folder, hidden files, Library, Application Support. Searched my Mac for WebSSH too but it only found the .app file.

**Comment by isontheline** [comment]
@jarrah31 You can locate the directory by launching WebSSH > mashREPL > `pwd`

**Comment by jarrah31** [comment]
hah, I'd have never have found it there - thanks!
So, next problem, can't seem to find any logs... :)
The base directory is: `/Users/me/Library/Containers/com.itimeteo.webssh/Data`. Within here we have:
```
CloudKit
Desktop -> ../../../../Desktop
Documents
Downloads -> ../../../../Downloads
Library
Movies -> ../../../../Movies
Music -> ../../../../Music
Pictures -> ../../../../Pictures
SystemData
tmp
```
Library folder appears to be the best bet because it actually has a Logs folder:
```
Application Scripts
Application Support
Audio -> ../../../../Audio
Caches
Calendars -> ../../../../Calendars
ColorPickers -> ../../../../ColorPickers
ColorSync -> ../../../../ColorSync
Colors -> ../../../../Colors
Components -> ../../../../Components
Compositions -> ../../../../Compositions
Cookies
Dictionaries -> ../../../../Dictionaries
Favorites -> ../../../../Favorites
Filters -> ../../../../Filters
FontCollections -> ../../../../FontCollections
Fonts -> ../../../../Fonts
Images
Input Methods -> ../../../../Input Methods
KeyBindings -> ../../../../KeyBindings
Keyboard Layouts -> ../../../../Keyboard Layouts
Keychains -> ../../../../Keychains
Logs
Mail -> ../../../../Mail
PDF Services -> ../../../../PDF Services
Preferences
QuickLook -> ../../../../QuickLook
Saved Application State
Sounds -> ../../../../Sounds
Spelling -> ../../../../Spelling
WebKit
```
Logs is empty though:
```
➜  Logs ls -al
total 0
drwx------   2 me  staff    64 13 Sep  2021 .
drwx------  32 me  staff  1024 13 Sep  2021 ..
➜  Logs pwd
/Users/me/Library/Containers/com.itimeteo.webssh/Data/Library/Logs
➜  Logs
```
Confirmed that Verbose logging is enabled:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/3072303/160094634-c3993f2a-2da8-4868-be04-8f09300e7536.png">
I've checked the other folder but had no luck finding the logs.

On another note, I tried this on my phone and it did indeed work ok. However I noticed that it worked by setting up a VPN profile on the phone. Does the Intel Mac version try to do the same? I didn't see any messages asking me to add WebSSH to VPN Configuration on the Mac like it does here on the phone:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/3072303/160096197-e06acee3-a7dd-4e26-a352-e7934475cc7f.png">

**Comment by isontheline** [comment]
@jarrah31 

1. Have you restarted (killed) WebSSH after choosing verbose logging?
Log file should be here :
<img width="604" alt="image" src="https://user-images.githubusercontent.com/44212923/160191570-f979f780-4a3a-444a-8d81-12fd4ea8e16e.png">

2. VPN-Over-SSH is only available on iOS. On macOS there is no need to add VPN profile in order to work properly.

Please come back to me at any time

Have a nice day ☀️

**Comment by jarrah31** [comment]
A restart of WebSSH is what I was missing! Logs now appear within Documents as you described. :) 

Tested this at home today and found the connection to 192.168.0.10 only works when on my local network (with or without the tunnel). When I connect externally (via my phones data connection), the tunnel link works but the subsequent connection to 192.168.0.10 doesn't.
```
2022/03/26 13:40:47:987 [VERBOSE] not launched
2022/03/26 13:40:48:099 [VERBOSE] Want to connect with a Private Key
2022/03/26 13:40:48:099 [VERBOSE] Private Key is encrypted : 1
2022/03/26 13:40:48:099 [VERBOSE] Load Private Key in OpenSSH Format
2022/03/26 13:40:48:223 [VERBOSE] Launching connection...
2022/03/26 13:40:48:223 [VERBOSE] Connecting to TUNNEL...
2022/03/26 13:40:57:117 [DEBUG] Fetching from iCloud with a change token
2022/03/26 13:41:00:479 [VERBOSE] Is now connected to TUNNEL
2022/03/26 13:41:00:479 [VERBOSE] Fresh requested for connection list...
2022/03/26 13:41:00:671 [DEBUG] iCloud data fetched with success.
2022/03/26 13:41:07:984 [VERBOSE] Want to connect with a Private Key
2022/03/26 13:41:07:984 [VERBOSE] Private Key is encrypted : 1
2022/03/26 13:41:07:984 [VERBOSE] Load Private Key in OpenSSH Format
2022/03/26 13:41:08:111 [VERBOSE] Launching connection...
2022/03/26 13:41:08:111 [VERBOSE] Connecting to SSH...
2022/03/26 13:41:08:111 [VERBOSE] Launching connection with block...
2022/03/26 13:41:08:112 [VERBOSE] Won't dismiss prompt because no one is displayed.
2022/03/26 13:41:12:119 [DEBUG] Fetching from iCloud with a change token
2022/03/26 13:41:14:843 [DEBUG] iCloud data fetched with success.
2022/03/26 13:41:27:119 [DEBUG] Fetching from iCloud with a change token
2022/03/26 13:41:28:195 [DEBUG] iCloud data fetched with success.
2022/03/26 13:41:42:119 [DEBUG] Fetching from iCloud with a change token
2022/03/26 13:41:42:486 [DEBUG] iCloud data fetched with success.
2022/03/26 13:41:57:119 [DEBUG] Fetching from iCloud with a change token
2022/03/26 13:41:59:419 [DEBUG] iCloud data fetched with success.
2022/03/26 13:42:10:838 [VERBOSE] <SSHLog>
  <Connect_Ssh>
    <SSHVersion>9.5.0.88</SSHVersion>
    <connectInner>
      <hostname>192.168.0.10</hostname>
      <port>22</port>
      <sshConnect>
        <connectSocket>
          <connect_ipv6_or_ipv4>
            <error>timeout waiting for connect to complete;</error>
            <timeoutMs>60000</timeoutMs>
            <failedWaitToConnect>Socket operation timeout.</failedWaitToConnect>
          </connect_ipv6_or_ipv4>
        </connectSocket>
        <error>Failed to establish initial TCP/IP connection</error>
        <hostname>192.168.0.10</hostname>
        <port>22</port>
      </sshConnect>
    </connectInner>
    <error>Failed.</error>
  </Connect_Ssh>
</SSHLog>
2022/03/26 13:42:10:947 [VERBOSE] Dismissing prompt...
2022/03/26 13:42:12:120 [DEBUG] Fetching from iCloud with a change token
2022/03/26 13:42:12:548 [DEBUG] iCloud data fetched with success.
2022/03/26 13:42:12:861 [VERBOSE] Error : Can not establish connection to 192.168.0.10
2022/03/26 13:42:27:120 [DEBUG] Fetching from iCloud with a change token
2022/03/26 13:42:27:500 [DEBUG] iCloud data fetched with success.
```

**Comment by isontheline** [comment]
@jarrah31 

Some relevant log lines should be there in your report but I don't find them, perhaps an older release (or a bug on my side).

Could you give me your WebSSH build number?

**Comment by jarrah31** [comment]
Really sorry, I should know that the first rule of thumb is to always upgrade to the latest version before saying something doesn't work! 

I was on v17.0, so upgraded to 17.3 and now it all works. :) 

Thank you for being patient, and for producing such an excellent SSH app! Finally - a proper Putty for macOS alternative!

**Comment by isontheline** [comment]
@jarrah31 Don't worry, you're Welcome!

Thank you again for your feedback about WebSSH usage 👍

> Finally - a proper Putty for macOS alternative!

🙏 You have made my day

**Comment by jarrah31** [comment]
Just a little suggestion for future new WebSSH users, could you make a note on your "Dynamic Port Forwarding" help pages that says this is a ProxyJump alternative please? (perhaps it could say (aka Bastian or ProxyJump))

**Comment by isontheline** [comment]
@jarrah31 This could be an alternative but I've juste created an issue for the "true" jump feature : [Jump and multi-jumps](https://github.com/isontheline/pro.webssh.net/issues/577)

May I ping you when this new jump feature will be ready?

**Comment by jarrah31** [comment]
Yes please, that would be great! Thanks!
