### ISSUE TITLE
Add visibility of enabled tunnel

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#267]
**Describe the feature**
When a tunnel is alive it should be great that an indicator in WebSSH is enabled :
* Icon on navigation bar 
* OR
* A different navigation bar color : purple?

**Comment by BruceAC** [comment]
Not sure if my comment is the same as this enhancement, or a different enhancement.
I would like to see an indication of an active tunnel displayed in the upper right corner, the same place where I now see battery level, wireless network signal strength and a VPN indicator is displayed when using a standard IOS configured VPN.  For a WebSSH tunnel, the indicator could be a small rectangle with SSH, or it could simply use the standard IOS VPN indicator.  Some indicator would be nice to reassure me that a SSH tunnel is still active, and remind me to turn it off when I don’t need it anymore

**Comment by isontheline** [comment]
Hello @BruceAC 👋

Yes it's the same enhancement.
The VPN icon have disappeared since the [notch](https://discussions.apple.com/thread/8224478).

Unfortunately the status bar can't be customized 😢  so I need to find another way to notify the user.

Perhaps you would like to [turn off VPN-Over-SSH](#451) in the upcoming 17 release instead?

**Comment by isontheline** [comment]
I'm closing this issue yet as I can't improve the visibility of enabled tunnels under iOS
