### ISSUE TITLE
Some commands have a chance to have the word "the" appended to them.

### ISSUE THREAD

**Issue by icedterminal** [isontheline/pro.webssh.net#269]
**Information**
 - Device : iPhone 7
 - OS : 14.4.2
 - WebSSH Pro version : Not sure. There's two number strings here. https://i.imgur.com/D86mGhB.png

**Video**
https://youtu.be/hgv343spzeU

**Details**
Typing out `apt update` and tapping RETURN or SPACE will append the word _“the”_ to the command. So you get `apt updatethe` – This is a consistent problem.

I've narrowed it down to being related to the use of the letter _“e”_. If a command ends with a word that ends with this letter, it has a chance to happen. Not always. Hence why `apt upgrade` had no issue in this example, as did a few other examples. I kept trying until it happened again just by typing out `te`. 

This appending behavior doesn’t happen when physically using the target computer terminal or through another desktop computer via ssh. It only happens in this app.

**Comment by isontheline** [comment]
Hello @icedterminal 👋

I can't reproduce your issue. 
Perhaps it's related with a system setting?

It's the first time I hear about this kind of issue.

**Comment by icedterminal** [comment]
> Perhaps it's related with a system setting?

In regards to iOS or Ubuntu?

If you mean Ubuntu, I did test that theory since you brought it up. I created a fresh install in a VM and bridged the network connection so iOS could see it. Sill occurs. https://youtu.be/Jo5rz0irWSs

Is there some way I could provide you app logs?

**Comment by isontheline** [comment]
In regards of iOS settings like autocomplete or auto-correct, not on the Ubuntu side.

Autocomplete is disabled inside WebSSH textarea, but perhaps there is a special settings in iOS to overwrite this behavior.

**Comment by icedterminal** [comment]
Autocomplete (text replacement) is empty. I don't have anything there. So it could be auto correct. In some form. That's a good point. I'll continue to try and figure it out.

**Comment by icedterminal** [comment]
This app allowed me discover a bug with my iOS autocorrect feature. I reset the phone and the problem is gone. Though I'd really like to know the correlation. But I guess at this point I'll never know.

**Comment by isontheline** [comment]
Thank you a lot for your feedback @icedterminal 👍

By reset you mean restart?
