### ISSUE TITLE
Tunnel : Red dot doesn't go to gray when disconnected

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#27]
Just downloaded 14.0.4. The tunnel connects (and works!) without crashing. 

However, when I try to disconnect the tunnel, nothing seems to happen. No matter how much I tap the name of the connection, the dot stays red.  But if I then try to connect via the tunnel, it no longer works. 

So it appears that it does disconnect the tunnel, but the dot stays red, and the only way I can reconnect is to force-quit the app and start again.

_Originally posted by @nborof in https://github.com/isontheline/pro.webssh.net/issues/18#issuecomment-667697465_

**Comment by nborof** [comment]
Just to be clear, the dot does not turn gray, AND I am unable to reconnect to that tunnel unless I force-quit the app and start over again.

**Comment by isontheline** [comment]
@nborof You are clear. I have two problems :
- Red dot don't changing color to gray when tunnel is off
- App can't reuse the same local forward port for a few seconds because not closed properly

I will fix these asap

**Comment by avalonix** [comment]
Will the application always fall asleep in the background?  nothing can be done about it?  the application from Microsoft for rdp does not support split view, only slide over.

**Comment by isontheline** [comment]
@avalonix Yes background operations are not welcomed by Apple due to battery drain.

That's why I think I should go to the direction of a VPN #25 

If anyone has another idea, please tell me.

**Comment by isontheline** [comment]
@nborof Red dot has been fixed inside the new beta release 14.1.6
Could you try it?

**Comment by nborof** [comment]
The red dot now turns gray, and I can connect, disconnect, and reconnect normally.  All seems good!

With regards to going in the direction of a VPN, I don’t understand the entirely how that would work, but I would like to still be able to use the classic port forwarding via tunneling, in addition to any new VPN features.

**Comment by isontheline** [comment]
@nborof Great!
Yes you're right : if a VPN feature will come it won't overwrite the current port forwarding feature. The current feature must be kept as it.
