### ISSUE TITLE
Snippets per host/group 

### ISSUE THREAD

**Issue by hunter-nl** [isontheline/pro.webssh.net#272]
**Describe the bug**
Update 14.16 has changed the feature ‘snippets’. Before update I had different snippets per host configured. Now they all merged into 1 list and only the first 5 (alfabetische in the list) are shown as icon. This makes for me the snippets much less usable.
Please restore the feature back to previous version.

**Informations**
 - Device : iPhone XS MAX
 - OS : iOS 14.15.1
 - WebSSH Pro version : 14.16.10

**Comment by isontheline** [comment]
Sorry to hear that this new **intended** behavior doesn't comply with your needs 😢  but it was a nightmare to maintain.

I need some time to think about your issue.

**Comment by isontheline** [comment]
Perhaps the best is to implement tags on snippets : a snippet could have a tag and the snippet will be displayed if the tag is the same as the host.

What do you think?

**Comment by hunter-nl** [comment]
If it is possible to assign multiple tags to snippets and hosts then that would be maybe a solution.

**Comment by isontheline** [comment]
@ash34 You seem to also use snippets in your connections :

* Did you use also specific snippets per host?
* Does tags assignation could be the ideal solution in order to split snippets per host?

**Comment by ash34** [comment]
No sorry I use the same for every host. “sudo journalctl -b -o short-iso -n 20 -p err“ because the first thing I need to know is if there are any problems.

**Comment by isontheline** [comment]
Thanks for your feedback @ash34 👍

@hunter-nl I will so implement tags on hosts and snippets.
Planned for current release 14.17 - Trèfle

**Comment by mbierman** [comment]
Tags would be a fine way to handle this. Maybe instead of free form tags a user could screw up, just have it so user can select the hosts they want the snippet available in or check boxes.

**Comment by mbierman** [comment]
I'm confused... is this still planned? What's the ETA?

**Comment by isontheline** [comment]
@mbierman Hello 👋

* Still planned but still delayed in favour of bugs.
* No ETA. I don't drive by ETA.
* What about https://github.com/isontheline/pro.webssh.net/issues/309#issuecomment-859897583 ?

**Comment by isontheline** [comment]
Work In Progress : Ability to add tags on snippets and hosts

**Comment by isontheline** [comment]
# Tags on servers and snippets

| From terminal | Server list |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/44212923/127709227-7b22a753-e8cd-4558-b143-f1285b599389.png) | ![image](https://user-images.githubusercontent.com/44212923/127709291-71250ab3-0224-459d-985e-11635578726e.png) |

**Comment by isontheline** [comment]
Hello @mbierman @hunter-nl @ash34 👋

I hope your are fine 🏖

Could you try WebSSH 15.0.8?
https://testflight.apple.com/join/QSrBK59z

Have a nice day ☀️

**Comment by mbierman** [comment]
> Hello @mbierman @hunter-nl @ash34 👋
> 
> I hope your are fine 🏖

I am indeed!

> Could you try WebSSH 15.0.8?
> https://testflight.apple.com/join/QSrBK59z

I cannot get to snippets. Clicking the gear brings up the keyboard. 

> Have a nice day ☀️
You too.

**Comment by isontheline** [comment]
@mbierman Thanks for your feedback but I don't understand 😕

* Are you sure that you don't press the search bar?
* Are you running iOS 14 or iOS 15?
* Could you make a video to replay the bug?

**Comment by mbierman** [comment]
Sure. I can’t use snippets at all because they aren’t selectable. All that happens is the keyboard opens.

https://youtu.be/b3VP2TlIp3E

**Comment by isontheline** [comment]
@mbierman OK I see 😬 sorry.

I will send a fix tonight.

**Comment by mbierman** [comment]
No worries. That’s what testing is for.  Thank you

**Comment by isontheline** [comment]
Does WebSSH 15.0.9 fix the issue?

**Comment by mbierman** [comment]
@isontheline yes, but I don't understand how to assign snippets to one or more connections. Tags don't seem to do it.

**Comment by isontheline** [comment]
@mbierman When a connection and a snippet share at least one tag then they are linked.

There is a limit of five snippets that can be shown at same time (due to yesterday bug), but others snippets can be shown inside a list when you press the gear.

**Comment by mbierman** [comment]
O.K. some feedback

1. It can be hard to edit the ssh list in some cases. See the last one in my list which is covered by the “+” button.
![A3697464-675D-431B-9DE5-CAB50266FA9D](https://user-images.githubusercontent.com/1205471/127777633-2718da82-a9fb-48e6-93f9-bdbe6f841c6d.png)

2. How can I add two tags? “A,b” “A/b” “A b”? It would be nice if there was some example text in the UI to remind users. 
3. Does capitalization matter?
4. Maybe there can be a default tag for connections? Hostname or IP? Initially I applied tags to snippets and nothing happened.

**Comment by isontheline** [comment]
@mbierman 

1. I have [planned](https://github.com/isontheline/pro.webssh.net/issues/365) a fix thank you! Workaround : you can also edit a connection by long pressing a row.
2. Tags can be separated by any of these chars : `,;/-|` and `space`. You can mix the separators on the same line. OK I will add a reminder.
3. Tags are always capitalized. It's "not possible" to add a lower case tag (or should be reported as bug).
4. By default a blank tag is applied so all snippets are linked to all connections. If you add a tag to a snippet, the same tag should applied to a connection in order to link them. You can also use the wildcard `*` to link a snippet to all connections.

**Comment by isontheline** [comment]
@mbierman Does my previous feedback answers all your questions or do you need more information?

**Comment by mbierman** [comment]
So if space is a valid separator can you quote two words to have a tag with a space?

**Comment by isontheline** [comment]
No - yet - only one word tags are supported in order to reduce complexity of implementation.
