### ISSUE TITLE
Rename "Remote command" to "Execute command"

### ISSUE THREAD

**Issue by ash34** [isontheline/pro.webssh.net#276]
**Describe the bug**
The function where a snippet would automatically be run after an SSH connection is made has stopped working. In fact I can’t even find where the setting is anymore. 

**Informations**
 - Device : IPad 7
 - OS : iOS 14.5
 - WebSSH Pro version : 14.16.10

**Screenshots**
N/A

**To Reproduce**
1. Select a saved SSH connection to begin the connection
2. After connection and login observe that your previously auto running snippet no longer is executed automatically.

**Comment by ash34** [comment]
I see that it has been removed intentionally. 

“ Run snippet at connection startup is now removed. Use instead remote command.”

But what is “remote command”? Where do I find that?

**Comment by isontheline** [comment]
@ash34 On connection settings > terminal settings > Remote command

You should use something like this :

`df -h; bash`

The last command let you to continue in the terminal.

Snippets won't run anymore at startup because a lot of time we can't know when the shell is available and ready.

**Comment by ash34** [comment]
Ok thanks. Maybe the name “remote command” is not so obvious, though. “Initial command”, “auto command” or something similar might be better.

**Comment by isontheline** [comment]
@ash34 It's not "initial" or "auto" because it could be a command that closes the connection after it's execution. But I don't know how to name it right.

* "Launch command"?
* "Startup command"?
* "Execute command"?

**Comment by ash34** [comment]
Maybe execute is best out of those.

**Comment by isontheline** [comment]
Thanks for your feedback @ash34 I will change this label on this release 14.17 - Trèfle
