### ISSUE TITLE
Crash when try to save a file

### ISSUE THREAD

**Issue by Killer0561** [isontheline/pro.webssh.net#28]
If you try to edit a file and want to save it, the app crashes and you have to open it again.

**Comment by isontheline** [comment]
Hey @Killer0561 !
Could you try if it crashes with this beta release?
https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
Seems to be related to #15 
Waiting for @Killer0561 for joigning beta release

**Comment by isontheline** [comment]
@Killer0561 I'm closing this issue because I don't I received any crash report through TestFlight.

Crash keep happening? Just ask to re-open this issue ;)

Have a nice day
