### ISSUE TITLE
Allow multiple port forwarding tunnels at the same time : VPN-Over-SSH

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#284]
I bought the webssh on 08/20/2017 (iphone SE). Previously, multiple tunnels worked, but now writes "Please disconnect tunnel before launching another"

_Originally posted by @rootrrv in https://github.com/isontheline/pro.webssh.net/discussions/283_

**Comment by isontheline** [comment]
Checking if multiple forwards (not dynamic, just port forward) can be allowed in the new NEVPN component used by WebSSH since October 2020.

**Comment by rootrrv** [comment]
hello, do you have any news?

**Comment by rootrrv** [comment]
Hello, do you have any news?

**Comment by isontheline** [comment]
Hello @rootrrv Roman,

Yes checks are OK it could be implemented again inside WebSSH.

However, I don't have any ETA :/

**Comment by isontheline** [comment]
Hello @rootrrv Roman 👋

Do you need multiple port forwarding on the same connection like this issue #319 ?

**Comment by rootrrv** [comment]
This is desirable, but not necessary. The main thing is that I can forward tunnels in different sessions. For forwarding a tunnel to the inside of another tunnel, for accessing internal servers that do not have an external IP and are available only within the local network.
Example:
1: my phone -> my_public_server:22 => port forward: 8222:my_private_server:22
2: my phone -> localhost:8222 => port forward: 83389:my_pc:3389 (RDP)
3: my phone RDP client -> localhost:83389

**Comment by isontheline** [comment]
@rootrrv Thanks for your feedback!

**Comment by isontheline** [comment]
@rootrrv Work In Progress

A beta release will be available soon : 
https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
Only non "VPN-Over-SSH" tunnels will allow multiple connections.
An option to enable / disable VPN-Over-SSH will be provided in the next few days.

**Comment by isontheline** [comment]
WIP

**Comment by isontheline** [comment]
Will be available tomorrow

**Comment by isontheline** [comment]
Available in latest beta release : 
https://testflight.apple.com/join/QSrBK59z
