### ISSUE TITLE
Ability to use tunnels with other VPN than WebSSH

### ISSUE THREAD

**Issue by jbcoffin** [isontheline/pro.webssh.net#287]
**Describe the bug**
We can not use the tunnel function with a proper VPN.
🇫🇷 FR :  on ne peut utiliser un pont et un VPN en même temps. Créer un pont  créer un VPN dans les réglages de l'appareil et déconnecte de tout autre VPN. 

case of use : 
- I would like to distance connect to my Jupiter-notebook (which is on my desktop) with my iPad.
- To do so, i need to connect to internet (4g or wifi whatever), use my VPN, then connect shh and finally create a tunnel.
- for the moment, webssh create a "kind of VPN as tunnel". That unallow using tunnel and VPN at the same time.  
**Informations**
 - Device : iPad 
 - OS : 14.4.12
 - WebSSH Pro version : 14.6

**Comment by isontheline** [comment]
Bonjour @jbcoffin 🇫🇷 👋

C'est exact WebSSH créer une connexion VPN pour établir en tâche de fond la redirection de ports ce qui cause des problèmes lorsque l'on souhaite utiliser un VPN.

I **will** so add an general option inside WebSSH (enabled by default) :
* Enable / Disable "VPN-Over-SSH"

When disabled it will allow you to use port forwarding with your VPN connection. The only drawback **will** be that the port forwarding will not survive about 30 seconds when WebSSH is in background.

@jbcoffin are you OK with these statements?

**Comment by jbcoffin** [comment]
> When disabled it will allow you to use port forwarding with your VPN connection. The only drawback **will** be that the port forwarding will not survive about 30 seconds when WebSSH is in background.

Je n'ai pas bien compris. Cela voudrais dire que je ne pourrais être connecté que 30 secondes ?

**Comment by isontheline** [comment]
@jbcoffin 30 secondes si WebSSH est en arrière plan. C'est pour cette raison que le fonctionnement VPN est adopté depuis octobre 2020 à la fois pour faire perdurer la connexion et offrir le tunneling à d'autres applications en dehors de WebSSH.

**Comment by isontheline** [comment]
@jbcoffin Est-ce OK pour vous ?

**Comment by isontheline** [comment]
@jbcoffin I'm closing this issue, please reopen it as soon as you want
