### ISSUE TITLE
Snippets not syncing betwen iPad and iPhone

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#308]
**Describe the bug**
When I go to Settings > Snippets on iPad I see many more snippets than when I go to the iPhone so they are not syncing. 

**Information**
 - Device : iPad 7th Gen, iPhone 12 mini
 - OS : iPad 14.6
 - WebSSH Pro version : 14.18.4

**Screenshots**
![IMG_4532](https://user-images.githubusercontent.com/1205471/120043249-77d4e880-bfc0-11eb-9674-79415247f1fb.PNG)
![IMG_6280](https://user-images.githubusercontent.com/1205471/120043655-37c23580-bfc1-11eb-917a-d57c8d144f0a.PNG)

**To Reproduce**
1. Go to 'Settings'
2. Touch on "Snippets"

**Comment by isontheline** [comment]
Please relaunch the full sync :
1. WebSSH Settings > iCloud > Disable
2. Wait 10 seconds
3. Enable sync again

Your snippets will be synced in about 30 to 60 seconds.

**Comment by isontheline** [comment]
@mbierman Does the provided steps above fix your sync?

**Comment by mbierman** [comment]
Yes, thank you.
