### ISSUE TITLE
Can't edit snippets on iPad

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#309]
**Describe the bug**
Can't edit Snippets on iPad

**Information**
 - Device : iPad 7th Gen
 - OS : iOS 14.6
 - WebSSH Pro version : 14.18.4

**Screenshots**
![IMG_102F12F12452-1](https://user-images.githubusercontent.com/1205471/120044004-d484d300-bfc1-11eb-981b-f47cb38dbc9d.jpeg)

**To Reproduce**
1. Go to 'Settings'
2. Touch on 'Snippets'
3. Try to edit a snippet
4. See error in screenshot

**Comment by isontheline** [comment]
Hello @mbierman 👋

Is it since 14.6?

**Comment by isontheline** [comment]
@mbierman I have upgraded to 14.16 and can't reproduce.

But I will make a fix related to https://github.com/isontheline/pro.webssh.net/issues/232

**Comment by mbierman** [comment]
The list of snippets has to be long enough to cause scrolling and then this happens  is only Delete and Cancel. 

![Uploading 22EEEE02-86BF-4BBA-A945-2B34AEA2F236.png…]()

**Comment by isontheline** [comment]
Thank you a lot for your feedback @mbierman 

I will work on #232 as soon as possible so it will fix your issue.

Sorry for the trouble though

**Comment by isontheline** [comment]
Hello @mbierman 👋

Does WebSSH 14.19.2 have fixed (or not) your issue?

**Comment by mbierman** [comment]
> Hello @mbierman 👋
> 
> Does WebSSH 14.19.2 have fixed (or not) your issue?

Yes, that takes care of this issue! Thank you so much.

**Comment by isontheline** [comment]
@mbierman Thank you a lot for your feedback 👍
