### ISSUE TITLE
Safe area not respected on iPad Pro with floating keyboard

### ISSUE THREAD

**Issue by Snowy1803** [isontheline/pro.webssh.net#311]
**Describe the bug**
The bottom of the terminal, where I'm writing the commands, is invisible as it's obscured by the keyboard accessory toolbar, which is itself not respecting the bottom safe area inset

**Informations**
 - Device : iPad Pro 12.9 5th Gen (2021)
 - OS : iOS 14.6
 - WebSSH Pro version : 14.17.10

**Screenshots**
![image](https://user-images.githubusercontent.com/7999977/120085629-26b91780-c0da-11eb-83c5-8388573053a7.jpeg)

**To Reproduce**
1. Open an ssh session
2. Cat a big file so the terminal takes up all the vertical space
3. Pinch the keyboard to get the floating keyboard
4. Can't see what you write anymore

**Comment by isontheline** [comment]
Bonjour @Snowy1803 Emil 🇫🇷 👋

Thank you a lot for your bug report!
You're right Safe Area Inset is not respected when the keyboard is detached and I will make a fix as soon as I can.

Belle journée à vous ☀️

**Comment by Snowy1803** [comment]
:/

**Comment by isontheline** [comment]
WIP

![image](https://user-images.githubusercontent.com/44212923/129492083-5b04e909-01dc-4be0-b418-ce8c5a18d21d.png)

**Comment by isontheline** [comment]
@Snowy1803 Now fixed inside WebSSH 15.1.1 : https://testflight.apple.com/join/QSrBK59z
