### ISSUE TITLE
SFTP: can't edit a file with a French letter inside

### ISSUE THREAD

**Issue by vc02** [isontheline/pro.webssh.net#317]
**Describe the bug**
SFTP : we can't edit a PHP file which contains French letters. For example, if there is an "é" in the HTML code, when you click on "edit file", a blank page appears.

**Informations**
 - Device : Iphone SE
 - OS : 14.6
 - WebSSH Pro version : 14.18.1

**Screenshots**

**To Reproduce**
1. Go to SFTP
2. log in to a server
3. edit a PHP file with an "é" in the code for example (any French letters) - ending in .php (maybe in other types)
4. a blank page appears, no content, no icon to save, can't edit the file

**Comment by isontheline** [comment]
Hello @vc02 👋

Thank you a lot for your bug report!
I can confirm too that this bug exists.

I will fix it as soon as I possible.

Bonne journée à vous ☀️

**Comment by isontheline** [comment]
It's not related with diacritics :
![image](https://user-images.githubusercontent.com/44212923/121735529-8c53cd80-caf6-11eb-8aff-af44c40088bd.png)

I'm searching the root cause...

**Comment by isontheline** [comment]
Related to file encoding and BOM. 

I'm fixing it.

**Comment by isontheline** [comment]
Hello @vc02  👋 

I have fixed it : please install _WebSSH Beta_ from TestFlight app : https://testflight.apple.com/join/QSrBK59z

☀️ Have a nice day

**Comment by vc02** [comment]
Super ! Merciiii 👍

**Comment by isontheline** [comment]
Avec plaisir 😉
