### ISSUE TITLE
Missing Multi Window Box on Mac Mini / MacOS

### ISSUE THREAD

**Issue by Obsidiannite21** [isontheline/pro.webssh.net#318]
**Describe the bug**
I’m using your app on a mac mini & ipad. On my ipad I can open multiple terminal windows using the little box in the upper right, but on my mac the box does not appear even though I’ve checked the box that says “allow multiple features at the same time”. Am I missing something?

**Informations**
 - 2020 Mac Mini / M1
 - OS : Newest
 - WebSSH Pro version : Newest

**Comment by isontheline** [comment]
Hello @Obsidiannite21 👋

Strange 🙁
On my side it works as expected.

Have you tried to 
* Restart the app?
* Disable then enable again the box?

**Comment by Obsidiannite21** [comment]
Hello,

Yep, along with a reboot to be sure. When I disable / re-enable that box it looks like the app "refreshes" but nothing changes.

**Comment by isontheline** [comment]
Doesn't this icon appear?
![image](https://user-images.githubusercontent.com/44212923/121814589-2a1fd780-cc72-11eb-814b-a04ed7372597.png)

**Comment by Obsidiannite21** [comment]
No. I'm using the iPad / IOS version found in the store. I didn't see one for mac, but your's looks different.....
![Screen Shot 2021-06-13 at 12 12 08 PM](https://user-images.githubusercontent.com/28603530/121814834-14de8500-cc41-11eb-95a5-852f1bc18cae.png)

**Comment by isontheline** [comment]
@Obsidiannite21 iCloud is enabled and working?

**Comment by Obsidiannite21** [comment]
Yes, all of my connections downloaded when I first installed the app today.

**Comment by isontheline** [comment]
@Obsidiannite21 Thanks

When you come back to the settings does the tick is always checked? 

Or you need to check it again every time?

I'm checking why the multiple features doesn't work for you.

**Comment by Obsidiannite21** [comment]
It always stays checked.

**Comment by isontheline** [comment]
Thanks @Obsidiannite21 

Could you try these step please?
1. On your iPad disable the "Multiple features"
2. Wait 15-30 seconds and check that the box have been disable on your mac mini
3. Enable the "Multiple features" again on your iPad
4. Wait 15-30 seconds and check that the box have been enabled on your mac mini
5. Close WebSSH on your mac mini
6. Open WebSSH again on your mac mini

Does it resolve your issue?

**Comment by Obsidiannite21** [comment]
Will do when I get home.

**Comment by Obsidiannite21** [comment]
Ok, I followed the steps you provided. Everything happens in the way you described but it did not resolve my issue.

**Comment by isontheline** [comment]
@Obsidiannite21 Thank you!

May I send you more additional tests?

1. Launch WebSSH on your macOS
2. Launch mashREPL (top right icon)
3. Type : `webssh database locate`
4. Copy the path of the database into the clipboard
5. Now open the "terminal" app on your **macOS**
6. Type `sqlite3 "past_path_here_of_database`
7. Type `SELECT * FROM NSFValues WHERE NSFAttribute='settingKey'`

You should obtain one or more results like this :
![image](https://user-images.githubusercontent.com/44212923/121844265-0006fd80-cce4-11eb-9af3-1b70bc0ebb01.png)

For each row returned, could you extract their values?
* Eg : `SELECT * FROM NSFValues WHERE NSFKey='C9CC0E3D-0475-4F14-8507-9963EB52B59B';`
* 'C9CC0E3D-0475-4F14-8507-9963EB52B59B' come from the previous steps, and you need to change it with your own values
![image](https://user-images.githubusercontent.com/44212923/121844639-90ddd900-cce4-11eb-865d-c4c869f20eb6.png)

Sorry for these hard steps but I need more information in order to help you.

Have a nice day.

**Comment by Obsidiannite21** [comment]
I coudln't copy / paste from webSSH so please double check for typo's. 
![Screen Shot 2021-06-14 at 7 55 53 AM](https://user-images.githubusercontent.com/28603530/121888565-27f76080-cce6-11eb-942d-17dc0a80bc31.png)

**Comment by isontheline** [comment]
@Obsidiannite21 Long press left button to show copy menu

**Comment by Obsidiannite21** [comment]
Ah, thanks, thats much easier. Same result though.

**Comment by isontheline** [comment]
@Obsidiannite21 Don't forget the semicolon ; at the end if the request

**Comment by Obsidiannite21** [comment]
Getting closer..... I tried to extract the values but it didn't seem to work on the first one. Should I try the rest or is there something wrong with my santax. 
![Uploading Screen Shot 2021-06-14 at 12.11.24 PM.png…]()

**Comment by isontheline** [comment]
No need to try the rest I think I have all information I need. 

But I can't find yet why the multiple windows (ALLOW_MULTIPLE_FEATURES_SAME_TIME_TAG) doesn't work 😕

**Comment by isontheline** [comment]
Instead of querying about '0FC.......' could you try about 'D31F....' please ?

**Comment by Obsidiannite21** [comment]
Sure....
![Screen Shot 2021-06-14 at 3 50 35 PM](https://user-images.githubusercontent.com/28603530/121950962-4ed68680-cd28-11eb-965a-335ddb816192.png)

**Comment by isontheline** [comment]
The last quote is not the same as the first one and the query can't execute. 

Could you put a "standard" quote on the last ?

**Comment by Obsidiannite21** [comment]
Here ya go.
![Screen Shot 2021-06-14 at 4 15 19 PM](https://user-images.githubusercontent.com/28603530/121953595-c0640400-cd2b-11eb-9aa4-f5adee1e4a6d.png)

**Comment by isontheline** [comment]
@Obsidiannite21 Thank you!

When you click on the blue bar center (eg mashREPL title) what does it do?

**Comment by Obsidiannite21** [comment]
It opens up the multi window selector.

**Comment by isontheline** [comment]
You're Welcome 😉

Have a nice day
