### ISSUE TITLE
Multiple Port Forwarding : VPN-Over-SSH

### ISSUE THREAD

**Issue by melonsode** [isontheline/pro.webssh.net#319]
It is not clear whether multiple port forward is available or not.
I write tunnel setting like this:
8080:localhost:80, 8081:localhost:8081
I can connect only to 8080 port, but not to 8081.
I made another setting like:
8081:localhost:8081
then, I can connect to 8081.
I would like to connect to multiple port with one setting.

**Comment by isontheline** [comment]
Hello @melonsode 👋

Thanks for your issue from the App Store!

Yes you're right WebSSH currently supports only one port forward 😭

I will fix this issue as soon as possible for the 14.19 release

Have a nice day☀️

**Comment by isontheline** [comment]
Hello @melonsode 

Sorry for the too long delay
Now available : 
https://testflight.apple.com/join/QSrBK59z

**Comment by melonsode** [comment]
Thank you for your great work. I have tried it and I have confirmed multiple port forwarding. I appreciate this improvement. I suggest that the instruction of this are added. At first, I write like this:

8080:localhost:80,1234:localhost:56

It doesn’t work. Next I tried like this:

8080:localhost:80
1234:localhost:56

It works.

I know the instruction is shown such that “ Starting WebSSH 17.3 you can add multiple forwards, one per line.”  But it seems a little bit abrupt. I suggest you show complete examples like this:

For multiple port forward:

8080:localhost:80
1234:localhost:56
789:localhost:1011
(one per line)

**Comment by isontheline** [comment]
> I know the instruction is shown such that “ Starting WebSSH 17.3 you can add multiple forwards, one per line.” But it seems a little bit abrupt. I suggest you show complete examples like this:

You're right!

I will do that in the next few hours :
* Allow comma separated char
* Update the documentation about the use of comma and new carriage return to separate multiple forwards

**Comment by jarrah31** [comment]
This is really awesome! No need to remember multi-port CLI commands anymore! Whoo!
e.g. `ssh -J mypi -L 8123:127.0.0.1:8123 -L 8124:127.0.0.1:8124 me@192.168.0.10`

**Comment by isontheline** [comment]
> This is really awesome! No need to remember multi-port CLI commands anymore! Whoo!

😅 Thank you @jarrah31 

Don't hesitate to ask for new features if they could help in your daily life. I will try to make the most I can.
