### ISSUE TITLE
Tunnel: Incorrect termination of the session when disconnecting the ssh tunnel.

### ISSUE THREAD

**Issue by avalonix** [isontheline/pro.webssh.net#33]
1. Open ssh tunnel.  Click on the connection on the tunnel tab
 2. Click on the connection again to disconnect it
 3. Go to the ssh tab and see that the connection to the this server is not available (the gray circle is lit, not blue).  If you try to connect via ssh to this server but from another device, then the connection will not occur.  The server freezes for a while and does not accept connections

**Comment by isontheline** [comment]
@avalonix Yet I Iabel this issue "wontfix" because I dont'k understand why this can be a client (WebSSH) side issue.

Have you more logs on server side that should indicate the client is in fault?
Thanks.

**Comment by avalonix** [comment]
client does not close the session when clicking on the connection in the tunnel tab

**Comment by isontheline** [comment]
> client does not close the session when clicking on the connection in the tunnel tab

Issue #27 is already opened for this bug behavior. So I will fix both issue into #27 in the next hours.

Thanks again for your feedback @avalonix 👍

**Comment by avalonix** [comment]
Ok thx! I’m wait next beta
