### ISSUE TITLE
Landscape mode with iPhone notch

### ISSUE THREAD

**Issue by zephyr2k7** [isontheline/pro.webssh.net#332]
**Describe the bug**
Part of the terminal is hidden when using the iPhone in landscape mode

**Informations**
 - Device : iPhone 11 Pro
 - OS : ios14
 - WebSSH Pro version : latest from app store

**Screenshots**

**To Reproduce**
1. open a ssh shell
2. go in landscape
3. press enter at some point the text is hidden by the notch

**Comment by isontheline** [comment]
Hello @zephyr2k7 👋

Thank you for your bug report about the notch on iPhone!

I will make a fix in order to prevent text hiding by the notch.

**Comment by akuropka** [comment]
Actually my experience is if started in landscape mode it works´.
However, once coming from portrait to landscape the terminal includes the notch part and makes things partly invisible.
Going back to landscape brings some funny display in the top row as well...
![PNG image](https://user-images.githubusercontent.com/22570574/125962832-aea5f0f2-f2c4-4021-bd55-e66f17cdc4bf.png)
(Anyways, I usually don't use landscape mode.)

**Comment by isontheline** [comment]
Thanks for your feedback @akuropka 👍

I'm keeping this issue for a future release because 2FA and macOS x86 have a higher priority

**Comment by isontheline** [comment]
# Need to improve landscape mode
> Please add a margin to landscape mode on iPhone. The notch and round border cut off a lot of displayed info. It’s quite annoying.

By *Gink X* on the **App Store**

**Comment by isontheline** [comment]
![](https://user-images.githubusercontent.com/45514952/189422357-a94140c3-c310-4b4e-b5e0-f5e250bc7d4f.jpeg)

From https://github.com/isontheline/pro.webssh.net/issues/729#issuecomment-1242345912

**Comment by isontheline** [comment]
Are you always experiencing problems with 20.0?

**Comment by zephyr2k7** [comment]
Its ok on my side I can turn the iPhone and still see the whole terminal thanks On 25 Sep 2022, at 22:09, Arnaud Mengus ***@***.***> wrote:﻿
Are you always experiencing problems with 20.0?

**Comment by isontheline** [comment]
Thank you a lot for your feedback @zephyr2k7 🙏

**Comment by Suspectxyzz** [comment]
for me the problem still persisted
I have the latest app update 20.1
iOS : 15.6.1 iPhone X
![4980537D-DA2A-4C26-A24F-1797206A9637](https://user-images.githubusercontent.com/45514952/192884034-e270e073-14e5-4f74-b59e-328890f26d10.png)

**Comment by isontheline** [comment]
@Suspectxyzz Could you make a photo of the issue an the reproduce steps?
On my Xr the problem has gone.

**Comment by Suspectxyzz** [comment]
> @Suspectxyzz Could you make a photo of the issue an the reproduce steps?
> On my Xr the problem has gone.

sorry for the late reply but i was busy and forgot

I have the latest app update 20.1
iOS : 15.6.1 iPhone X

https://streamable.com/vrieku

**Comment by isontheline** [comment]
Thanks for your feedback @Suspectxyzz 

I'm reopening this issue

**Comment by Suspectxyzz** [comment]
Hello, with today's update you solved this bug, but others appeared 🫡
It doesn't work to delete folders, I think you know it's old in "STFP" (https://streamable.com/dyvc9r)
&
And with new edit text you can't select more or press the x button to delete faster
(https://streamable.com/of5lvk) ‘I noticed that you can't open files of any kind with this new text to edit even 1mb in size’

Last update (app Store )

**Comment by isontheline** [comment]
Hello @Suspectxyzz 👋

Thank you a lot for all your feedback 👍

Could you open an issue for each trouble?
Without distinct issues I can't plan the fixes easily.
