### ISSUE TITLE
Custom font support - like for powerlevel10k?

### ISSUE THREAD

**Issue by paulroth3d** [isontheline/pro.webssh.net#339]
**Describe the bug**
No worries if not, but might support for custom fonts be considered?

for example 

- setup a box with zsh
- Install powerlevel10k , [such as the instructions here](https://github.com/romkatv/powerlevel10k#get-started)
- Then setup to configure, and have it “prefer icons” - if there are questions here, happy to help)
- Connect to the box using iSSH

Note that it will connect but the icons look like unfound Unicode, see here for an example

https://github.com/romkatv/powerlevel10k/issues/671

———

note that the end user can install fonts such as through the process here (less work for us)

https://support.apple.com/guide/iphone/install-and-manage-fonts-iphb2517689c/ios

Or we can download within the app dynamically 

see here for more on how to access both installed or dynamic fonts within swift, if it helps

https://stackoverflow.com/questions/58012123/list-of-installed-fonts

although I know fonts are a pain on ios, but this could be quite helpful. And I would love any way we can get more exposure for iSSH.

I really like the tool you all put together

**To Reproduce**

for example 

- setup a box with zsh
- Install powerlevel10k , [such as the instructions here](https://github.com/romkatv/powerlevel10k#get-started)
- Then setup to configure, and have it “prefer icons” - if there are questions here, happy to help)
- Connect to the box using iSSH

Note that it will connect but the icons look like unfound Unicode, see here for an example

https://github.com/romkatv/powerlevel10k/issues/671

Appreciate any thoughts and thanks

**Comment by isontheline** [comment]
Hello @paulroth3d 👋

Yes P10K and font support issues are already tracked :
* https://github.com/isontheline/pro.webssh.net/issues/97
* https://github.com/isontheline/pro.webssh.net/issues/60

I've tried a few months ago to import the "Meslo Nerd Font patched for Powerlevel10k" but without success 😢

I will retry soon.

**Comment by isontheline** [comment]
My tonight experiments are "good" 👍

![image](https://user-images.githubusercontent.com/44212923/125208873-78d28880-e295-11eb-96e1-575577d5b2b6.png)

**Comment by isontheline** [comment]
* https://github.com/uncon/MesloLGSNF-web-fonts
* https://www.uncon.net/MesloLGSNF-web-fonts/stylesheet.css
* https://stackoverflow.com/a/25798199/8102448

**Comment by isontheline** [comment]
Hello @paulroth3d 👋

Please try the latest WebSSH 15.0 Beta Release : 
https://testflight.apple.com/join/QSrBK59z

P10K font have been included.

Have a nice day ☀️
