### ISSUE TITLE
Face ID login crash : Crashing due to privacy violation

### ISSUE THREAD

**Issue by avalonix** [isontheline/pro.webssh.net#34]
**Describe the bug**
Face ID login crash

**Informations**
 - Device : iPhone 11
 - OS : 13.6
 - WebSSH Pro version : 14.1.1

**Video**
https://youtu.be/g3ElNDH8M9k

**To Reproduce**
1. run the application.  go to settings and set a digital password.
 2. The switch for using Face ID is on
 3. I close the application
 4. I open it in order to log in with Face ID
 5. Application opens and exits with an error

**Comment by isontheline** [comment]
> Termination Reason: TCC, This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSFaceIDUsageDescription key with a string value explaining to the user how the app uses this data.

I will fix it in a few hours.

**Comment by isontheline** [comment]
@avalonix Should be fixed by 14.1.2 but does it?

**Comment by isontheline** [comment]
@avalonix Please reopen this issue if the crash is not fixed
Have a nice day!
