### ISSUE TITLE
3D Touch / Force Touch to directly connect to servers

### ISSUE THREAD

**Issue by akuropka** [isontheline/pro.webssh.net#340]
mashREPL can be already called directly from Home Screen. It would be neat if same would be possible with other items such as ssh connections…

![3282D508-DCD6-41DF-82E5-2CA5BE34B057](https://user-images.githubusercontent.com/22570574/125289823-f4791780-e31f-11eb-96ed-b748b354945d.png)

**Comment by isontheline** [comment]
Good idea 👍

Yes I can implement an option inside each connection as "Quick connect" in order to add items to [Home Screen Quick Actions](https://developer.apple.com/documentation/uikit/menus_and_shortcuts/add_home_screen_quick_actions?language=objc).

I'm planning this issue.

**Comment by akuropka** [comment]
This is off-topic but how do I support using TestFlight? Purchases are disabled there…

**Comment by isontheline** [comment]
@akuropka You could :
1. Re-install the App Store release (you won't loose any data)
2. Make the purchase
3. Re-install the TestFlight release (you won't loose any data)

Then you will be able to use your purchase inside the TestFlight release.

**Comment by akuropka** [comment]
Sounds a stupid question but after doing 1. where can I do 2.?

**Comment by isontheline** [comment]
No stupid question 😇

The only purchase inside WebSSH is the "PRO" one.
You can purchase it when :
* You add more than one connection (a popup ask you to purchase)
* You go to WebSSH Settings (top left gear icon) and choose "In-App Purchases"

If none of these options work then you already have the "PRO" purchase.

Does it help you?

**Comment by akuropka** [comment]
Sadly, both don’t work and I’m pretty sure I did not purchase anything yet since the app did not work for me due to the problem with Duo 2FA. 
I‘m open to any other option…
![A8169AE0-C1C9-42A4-B740-B077E97754F3](https://user-images.githubusercontent.com/22570574/125348022-fb258000-e35b-11eb-9d0e-6b722bf9e607.png)
![7261DA52-F260-411C-8C76-5CF48A0A35C7](https://user-images.githubusercontent.com/22570574/125348029-fe207080-e35b-11eb-83b1-70ec0ab50190.png)

**Comment by isontheline** [comment]
Strange 🧐

I will call it a "bug" so 😅

Your feedbacks and issues will reward me more than you think 🙏

**Comment by isontheline** [comment]
Hello @akuropka 👋

I'm closing this issue because I've published 25.8 : https://github.com/isontheline/pro.webssh.net/issues/1082

Available on TestFlight : 
https://testflight.apple.com/join/QSrBK59z

**Comment by akuropka** [comment]
Hi @isontheline, thank you very much. 👋
