### ISSUE TITLE
2FA w/ DUO PAM : SFTP does not work

### ISSUE THREAD

**Issue by akuropka** [isontheline/pro.webssh.net#343]
Bonjour! 👋

I use SSH with key authentication and Duo 2FA.
The shell works flawlessly, thanks to fixing #51.

However, login to SFTP is not possible. The 2FA request is pushed (and approved) but then the connection fails:
![PNG image](https://user-images.githubusercontent.com/22570574/125420604-a1e6f73a-fd2d-430a-bd02-d534e1ce6c78.png)

I'm not getting any clues out of the log what the issue may be...
[log-DB28A1.txt](https://github.com/isontheline/pro.webssh.net/files/6807297/log-DB28A1.txt)

Same for the server log:
[log-sshd.txt](https://github.com/isontheline/pro.webssh.net/files/6807347/log-sshd.txt)

WinSCP works btw.

Any ideas?

**Comment by isontheline** [comment]
Bonjour @akuropka 👋

Thank you a lot for your feedback.

I'm searching the root cause of this trouble.

**Comment by akuropka** [comment]
Salut! 😀

If there's anything further I can provide or do please let me know.

Thanks for your great support! ☕

**Comment by isontheline** [comment]
It seems you are running SCP and not SFTP subsystem. 

Isn't it?

**Comment by akuropka** [comment]
Nope, it's SFTP (included with SSH)...

![20210715_053605_WinSCP](https://user-images.githubusercontent.com/22570574/125725284-bd8285b1-05a2-4a3b-9300-56b690fb17bc.png)

**Comment by isontheline** [comment]
@akuropka Thanks ;)

* Could you try WebSSH 15.0.6?
* Could you tell me the error message, it's the same now?

https://testflight.apple.com/join/QSrBK59z

**Comment by akuropka** [comment]
[log-581788.txt](https://github.com/isontheline/pro.webssh.net/files/6822183/log-581788.txt)

**Comment by isontheline** [comment]
@akuropka Merci 👍

I'm trying another idea.

**Comment by akuropka** [comment]
Salut, @isontheline! 👋
attached you will find a verbose output from a succesful connection with sftp, maybe it helps.
Bonne journée! ☀️

[sftp.log.txt](https://github.com/isontheline/pro.webssh.net/files/6835757/sftp.log.txt)

**Comment by isontheline** [comment]
Hey @akuropka !

Merci beaucoup 🙏

**Comment by isontheline** [comment]
I'm using Duo Unix and it works as expected 😢

Here is my Dockerfile about Duo installation :
```
FROM debian:latest

ARG DUO_UNIX_VERSION=1.11.4

RUN apt-get update && apt-get -y upgrade && \
    DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
    wget ca-certificates libssl-dev gcc make libc6-dev openssh-server

RUN cd /tmp && wget https://dl.duosecurity.com/duo_unix-$DUO_UNIX_VERSION.tar.gz && \
    tar zxf duo_unix-$DUO_UNIX_VERSION.tar.gz && cd duo_unix-$DUO_UNIX_VERSION && \
    ./configure --prefix=/usr && make && make install

RUN mkdir /var/run/sshd

RUN echo "ForceCommand /usr/sbin/login_duo" >> /etc/ssh/sshd_config
RUN echo "PermitTunnel no" >> /etc/ssh/sshd_config
RUN echo "AllowTcpForwarding no" >> /etc/ssh/sshd_config
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

RUN echo "root:$(pwgen 14 1)" | chpasswd

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
```

**Comment by isontheline** [comment]
Or perhaps this command help in my case :
`RUN echo "ForceCommand /usr/sbin/login_duo" >> /etc/ssh/sshd_config`

**Comment by isontheline** [comment]
Works like a charm even with Private Key

**Comment by isontheline** [comment]
I think I'm not using Duo MFA not like you. I'm using Duo Unix (command) and not PAM.

**Comment by akuropka** [comment]
Salut, @isontheline! 👋
Yes, Duo has two modules, login_duo and pam_duo. I am using PAM due to the option of having a centralized authentication server implemented and the keyboard-interactive instruction seems to be troublesome.
I can confirm login_duo does work as expected.
Keep up the good work! 🌻

**Comment by isontheline** [comment]
Salut @akuropka 👋

Thank you a lot for your feedback 👍

I will try to build a pam_duo docker environment asap.
