### ISSUE TITLE
2FA SFTP : Authy

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#346]
Un lien à quel sujet ?
Du traitement de l'A2F pour SSH par Authy ?
Si oui, ils ont repo GitHub à [ce lien](https://github.com/authy/authy-ssh) qui, en effet, n'a pas obtenu de mise à jour depuis 2018.

_Originally posted by @LProgead in https://github.com/isontheline/pro.webssh.net/discussions/330#discussioncomment-899560_

**Comment by akuropka** [comment]
Authy (as client to generate the codes like many others) works also with
Google Authenticator (https://github.com/google/google-authenticator-libpam)
OATH Toolkit (https://www.nongnu.org/oath-toolkit/index.html)
Those two, especially the later one, are still maintained.
(Note: DUO on the other hand sending push messages for authentication which need to be approved to proceed.)

**Comment by isontheline** [comment]
Google Authenticator LIBPAM works like a charm on my side but @LProgead have a problem with Authy one.

**Comment by akuropka** [comment]
I was just mentioning this, because the Google Authenticator implementation on the server side can be used for the Authy client. It would be recommended to switch to a maintained version on the server side.

**Comment by isontheline** [comment]
@akuropka I agree with you that Authy is not supported anymore

**Comment by isontheline** [comment]
I'm closing this issue as Authy signup can't be done (redirect to twilio).

**Comment by isontheline** [comment]
Integration : https://www.authy.com/integrations/ssh/

Need to make a Dockerfile

**Comment by isontheline** [comment]
@LProgead
Dockerfile OK.

I'm able to reproduce :
* SSH is working with Authy and WebSSH
* SFTP isn't working with Authy and WebSSH

**Comment by isontheline** [comment]
@LProgead Does WinSCP works with SFTP and Authy?

Because I can't access SFTP with macOS terminal :
```
sftp -P2228 root@127.0.0.1
root@127.0.0.1's password: 
Received message too long 1098216552
Ensure the remote shell produces no output for non-interactive sessions.
```

And Authy says :
![image](https://user-images.githubusercontent.com/44212923/126048860-d2949fb0-b29d-4a76-8e03-207214382f40.png)

**Comment by isontheline** [comment]
@LProgead I can confirm that the initialization of SFTP subsystem seems not to be possible by using Authy.

**Comment by LProgead** [comment]
Ow, okay. I didn't know that Authy works only with SSH. 
Thanks for trying, though !

LProgeqd.
