### ISSUE TITLE
Crashed in first time ssh  connection

### ISSUE THREAD

**Issue by celerysoft** [isontheline/pro.webssh.net#35]
First of all, welcome back:D

**Describe the bug**
after adding a new SSH connection, the app crashed and only crashed in first connection. work fine in second and other times.

**Informations**
 - Device : iPhone X
 - OS : iOS 13.6
 - WebSSH Pro version : 14.0.4

**Screenshots**

**To Reproduce**
1. Go to SSH tab
2. Add SSH connection
3. Enter the server info, login with Private key, Save
4. Tap the server created in step 3 to connect first time
5. After the fingerprint dialog, turn to the terminal screen, app crash when the transition animation playing

**Comment by isontheline** [comment]
Hey @celerysoft  👋 
Thank you a lot for your harm support and for your issue!

Please come on and join on my beta releases :

1. Please install _WebSSH Beta_ from TestFlight app : https://testflight.apple.com/join/QSrBK59z
2. Then reproduce the crash
3. Finally you will able to send the crash report to me through TestFlight app

Could you try again?

☀️ Have a nice day

**Comment by celerysoft** [comment]
awesome, this bug was fixed in TestFlight version
