### ISSUE TITLE
Implementation of Alt / Meta key on virtual and physical keyboard

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#350]
Hi, thanks for the reply

My question was badly worded. What I meant was to send the Meta or Esc+ combination with an arrow key, for example as used frequently in Fish shell.

I'm coming to WebSSH from Prompt which provides a keyboard shortcut for the Meta key, and when using an external keyboard maps Option to Meta/Esc+

I couldn't find a way of using Meta in WebSSH

Thanks

_Originally posted by @matteck in https://github.com/isontheline/pro.webssh.net/discussions/345#discussioncomment-1036492_

**Comment by isontheline** [comment]
WIP

**Comment by isontheline** [comment]
Specials Keys doesn't work on macOS since 16.2

**Comment by matteck** [comment]
Thanks! Working for me

**Comment by isontheline** [comment]
Thank you a lot for your feedback @matteck 🙏
