### ISSUE TITLE
Ssh terminal repeats bugs.

### ISSUE THREAD

**Issue by chuan01** [isontheline/pro.webssh.net#36]
**Describe the bug**

**Informations**
 - Device : [e.g. iPhone 11]
 - OS : [e.g. iOS 14b4]
 - WebSSH Pro version : [e.g. 14.1.2]

**Screenshots**

**To Reproduce**
1. Go to 'Ssh terminal'
2. Touch on 'Use Chinese input method.'
3. Touch the keyboard. to 'Enter any content and click to confirm.
![93765C39-5A03-4802-A789-3DC74764FF19](https://user-images.githubusercontent.com/43603829/89481442-4b9a7200-d7ca-11ea-9df6-a74408ecc317.jpeg)
![CB4D4EE2-D253-4D25-B09A-8676E02DEB96](https://user-images.githubusercontent.com/43603829/89481454-4e956280-d7ca-11ea-83cb-85cee366ba67.jpeg)

'

**Comment by isontheline** [comment]
Hello @chuan01 

I have fixed the repeat bug. Please note that a black bar will remain above the keyboard (pinyin prediction?) **and I will not** remove it **yet**.

Could you test the TestFlight release?

☀️ Have a nice day
