### ISSUE TITLE
TOR implementation

### ISSUE THREAD

**Issue by sketax** [isontheline/pro.webssh.net#362]
### Discussed in https://github.com/isontheline/pro.webssh.net/discussions/353

<div type='discussions-op-text'>

<sup>Originally posted by **sketax** July 24, 2021</sup>
Hey,

it is possible to implement a tor functionality?
Would be great to connect with SSH over an onion adress.

ty :)</div>

**Comment by isontheline** [comment]
Hey @sketax 👋

Thanks for creating this issue in order to track progress of this feature!

It should be implemented as another type of tunneling like VPN-Over-SSH

**Comment by isontheline** [comment]
MIT / BSD projects to look at :
* https://github.com/BlockchainCommons/BCSwiftTor
* https://github.com/iCepa/iCepa
