### ISSUE TITLE
iOS 14.x used spacd

### ISSUE THREAD

**Issue by giulianozor** [isontheline/pro.webssh.net#363]
Hello,
Sorry, I have no ideas about how to reproduce the issue.
If I go to settings, general, storage, I see WebSSH is using about 9.5gb of storage.
The only way to regain that space is to remove/reinstall the app.
I think it would be useful to add a cleanup button somewhere. If that already exists, I could not find it, sorry

thanks

**Comment by isontheline** [comment]
Hello @giulianozor 👋

Wouah never heard about a size problem like this 😭
9.5GB, I don't know what can cause this trouble.

Could you tell me how many months / years have you used WebSSH?

**Comment by giulianozor** [comment]
I think about 4 or 5 months.Server is on a raspberry pi 4 and i used to SCP large files (from server to iPad). With the old access point the connection was not stable, so maybe there was some partial files.Il 1 ago 2021 17:13, Arnaud ***@***.***> ha scritto:

Hello @giulianozor 👋

Wouah never heard about a size problem like this 😭

9.5GB, I don't know what can cause this trouble.

Could you tell me how many months / years have you used WebSSH?

**Comment by isontheline** [comment]
@giulianozor Thanks for your feedback!

You're right partial files could count in the total size and I need to provide an easy way to delete the temporary files (if any).

**Comment by isontheline** [comment]
If anyone encounter the same problem again, please reopen this issue.
