### ISSUE TITLE
"Plus" button covers the last row to edit

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#365]
It can be hard to edit the ssh list in some cases. See the last one, living room, in my list which is covered by the “+” button.
![A3697464-675D-431B-9DE5-CAB50266FA9D](https://user-images.githubusercontent.com/1205471/127777633-2718da82-a9fb-48e6-93f9-bdbe6f841c6d.png)

_Originally posted by @mbierman in https://github.com/isontheline/pro.webssh.net/issues/272#issuecomment-890545795_

**Comment by isontheline** [comment]
Hello @mbierman 👋

Enhancement available inside [WebSSH 15.1 - Cactus (Opuntia)](https://testflight.apple.com/join/QSrBK59z)

**Comment by mbierman** [comment]
Nice! 🙏🏻
