### ISSUE TITLE
Execute Command not working 

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#368]
**Describe the bug**
I put the following as an execute command 

`source $HOME/.bash_profile `

And it is not working. The file exists, but the shell

**Informations**
 - Device : iPad 8
 - OS : 14.7.1
 - WebSSH Pro version : 15.0.9
 
**Screenshots**
![DC02F654-3A5C-4708-9D95-6DFD497D8E45](https://user-images.githubusercontent.com/1205471/127796742-8a4cebc5-f3b7-4127-a7ef-da51a5a1a67e.png)

**To Reproduce**
1. Go to connection Settings > Terminal Settings > Execute command
2. Enter `source $HOME/.bash_profile `
3. Save settings 
4. Start SSH session

**Comment by isontheline** [comment]
@mbierman I think this isn't a valid command. 

The file you mention is a settings file. You need to add `; bash` at the end of your command I think or any command related to your shell program.

**Comment by isontheline** [comment]
> [RE: 386](https://github.com/isontheline/pro.webssh.net/issues/368) this command works in any shell and is pretty common in my experience.
> 
> * https://apple.stackexchange.com/questions/315985/terminal-run-source-bash-profile-every-time-start-new-terminal
> * https://stackoverflow.com/questions/16011245/source-files-in-a-bash-script
> * https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x237.html
> * https://www.computerhope.com/unix/bash/source.htm

**Comment by isontheline** [comment]
@mbierman `source $HOME/.bash_profile` is not a launching command because there isn't any shell starting with .bash_profile

Instead you could use `bash -c "source $HOME/.bash_profile"`

I won't fix this issue because it's not on WebSSH part it's on your SSH server.

**Comment by isontheline** [comment]
Closing because related to #373
