### ISSUE TITLE
Reopening 368

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#370]
[RE: 386](https://github.com/isontheline/pro.webssh.net/issues/368) this command works in any shell and is pretty common in my experience. 

- https://apple.stackexchange.com/questions/315985/terminal-run-source-bash-profile-every-time-start-new-terminal
- https://stackoverflow.com/questions/16011245/source-files-in-a-bash-script
- https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x237.html
- https://www.computerhope.com/unix/bash/source.htm

**Comment by isontheline** [comment]
@mbierman Please comment on the original issue
