### ISSUE TITLE
Unable to change SSH settings : Virtual Arrow Keys & Read Buffer Size

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#372]
**Describe the bug**
The press on these rows doesn't do anything 😤

![image](https://user-images.githubusercontent.com/44212923/127916734-b40dda0c-e3d3-48b2-aad0-09cbe9fd8d31.png)

**Comment by isontheline** [comment]
Now fixed : https://testflight.apple.com/join/QSrBK59z

**Comment by mbierman** [comment]
With build above I see this: but nothing happens when I tap on "Pad" or "Fast"
![IMG_A337B3C03989-1](https://user-images.githubusercontent.com/1205471/127920968-ed74a37a-50c8-40fb-bc28-ac525cc91599.jpeg)

**Comment by isontheline** [comment]
Hello @mbierman 👋

Latest release should work :
![image](https://user-images.githubusercontent.com/44212923/128076953-c86e97e5-dbe4-4bf2-9ff2-c32f993377e6.png)

Which release version are you using?

**Comment by mbierman** [comment]
Yes, works now!
