### ISSUE TITLE
RE: 368

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#373]
Sorry, but I can't comment when you close an [issue](https://github.com/isontheline/pro.webssh.net/issues/368). 🙏🏻 

> @mbierman source $HOME/.bash_profile is not a launching command because there isn't any shell starting with .bash_profile

No, but there is a file. If I am in a shell on that device (a Mac) I can source the file and any changes made to it are now active in the shell. 

> Instead you could use bash -c "source $HOME/.bash_profile"

This also does not work. Eg. 
```
#existing .bash_profile
...
echo "bash env is updated" 
```
Does not work and in fact I still can't login _at all_ to the machine if this is active via webssh. However, this works _perfectly_ on the machine in terminal: 

```
source  source $HOME/.bash_profile
bash env is updated
```

> I won't fix this issue because it's not on WebSSH part it's on your SSH server.

Sorry, what does this mean? Once I'm logged in shouldn't I be able to execute any valid command that otherwise works on the Mac? 

> Moreover I don't understand why launching source `$HOME/.bash_profile` command. Isn't it launched by your shell at it startup?

I have a PATH set in my `.bash_profile`. If I don't source it the path is not reflected so I can't easily access some commands which is annoying. Setting it and sourcing a file seems like the normal, and easiest way to solve this. Is there a better way? 

But setting the particular file aside, if I had any set of commands I wanted to run upon logging in can't I source any file with valid commands?

**Comment by isontheline** [comment]
It seems that I have locked the issue unintentionally :
![image](https://user-images.githubusercontent.com/44212923/127918619-975f586d-e90a-4c64-a6ea-ca5dc20f5ed6.png)

Sorry I don't understand 😢 I'm tired by my work day 😅

If you have a .bash_profile file then it's executed by "bash" automagically, this point I understand.
Inside this .bash_profile you have one variable "PATH" that you want to add some search paths and you say that the variable "PATH" isn't propagated to other subterminals, isn't it?

Does the "PATH" variable is [exported](https://unix.stackexchange.com/questions/138504/setting-path-vs-exporting-path-in-bash-profile)?

Thank you again for your explanations @mbierman

**Comment by mbierman** [comment]
No problem! I'm sorry I wasn't clear. I'll try to clear up what I meant. 

> If you have a .bash_profile file then it's executed by "bash" automagically, this point I understand.

I would think so too, but that doesn't seem to be the case. As I said I set a path in my` .bash_profile` AND I added an `echo` to see when it is executed. The path update **is not** happening **nor** is the `echo` happening if I login via webssh. HOWEVER If I do it on the machine: 👍🏻  If I login via websh and then `source .bash_profile`: 👍🏻 ONLY if I use the execute command in webbssh is it not working.  That's why it seemed to me that this was worth raising. The mac _is_ doing what I expect except when webssh tries to send this command directly.

> Inside this .bash_profile you have one variable "PATH" that you want to add some search paths and you say that the variable "PATH" isn't propagated to other subterminals, isn't it?

No, that is not working when I login from webssh. That's my problem precisely. But in general, it might be nice to be able to execute a series of commands by sourcing a file on the target host rather than in the one line in webssh. I don't know why this shouldn't work, but it isn't. 

I have tried exporting the variable and that didn't seem to help. I also tried moving it to .bashrc thinking maybe it would be better there and no difference.

**Comment by isontheline** [comment]
Could you try this remote execution command please :

`bash --login`

When using this command I'm able to execute the .bash_profile with an echo inside :
![image](https://user-images.githubusercontent.com/44212923/128078669-b00c0597-ae04-45bf-8a32-93f436f0af14.png)

**Comment by mbierman** [comment]
That does get me the path! .bashrc didn’t seem to execute though so my echo didn’t work, but that was just a test in this case. I wasn’t familiar with this option.

**Comment by isontheline** [comment]
Happy to hear that it solves your issue 👍

Thank you again for your feedback!
