### ISSUE TITLE
vim glitches

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#374]
**Describe the bug**
HI Arnaud, the beta version looks pretty good. I spotted a bug with vim (possibly related to buffer refreshing). As you may know, when you vim a file, the file content should “overwrite” everything in the terminal. While WebSSH doesn’t seem to be able to show the content correctly. The screenshot attached is the WebSSH interface in vim. Hopefully this can be fixed soon. 

*Tianyi*

**Screenshots**
![image](https://user-images.githubusercontent.com/44212923/128643335-53ac9fb1-e297-4d8b-8d6e-beca76e4ef38.png)

**To Reproduce**
I’m using vim on Ubuntu 18.04.4 LTS. To reproduce the problem, try to vim an existing file, e.g., vim foo.bar. If there are some lines on the top in the terminal before you vim a file, these lines will be merged with the content of the file you vimed. Also, when you use arrow keys in vim, it shows some problems. 

Thank you and good luck!

**Comment by tianyi21** [comment]
Knock knock

**Comment by isontheline** [comment]
Hi @tianyi21 👋

**Comment by isontheline** [comment]
Hello @tianyi21  👋

I can't reproduce
![image](https://user-images.githubusercontent.com/44212923/130333417-943a88af-7579-4c03-b903-8403df441e42.png)

**Comment by isontheline** [comment]
@tianyi21 What's yours terminal settings?
![image](https://user-images.githubusercontent.com/44212923/130333449-603aa7c4-9ba1-4cc1-8a5d-ae43aea050fb.png)

**Comment by tianyi21** [comment]
That's quite embarrassing. I found my terminal type was somehow set to "DUMB" and this explains everything. Thanks for helping me to troubleshoot the problem. WebSSH is a great piece of work 🆒

**Comment by isontheline** [comment]
@tianyi21 No problem thank you a lot for your feedback 🙏

Have a nice day ☀️
