### ISSUE TITLE
Add Tag help to Snippets screen

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#378]
**Describe the feature**
In #366 help text for tags was added. (nicely done!) I suggest putting a link to the same information under snippet editing. 

**Screenshots / Draws**
![IMG_346E85700944-1](https://user-images.githubusercontent.com/1205471/128769621-daf33871-f186-4abe-b466-7a159375898f.jpeg)

**Comment by isontheline** [comment]
Hello @mbierman 👋

You're right I've missed it out here 👍

Thank you for your invaluable feedback 🙏

**Comment by isontheline** [comment]
WebSSH 16.2.1 (available in a few hours) will show :
![image](https://user-images.githubusercontent.com/44212923/141854581-93ac7056-170e-486a-8012-df84de8f097d.png)
