### ISSUE TITLE
App update no longer usable with IOS 12.5.4

### ISSUE THREAD

**Issue by JohannUmana** [isontheline/pro.webssh.net#384]
**Describe the bug**
Hello guys, just to let you know that the new app update 15.0.1 doesn't work with IOS 12.5.4. anymore... Since the App Store believes it is still compatible (it says minimum requirements IOS 11), it doesn't let me download the last compatible version as well, any ideas?

**Informations**
 - Device : [iPhone 6]
 - OS : [iOS 12.5.4]
 - WebSSH Pro version : [15.0.1]

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**To Reproduce**
Update the app in an iPhone or iPad with IOS 12.5.4 The app will look like its downloading the update, but it will never finish.

**Comment by isontheline** [comment]
Hello @JohannUmana 👋

It seems to be an App Store bug because on my side the minimum deployment is iOS 14.1 :
![image](https://user-images.githubusercontent.com/44212923/129841334-af190613-02ec-4a26-b13d-9fad0784df76.png)

I'm searching the root cause

**Comment by isontheline** [comment]
@JohannUmana OK found the problem :(

I'm submitting a new binary

**Comment by isontheline** [comment]
Now "fixed"

![image](https://user-images.githubusercontent.com/44212923/129955242-697cd32d-db9b-4a5f-82e0-294fa5a3edf5.png)

**Comment by JohannUmana** [comment]
I can confirm it works perfectly right now, iOS 12.5.4, thank you very much!

**Comment by isontheline** [comment]
Thank you a lot for you feedback @JohannUmana 🙏
