### ISSUE TITLE
WebSSH Database : VACUUM

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#385]
**Describe the feature**
Ability to VACUMM WebSSH SQLite Database

**Why?**
In order to reduce the database size which grows even after deletions (SQLite engine).

**Comment by mmmhmmd77** [comment]
- [x]

**Comment by mmmhmmd77** [comment]
> **Describe the feature**
> 
> Ability to VACUMM WebSSH SQLite Database
> 
> 
> 
> **Why?**
> 
> In order to reduce the database size which grows even after deletions (SQLite engine).
