### ISSUE TITLE
STARTER In App Purchase can't be used anymore

### ISSUE THREAD

**Issue by nihilisme** [isontheline/pro.webssh.net#388]
Bonjour 
J ai acheté la version starter pour 10 connexions , mais on effectuant la mise a jours , je ne peux plus ouvrir plus d'une session ssh
Merci

**Comment by isontheline** [comment]
Bonjour @nihilisme 👋

Effectivement je viens de constater mon erreur.

Je corrige immédiatement.
Veuillez m'excuser de cette erreur.

**Comment by isontheline** [comment]
Pourriez-vous essayer cette version beta ?
https://testflight.apple.com/join/QSrBK59z

**Comment by nihilisme** [comment]
Bonjour&nbsp;
Merci&nbsp;beaucoup&nbsp;pour&nbsp;votre&nbsp;retour&nbsp;,&nbsp;la&nbsp;version&nbsp;beta&nbsp;fonctionne&nbsp;a&nbsp;merveille&nbsp;
Cordialement&nbsp;&nbsp;&nbsp;&nbsp;
---原始邮件---
***@***.***&gt;
发送时间:2021年8月28日(星期六)&nbsp;下午2:31
***@***.***&gt;;
主题:&nbsp;[isontheline/pro.webssh.net]&nbsp;STARTER&nbsp;In&nbsp;App&nbsp;Purchase&nbsp;can&amp;#39;t&nbsp;be&nbsp;used&nbsp;anymore&nbsp;(#388)


&nbsp;Pourriez-vous&nbsp;essayer&nbsp;cette&nbsp;version&nbsp;beta&nbsp;?
&nbsp;https://testflight.apple.com/join/QSrBK59z
－
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;were&nbsp;mentioned.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,&nbsp;view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;or&nbsp;unsubscribe.
