### ISSUE TITLE
Set password black/white keyboard

### ISSUE THREAD

**Issue by avalonix** [isontheline/pro.webssh.net#39]
**Describe the bug*
when setting a password for the application, keyboards of different colors open

**Informations**
 - Device : iPad Pro, iPhone 11
 - OS : 13.6
 - WebSSH Pro version : 14.1.9

**video**
Ipad:
https://youtu.be/qfEWZ_jjVf8

**To Reproduce**

iPad (the system settings have a dark theme)
1.Tap on set password. Opened black keyboard. 
2.After press ok opened white keyboard

iPhone (the system settings have a white theme)
1.Tap on set password. Opened black keyboard. 
2.After press ok opened black keyboard

**Comment by isontheline** [comment]
I can't reproduce on iPad Pro (iOS 13.6), keyboard is always black when setting the password.

Could you check again against WebSSH 14.3?
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-09-13 at 22 11 33](https://user-images.githubusercontent.com/44212923/93027576-1c1f2680-f60e-11ea-90dd-bf44f85e4bbd.png)
