### ISSUE TITLE
Mac Catalyst : Message ribbons are behind the navigation bar

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#399]
**Describe the bug**
A screenshot instead of a description :
![image](https://user-images.githubusercontent.com/44212923/132579347-da920a45-030c-4a39-b38d-a51afe88dac2.png)

![image](https://user-images.githubusercontent.com/44212923/132807196-2f74c548-8d9f-4544-90b3-7d459357db2b.png)

On Mac Catalyst

**Comment by jarrah31** [comment]
This also affects the MacOS Intel version.

**Comment by isontheline** [comment]
@jarrah31 Yes Mac Catalyst is the Apple "name" for Intel and M1 apps that runs "iOS apps" "natively".

Thank you a lot for your invaluable feedback ❗️
