### ISSUE TITLE
Use icmp to implement port knock

### ISSUE THREAD

**Issue by bigboyq** [isontheline/pro.webssh.net#40]
Currently I see port knocking implementations.
Actually, it is too complex to implement port knocking in server side.
My implementation in server side is icmp with particular size.
Such as icmp size 256 will result ssh port open for 30 seconds.
And this implementation would be as easy as 2 potable rules....in server side.
This feature Implementation on WebSSH Would be appreciated.

Server side rule listed for understanding
/sbin/iptables -A INPUT -p icmp --icmp-type 8 -m length --length 256 -m recent --set --name SSHOPEN --rsource -j ACCEPT 
/sbin/iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --name SSHOPEN --rsource -j ACCEPT

**Comment by isontheline** [comment]
Hello @bigboyq  👋 
Thanks for your issue!

Your current implementation of port knocking is genius 👍 

As I already use ICMP as part of WebSSH ping feature, I can implement this issue by setting the payload size of ICMP packets.

Here is the TestFlight link for beta releases if you want : https://testflight.apple.com/join/QSrBK59z

Please note that I will implement it later after 14.1, not immediately but I will do!

☀️ Have a nice day

**Comment by isontheline** [comment]
Hello @bigboyq 👋

Are you still using WebSSH?

**Comment by bigboyq** [comment]
Actually, No

I am using iSH, as it could be customized by ssh config file

Regards
Quaker

**Comment by isontheline** [comment]
Hello Quaker 👋

Perfect so!
Thank you a lot for your feedback 🙏
