### ISSUE TITLE
App crash on load

### ISSUE THREAD

**Issue by oxygen77** [isontheline/pro.webssh.net#400]
**Describe the bug**
I'm using your app for several years now. And today it won't load at all. I can see briefly a blank screen with blue at the top/header. And then back to launcher. Same view is visible in app list. 

Note:
Killing the app did nothing
Rebooting the device did nothing

**Informations**
 - Device : iPhone 12
 - OS : 14.7.1
 - WebSSH Pro version : 15.2

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**To Reproduce**
1. Launch app

**Comment by isontheline** [comment]
@oxygen77 Please try 16.0 : 
https://testflight.apple.com/join/QSrBK59z

**Comment by oxygen77** [comment]
Solved with this version

**Comment by isontheline** [comment]
Thank you a lot for your feedback 🙏
