### ISSUE TITLE
Connection to IPv6 Only Servers Failing

### ISSUE THREAD

**Issue by admdly** [isontheline/pro.webssh.net#401]
**Describe the bug**
Unable to connect to IPv6 only servers (servers with an AAAA DNS record but no A record). The app provides an error saying the Connection Failed. 

**Information**
 - Device : [e.g. iPhone 11]
 - OS : [e.g. iOS 14.7.1]
 - WebSSH Pro version : [e.g. 16.0.4]

**Screenshots**
![WebSSH screenshot](https://user-images.githubusercontent.com/2807620/132859680-48145bbc-c5af-444c-a38c-7876ce94a9d9.jpeg)

**To Reproduce**
1. Go to 'SSH’
2. Touch on '+’ to add a server. 
3. Enter a host that only has an AAAA record / IPv6 support. 
4. Complete remaining the server details. 
5. Touch ‘✔️’ to save. 
3. Swipe down to server in list, and click on server to connect. 
4. See error.

**Comment by isontheline** [comment]
Hello @admdly 

Thank you a lot for your issue and it's reproduce steps 🙏

I will look at it asap.

Have a nice day ☀️

**Comment by isontheline** [comment]
@admdly In order to have more information about this issue, could you do these steps please?

1. Go to iOS settings
2. Got to WebSSH settings
3. Enable "VERBOSE" level
4. Close (kill) WebSSH
5. Launch WebSSH
6. Try to establish your IPv6 connection
7. Extract useful logs from iOS > Files > WebSSH > log-XXXXXX

Thank you a lot 🙏

**Comment by admdly** [comment]
@isontheline thank you for your response. Please find the requested log file attached - I have removed any sensitive information. 

Hope this will be helpful. 🙂

[log-6DF797.txt](https://github.com/isontheline/pro.webssh.net/files/7148397/log-6DF797.txt)

**Comment by admdly** [comment]
@isontheline many apologies - I see the error in the log and upon checking this was my mistake. 🙏 

I can confirm it is working as intended with the correct settings. I'll close this issue.

**Comment by isontheline** [comment]
@admdly No worry, thank you so much for your quick feedback ❤️

Feel free to open any issue if needed.

Have a nice day ☀️
