### ISSUE TITLE
Force IP Protocol Version for given Hostname

### ISSUE THREAD

**Issue by AInteriorB** [isontheline/pro.webssh.net#406]
First of all: Thank you very much for your webssh client. It‘s a great tool that helps me a lot when I‘m on the road :)

**Describe the feature**
Is there a way to specify the ip protocol version for the given FQHN, i.g. ipv4:my.host.com? Behind Firewalls this can be necessary.

Alternative would be to provide an ipv4/6 instead of the hostname. But it‘s not easy to remember a number ;-)

**Comment by isontheline** [comment]
Hello @AInteriorB 👋

Thank you a lot for using WebSSH on the road 🙏

Could explain your request as I don't understand why you need to specify the IP Protocol Version.
Doesn't the DNS works on your case?

**Comment by AInteriorB** [comment]
Wow, that was fast @isontheline 😁 Sure! Lot‘s of mobile carriers provide a dual stack network connection where you get two ip addresses, one ipv4 and one ipv6. Also, lots of servers are reachable via ipv4 and ipv6 thesedays, thus a DNS response delivers both addresses. So far so good 😉 But if your ssh port is protected by a firewall, a typical approach is to use a vpn in split mode: some ip addresses are routed through the vpn to access endpoints behind firewalls and the rest of the traffic goes „directly to the internet“. In this scenario the ipv6 is always preferred by iOS and one is not able to connect to the hostname (through the vpn) via ipv4. 

Alternatives would be:
* provide an ipv4 instead of a FQHN
* disable ipv6 when using the vpn
* configure the vpn to also route ipv6 traffic
* let the client choose the protocol version as we know it from linux commands, i.e. `ssh -4, ping -6, …`

**Comment by isontheline** [comment]
Thank you a lot @AInteriorB for your feedback 👍

I know understand 😇

Have you tried to disable WebSSH > Settings (Gear) > WebSSH Settings > "Prefer IPv6 over IPv4"?
Perhaps this feature doesn't reply to your request, just let me know.

Have a nice day ☀️

**Comment by AInteriorB** [comment]
Yeeaahhh 🎉🥳 that works in my case, @isontheline ! Thanks a lot for your support

**Comment by isontheline** [comment]
🎉
Happy to hear that I could help you 😉
You're Welcome @AInteriorB 👍
