### ISSUE TITLE
External Keyboard : First responder issue when switching between apps

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#409]
Correct iOS 14, most up to date. 

Just realized I left out critical information. I’m using the apple magic keyboard. Just tested it now without using the keyboard and it works just fine. So this is something to do with the apple keyboard. 

I just tested the following: 
* Keyboard connected, fired up WebSSH, connected to my machine. 
* Keyboard still connected, switched over to chrome
* Keyboard still connected, switched back to WebSSH - No input works as stated before
* pulled my ipad off the keyboard. On screen keyboard works just fine
* Put ipad back on the magic keyboard, everything works. 

Very interesting. Anything else you want me to try? I really like this product and would like to help out in any way.

_Originally posted by @rkratochvil in https://github.com/isontheline/pro.webssh.net/discussions/408#discussioncomment-1351297_

**Comment by rkratochvil** [comment]
FYI this issue goes away with iPadOS 15. I just installed 15 and tried to re-create the issues. Everything worked.

**Comment by isontheline** [comment]
@rkratochvil Good to hear that iOS 15 solves your issue.

Reopen this issue at any time if the trouble occurs again.

Have a nice day ☀️
