### ISSUE TITLE
Tunnelling problem

### ISSUE THREAD

**Issue by devabdicant** [isontheline/pro.webssh.net#41]
Hi, I'm not sure if I am doing things right so I prefer to write this:
I have a ssh connection configured to my server with private key and everything is OK.
Now I want to map a ip:port into my localhost, so when I enter localhost:xxxx in my explorer I am performing a myserver:xxxx through ssh tunneling. I set things up, see the ball in grey and when I click it gets red. Then I go to web, where I have my localhost:xxxx and it gets frozen. Sometimes the app shuts down, sometimes not. The thing is I can not load localhost:xxxx using the app, not even opening chrome, safari, etc

**Informations**
 - Device : iphone xr
 - OS : [e.g. iOS 13.6
 - WebSSH Pro version : latest from today

**Screenshots**

**To Reproduce**
In Tunnel create a new tunnel using:
Server: the ip
port: 22
user: root
private key: already entered key
port forwarding: 8040:xx.xxx.xxx.xxx:8085
Then it gets red when clicking but no explorer can access localhost:8040

**Comment by jmcarlyle** [comment]
I was having a similar problem creating a tunnel for VNC between iOS devices and my Ubuntu box. The red spot appeared on the tunnel, I got a response from the server VNC for password entry, but then things hung. I was able to get it working by going to Settings | WebSSH Settings, and turning on the slider for keeping the device awake when the tunnel was opened. 

This was on my iPad 6 running iOS13.6, using WebSSH v14.0.4 and VNC Connect v3.9.1.42499. Strangely, the exact same settings for WebSSH and VNC but now on my iPhone XS resulted in an identical hang until I turned on the slider for keeping the device awake when SSH was opened.

Hope this helps.

**Comment by isontheline** [comment]
Hello @jmcarlyle @devabdicant !

@devabdicant does tip written by @jmcarlyle helps you?

**Comment by isontheline** [comment]
@devabdicant Could you try dynamic port forwarding instead?

Juste put a single * character in the whole field of port forwarding?

**Comment by devabdicant** [comment]
I had set the slider on/Off and tried a few times but it behaves the same way: frozen app. Last time was with slider off, after clicking on tunnel and then going to WEB, where I have configured the http://localhost:8040. It seems the app returns after some time with the slider off though.

The issue remains: I can not tunnel a port and navigate into my remote server using http:// localhost:8040

>Juste put a single * character in the whole field of port forwarding?
mhhh I am not sure what to do then....I mean if I put that how can I map only that port to my local? because what I need is to perform 2 tunnels, one to a different server, and navigate to both using localhost:8040 and localhost:8041. If I put * then I can only use one, right?

**Comment by isontheline** [comment]
@devabdicant I will try to reproduce your problem asap

**Comment by isontheline** [comment]
@devabdicant Do you have a blank screen by using the browser inside WebSSH?

**Comment by isontheline** [comment]
TestFlight release of WebSSH 14.1.11 has been to fix a crash in web tunneling

**Comment by devabdicant** [comment]
> @devabdicant Do you have a blank screen by using the browser inside WebSSH?

yes, blank screen inside webssh

Thanks for the quick bug fix. Is 14.1.11 available to use from my iphone?

**Comment by isontheline** [comment]
Please install _WebSSH Beta_ from TestFlight app : https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
I can't reproduce :(

When I enter 8080:127.0.0.1:80 through tunnel by using a LAN server (192.168.0.150) it works "great" :
- Tunnel is established
- Web view display the web page

Does your tunnel forward an external IP (outside the remote server)?

**Comment by devabdicant** [comment]
Yeah, i finally did it with 14.1.11. It works Perfect!

Thanks!

**Comment by isontheline** [comment]
So great and thanks for your feedback!

☀️ Have a nice day
