### ISSUE TITLE
Cannot edit text file when connected to Apple magic keyboard.

### ISSUE THREAD

**Issue by davidjhk** [isontheline/pro.webssh.net#413]
**Describe the bug**
I connected to an AWS EC2 instance using SFTP. Then I opened a text file to edit.
When I touch the screen, the screen swipes to blank screen with circled +(plus) icon and I cannot edit anything. It only happens when I was using Apple Magic Keyboard connected, but if I detach the magic keyboard, it works fine.

**Informations**
 - Device : iPad Pro 12.9 2021
 - OS : iPadOS 15.1
 - WebSSH Pro version : 16.0.4

**Screenshots**

**To Reproduce**
1. Connect an iPad to Apple magic keyboard
2. Go to 'sftp'
3. Open a host and lookup any text file
4. Click the file
5. When asked "What do you want to do ?", click "Edit"
6. Touch on the screen to edit
7. The screen changes to blank screen with circled plus sign and I cannot edit the file.

**Comment by isontheline** [comment]
Thank you a lot for your issue 🙏

I think it's same with all hardware keyboard.
I will give a try asap.

**Comment by isontheline** [comment]
OK I can reproduce

![image](https://user-images.githubusercontent.com/44212923/135600475-ba14904b-eef6-4250-a721-3c6bb1e77dee.png)

**Comment by isontheline** [comment]
I'm fixing it right now.

**Comment by isontheline** [comment]
@davidjhk Could you try WebSSH 16.1.2? 
https://testflight.apple.com/join/QSrBK59z

**Comment by davidjhk** [comment]
Hello Arnaud,

Thank you for the quick response.
Now it is working with version 16.1.2

Thanks again.



with best regards,

David Joo


From: Arnaud ***@***.***>
Reply-To: "isontheline/pro.webssh.net" ***@***.***>
Date: Friday, October 1, 2021 at 5:13 AM
To: "isontheline/pro.webssh.net" ***@***.***>
Cc: David Joo ***@***.***>, Mention ***@***.***>
Subject: Re: [isontheline/pro.webssh.net] Cannot edit text file when connected to Apple magic keyboard. (#413)


@davidjhk<https://github.com/davidjhk> Could you try WebSSH 16.1.2?
https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
Hello David 👋

Thank you a lot for your feedback 🙏

Have a nice day ☀️
