### ISSUE TITLE
SSH Tunnel Causes VNC Mouse Sync Problem

### ISSUE THREAD

**Issue by jmcarlyle** [isontheline/pro.webssh.net#42]
**Describe the bug**
When using VNC a small black square shows where the mouse cursor is located on the VNC client side. When you move this square (with your finger) the normal mouse arrow cursor (from the VNC server side) will follow the square (after a small delay). 

This behavior is what I get when I connect the VNC client on my iPhone directly to the VNC server on my Ubuntu box. But, when I set up an SSH tunnel using WebSSH and connect VNC via this tunnel, the mouse arrow cursor will stop following the black square (either after some quick moves of my finger or after I double tap my finger). If I create an SSH tunnel using puTTY on my Windows box, then connect to the VNC server on my Ubuntu box, the mouse arrow cursor and the black square always stay in sync, no matter what I do. So the problem definitely lies with WebSSH.

**Informations**
 - Client Device :  iPhone XS and iPad 6th Generation
 - OS :  iOS 13.6
 - WebSSH Pro version : 14.0.4
 - Real VNC Connect v3.9.1.42499 

 - Server Device :  System 76 Galago Pro laptop
 - Ubuntu 20.04 LTS
 - Built-in SSH (openssh-client 1:8.2p1-4)
 - Built-in VNC (Vino v3.22.0-5ubuntu2)

**To Reproduce**
1. Start the SSH program (port 22) and the VNC server (port 5900) on the Ubuntu box
2. Use WebSSH to set up a tunnel (I used 59000:x.x.x.x:5900) and start it up. Configure VNC Connect for 127.0.0.1:59000 and start it up.
3. Find the small black box on the iOS screen (will be near the tip of the hollow arrow cursor) 
4. Move your finger to move the black box. The hollow arrow should follow the box. Then move your finger faster to see if the hollow arrow still follows the box. Finally, quickly double tap some distance away from the present box location. On my system the double tap always breaks the box/arrow connection, while the quick finger move only sometimes breaks the connection.

**Comment by isontheline** [comment]
It's related to the fact that Apple doesn't allow to continue apps in background for more than a few seconds. 

It's why tunneling has been designed to work inside WebSSH only or to be used in split mode on an iPad device.

Issue #25 would be a future possible solution : a VPN through a SSH connection.

I'm convinced that WebSSH isn't linked to this problem.

**Comment by jmcarlyle** [comment]
Yes, no operation in the background would definitely explain the problem! Not much you can do to get around that...

I'm trying to implement an encrypted data stream for VNC. Since your solution is for the future, I think I'll set up a VPN tunnel. 

By the way, congratulations on WebSSH. It's a very nice program overall!

**Comment by isontheline** [comment]
Thank you a lot for your support @jmcarlyle !

Issue #25 will be updated as soon as I work on it
