### ISSUE TITLE
tmux : Switching windows doesn’t work without keyboard up

### ISSUE THREAD

**Issue by jeff-geoff** [isontheline/pro.webssh.net#429]
When I have two connections open in two separate “windows”, pressing the “window” button on the right side overlay does not display the dashboard unless the keyboard is active.

Without the keyboard active, the screen bounces, but returns to the current session rather than showing the dashboard. Activating the keyboard allows switching between active sessions.

**Comment by isontheline** [comment]
Hello @jeff-geoff 👋

I can't reproduce on iPhone.

Could you please post :
* reproduce steps
* your device specs (hardware and software)
* a video showing your trouble

Thank you a lot.

Have a nice day ☀️

**Comment by jeff-geoff** [comment]
iPad Pro 12, iOS 15, webssh 16.0.4

it’s a little more complicated to reproduce than I realized.

The terminal needs to be scrolling/printing to stdout (e.g. download stuff with wget and leave the operation running and try to switch).

rclone triggers it, as does wget, but `find / *` does not

**Comment by isontheline** [comment]
Thank you for these reproduce steps!

I will try on my side.

**Comment by isontheline** [comment]
@isontheline I can't reproduce 😢

**Comment by isontheline** [comment]
@jeff-geoff I can't reproduce 😢

**Comment by jeff-geoff** [comment]
Video is too big to attach… I’ll work on it. This works consistently:

1. Start a session
2. Open a new window and start a second session
3. Return to first window and fill the buffer. I used `rclone check / ~` (you can kill it before it completes)
4. Attempt to switch back to the second session. (Should work)
5. Switch back to the first session (should also work, but the keyboard doesn’t appear by default)
6. Switch to the second session without calling the keyboard (doesn’t work)


you can also simply collapse the keyboard after step 3, and you will find yourself stuck in the same terminal

**Comment by jeff-geoff** [comment]
https://user-images.githubusercontent.com/56777875/136092760-c02517ba-229e-433e-bde6-aa08935e3565.MOV

**Comment by isontheline** [comment]
Do you have a hardware keyboard attached?

On my side I can't reproduce with your steps, I can switch between windows as expected.
Strange behavior.

https://user-images.githubusercontent.com/44212923/136096865-4d8355f3-6b44-4800-b78f-3b1b2aa84f0f.mov

**Comment by jeff-geoff** [comment]
I do not have a hardware keyboard attached.

I’m using tmux on my first session… could that be a factor?

**Comment by isontheline** [comment]
WebSSH isn't aware of apps running on the server so I think tmux shouldn't be a factor.

**Comment by isontheline** [comment]
@jeff-geoff When not using tmux, are you able to switch to other windows?

**Comment by jeff-geoff** [comment]
> @jeff-geoff When not using tmux, are you able to switch to other windows?

I have not been able to recreate this behavior without tmux.

**Comment by isontheline** [comment]
Thank you a lot for your feedback @jeff-geoff 👍

Yes that makes no sense but I will try to reproduce with tmux in order to check what's wrong on WebSSH part.

I don't think that make sense but could you disable "Reverse Wrap-Around" (just a test you can back after) 👍 
![image](https://user-images.githubusercontent.com/44212923/136710168-4f20a944-3a6a-49e0-a7fc-7f18f45ef697.png)

**Comment by isontheline** [comment]
Hello @jeff-geoff 👋

Does this issue occurs with WebSSH 17 beta?
https://testflight.apple.com/join/QSrBK59z
