### ISSUE TITLE
Export / Import feature (connections, tunnels, sftps, keys?, ...) : Through iCloud, ZIP, mashREPL

### ISSUE THREAD

**Issue by marek90** [isontheline/pro.webssh.net#43]
It would be nice to be able to export/import WebSsh settings, so I can use the same setup on my iPhone and my iPad (or vice versa). 
- This may or may not include the private keys and passwords 
- You can password protect the created archive (maybe enforced if you're exporting keys/passwords?) 

Just an idea. What do you think? Btw, glad to see you back on the project and thanks so much for fixing some of the bugs already! 

Cheers!

**Comment by isontheline** [comment]
Hi @marek90 

Thank you very much for your support!

Not just an idea, a real useful use case for a lot of users ;)

I of course accept this great needed feature.

Does the sync need to be manual (import/export actions), or do I can use Apple cloud's framework?

**Comment by marek90** [comment]
Hi @isontheline, thanks for looking into this! Well, I've some apps (can't remember which off top of my mind) to offer both -- you can select to use iCloud backuo/sync (using a toggle) in addition to being able to export the settings into a zip file (via a share sheet).

**Comment by isontheline** [comment]
Now planned ;)

**Comment by chuan01** [comment]
Can you add a key management system, including one-click key generation, management of public keys, private keys, etc., import and export. Write public key to server with one click

**Comment by isontheline** [comment]
# In-App Purchase
- [ ] (Tier 2) Export / Import database #23
- [ ] (Tier 3) iCloud Sync #23

**Comment by isontheline** [comment]
I also plan to let user import/export WebSSH database through mashREPL

**Comment by mbierman** [comment]
I can’t wait! Thank you!

**Comment by isontheline** [comment]
I will do my best efforts 😇

**Comment by mbierman** [comment]
This hasn’t made it to the beta yet, has it?

**Comment by isontheline** [comment]
I'm afraid @mbierman, even if this issue is six months old I haven't been working on it yet 😕

**Comment by alexhk** [comment]
I had WebSSH installed on my phone for a while for some reason, but just today purchased Premium and started using it (used Termius for a while and paid for it, but just don't like another subscription for my occasional use - I always try to get to a real computer anyway if possible).

I am looking forward to import/export (and sync), I have a lot of servers to connect to and setting them all up manually is a pain in the neck. Even from a simple text file, JSON or XML would be better than nothing. Or manually editing a database file in worst case.

**Comment by isontheline** [comment]
Hello @alexhk 👋

Thank you **a lot** for your purchase!

I'm late on this issue, sorry.

I agree an import feature from a text file should be implemented asap.

What do you need **firstly** : a sync between devices or an import feature ?

**Comment by alexhk** [comment]
I assume importing would be of higher priority for me personally, but either way both would be great and will drive new customers. While you are at it, export would also be nice :)

I am using SecureCRT. It's a commercial application and Termius also allows imports from SecureCRT's exported XML file.

As far as I know the way to export hosts from Termius is via their CLI:

`termius export-ssh-config  # Export to ./termius/sshconfig
`
https://github.com/termius/termius-cli

Not sure what format that would be.

**Comment by isontheline** [comment]
Thank you for your feedback @alexhk 

I'm currently implementing Dark Mode and I will switch to export / import / sync feature just after

**Comment by josemmba** [comment]
Synchronizing through iCloud would be the best option. I think.

**Comment by isontheline** [comment]
Let's go! 

I'm now working on iCloud sync 😇

**Comment by isontheline** [comment]
- [ ] Allow removing data after sync (31 days && iCloud Backup == 0)

**Comment by isontheline** [comment]
I will release beta iCloud support in a few hours

**Comment by isontheline** [comment]
Sorry for the trouble

Do you lost the credentials on your main device or your secondary device?

**Comment by isontheline** [comment]
Hello @svenh0 👋

Thank you a lot for your quick feedback about iCloud implementation inside WebSSH 👍

**Comment by isontheline** [comment]
Need to improve (future) with sync notifications : https://developer.apple.com/documentation/cloudkit/ckquerysubscription?language=objc

**Comment by isontheline** [comment]
@marek90 @mbierman Could you try the iCloud sync?

You can also make a database backup before enabling it by using this command in mashREPL :
webssh database backup

**Comment by marek90** [comment]
@isontheline , I have an older iPad mini and just found out that the highest version of WebSSH I can run is 14.10 :(

**Comment by isontheline** [comment]
@marek90 Oh sorry.
iPad mini under 4?

**Comment by marek90** [comment]
Yeah, iPad mini 3.

**Comment by isontheline** [comment]
Sorry for this bad news 🙁
In order to update the libraries used inside WebSSH I have to upgrade the minimum iOS version to 14.x

**Comment by isontheline** [comment]
WebSSH database can now be backed up and restored through mashREPL :
* https://webssh.net/documentation/help/howtos/mashREPL/database-backup/
* https://webssh.net/documentation/help/howtos/mashREPL/database-restore/
