### ISSUE TITLE
webssh restore previous purchase - iPad to MacBook M1

### ISSUE THREAD

**Issue by KeumYongWoo** [isontheline/pro.webssh.net#430]
I bought webssh pro version on ipad. , I bought a MacBook M1 and installed webssh. Previous purchases cannot be restored. What should I do? First of all, I am using webssh using icloud. But I can't add server...

reture answer to email :  kyu3856@naver.com. thank you

**Comment by isontheline** [comment]
Hello @KeumYongWoo 👋

You should use the same iCloud credentials in order to unlock on your MacBook M1.

Please send your iOS purchase receipt about WebSSH to : team (AT) webssh [DOT] net

Thank you. 

Have a nice day ☀️
