### ISSUE TITLE
ECDSA keys can't be used

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#437]
**Describe the bug**
When we use ECDSA keys WebSSH throws an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/44212923/137194438-24f7691a-6691-4b05-abc1-c4d119abe473.png)

**Comment by isontheline** [comment]
Works flawlessly!
ssh-keygen -t ecdsa -f ecdsa.pkey

**Comment by isontheline** [comment]
Quel est le début de l'entête de la clé (sans en divulguer le contenu) ? Avec les tirets --
Ou alors pouvez vous poster une clé générée par vos soins qui ne sera jamais utilisée ?

Merci d'avance,

**Comment by philippelt** [comment]
```
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC…….
```

Pour mémoire, le même fichier de clé est utilisé par WebSSH sur iPhone et ne pose aucun problème…

J’ai généré le fichier de clé sur un serveur et récupéré le même fichier avec FE (File Explorer pro) sur chaque device sans aucune modification. Puis ajouté dans WebSSH à partir du répertoire local Download dans lequel la clé était chargée. Même processus sur iPhone et iPad.

Une librairie oubliée au make sur la version iPad ?

**Comment by philippelt** [comment]
Oups, depuis l’installation de la beta, toutes les clés me donnent le message ci-dessus ! Plus moyen de se connecter depuis l’iPad a aucun serveur… Jusque là, je n’avais pas de problème avec les clés RSA.

Pas très grave, j’utiliserai un MacBook jusqu’à la prochaine release.

**Comment by isontheline** [comment]
Il est possible de rétrograder en 16.x depuis TestFlight.
Que donne une ancienne version sur l'iPad ?

**Comment by isontheline** [comment]
@philippelt Auriez-vous quelques minutes pour tester WebSSH 16.1.7 ?
https://testflight.apple.com/join/QSrBK59z

Cette version devrait fonctionner concernant la demande de mot de passe pour les clés privées.
