### ISSUE TITLE
Keyboard : can't hide it by using the bottom right button

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#44]
Can you check the problem, that most i can't close the virtual keyboard with the hide-button right down in the keyboard (the button in the right down corner to close the keyboard). 
On this way it works always:
1. close keyboard
2. press button top right to toggle on/off the full screen mode (the third button in the right menu with the 4 arrows)
3. press button top right to show keyboard
4. press button down right in the keyboard to close keyboard (this works)
If you open again the keyboard on second time, it's not work:
5. press button top right to show keyboard
6. press button down right in the keyboard to close keyboard (don't works)

Close keyboard with the button in the virtual keyboard works only if you toggle fullscreen before open the keyboard.

_Originally posted by @svenh0 in https://github.com/isontheline/pro.webssh.net/issues/37#issuecomment-673054186_

**Comment by avalonix** [comment]
confirm the problem.  I have reproduced the repeat bug.
iPad iOS 13.6.1
Webssh 14.1.11

Video: https://youtu.be/jWpN0e6TA6E

**Comment by isontheline** [comment]
Hello @avalonix 👋

On iOS 14 (iPad OS Simulator) this bug doesn't appear anymore.
I don't have tried on a real iOS 14 iPad.

Have you tried?

**Comment by svenh0** [comment]
the problem still exists

iPad Pro IOS 14.2
WebSSH 14.7.1

**Comment by avalonix** [comment]
Hi)

I confirm.  the problem still exists.  the hide keyboard button on the keyboard does not work

**Comment by isontheline** [comment]
Thanks for your confirmation, I will try to find a fix asap.

**Comment by ash34** [comment]
Maybe this is the same bug as when the display does not scroll so the input line is hidden behind the keyboard? A workaround is to close the keyboard with the upper-right icon then open it again. The display will resize and the input line sits above the keyboard again.

**Comment by isontheline** [comment]
Hello @ash34 👋

Same as #111 also

**Comment by isontheline** [comment]
Hello 👋

Don't worry about this issue closing : I'm merging this issue into #37 in order to track all Virtual Keyboard Enhancements needed. I will work on it soon.

Have a nice day. ☀️

**Comment by isontheline** [comment]
Working on a fix right now
Will be available in 14.8.11
#37

**Comment by isontheline** [comment]
Hello 👋

Could you try 14.8.11?

Have a nice day ☀️

**Comment by ash34** [comment]
Seems fixed in 14.8.11 🎉

**Comment by svenh0** [comment]
Thanks. It's working now.

**Comment by isontheline** [comment]
Thank you a lot for your feedback 👍
