### ISSUE TITLE
Password / FaceID : Ability to set timeout instead of default 60 seconds

### ISSUE THREAD

**Issue by Panja0** [isontheline/pro.webssh.net#448]
Password/FaceID prompt when resuming the app. 

At the moment a password or FaceID prompt shows (when setup) when first starting the app.
For safety reasons I would be great to have the password/FaceID prompt when resuming the app. So when you put it to the background and come back.

**Comment by isontheline** [comment]
Since WebSSH 18.0 (#589) you can set a timeout (>= 60)
