### ISSUE TITLE
SSH Tunnel Issues on macOS : VPN-Over-SSH

### ISSUE THREAD

**Issue by joninmoz** [isontheline/pro.webssh.net#449]
**Describe the bug**
SSH tunneling does not work on my MacBook. However, the exact configuration works fine on my phone. The SSH connection works fine on the SSH and the SFTP tabs.

SSH is using a nonstandard port.

WebSSH appears to have the correct permissions and the OS shows "connecting" in the VPN icon area but fails to connect shortly afterwards.

**Information**
 - Device : MacBook Air 2020 M1
 - OS : Monterry 12.0
 - WebSSH Pro version : 16.0

<img width="794" alt="Screen Shot 2021-10-28 at 4 47 24 PM" src="https://user-images.githubusercontent.com/15256665/139281731-f1dc8b90-cc21-4100-8031-017e6d7292bd.png">

<img width="671" alt="Screen Shot 2021-10-28 at 4 50 40 PM" src="https://user-images.githubusercontent.com/15256665/139280966-0710ae86-a513-44dd-a3fa-94d3a94d8a76.png">

**Comment by isontheline** [comment]
Always searching the root cause...

**Comment by isontheline** [comment]
I'm now fixing the issue on macOS.

@joninmoz Have you access to TestFlight (macOS)? 
You need a developer account.
If not, don't worry I will submit the fix asap.

**Comment by joninmoz** [comment]
Hi @isontheline,

Thanks for your quick response on this. I have a developer account but it's saying TestFlight is only for iOS and not the Mac. I will PM you my email and you can invite me to the beta and I can test from there.

**Comment by joninmoz** [comment]
It doesn’t look like there is a pm option on GitHub… my Apple developer account is through my Jon@equipmoz.org account

**Comment by isontheline** [comment]
Hi @joninmoz 👋

You can download TestFlight (beta) for macOS here : https://download.developer.apple.com/Applications/TestFlight_3.2_beta/TestFlight_3.2_beta.dmg

WebSSH 16.1.11 on TestFlight will be available after Apple approval. I will let you know.

**Comment by isontheline** [comment]
@joninmoz Now available on TestFlight macOS :
![image](https://user-images.githubusercontent.com/44212923/139645659-4672324e-590e-4f08-a65e-3cef2e1b831d.png)

Have a nice day ☀️

**Comment by joninmoz** [comment]
> @joninmoz Now available on TestFlight macOS : ![image](https://user-images.githubusercontent.com/44212923/139645659-4672324e-590e-4f08-a65e-3cef2e1b831d.png)
> 
> Have a nice day ☀️

Hi @isontheline,

I can confirm the bug is fixed in the beta. Thank you again for your quick response!

**Comment by isontheline** [comment]
You're Welcome @joninmoz 👍

Thank you a lot for your feedback 🙏

See you
