### ISSUE TITLE
Keyboard: button with three dots incomprehensible command

### ISSUE THREAD

**Issue by avalonix** [isontheline/pro.webssh.net#45]
**Describe the bug**
when you press the button with three dots, an incomprehensible command is sent to the terminal

**Informations**
 - Device : iPhone 11, iPad Pro
 - OS : 13.6.1
 - WebSSH Pro version : 14.1.11

**video**
https://youtu.be/ZJqW--wiR7E

**screenshot**
![image](https://user-images.githubusercontent.com/29081475/90196843-1f4caa00-ddf7-11ea-8056-42944a26868a.jpeg)

**To Reproduce**
1. Connect to the terminal.  call the keyboard
2. One tap on the button with three dots. vibration occurs (iPhone)
3. Second tap on the button with three dots, sent command to the terminal

Ps: maybe this is adequate behavior and I don't understand something

**Comment by isontheline** [comment]
@avalonix Yes you're right it's a bug

These 3 dots must be long presses to show a submenu, but a short press shouldn't send the first submenu button.

I will fix it.

**Comment by isontheline** [comment]
@avalonix Hello!

A fix is now available on TestFlight.

☀️ Have a nice day
