### ISSUE TITLE
Virtual keyboard overlaps terminal

### ISSUE THREAD

**Issue by heluca** [isontheline/pro.webssh.net#452]
I am using an iPad Pro on iOS 15 with the Apple Magic Keyboard and trying this app for the first time.
The single row virtual keyboard (Esc, Ctrl…) appears over the last row of text in the terminal, blocking my view of what I am typing.  This occurs when I am in split screen or hovering window.
It seems to behave as expected when started in full screen mode, the last line of text is above the virtual keyboard.  However, once I go to split screen and return to full screen, I encounter the same problem with he keyboard obscuring the last line or 2 of text.
It makes the app very difficult to use.

**Comment by isontheline** [comment]
Hello @heluca 👋

Thank you a lot for your issue!

Does the problem (in Split Screen, Hovering Window) occurs only when the Magic Keyboard is enabled or the issue is also available with the virtual keyboard?

**Comment by heluca** [comment]
Hello!  My iPad just updated to 15.1, so tried with and without the keyboard attached.  In both situations the problem happens in split/hover mode.  

The app still works properly in full screen (landscape and portrait).

**Comment by isontheline** [comment]
Thank you a lot for your feedback 🙏

I will make a fix for the next release WebSSH 17 - Shell

**Comment by heluca** [comment]
You're welcome.  Thank you for the quick response.

**Comment by isontheline** [comment]
Hello @heluca 👋

Does the latest WebSSH beta fixes the problem?

**Comment by heluca** [comment]
Yes, this works perfectly now.  Thank you!

**Comment by isontheline** [comment]
Thank you so much for your feedback 🙏
