### ISSUE TITLE
Copy / Paste Terminal Content : Ability to use Cmd-C / Cmd-V

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#456]
OK j'ouvre une issue pour pouvoir faire Cmd-C Cmd-V à la place du clic prolongé pour 
2- is it possible to copy paste easier ?

_Originally posted by @isontheline in https://github.com/isontheline/pro.webssh.net/discussions/455#discussioncomment-1647039_

**Comment by AInteriorB** [comment]
I can confirm, that an easier way to copy stuff from the terminal would be great. ☺️

**Comment by isontheline** [comment]
Will be done by choosing [xterm.js](https://github.com/isontheline/pro.webssh.net/issues/150) as rendering engine instead of hterm

**Comment by isontheline** [comment]
A TestFlight release will be available in a few hours : ability to select / copy / paste from terminal easier (macOS only)

**Comment by AInteriorB** [comment]
Cannot confirm that the beta works in macOS, but in iOS select and copy is no longer possible at all. Thus this update would break the „Select“ functionality on iPads/iPhones.

**Comment by isontheline** [comment]
@AInteriorB Yes "Copy" on iOS support is tracked here : https://github.com/isontheline/pro.webssh.net/issues/150#issuecomment-1021656119

Should be available soon. 
Sorry for the trouble.

**Comment by isontheline** [comment]
iOS text selection improvement will be tracked on #536
