### ISSUE TITLE
Key Management System

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#46]
Can you add a key management system, including one-click key generation, management of public keys, private keys, etc., import and export. Write public key to server with one click

_Originally posted by @chuan01 in https://github.com/isontheline/pro.webssh.net/issues/43#issuecomment-674423540_

- [x] https://github.com/isontheline/pro.webssh.net/discussions/402 by @apenen
  - [x] Long press (right click) to copy Public Key
  - [x] Long press (right click) to generate Public Key from the private one
- [x] Ability to copy Public Key to a remote server : https://github.com/isontheline/pro.webssh.net/discussions/616#discussion-4073397
- [x] When generating a new private key :
  - [x] Ask if we need to add a passphrase
  - [x] Ask if we can save the passphrase

**Comment by GrahamCobb** [comment]
Thx for the app! Generating a key is an important feature for me. I use ssh apps on many devices and prefer the private keys to be unique for each device so I can easily disable access for 1 device if lost.

I also like to then be able to use the same key for a few different hosts as I consider the key identifying a device and a person, not a destination/server.

**Comment by isontheline** [comment]
Hello @GrahamCobb 👋

Thank you for your feedback about this issue it will help me to drive the roadmap!

**Comment by isontheline** [comment]
For @isontheline work :
* https://github.com/openssh/openssh-portable/blob/35253af01d8c0ab444c8377402121816e71c71f5/contrib/ssh-copy-id#L239
* https://www.ssh.com/academy/ssh/copy-id
* https://linux-audit.com/distributing-ssh-keys-using-ssh-copy-id-manually-automated/
* https://github.com/VijayS1/Scripts/tree/master/ssh-copy-id

**Comment by isontheline** [comment]
A first beta release will be available in a few hours (TestFlight)

**Comment by isontheline** [comment]
Available on TestFlight for iOS : https://testflight.apple.com/join/QSrBK59z

On macOS, I'm waiting for review : 

![Image](https://user-images.githubusercontent.com/44212923/233174036-580d5651-86d1-4a45-9832-1c13ac1f09ff.png)

**Comment by isontheline** [comment]
Ability to copy Public Key to server will come (very) soon.

**Comment by isontheline** [comment]
"ssh-copy-id" now available : 
1. Launch a connection (with password or already known key)
2. Use "..." ellipsis top right button on the terminal
3. Choose Tools submenu
4. Choose ssh-copy-id
5. Choose the Private Key you want to have it's Public Key sent to .ssh/authorized_keys
6. You will obtain a success or error message
7. Go back to the terminal
8. Disconnect
9. Use your Private Key to connect again

If your private key is protected by a passphrase : at step five (5) long press / right click to generate a public key.

Have a nice day ☀️

**Comment by isontheline** [comment]
WebSSH 21.8 is now being pushed to the App Store for review.
If you see any issue, your feedback is welcome 🙏
