### ISSUE TITLE
Unable to purchase

### ISSUE THREAD

**Issue by 997862** [isontheline/pro.webssh.net#462]
![IMG_2651](https://user-images.githubusercontent.com/1093092/143447186-464fd1ef-e3f2-4685-8e3f-a2198837d0b0.PNG)
![IMG_2650](https://user-images.githubusercontent.com/1093092/143447211-d5e402ae-bf47-4ec0-8ef9-35c3c042e4ff.PNG)
![IMG_2648](https://user-images.githubusercontent.com/1093092/143447214-3b824cdd-95da-4fac-bf98-ca0e5ffd565a.PNG)

**Comment by 997862** [comment]
Informations

Device : [e.g. iPhone 12]
OS : [e.g. iOS 15.1.1]
WebSSH Pro version : [e.g. 16.2.1]

Informations

Device : [e.g. iPad air4]
OS : [e.g. ipadOS 15.1]
WebSSH Pro version : [e.g. 16.1.11]

**Comment by 997862** [comment]
Unable to upgrade and purchase through app store.

**Comment by isontheline** [comment]
Hello @997862 👋

Could you translate this App Store message please :
![image](https://user-images.githubusercontent.com/44212923/143497667-8134e2d7-fe8e-4694-9cbd-7cdce495aa51.png)

**Comment by 997862** [comment]
Your purchase cannot be completed. For assistance, please contact iTunes support

——————————————————
                                         顺祝商祺

**Comment by isontheline** [comment]
It seems to be related to iTunes so?

In which country are you trying to purchase?

**Comment by 997862** [comment]
If you can buy in China, it's the best. I'm Chinese. However, I can also buy other applications through my U.S. account, but I can't buy webssh developed by you.

**Comment by isontheline** [comment]
WebSSH isn't available from China region. 
It's strange that you can't buy from USA. 

Does the app have downloaded from the US store?

**Comment by 997862** [comment]
Yes, I have downloaded and installed it from the American store.
But I can't buy webssh through American stores, but I can buy other apps. Such as view source and other tools.
Can webssh have a pro version that needs to be purchased directly? No, we buy it through the built-in.

**Comment by isontheline** [comment]
Unfortunately I can't do anything about App Store errors. 

Perhaps you may contact Apple in order to have more information about your trouble?

**Comment by 997862** [comment]
Can't we make a webssh Pro version and sell it directly?

——————————————————
                                         顺祝商祺


> 在 2021年11月28日，上午1:28，Arnaud ***@***.***> 写道：
> 
> Unfortunately I can't do anything about App Store errors.
> 
> Perhaps you may contact Apple in order to have more information about your trouble?

**Comment by isontheline** [comment]
WebSSH is linked to the App Store Sandbox and thus can't be sell outside.
