### ISSUE TITLE
Pipe, curly braces and other special chars no longer available via iPad Smart Keyboard

### ISSUE THREAD

**Issue by AInteriorB** [isontheline/pro.webssh.net#474]
**Describe the bug**
Pipe is usually available via Option+7, Curly braces Option+8 and +9. When typing this combination on an ipad Smart Keyboard, you only find (arg: 7) in the shell. Still working as expected in other iPad apps like Safari | { } . This behavior must have changed in one of the latest versions because it was available back then.

**Informations**
 - Device : iPad Pro 11‘‘ (3rd gerneration)
 - OS : iPad OS 15.2
 - WebSSH Pro version : 16.2

**To Reproduce**
1. Open connection to linux debian server
2. Type Option+7

Expecting: Pipe |
Result: (arg: 7)

**Comment by AInteriorB** [comment]
Furthermore exit/detach from a xen console via Ctl + ] or Ctl + is no longer possible.

**Comment by isontheline** [comment]
Hello @AInteriorB 👋

Could you post the link of your keyboard on the Apple Store?
I would like to check the layout.

**Comment by AInteriorB** [comment]
Hey @isontheline ✌️

First of all: thanks for your great work!

Sure: [Apple iPad Smart Keyboard Folio German Layout](https://www.apple.com/de/shop/product/MXNK2D/A/smart-keyboard-folio-für-das-11-ipad-pro-3-generation-und-das-ipad-air-4-generation-deutsch)

I also found out, that a simple @ is no longer working, too 😂

Standard is `Ctl + ]` (which is working if I use the virtual keyboard, by the way) but in some Windows environments (with putty for example) it is `Ctl + PLUS` . `Ctl` on the WebSSH screen and the `+` on the iPad Smart Keyboard was definitely working in one of the earlier versions of WebSSH. And the @ symbol as well, of course 😉

**Comment by isontheline** [comment]
Hi @AInteriorB 👋

Thank you a lot for your great feedback 🙏

Does WebSSH 16.1 or 16.0 works as expected?
The downgrade is available on TestFlight : https://testflight.apple.com/join/QSrBK59z

I have made several addons on the keyboard management on 16.2 which may have caused these troubles.

I'm also planning to buy an Apple Smart Keyboard. Yet I'm using an Amazon' bluetooth keyboard which work as expected.

Thank you again for your support and help 😉

**Comment by AInteriorB** [comment]
It is working until and including version 16.2 (830) and brakes in all greater versions than 16.2 (831).

**Comment by isontheline** [comment]
@AInteriorB Awesome feedback 🙏

It seems I have some troubles on my side also.

Could you run this command on your Linux box?
`showkey -a`

What is the output when you press the `@` character?

**Comment by isontheline** [comment]
I'm trying to build with the latest Xcode 13.2.1

**Comment by AInteriorB** [comment]
In working version 16.2 (830):
```
@        64 0100 0x40
[        91 0133 0x5b
]        93 0135 0x5d
|       124 0174 0x7c
{       123 0173 0x7b
}       125 0175 0x7d 
```

In latest version 16.2 (833) same order:
```
^[l      27 0033 0x1b
        108 0154 0x6c
^[5      27 0033 0x1b
         53 0065 0x35
^[6      27 0033 0x1b
         54 0066 0x36
^[7      27 0033 0x1b
         55 0067 0x37
^[8      27 0033 0x1b
         56 0070 0x38
^[9      27 0033 0x1b
         57 0071 0x39
```

**Comment by isontheline** [comment]
Thank you. I'm searching an alternative for keyboard management. Hope I will find a solution tonight.

**Comment by isontheline** [comment]
@isontheline I'm on the good way but I need extra hours.
When you use the Terminal app on macOS, how do you do send Meta / Alt keys ?

**Comment by isontheline** [comment]
@AInteriorB I'm on the good way but I need extra hours.
When you use the Terminal app on macOS, how do you do send Meta / Alt keys ?

**Comment by isontheline** [comment]
@AInteriorB I think I have found the root cause. The "Alt / Option" key have been used to send "Meta" key which is wrong on some layouts. Now it will require "Ctrl + Alt" in order to send "Meta".

A new build will be available in a few hours, I will notify you asap.

**Comment by isontheline** [comment]
Hey @AInteriorB 👋

Could you try WebSSH 16.3 (Build 836)?
https://testflight.apple.com/join/QSrBK59z

Have a nice day ☀️

**Comment by AInteriorB** [comment]
Yeah, I tried and it's working again 😉😉😉

**Comment by isontheline** [comment]
@AInteriorB Great to hear! Thank you again for your quick and strong feedback 🙏

**Comment by AInteriorB** [comment]
@isontheline thank you for your great work!

By the way, not directly related to this issue but also a "keyboard problem": When you copy a multi-line text to your clipboard from somewhere (like Safari) and you paste it to your WebSSH terminal via keyboard `cmd + v` the new lines are gone. When doing the same via "long finger touch" + Paste the new lines are there.

**Comment by isontheline** [comment]
@AInteriorB I have experienced the same thing today. 

I have opened an issue from your comment : https://github.com/isontheline/pro.webssh.net/issues/477

I think it's not a hard task, so I will try make a fix this week (or next 🎄) 😇

**Comment by AInteriorB** [comment]
@isontheline awesome! You're great 🥇 😄
