### ISSUE TITLE
When pasting from "cmd + v" the new lines are gone

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#477]
@isontheline thank you for your great work!

By the way, not directly related to this issue but also a "keyboard problem": When you copy a multi-line text to your clipboard from somewhere (like Safari) and you paste it to your WebSSH terminal via keyboard `cmd + v` the new lines are gone. When doing the same via "long finger touch" + Paste the new lines are there.

_Originally posted by @AInteriorB in https://github.com/isontheline/pro.webssh.net/issues/474#issuecomment-998208475_

**Comment by isontheline** [comment]
A fix will be available in a few hours (currently building).

Merry Xmas 🎄

**Comment by isontheline** [comment]
@AInteriorB Could you check WebSSH 16.4 (838)?
https://testflight.apple.com/join/QSrBK59z

Merry Xmas

**Comment by AInteriorB** [comment]
@isontheline looks good here 😀👍 Works like a charm. Thanks for the Christmas present 🎄😁

One short question, though: why did you change the shortcut for searching a connection from `control+R` to `option-cmd-S`? Is this more a standard shortcut? Very hard to press for me without breaking my fingers 🤣🤣🤣

**Comment by isontheline** [comment]
You're Welcome, thank you for your feedback 💪

The change from `Ctrl+R` to the longer one is because on macOS the `Cmd+` sequence is used "everywhere" on "all" apps.
`Ctrl+` is used "only" for terminal commands.

So each sequences won't interact between the system and the terminal.

Would you like an option inside WebSSH settings in order to let users to choose between the wanted sequence?
