### ISSUE TITLE
Local Shell Commands

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#48]
Hello Folks :)

What do you think about an integration of local shell commands like :
* ls, cp, rm
* curl, scp, sftp, ssh, tar, gzip
* ping, nc, nslookup, host, dig, telnet, whois

By local I mean that command are executed on your device and not remote.

Could an integration like this can be useful for WebSSH?

**Comment by lateparty** [comment]
Definitely would be useful

**Comment by isontheline** [comment]
Thanks for your feedback @lateparty !

**Comment by Dragon-Fish** [comment]
Oh, really? May I ask to run Node.js on my mobile device? 😂

Whatever it’s a good idea!

**Comment by isontheline** [comment]
@Dragon-Fish 😂 
Thanks for your feedback!

**Comment by isontheline** [comment]
# In-App Purchase
- [ ] (Tier 3) Unlock all local commands #23

**Comment by isontheline** [comment]
I think I will use : https://github.com/holzschu/ios_system/

**Comment by isontheline** [comment]
Available in TestFlight release (not all commands).
