### ISSUE TITLE
Faster scrolling on iOS

### ISSUE THREAD

**Issue by AInteriorB** [isontheline/pro.webssh.net#492]
**Describe the feature**
Currently, it is very hard to scroll a long way in iOS. Whenever you take your finger from the touchscreen, scrolling stops immediatly. This is not the normal behaviour of iOS where you can „accelerate“ the scrolling and it conitnues to scroll. Also I expect to be „back at the bottom“ as soon as I type any key. This would accelerate a usual workflow, when I have to look what happened above and then continue my work 😉

**Comment by isontheline** [comment]
Closing this in favor of https://github.com/isontheline/pro.webssh.net/issues/201

But I add your statement to #201 : 
` Also I expect to be „back at the bottom“ as soon as I type any key. This would accelerate a usual workflow, when I have to look what happened above and then continue my work 😉`
