### ISSUE TITLE
Translate error.

### ISSUE THREAD

**Issue by cxy5014** [isontheline/pro.webssh.net#50]
**Describe the bug**
Translate error.
1. “简体中文” not “简体中国”.
2. “日本語” not “日本人”.

**Informations**
 - Device : iPhone 6s Plus
 - OS : iOS 14.0
 - WebSSH Pro version : 14.1

**Screenshots**
![image](https://user-images.githubusercontent.com/42842481/90653874-4fba9b00-e272-11ea-93e9-fa5c4fb4021c.jpeg)
**To Reproduce**
None.

**Comment by isontheline** [comment]
Hello @cxy5014 

Thanks for your feedback!

Translation sentences have been written by users a long time ago.

Could you teach me why only the latest "character" need to be changed?

Sorry for my ignorance :(

**Comment by isontheline** [comment]
Fixed in 14.2.4 available on TestFlight : https://testflight.apple.com/join/QSrBK59z

☀️ Have a nice day
