### ISSUE TITLE
No force keyboard interactive toggle in Tunnel tab

### ISSUE THREAD

**Issue by linuxtesting999** [isontheline/pro.webssh.net#503]
**Describe the bug**

No force keyboard interactive toggle in Tunnel tab and that lead to no prompt when connecting the SSH server with 2FA….and come up with an error message of connection failed.  The SSH tab has this toggle so that when I connect to the SSH server. There is a prompt asking for the token and which I can successfully login to the server but cannot do the tunneling.

**Screenshots**
![image](https://user-images.githubusercontent.com/86144431/151129567-270a8d54-0380-4aca-bbf5-46e9b32a34ba.jpeg)

**To Reproduce**
1. Go to 'Tunnel'
2. Touch on 'connect' but the ssh server must have the 2FA setting
3. See error

**Comment by isontheline** [comment]
Hello @linuxtesting999 👋

I understand your need.

The "Force keyboard interactive" toggle isn't available on the tunnel because I use the NEVPNTunnelPlugin iOS component which doesn't allow a simple communication between WebSSH and the tunnel.

I will find a solution in order to be able to use 2FA on tunneling. 
Perhaps the VPN feature could be disabled - setting toggle - in order to have this option on tunnel available in an upcoming release.

**Comment by linuxtesting999** [comment]
I support you 😜

![image](https://user-images.githubusercontent.com/86144431/148665673-695637f9-241c-492f-88a0-87c45169f72a.jpeg)

**Comment by isontheline** [comment]
Thank you so much @linuxtesting999 🙏

**Comment by isontheline** [comment]
Related #422

**Comment by isontheline** [comment]
Hello @linuxtesting999 👋

Will you need to use the forwarded ports outside WebSSH?

**Comment by isontheline** [comment]
https://github.com/isontheline/pro.webssh.net/issues/422#issuecomment-1219801202

**Comment by isontheline** [comment]
WIP

**Comment by linuxtesting999** [comment]
> Hello @linuxtesting999 👋
> 
> 
> 
> Will you need to use the forwarded ports outside WebSSH?

Yes 👍

**Comment by linuxtesting999** [comment]
> WIP

Thank you very much.

**Comment by isontheline** [comment]
@linuxtesting999 Thank you!

Are you using Google Authenticator on your server or another one?

**Comment by linuxtesting999** [comment]
> @linuxtesting999 Thank you!
> 
> Are you using Google Authenticator on your server or another one?

I use both Authy and Google Authenticator.

**Comment by isontheline** [comment]
@linuxtesting999 Latest beta will allow you to use 2FA with TUNNEL
