### ISSUE TITLE
2FA : Can't establish SSH connection

### ISSUE THREAD

**Issue by lanxia** [isontheline/pro.webssh.net#51]
**Describe the bug**

**Informations**
 - Device : iPad Air3
 - OS : iOS 13.6
 - WebSSH Pro version : latest

**To Reproduce**
When using ssh to connect my server in company, normally I will tap my phone to confirm the connection and then the connection will establish. But I can't do this in web ssh, and I try another ssh software in iPad can do it, so please fix it.

**Comment by isontheline** [comment]
Hello @lanxia !

* Are you talking about 2FA for your SSH connection?
* Which other applications are you using on iOS? Does they support keyboard interactive?
* I need more information about your use case.

**Comment by lanxia** [comment]
> Hello @lanxia !
> 
> * Are you talking about 2FA for your SSH connection?
> * Which other applications are you using on iOS? Does they support keyboard interactive?
> * I need more information about your use case.

1. I think so but I tried the two factor feature the ssh pro provide but it doesn't work;
2. termius

Below is the typical process that  connect to my company's  server using Mac:
1. ssh -i ~/.ssh/id_rsa username@server
2. then something like below will show up and a message wil be sent to my phone:
<img width="873" alt="image" src="https://user-images.githubusercontent.com/4338871/90708233-dfd8fe80-e2cb-11ea-9ab2-8945c6821831.png">
3. there is a link in the message and when I click it, the connection establish.

The termius will show up the screenshot I uploaded and when I click the process will continue. But ssh pro doesn't show up and  sometimes I can get the message and sometimes not. Even when I receive the message and click the link, the ssh pro report a error message. If you need, I can provide the error message.

**Comment by isontheline** [comment]
@lanxia 

If the error message doesn't contain any sensitive datat, yes please provide it.

I think I have a bug with 2FA or with keyboard interactive for authentication.
Have you the name of the system installed at your company (in order to reproduce the same error)?

Thanks for your feedback

**Comment by lanxia** [comment]
@isontheline 
here is the error message:
![IMG_0025](https://user-images.githubusercontent.com/4338871/90777473-0d569400-e32e-11ea-9502-2add09d02d91.png)
and sorry that I don't know the name of the system.

**Comment by isontheline** [comment]
I will check why keyboard interactive doesn't work as expected

**Comment by isontheline** [comment]
@lanxia Does your MFA is based on DUO ?
https://duo.com/product/multi-factor-authentication-mfa

**Comment by lanxia** [comment]
> @lanxia Does your MFA is based on DUO ?
> https://duo.com/product/multi-factor-authentication-mfa

@isontheline  I think the MFA that my company use that looks like the documentation describe but as I mentioned before I don't know the name, thanks a lot that your are still trying to solve this problem.

**Comment by isontheline** [comment]
@lanxia Thanks for your quick reply

I will try to make Duo compatible with WebSSH and we will check if resolves your issue too

Have a nice day ☀️

**Comment by isontheline** [comment]
@akuropka

Another issue related to DUO 2FA :
https://github.com/isontheline/pro.webssh.net/issues/250

**Comment by isontheline** [comment]
Hello @lanxia 👋

I'm working on 2FA issues.

Could you check the latest beta please?
https://testflight.apple.com/join/QSrBK59z

Have a nice day ☀️

**Comment by akuropka** [comment]
Works with Duo2FA! 👍
Thank you for your great work! 👌

**Comment by isontheline** [comment]
Hello @akuropka 👋

Thank you a lot for your quick feedback about Duo2FA 🙏

Have a nice day ☀️
