### ISSUE TITLE
Keyboard no longer active after switching to another window

### ISSUE THREAD

**Issue by AInteriorB** [isontheline/pro.webssh.net#510]
**Describe the bug**
Whenever you switch to another window (multi windows enabled) the keyboard is no longer active and needs to be activated even though the keyboard was active before.

**Informations**
 - Device : iPad Pro
 - OS : iOS 15.2.1
 - WebSSH Pro version : Beta 17.0

**To Reproduce**
* Work with keyboard in a window
* Switch to another window
* Keyboard needs to be activated
* Switch back to first window
* Keyboard needs to be activated again

**Comment by isontheline** [comment]
Hello @AInteriorB 👋

You're right and it's quite annoying when working in office.

I will fix it

**Comment by isontheline** [comment]
@AInteriorB Should be fixed by the use of iOS native Split View

**Comment by AInteriorB** [comment]
Hey @isontheline , thanks again for your great work! 🥇 

I already use the new split view, works like a charm. It's way easier to organize your windows. I like it 👍 

The only negative thing I observe: When I have two windows opened and I close one by swiping it up, the other window then turns back to the home screen even when there was a connection before. I cannot tell, when this happens, because it only happens sometimes. But I will monitor this and if it is really an issue, I will tell you details.

**Comment by isontheline** [comment]
Thank you a lot for your support and feedback @AInteriorB 🙏

> I cannot tell, when this happens, because it only happens sometimes. But I will monitor this and if it is really an issue, I will tell you details.

Yes thank you a lot, if the issue persists please feel free to open an issue
