### ISSUE TITLE
Add support for ssh agent forwarding

### ISSUE THREAD

**Issue by SidShetye** [isontheline/pro.webssh.net#513]
Tried out webSSH on my iPhone and liked it enough to purchase it. Thanks for making a quality app.

I do have a request - please support SSH agent forwarding ([explained](http://www.unixwiz.net/techtips/ssh-agent-forwarding.html)). I use it to run `sudo` on target machines without re-typing complex passwords all the time. There is a server side configuration is explained [ here (SSH Agent for sudo).](https://www.lorier.net/docs/ssh-agent-sudo.html) but it does require the client (webssh) to support ssh agent forwarding to begin with.

**Comment by isontheline** [comment]
Agent Forwarding could be [insecure](https://duckduckgo.com/?q=ssh+agent+forwarding+insecure&atb=v295-1&ia=web) in some situations.

Does the "bastion" could be used in your case?
* https://github.com/isontheline/pro.webssh.net/discussions/463
* https://github.com/isontheline/pro.webssh.net/issues/266

**Comment by SidShetye** [comment]
Agreed about the possible insecurity in certain settings. I use it to SSH into a toy project raspberry pi which is otherwise network segmented off. 

Anyways, there is another iOS SSH app, Shelly which is comparable to WebSSH but also support SSH Agent forwarding, so right now I'm set to be able to sudo off my iPhone. I'll go ahead and close this ticket out.

**Comment by isontheline** [comment]
Hey @naggie 👋

Unfortunately WebSSH lacks of Agent Forwarding feature 😔 

I’m sorry

**Comment by naggie** [comment]
Sorry wrong mention. Thanks, instead, @isontheline :) -- ok got it.

Cal
