### ISSUE TITLE
Ability to use resolve server names when using DPF?

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#514]
**Describe the bug**
Thank you for putting together WebSSH. I am still feeling my way around it, but it does give me some capabilities i have been missing on my iPad for a while. I am a longtime SSH tunneling fan and until Apple screwed around with SSH background operations, I never had need of a VPN when SSH tunnels were available. Especially when using dynamic port forwarding as a SOCKS proxy

With WebSSH, i am not sure about how i should be using DPF - i thin i have got to be missing something. When I setup the tunnel, i used * in the port forward section, and was able to create terminal sessions after that, but only if i connected to the server by address, not by name. Is there a way to have the tunnel resolve the names of the servers I want to ssh to ? (What am I doing wrong? :) )

Also, if i want to interact with web servers, it looks like i have to set up a specific local tunnel as opposed to consuming a SOCKS proxy - is that right? How can I set up multiple targets to be available at the same time?

By @psmode

**Comment by isontheline** [comment]
Hello @psmode 👋

Thank you so much for your support about WebSSH 🙏

You have configured DPF with success I think by using the * wildcard.
If you can't have a successful connection by using names of the servers then it should be a WebSSH bug.
I'm opening an issue to check and fix this trouble.

Multiple targets at same time will be available "soon" : 
https://github.com/isontheline/pro.webssh.net/issues/284
https://github.com/isontheline/pro.webssh.net/issues/319
https://github.com/isontheline/pro.webssh.net/issues/220

Have a nice day Peter ☀️

**Comment by isontheline** [comment]
Hello @psmode 👋

Are you experiencing any issue again?

I would like to troubleshoot it with your help.

**Comment by psmode** [comment]
As a simple SSH client, the program works great. The support for private keys works well and I do like the clarity of the text and color choices.

However, I still struggle with DPF. I am able to bring up a subsequent SSH session if i specify the target there by IP address, but will not work if i specify the target by its fully qualified domain name. This is something that PuTTy is able to do. Also, within WebSSH, while i can start multiple SSH sessions over the DPF tunnel, only the last one works. Once I start up a new SSH, the previous one hangs.


Peter Smode
***@***.***
m: 212-738-9721

**Comment by isontheline** [comment]
> As a simple SSH client, the program works great. The support for private keys works well and I do like the clarity of the text and color choices. 

Thank you for your feedback and support

> However, I still struggle with DPF. I am able to bring up a subsequent SSH session if i specify the target there by IP address, but will not work if i specify the target by its fully qualified domain name. This is something that PuTTy is able to do. 

When you say it doesn't work you are talking about the fact that WebSSH doesn't resolves the hostname through the DPF? Could you confirm that you want the hostname to be resolved in the other side of the DPF?

> Also, within WebSSH, while i can start multiple SSH sessions over the DPF tunnel, only the last one works. Once I start up a new SSH, the previous one hangs.

I don't understand that. I've just launched a DPF on my side and I'm able to launch multiple SSH connections other it without any issue. Could you share your settings?
