### ISSUE TITLE
Chinese characters are not displayed correctly.

### ISSUE THREAD

**Issue by HaloWww** [isontheline/pro.webssh.net#516]
**Describe the bug**
In the Chinese sentence, the Chinese characters at the end cannot be displayed correctly.

**Informations**
 - Device : iPad pro 11
 - OS : iOS 14.5
 - WebSSH Pro version : 16.3

**Screenshots**
![微信图片_20220118125250](https://user-images.githubusercontent.com/64211024/149873096-c085a2c3-29fe-4e92-b4f8-2e12722a274d.jpg)

**To Reproduce**
code: 

menu() {
	clear
	while :; do
		echo
		echo "........... V2Ray 管理脚本 $_version by 233v2.com .........."
		echo
		echo -e "## V2Ray 版本: $cyan$v2ray_ver$none  /  V2Ray 状态: $v2ray_status ##"
		echo
		echo "帮助说明: https://233v2.com/post/1/"
		echo
		echo "反馈问题: https://github.com/233boy/v2ray/issues"
		echo
		echo "TG 频道: https://t.me/tg2333"
		echo
		echo "捐赠脚本作者: https://233v2.com/donate/"
		echo
		echo "捐助 V2Ray: https://www.v2ray.com/chapter_00/02_donate.html"
		echo
		echo -e "$yellow  1. $none查看 V2Ray 配置"
		echo
		echo -e "$yellow  2. $none修改 V2Ray 配置"
		echo
		echo -e "$yellow  3. $none下载 V2Ray 配置 / 生成配置信息链接 / 生成二维码链接"
		echo
		echo -e "$yellow  4. $none查看 Shadowsocks 配置 / 生成二维码链接"
		echo
		echo -e "$yellow  5. $none修改 Shadowsocks 配置"
		echo
		echo -e "$yellow  6. $none查看 MTProto 配置 / 修改 MTProto 配置"
		echo
		echo -e "$yellow  7. $none查看 Socks5 配置 / 修改 Socks5 配置"
		echo
		echo -e "$yellow  8. $none启动 / 停止 / 重启 / 查看日志"
		echo
		echo -e "$yellow  9. $none更新 V2Ray / 更新 V2Ray 管理脚本"
		echo
		echo -e "$yellow 10. $none卸载 V2Ray"
		echo
		echo -e "$yellow 11. $none其他"
		echo
		echo -e "温馨提示...如果你不想执行选项...按$yellow Ctrl + C $none即可退出"
		echo
		read -p "$(echo -e "请选择菜单 [${magenta}1-11$none]:")" choose
		if [[ -z $choose ]]; then
			exit 1

**Comment by isontheline** [comment]
Hello @HaloWww 👋

Could you also post the expected good result? (from another terminal app)

Thank you a lot

Have a nice day☀️

**Comment by HaloWww** [comment]
> Hello @HaloWww 👋
> 
> Could you also post the expected good result? (from another terminal app)
> 
> Thank you a lot
> 
> Have a nice day☀️

This is the correct output.

![image](https://user-images.githubusercontent.com/64211024/149883440-e6fb47c6-6211-4f86-8724-89ad8f03ae14.png)

This is the output now.

![image](https://user-images.githubusercontent.com/64211024/149883817-55a29c0b-ff78-4815-8cbe-d960288fadf6.png)

**Comment by isontheline** [comment]
A TestFlight release will be available in a few hours

**Comment by isontheline** [comment]
Hello @HaloWww 👋

Could you check WebSSH 17 beta?
https://testflight.apple.com/join/QSrBK59z

Have a nice day ☀️

**Comment by HaloWww** [comment]
i have no ios15 devices right now. when i get the devices ，i will tell you the result.

thanks for your jobs.
