### ISSUE TITLE
In-App Purchases Section of the Beta Enrollment page

### ISSUE THREAD

**Issue by an-d-uu** [isontheline/pro.webssh.net#521]
https://webssh.net/documentation/becoming-external-tester/

The wording did not parse correctly or translated oddly.

Current wording:

- You will not be able to use some features if you don't have buyed them through the App Store with the full version of WebSSH.
- Please don't to become an External Tester in order to unlock some features, it won't be the case.

Suggested Wording:

- You will not be able to use some of the features if you haven't purchased the full version of WebSSH through the App Store.
- Please don't to become an External Tester in order to unlock some features. The full version still requires purchase through the App Store.

*I am not a grammar expert so please adjust the wording how you see fit.

**Comment by isontheline** [comment]
Hello @an-d-uu Andy 👋

Thank you a lot for your issue 🙏

I will make the changes in the upcoming days.

**Comment by isontheline** [comment]
Hello @an-d-uu 👋

Your suggestion is now online 👍 

Thank you again!
