### ISSUE TITLE
Copy to pasteboard on selection

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#523]
**Describe the feature**
Ability to copy to pasteboard when text selection is done.

**Comment by jarrah31** [comment]
I too would like this feature please. 

Plus if possible, the ability to paste using the middle mouse button too (macOS and perhaps an iPad with a paired mouse?)

Thanks.

**Comment by isontheline** [comment]
@jarrah31 No problem for macOS, should be "easy".

For iPad / iPhone, I need to implement text selection first (#144) 

Thank you a lot for your feedback 👍

**Comment by isontheline** [comment]
I'm working on copying text selection (macOS) to the pasteboard.

As I can't (I don't know how) paste when middle mouse button is pressed under Mac Catalyst, you can use this tip instead : https://github.com/isontheline/pro.webssh.net/issues/699#issuecomment-1243025213

**Comment by jarrah31** [comment]
That's a useful workaround, thank you!

**Comment by jarrah31** [comment]
Works great, thank you!
