### ISSUE TITLE
No copy/paste options in build 848

### ISSUE THREAD

**Issue by DustyBawls** [isontheline/pro.webssh.net#524]
No option for copy paste. No ability to open multiple windows.

**Information**
 - Device : [iPad Gen 3]
 - OS : [e.g. iOS 15.4]
 - WebSSH Pro version : [17.0 (848)]

**Screenshots**
N/A

**To Reproduce**
1. Open ssh connection
2. Attempt any copy paste operation either by selecting text of from the buffer.

1. Open a connection
2. Attempt to open a second connection window

**Comment by isontheline** [comment]
Hello @DustyBawls 👋

* iOS terminal copy tracking is here : https://github.com/isontheline/pro.webssh.net/issues/150#issuecomment-1021656119
* I don't understand "attempt to open a second connection window". Doesn't the multi window working on your device? Could you post a video?

**Comment by DustyBawls** [comment]
My apologies,

Having reopened WebSSH the multiple window option is working fine. The copy paste is still not working.

Kind regards

-- Nigel
