### ISSUE TITLE
New terminal rendering engine : Issues after implementation

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#525]
- [x] The keyboard does weird when you make a connection. Then the keyboard is gone en when you click on the screen it goes up back to normal. 
- [x] And the green letters seems bit weird.

![image](https://user-images.githubusercontent.com/44212923/151860770-751c51c6-9df0-4bca-9700-895f682ed1bf.png)

**Comment by isontheline** [comment]
# Collection 2
- [ ] Some colors are more matte : https://github.com/isontheline/pro.webssh.net/issues/201#issuecomment-1026139081

**Comment by isontheline** [comment]
@AInteriorB 

> * There is no longer any information about available rows and columns when resizing the terminal. This information is sometimes needed.

I have removed it instead of disable : https://github.com/isontheline/pro.webssh.net/issues/468
Sorry.
-> I'm reopening this issue

> * Switching windows is broken if you have disabled the keyboard by clicking on the keyboard icon on the right side. The strange thing is, if you disable the keyboard by touching the screen, switching widows still works. Also, if you enable the keyboard again it works in all cases.

- [ ] I will check this trouble asap


> * iPad hardware keyboard in duty: If you disable the keyboard by touching the screen, there appears a strange background color around the virtual keys. Not so, if you disable the keyboard by clicking on the keyboard icon on the right side.

Have you got a screenshot of this issue?

**Comment by AInteriorB** [comment]
> > * There is no longer any information about available rows and columns when resizing the terminal. This information is sometimes needed.
> 
> I have removed it instead of disable : #468 Sorry. -> I'm reopening this issue
I now got the information with `stty size`. This is okay for me. An alternative would be either a setting like mentioned in #468 or a (i) info icon that gives this information if requested.

**Comment by AInteriorB** [comment]
> > * iPad hardware keyboard in duty: If you disable the keyboard by touching the screen, there appears a strange background color around the virtual keys. Not so, if you disable the keyboard by clicking on the keyboard icon on the right side.
> 
> Have you got a screenshot of this issue?

![7092781E-0D6A-4D5D-84FA-B18E345010FF](https://user-images.githubusercontent.com/49516700/152045558-22a23030-00b6-48de-8152-e9dd161a011a.jpeg)

**Comment by isontheline** [comment]
Thanks for the screenshot @AInteriorB 🙏 
Seems a white terminal background I will fix it.


> I now got the information with `stty size`. This is okay for me. An alternative would be either a setting like mentioned in #468 or a (i) info icon that gives this information if requested.

I will try to add a setting first. 
A (i) could also be a good idea, I'm adding this tip to #468
