### ISSUE TITLE
Color Themes

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#526]
**Describe the feature**
* From https://github.com/mbadolato/iTerm2-Color-Schemes
* Use JSON : https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/windowsterminal
* Ability to show screenshots OR
* Ability to preview the choice (show mashREPL window as example?)

# iTerm2 implementation
![](https://iterm2.com/img/screenshots/profiles1.png)

# Terminal implementation
![image](https://user-images.githubusercontent.com/44212923/182451720-b11fc5eb-0c50-4d23-ae60-7470e2f80422.png)

**Comment by isontheline** [comment]
WIP


![Image](https://github.com/isontheline/pro.webssh.net/assets/44212923/4987d6c1-43eb-43aa-b32e-e3bdc602ed57)

**Comment by isontheline** [comment]
Now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z

**Comment by cybardev** [comment]
Can the JSON be imported? E.g. if I want [Kanagawa Dragon](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/windowsterminal/Kanagawa%20Dragon.json), do I have to copy-paste every colour in the Create New Colourscheme UI, or can I download the JSON file, and select that somehow in WebSSH?

**Comment by cybardev** [comment]
That would be great. There's already one Kanagawa theme "Kanagawabones", but I prefer "Kanagawa Dragon" because of its muted colours that are easier on the eyes.

Thanks for the awesome app and responsive support. Really appreciate your work. 😊
