### ISSUE TITLE
+ button is hidden to add a connection in my old iPhone 6+ (iOS v12.4.8).

### ISSUE THREAD

**Issue by antdude** [isontheline/pro.webssh.net#53]
**Describe the bug**
Blue + button is hidden to add a connection in my old iPhone 6+ (iOS v12.4.8).

**Informations**
 - Device : iPhone 6 Plus
 - OS : iOS v12.4.8
 - WebSSH Pro version : 14.1

**Screenshots**
https://ibb.co/album/6Rtm10

**To Reproduce**
1. Use an old iPhone 6+ with its iOS v12.4.8.
2. Download, install, and run a brand new WebSSH Pro v14.1.
3. Add a new first SSH or SFTP server connection.
4. It says "Tap the + button to add your first connection", but I don't see it because it is hidden under "Add SSH connection" text pop-up. I was pressing this text pop-up to add my first server connection and nothing was happening until I press the partial blue button.

Thank you for reading and hopefully fixing this comestic issue soon. :)

**Comment by avalonix** [comment]
I confirm.  the problem has existed for a long time.  shows up on my iPhone 11 too

**Comment by antdude** [comment]
Wow. Even on the newest model! That's not good. This is a bad user experience for newbies like me. :(

**Comment by avalonix** [comment]
![image](https://user-images.githubusercontent.com/29081475/91651515-d879d800-eab7-11ea-8302-8ba23d161796.jpeg)

**Comment by isontheline** [comment]
Hello @antdude  👋 
Thanks for your issue!

I will fix it in a few hours!

In the mean time :
Please install _WebSSH Beta_ from TestFlight app : https://testflight.apple.com/join/QSrBK59z

You will receive a notification as soon as the fix is available.

☀️ Have a nice day

**Comment by antdude** [comment]
Thanks isontheline! I'll just wait for the stable fixed version from Apple's App Store. :)

**Comment by isontheline** [comment]
No problem 👍

**Comment by antdude** [comment]
I got a new updated app, but don't see this fixed?

**Comment by isontheline** [comment]
It's planned for 14.3 not 14.2
As mentionned above, please install the TestFlight release in order to test the fix. This beta release is as stable as the App Store one.

14.3 is not planned for release right now, there are others bugs waiting for a fix.
I think 14.3 should be released in 15-30 days, or before.

**Comment by antdude** [comment]
Thanks. I will wait again. :)

**Comment by antdude** [comment]
I got the updated app and confirmed that it is fixed. Thanks again. :)

**Comment by antdude** [comment]
I got the updated app and confirmed that it is fixed. Thanks again. :)

**Comment by isontheline** [comment]
Thanks for your feedback @antdude 
☀️ Have a nice day!
