### ISSUE TITLE
New rendering engine : Keyboard glitches

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#541]
1. Switching windows is broken if you have disabled the keyboard by clicking on the keyboard icon on the right side. The strange thing is, if you disable the keyboard by touching the screen, switching widows still works. Also, if you enable the keyboard again it works in all cases.
2. iPad hardware keyboard in duty: If you disable the keyboard by touching the screen, there appears a strange background color around the virtual keys. Not so, if you disable the keyboard by clicking on the keyboard icon on the right side.
![image](https://user-images.githubusercontent.com/44212923/152701932-4a417317-28c6-4e71-b89b-aaa6f6279862.png)

_Originally posted by @AInteriorB in https://github.com/isontheline/pro.webssh.net/issues/525#issuecomment-1027237697_

**Comment by isontheline** [comment]
Hello @AInteriorB 👋

Strange 😢
I'm not able to reproduce (1) and (2) on my iPad mini 4

**Comment by AInteriorB** [comment]
I captured both.

(1) Doesn‘t happen always! If you restart the app, the problem is gone for some time.

https://user-images.githubusercontent.com/49516700/152702498-518d607d-82f8-4d21-b695-4d0c6941c9a2.mp4

 (2)

https://user-images.githubusercontent.com/49516700/152702514-87a99c15-bcd8-49f3-b7d0-8c87306f2830.mp4

**Comment by isontheline** [comment]
@AInteriorB Thank you again for your strong feedback 👍

I will reproduce and fix them.

**Comment by AInteriorB** [comment]
You're welcome. And to be honest: (2) is just a little beauty thing, nothing important ;-)

**Comment by isontheline** [comment]
Hello @AInteriorB 👋

Multi-windows have been replaces with iOS native Split View.
So (1) should be resolved.

Have you tried the latest beta available?

**Comment by AInteriorB** [comment]
Hey @isontheline , greeeeat as mentioned in #510 👍 

Info for (2): Same effect, if no hardware keyboard is attached. The entire virtual keyboard gets inverted when touching the screen for disabling the (virtual) keyboard.

**Comment by isontheline** [comment]
Thank you @AInteriorB for your string feedback 💪

I'll try to reproduce on my hardware asap.

**Comment by isontheline** [comment]
Hello @AInteriorB 

I come back to you about the "white glitch".

Are you always encountering it inside WebSSH 18.0?

Have a nice day ☀️

**Comment by isontheline** [comment]
@AInteriorB Feel free to ping me if this issue isn't fixed inside latest WebSSH releases
