### ISSUE TITLE
Groups improvements

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#543]
It would be nice to have :

- [ ] ~~an option to expand/collapse groups~~
- [x] suggestion of existing groups while entering group name while creating new connection

_Originally posted by @freepaddler in https://github.com/isontheline/pro.webssh.net/discussions/542_

**Comment by jarrah31** [comment]
> suggestion of existing groups while entering group name while creating new connection
Great, I was going to suggest this feature too. Thanks!

> an option to expand/collapse groups
This will be useful as well.

**Comment by isontheline** [comment]
@jarrah31 
You've removed "an option to expand / collapse groups". 
But I think it could be great, at least on macOS.

What do you think about?

**Comment by jarrah31** [comment]
Yes sorry, misunderstanding there. I do definitely think that adding the ability to expand/collapse groups will be useful. I found this issue as I was originally looking for the ability to suggest existing groups, so I decided to just comment on that particular feature, and then give my thumbs up in the first post to indicate I liked both features. :)

**Comment by isontheline** [comment]
Perfect 😉

**Comment by jedis00** [comment]
Would love the ability to select an already existing group.

**Comment by isontheline** [comment]
Thanks for your feedback @jedis00 about this feature

I increase the priority of this issue inside the roadmap

**Comment by isontheline** [comment]
Groups suggestion now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
