### ISSUE TITLE
sftp couldn't upload and download file

### ISSUE THREAD

**Issue by Freakboy** [isontheline/pro.webssh.net#55]
I tried add a sftp connection,but it is haven't upload and download file,files function

**Comment by isontheline** [comment]
Hello @Freakboy  👋 
Thanks for your issue! 
But...

...Every time someone does not respect the issue's template, a little mouse dies.

<details> 
<summary>Learn how</summary>

![little-mouse-dies-or-not-it-depends-on-you](https://user-images.githubusercontent.com/44212923/91720843-10584c80-eb98-11ea-80b8-fdc48f92392c.gif)
</details>

Please edit your issue description to respect the issue template as much as possible :
* https://github.com/isontheline/pro.webssh.net/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
