### ISSUE TITLE
Hostname validate missing and UI confusion around private key and passcode

### ISSUE THREAD

**Issue by j256** [isontheline/pro.webssh.net#555]
**Describe the bug**
1) I made the mistake and entered foo@bar.com as the hostname for a server connection instead of foo.bar.com.  There was no validation on the hostname form and it just would not connect.  Some sort of invalid hostname message would have been more helpful.

2) If I enter a bad passcode for my ssh secret key a red "Connection error" dialog appears.  It seems like this information gets cached for a while because when I try to click on the server name again, it doesn't prompt me but immediately shows the "Connection error" again.  It shouldn't.  It should prompt me immediately for a new passcode.

3) When there is a "Connection error", the dialog comes down and it has a red X image on the left.  I keep on trying to click that X to close the dialog because of UX behavior under MacOS.  Either remove the X, add a cancel button to the dialog, or let it be clickable _and_ swipe-able to remove it.  I vote for the click option.

**Informations**
 - Device : iPhone 11
 - OS : iOS 15.3.1
 - WebSSH Pro version : 17.0 (861)

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**To Reproduce**
1. Go to servers
2. Press + in the upper right
4. Enter hostname with @ sign in it.
5. Try to connect to it.

2nd problem:
1. Add a private key with a passcode.
2. Try to connect to the server with that key.
4. Enter an invalid passcode.  Red dialog should come down.
6. Try to connect to that server immediately afterwards.  No passcode prompt.

3rd problem:
1. Add a private key with a passcode.
2. Try to connect to the server with that key.
4. Enter an invalid passcode.  Red dialog should come down.
6. Try to click on the red X to get rid of the dialog.

**Comment by isontheline** [comment]
Hello @j256 👋

Thank you a lot for making this issue about WebSSH' UX!

I'm planning it for the upcoming milestone

Have a nice day ☀️
