### ISSUE TITLE
Ability to paste the current connection password by pressing a key

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#563]
I’m using WebSSH on a nearly daily basis to manage my home lab across all my devices, I love it.
During my use I’ve notices a few things I would change/add.

The first thing would be an auto password fill.
When ever I type sudo XX and I’m asked for my password, I would love to see a special key which will enter the saved password for this host.
Currently my workaround is, to have a snippet for each host but this is not ideal in my opinion 

I would be more than happy to help you with all those requests.
Thanks for this amazing part of software.

_Originally posted by @Dag0d in https://github.com/isontheline/pro.webssh.net/discussions/560_

**Comment by isontheline** [comment]
Hello @Dag0d 👋

If I add an option menu here :
![Image](https://user-images.githubusercontent.com/44212923/200568130-b6c2569b-1239-4828-93a5-2cf701beeb04.png)


Like "Put this connection password" => will be OK for you?

**Comment by Dag0d** [comment]
Hi @isontheline 
This sounds like the perfect location for me.

**Comment by isontheline** [comment]
Thank you a lot for your feedback @Dag0d 🙏

I will plan this issue asap

**Comment by isontheline** [comment]
Available in latest beta release :
https://testflight.apple.com/join/QSrBK59z

**Comment by egolfeld** [comment]
Where password will be stored? In the memory? My only concern is: if users will need custom passwords, for other services, not for ssh, they will have to go to password manager

**Comment by isontheline** [comment]
@egolfeld This issue is only about pasting the current connection password not to make a password manager.

Your own root issue is about to put password from the password manager, isn't it?

If I don't understand your need, could you explain it again please?
