### ISSUE TITLE
Editing active tunnel prevents it from being disabled

### ISSUE THREAD

**Issue by eapache** [isontheline/pro.webssh.net#571]
**Describe the bug**
Create and activate an SSH tunnel. Then, while the tunnel is still active, edit the tunnel and change the ports. Then try disabling the tunnel. The tunnel remains active.

Probably, we should forbid editing tunnels (and any connection) at all while they are active, it can only lead to problems.

**Informations**
 - Device : iPad Air 4
 - OS : iPadOS 15.4
 - WebSSH Pro version : 17.2

**Comment by isontheline** [comment]
Hello @eapache 👋

Thank you a lot for your feedback 🙏

OK I will forbid tunnel editing while they are active, in the next few hours.

Other connections management will remain as is, yet.

**Comment by isontheline** [comment]
@eapache Fixed inside latest WebSSH 17.3 beta release : 
https://testflight.apple.com/join/QSrBK59z
