### ISSUE TITLE
Cursor Key not working in PWSH

### ISSUE THREAD

**Issue by MrFly72** [isontheline/pro.webssh.net#572]
# Bug description
Great that pwsh is now working. So I was able to test it more. So this came up:
Cursor up,down,left,right is not working in pwsh. It outputs characters instead of cursor moving

# Steps to reproduce
1. Open PWSH
2. either use the "joystick" button or the cursor cross to move the cursor or step back in history (cursor up)
3. 
4. Error is thrown

I tested it also with tmux and actually it works there.

**Comment by isontheline** [comment]
Does "Cursor Keys Mode" is set to "Application" inside your SSH advanced terminal settings ? (On connection)

On my side I can use arrow keys above the keyboard.

Thanks again for your feedback @MrFly72

**Comment by MrFly72** [comment]
That was the magic trick. It was set to normal.
Weird enough that it works with tmux then?

**Comment by isontheline** [comment]
Nice to hear that it works now 😅

My understand is that tmux remap keys on the fly 💪

May I close this issue?

Have a nice day ☀️

**Comment by isontheline** [comment]
Thanks for your strong feedback 🙏

**Comment by MrFly72** [comment]
You are welcome.
And thank for the hint to tmux. It is really cool and I cannulae it great for background download tasks, started now with an ssh session.
