### ISSUE TITLE
Can’t switch between windows on SFTP

### ISSUE THREAD

**Issue by ukguy** [isontheline/pro.webssh.net#574]
# Bug 
Can’t switch between screens anymore

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. Log into an ssh session, then click the multi screen icon
2. Log into a sftp session
3. Click at the top to switch screen 
4. It no longer works
5. We have to sign out before we can switch

**Comment by isontheline** [comment]
Hello @ukguy 👋

WebSSH is now using the native way to use multiple windows : https://webssh.net/documentation/help/howtos/launching-multiple-terminals/

Could you try it out?

Have a nice day ☀️

**Comment by ukguy** [comment]
Hi there,
I have that turned on, it’s always worked before but it doesn’t now.

“ You will now be able to switch or add new windows by pressing the navigation bar.”

That doesn’t work once logged into a sftp server, we have to disconnect/log out and lose where we were. 

I am on iOS 15.4
iPhone XS 

thanks!

**Comment by isontheline** [comment]
Hi @ukguy 

Ouch you're right 😢 there is a bug on iPhone.

I will fix it in the next hours.

Sorry for the trouble

**Comment by ukguy** [comment]
Brilliant! 
thanks so much for such a fast response 👍

**Comment by isontheline** [comment]
Thank you too for your feedback!

Are you already enrolled to beta releases?
https://testflight.apple.com/join/QSrBK59z

New beta will be available tomorrow.

**Comment by isontheline** [comment]
@ukguy Could you try the latest beta release please?

https://testflight.apple.com/join/QSrBK59z

**Comment by ukguy** [comment]
Perfect!!
It’s fixed!

top work 👍
And so quick! Thank you, it’s sooo much easier with the switching. I use your app a lot and really do appreciate your work

**Comment by isontheline** [comment]
@ukguy Thank you so much for your strong support about my work 🙏

Sorry again for the trouble. Please come back to me for any issue you may find.

Have a nice day ☀️
