### ISSUE TITLE
22nd March update

### ISSUE THREAD

**Issue by rce1086** [isontheline/pro.webssh.net#575]
# Bug 
Prior to this update, I have been able to use multiple terminal sessions open at the same time, and cut/paste between them etc.
Since applying this update, I can only open a single window.
I have tried Restore Purchase, but it says I haven’t purchased it, but if I try to initiate a purchase in the App Store, it won’t let me, and nor can I find how to try this in-app…

help, please?

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by isontheline** [comment]
Hello @rce1086 👋

Which OS are you using (macOS / iOS / iPadOS)?

**Comment by isontheline** [comment]
Hello @rce1086 👋

Feel free to reopen this issue at any time.

Have a nice day ☀️

**Comment by rce1086** [comment]
Sorry for the delay - I was expecting an email from GitHub when you responded, but didn’t see one…
iPadOS

thanks

**Comment by isontheline** [comment]
Hello Carl @rce1086 👋

Thank you for your feedback.
Could you check this howto? https://webssh.net/documentation/help/howtos/launching-multiple-terminals/

Does it help you to use multiple windows?
