### ISSUE TITLE
Ability to launch a new tab on macOS from a keyboard shortcut

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#578]
# Feature description
The documentation [found here](https://webssh.net/documentation/help/howtos/launching-multiple-terminals/) says that I should be able to open a new tab by pressing "Shift + Cmd + `", but this doesn't appear to be working for me.

I'm on v17.3.

# Screenshots
N/A

# Steps to reproduce
1. Open WebSSH
2. Start a connection within SSH
3. Press "Shift + Cmd + `" to try and open a new tab. 
4. Nothing happens

Thanks!

**Comment by isontheline** [comment]
This shortcut isn't made by WebSSH but macOS.
It won't allow to launch a new tab directly but instead show all tabs then you will be able to add a new tab by pressing the plus button.

Which shortcut is shown on your macOS?
Here is mine :
<img width="591" alt="image" src="https://user-images.githubusercontent.com/44212923/160465803-fcd65b91-28a8-4e2b-8ae5-10036c1fe3e0.png">

**Comment by jarrah31** [comment]
Oh that's interesting, mine doesn't have that:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/3072303/160467298-eac1b650-2c76-4771-ad5d-c89bab8834bb.png">

**Comment by isontheline** [comment]
Strange. 
macOS 12.3 also as me?

I will improve the documentation by deleting the shortcut.
I also need to find a way to add this shortcut but I don't have found any way - yet - to open a tab from code.

**Comment by jarrah31** [comment]
Thanks Arnaud! (Yep, 12.3 as well)

**Comment by isontheline** [comment]
I was sure that shortcut were same on all languages but I'm wrong.

Documentation will be updated soon after being updated by the pipeline.
Thanks too!

**Comment by jarrah31** [comment]
I've been trying to see if it's an option I've just not enabled somewhere, but had no luck so far. 

Thank you for adding this as a feature request. Multiple tabs and [split view](https://github.com/isontheline/pro.webssh.net/issues/573) are new features I'm looking forward to on the macOS app. :)

**Comment by isontheline** [comment]
🙏👍💪❤️ Thank you so much @jarrah31 about sponsoring my work ❤️💪👍🙏

**Comment by jarrah31** [comment]
There's a workaround! 

If I select "Show All Tabs", it gives me the following window:
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/3072303/160474056-c18bd29f-ea21-417d-84c2-ef7fe0bfa317.png">

Which then gives me multiple tabs! 
<img width="826" alt="image" src="https://user-images.githubusercontent.com/3072303/160474212-89a128c0-f442-4687-88a0-9d38c743a68a.png">

**Comment by jarrah31** [comment]
> 🙏👍💪❤️ Thank you so much @jarrah31 about sponsoring my work ❤️💪👍🙏

You're welcome, I'm more than happy to do so! Your app is genuinely very useful! The fact you don't charge a monthly subscription makes a big difference, but I realise you still need to cover monthly costs, so I just wanted to show my appreciation for the price of a monthly coffee/beer. 🍺

**Comment by isontheline** [comment]
Already enhanced inside WebSSH 18.0 : `Cmd + t` will allow to open a new tab

Beta release will be available in the next few days

**Comment by isontheline** [comment]
Now available inside WebSSH 18.0

**Comment by jarrah31** [comment]
This also works great in 18.0 beta, thank you!
