### ISSUE TITLE
Ability to set default Terminal Settings for new connections

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#581]
# Feature description
Would it be possible to have configurable default Terminal Settings that are then applied to any new SSH connection please?

For example, I prefer to use font-size 12 on my iPad, but this defaults back to 15 when I create a new connection. 

I know that a workaround is to clone an existing connection, but it would be a nice option to modify default settings instead.

**Comment by isontheline** [comment]
@jarrah31 It should be #488 isn't it?

**Comment by jarrah31** [comment]
aha, yes indeed! I searched for "Terminal Settings" which didn't find that issue, but I should have searched for default too. Thanks!
