### ISSUE TITLE
Ability to edit new connection straight after cloning 

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#582]
# Feature description
I've started to create lots of new connections in earnest now that I can do ProxyJumps, and one feature that would be useful is the ability to edit a cloned connection straight away, reducing the number of taps/clicks. I guess that this would depend on general consensus though as some people may not want to edit straight away...

At the moment my cloning workflow is as follows:
1. Right-click / tap-hold a connection
2. Click Clone -> SSH
3. Tap screen again to dismiss confirmation
4. Right-click / tap-hold cloned connection
5. Tap Edit

I would like to propose the following instead please:
1. Right-click / tap-hold a connection
2. Click Clone -> SSH
3. User is taken to the cloned connection edit screen, perhaps with a 2-3 second green message to say "Cloned", that automatically disappears without having to tap the screen to dismiss it.

Thanks.

**Comment by jarrah31** [comment]
Hmm tricky one - my preference would be to go straight to the edit screen, but I guess you'd need to consider if there's a scenario where users just want to create multiple clones and then edit each connection later. However, given that we currently need to tap to dismiss the green success message anyway, it won't make a difference if that is replaced with a "Would you like to edit the connection now?" as you suggest above. It's the same number of taps and no loss for either side.

**Comment by isontheline** [comment]
Thank you a lot for your strong feedback!
