### ISSUE TITLE
Still get that upper popup advertising the full version

### ISSUE THREAD

**Issue by dechimp** [isontheline/pro.webssh.net#583]
# Bug description
I still get that upper popup advertising the full version, even though I already bought it. Love the app. Thanks.

**Comment by isontheline** [comment]
@dechimp Could you screenshot the bottom part of WebSSH settings screen please ?

Some useful information are there.

Does the issue is still there after app restart (kill)?

**Comment by dechimp** [comment]
Perhaps I didn’t kill the app, so that might’ve been the issue. I haven’t figured out what reliably produces the popup, but if I do, I will write back again. Thanks. 

I’m on an iPhone SE 2022

**Comment by isontheline** [comment]
Thank you so much for your feedback @dechimp 🙏

I'm here if you need any help about anything inside WebSSH.

**Comment by isontheline** [comment]
Sorry @dechimp screenshots should sent though GitHub in order to be added to the issue

That's strange the advertising popup is shown. I have bought my own copy on the App Store several months ago and I don't have seen any.

**Comment by isontheline** [comment]
@dechimp Perhaps enabling verbose logging should help for searching about the root cause :

In order to enable verbose logging you can follow the steps :
1. iOS Settings
2. WebSSH
3. Settings
4. Log Level > Verbose
5. Restart WebSSH
6. Reproduce your action
7. Find the log files inside iOS > Files > WebSSH

**Comment by dechimp** [comment]
lol.  It says I commented this today but I sent that comment over 6 months ago :stuck_out_tongue: 

I still do see the buy-this-app popup, but I still cant figure out how to reliably reproduce it.  It seems to happen sometimes when using the iOS task switcher to re-open WebSSH.

**Comment by isontheline** [comment]
Perhaps a GitHub bug 😁
