### ISSUE TITLE
Ability to remember open connections within multiple tabs and re-establish them after quitting

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#585]
# Feature description
I like to have multiple tabs open within WebSSH, with each one connecting to a different server. However, when I quit and then start WebSSH, it opens back up with the same number of tabs but looses/forgets the sessions that were open within that tab.

If possible I'd like WebSSH to remember which connections were open in each tab and then re-establish them again when the app starts. Perhaps it could be done the same way as multi-tabs on the iPad whereby it remembers each connection per window and prompts you to either (R) restart or (Q) quit?

**Comment by isontheline** [comment]
You're right this will be a great enhancement!

I'm renaming this issue because it's also related to iPad : if you open multiple windows and leave them a few minutes / hours WebSSH will reopen blank windows like on macOS and won't stay on your connections.

**Comment by jarrah31** [comment]
That's great, thank you again for making a really useful desktop/iPad/iPhone ssh client Arnaud!

**Comment by isontheline** [comment]
Thank you too for your strong support 🙏
