### ISSUE TITLE
Granular control of terminal colour settings

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#587]
# Feature description
Please could we have the ability to define custom background, foreground, and cursor colours.
At the moment there's only a pre-defined list of colours such as grey, black, white, red, etc. I would be great if we could define colours via their RGB values as well please.

e.g. I like the shades of grey that iTerm uses as it's less harsh on my eyes than the current WebSSH colours:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/3072303/161617385-b19bf202-c885-42ac-855e-d9d4bb6fc7aa.png">

The RGB colours in this example would be:
Background: 40 43 51
Foreground: 185 191 202

Thanks.

**Comment by isontheline** [comment]
Great addition!

I will implement the native iOS Color Picker : https://nemecek.be/blog/29/first-look-at-the-new-uicolorpickerviewcontroller-in-ios-14

**Comment by jarrah31** [comment]
That looks great, thank you!

**Comment by isontheline** [comment]
@jarrah31 Are you also interested in this issue :
* https://github.com/mbadolato/iTerm2-Color-Schemes
  * https://github.com/mbadolato/iTerm2-Color-Schemes

**Comment by jarrah31** [comment]
Yes that would be great! 👍

**Comment by DexterLagan** [comment]
Also, I noticed that it breaks vim's color themes. Say I have a cobalt color scheme setup in vim, the background color of characters doesn't match the background color of the rest of the screen. Here's a screenshot, with .vimrc open in vim:

<img width="1136" alt="Screen Shot 2022-08-12 at 11 02 43 AM" src="https://user-images.githubusercontent.com/38226103/184322180-843d6d0c-a699-4bdb-8afa-895971866621.png">

**Comment by isontheline** [comment]
Hello @DexterLagan 👋

Thank you a lot for your feedback 🙏

I will so take a look at this background trouble.

**Comment by r08n** [comment]
I would also love if we could customise the colours using RGB or HEX values, and if we could even use themes, that would of course be great! 😊

Many thanks! 🙏

**Comment by isontheline** [comment]
Hello @r08n Roger 👋

Thank you so much for your feedback 🙏

I will so increment priority of this issue and will try to work on it soon.

Have a nice day ☀️

**Comment by isontheline** [comment]
@r08n In the meantime you could also use SSH Config to configure custom colours as wanted :
https://webssh.net/documentation/help/SSH/ssh-config-file/#special-features

**Comment by isontheline** [comment]
Sorry for the delay
I'm now working on the ability to define custom colors

**Comment by r08n** [comment]
Perfect, thank you! 🙏

**Comment by isontheline** [comment]
Latest beta release let you set custom colours : https://testflight.apple.com/join/QSrBK59z

![Image](https://github.com/isontheline/pro.webssh.net/assets/44212923/2671a7c2-a731-48ff-aa0b-87df4cd2af7f)



![Image](https://github.com/isontheline/pro.webssh.net/assets/44212923/d3020cf0-51a6-4bed-8298-e77aa011205f)

**Comment by r08n** [comment]
Looks nice, Arnaud! Looking forward to the next official version 😊
Greetings from Switzerland, Roger

**Comment by isontheline** [comment]
I hope it should be available for Xmas 🎄
