### ISSUE TITLE
(macOS) WebSSH locks when active in a full-screen app for at least one minute

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#589]
# Bug description
If I swipe or switch to a full screen app (any other app will do) on my macOS laptop and stay active on there for at least one minute, when I swipe back to the desktop, WebSSH Access Locking prompt appears, asking you to unlock the app. 

This only ever happens when in a full-screen app view, and only locks after one minute (swiping back within that timeframe is ok). WebSSH will happily stay unlocked all day, even if I have the screensaver running or lock the screen for any length of time (at least I think so), as long as I never enter full-screen mode on another app. 😄 

# Steps to reproduce
1. Open WebSSH and leave it running in the fore or background
2. Select any other macOS app and press the little green circle to enter full-screen
3. Stay active on the app or leave it alone for one minute
4. Swipe back to desktop. WebSSH will prompt you to unlock the app

**Comment by isontheline** [comment]
Would you like to have one minute lock in all cases?

Or do you want to remove the lock feature? (Which was initially made for iOS)

Thanks for your feedback

**Comment by jarrah31** [comment]
At the moment I would prefer to remove the one minute lock because it doesn't make logical sense that it only locks when actively working in a full-screen app.

Ideally the lock would only apply if the app itself hasn't had any activity, but for this to happen I'd like the ability to define how long the lock timeout value is because one minute would be too short.

Hope that helps,
Thanks.

**Comment by isontheline** [comment]
It helps 👍

I will :
* implement the ability define the timeout
* fix the the lock that occurs only when in full-screen (macOS)

**Comment by jarrah31** [comment]
@isontheline If possible, could this be bumped up the priority list for fixing please? I'd have to say it's my number one issue with WebSSH on the Mac because I often use apps in fullscreen, and every time I swap back to the main desktop screen, the unlock prompt appears in front of everything and can't be hidden. I can wait for all the other issues I've raised, but this one is a daily annoyance. :)

**Comment by isontheline** [comment]
Thanks for the priority reminder!

I will try to make a fix tonight 😉
I hope I can make it on 17.x (18.0 alpha is near 80% ETA)

**Comment by isontheline** [comment]
@jarrah31 I have forgot if you are already enrolled to TestFlight on macOS?

**Comment by jarrah31** [comment]
Good point I haven't yet - could you let me know how I enrol please?

**Comment by isontheline** [comment]
Does this link works on Safari?
https://testflight.apple.com/join/QSrBK59z

TestFlight app on macOS is needed (from the App Store)

**Comment by isontheline** [comment]
New release isn't yet available but I would like to know if TestFlight can be used on your macOS.

**Comment by jarrah31** [comment]
Thanks, all sorted with TestFlight on macOS now.

**Comment by isontheline** [comment]
I have added an option inside settings :
<img width="275" alt="image" src="https://user-images.githubusercontent.com/44212923/165621702-0c3cd60a-1c84-41ae-b75a-43fb2fe89d2a.png">

Being pushed to Apple Xcode Cloud :
<img width="894" alt="image" src="https://user-images.githubusercontent.com/44212923/165621804-ff58ece6-b381-474c-913a-c782dbeede41.png">

I hope 17.5 release number will be allowed as I already have pushed 18.0

Should be available in a few hours

**Comment by jarrah31** [comment]
Fantastic, thank you! I'll give that a go tomorrow morning. :)

**Comment by isontheline** [comment]
Could you tell me if you can install 17.5 (892) from TestFlight ?

**Comment by isontheline** [comment]
You will need to restart the app after choosing the delay, I have made a bug

**Comment by jarrah31** [comment]
Morning! Yep, I realised it needed a restart for the change to work, but all good with 17.5 now! Thank you very much!

**Comment by isontheline** [comment]
You're Welcome!

I keep it open as I need to merge it inside 18.0 and fix above bugs

Have a nice day ☀️

**Comment by isontheline** [comment]
Merged inside 18.0

**Comment by jarrah31** [comment]
Works great in 18.0 beta, thank you!
