### ISSUE TITLE
Swipe on screen to move cursor

### ISSUE THREAD

**Issue by SJ50** [isontheline/pro.webssh.net#59]
**Describe the feature**
Swipe on screen to move cursor to go left and right. Up and down for scrolling terminal up and down.

**Comment by isontheline** [comment]
Good one!

Now planned.

☀️Have a nice day

**Comment by isontheline** [comment]
From @sgberman issue #64 :

> Can you make the touch screen emulate a mouse? This feature would be useful when editing a file in VIM to allow you to move the cursor to the location you point at with your finger thereby allowing for faster text editing.

**Comment by liqimai** [comment]
If so, we will have full mouse support when using vim or tmux.

**Comment by mbierman** [comment]
Awesome! I look forward to this. Thank you!
