### ISSUE TITLE
3-rd keyboard do not function

### ISSUE THREAD

**Issue by antenna2008** [isontheline/pro.webssh.net#591]
# Bug descriptio

3-rd party keyboard do not function
ios 15.5

# Screenshots
![35B1674C-5277-400C-AFBA-12E910BB3B99](https://user-images.githubusercontent.com/22744518/162021571-bee89bfe-3843-4698-8c4e-9942ac27af2c.jpeg)

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by isontheline** [comment]
Hello @antenna2008 👋

Thank you so much for your issue!
I'm merging it inside : #545 

Have a nice day ☀️
