### ISSUE TITLE
Unable to select first character on the left side of the screen (macOS)

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#592]
# Bug description
If I try to highlight a line using my cursor, I can't select or start highlighting from the first character on that line because the text is right up against the edge of the window, resulting in the cursor turning into a window-resize icon.

The workaround is to start highlighting the text from the end of the line to the beginning.

# Screenshots
<img width="78" alt="image" src="https://user-images.githubusercontent.com/3072303/162067121-4368ae36-6830-41b5-a3f5-02bbeda6b3ef.png">

If possible, could there be a small margin around the edge of the window please, as seen in this example:
<img width="128" alt="image" src="https://user-images.githubusercontent.com/3072303/162067586-3441cce0-dc2c-4325-ab0d-a638ae518168.png">

**Comment by isontheline** [comment]
WebSSH 18.0 (available in a few days) already contains a possible fix :
<img width="704" alt="image" src="https://user-images.githubusercontent.com/44212923/162188184-f352ef94-bc91-40ca-b05e-cfdfc006a11a.png">

I don't know if the padding I have added (3px) will be sufficient in your case. On my side I can now select text from the left (before that I wasn't able to do so).
I will let you know when available.

**Comment by jarrah31** [comment]
That looks great, thanks!

**Comment by isontheline** [comment]
@jarrah31 
WebSSH 18.0 **Beta** should be released this week-end 🤞
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/44212923/168161905-d245cfca-bf73-493a-b318-c96f49fe1272.png">

**Comment by jarrah31** [comment]
Looking forward to it, thanks for the tip!

**Comment by isontheline** [comment]
Hello @jarrah31 👋

WebSSH 18.0 RC1 is now available on TestFlight

**Comment by jarrah31** [comment]
Works great in 18.0 beta, thank you!
