### ISSUE TITLE
Unable to grab or move the scroll bar in macOS

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#599]
# Bug description
I can see a scroll bar in the macOS version, but I'm unable to grab it with the mouse (left-click) so that I can quickly scroll over historic lines. If I then scroll with the mouse wheel, the scroll bar disappears off the bottom of the window.

It may also be useful to have a scroll bar in the iPad version so that we can quickly see historic info there too?

# Screenshots
<img width="103" alt="image" src="https://user-images.githubusercontent.com/3072303/164537458-70a89c40-b940-414b-ae07-014e5b4edb58.png">

Thanks as always!

**Comment by jarrah31** [comment]
Relating to scrolling on the iPad, I find there's a slight delay between swiping up or down on the screen and the text then moving along with my finger. It's not a problem, I just wanted to check if it's normal and not something specific to me? I guess it's a limitation of the rendering engine?

**Comment by isontheline** [comment]
Thanks for your feedback @jarrah31 !

About the scrollbar, I will check if it's related to https://github.com/xtermjs/xterm.js/issues/512 or related to a bad WebSSH implementation of Xterm.js

On iOS and iPadOS there are some glitches on the Xterm.js rendering engine :
* https://github.com/xtermjs/xterm.js/issues?q=is%3Aissue+is%3Aopen+touch+scroll
* https://github.com/xtermjs/xterm.js/issues/3357

**Comment by jarrah31** [comment]
Thanks Arnaud!

Related to history, is there an option to specify how many lines of text is available in the scroll buffer? I can't seem to find this option and I don't seem to be able to scroll too far back in my terminal windows? I'll be happy to raise a new feature request if not.

Thanks.

**Comment by isontheline** [comment]
@jarrah31 A free number input field as the scroll buffer size?

Yes please raise a feature request as I don't find this request inside opened issues.

**Comment by isontheline** [comment]
For @isontheline work :
* http://github.com/xtermjs/xterm.js/issues/2757
* http://github.com/microbit-foundation/python-editor-next/issues/380

**Comment by isontheline** [comment]
I'm working on it since a few days.
I need to implement my own scrollbar in order to have a compatibility against macOS / iOS / iPadOS.
First beta should be available next week.

**Comment by isontheline** [comment]
@jarrah31 First attempt of a custom scrollbar available on the latest beta release

**Comment by isontheline** [comment]
Custom scrollbar now available inside the latest beta release

**Comment by jarrah31** [comment]
Sorry for my delayed response, I missed the notification! :blush:

This works great, thank you very much! So much easier to navigate than before! :tada:

**Comment by isontheline** [comment]
@jarrah31 Thank you a lot for your feedback and your support 🙏
