### ISSUE TITLE
Terminal : Ability to choose a custom monospaced font

### ISSUE THREAD

**Issue by thaihugo** [isontheline/pro.webssh.net#60]
Hi,

A neat addition would be support for additional font, either by adding them as CSS font, or using the additional one installed as a profile from iOS (Using ifont for example).
Currently, other SSH programs have this support, so you can use for example a nerd font or a powerline font to display specific terminal symbols. If I open the same session under webssh, I dont get the proper characters.
The terminal can be configured by some parameters, and I guess there is a CSS defining the view. Maybe adding a font selector there would be the right place in the interface?

Thanks

Hugo

## For @isontheline work
* https://github.com/franklynw/FontPicker
* https://github.com/SwapnanilDhol/SUIFontPicker
* https://github.com/antranapp/google-font-picker-swift-combine
* https://swapnanildhol.blog/blog/tech/2021-03-24-swiftui-custom-fontpicker

**Comment by isontheline** [comment]
Hi @thaihugo !

Thanks for this neat feature request 👍 

In order to implement custom fonts I first need to upgrade the terminal engine on issue #21

**Comment by isontheline** [comment]
# In-App Purchase
- [ ] (Tier 1) Additional fonts for the SSH terminal #23

**Comment by thaihugo** [comment]
Thanks. If you want to see the full extend of font support (which I'm not asking but for you to know), you can have a look at the Iosevka font (https://github.com/be5invis/iosevka), ligatures Support  (for developers on vim for example to get special symbols with 2 caracters), vim-powerline like in this example if I launch vim:
![413DCA41-C19A-4D1C-9AF7-71A673FCB643](https://user-images.githubusercontent.com/17780673/92209957-975a3d00-ee96-11ea-992e-31e104be247f.jpeg)
That example would also ask for true color terminal however, which is another step.

**Comment by isontheline** [comment]
Thank you a lot for adding additional knowledge!

**Comment by isontheline** [comment]
As #21 is now done for the terminal engine, I will now work on adding additional fonts.

I will start with https://github.com/mshaugh/nerdfont-webfonts because I use hterm for the terminal rendering engine.

**Comment by thaihugo** [comment]
This is a good font that will cover most ground. Thanks

**Comment by isontheline** [comment]
Hello @thaihugo 👋

Please try the latest WebSSH 15.0 Beta Release : 
https://testflight.apple.com/join/QSrBK59z

P10K font have been included.

Have a nice day ☀️

**Comment by isontheline** [comment]
@thaihugo Does this issue is always needed since https://github.com/isontheline/pro.webssh.net/issues/97 has been done?

**Comment by thaihugo** [comment]
Hello @isontheline,

#97 has been a great evolution as having symbols definitely help for using many programs as special shell prompts and vi with specific configurations.

My request was more to be able to add any font or at least some fonts as the result can differ depending on the font. Let me show you an example from blink and from webssh on the following post.

I perfectly understand if you want to close this request but the spirit of what I asked was to be able to add any user selected font as they can differ greatly between versions

**Comment by isontheline** [comment]
Hello @thaihugo 👋

Thank you a lot for your feedback 🙏

It will help me to prioritize next releases.

**Comment by isontheline** [comment]
From **Jeff** by *email* :

> Hi Arnaud, 
> 
> Coming from a Mac and using Terminal a lot I have been accustomed to the Homebrew and Pro profiles which use Andale Mono 12 and Monaco 11, respectively. I would also like to be able to change the size and color as well as antialiased or not. I usually prefer non antialiased green text on a solid black background. Screenshots attached. 
> 
> Thanks! 
> 
> Jeff
![image](https://github.com/isontheline/pro.webssh.net/assets/44212923/4475148d-252f-453b-8082-fb7ba084217d)
![image](https://github.com/isontheline/pro.webssh.net/assets/44212923/6eee6fb3-2b6d-401b-a4d6-4b535d963af1)

**Comment by isontheline** [comment]
Using an app like "iFont" you can now install monospaced additional fonts and use them inside a custom theme of WebSSH.

Available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
