### ISSUE TITLE
Hang on disconnect (Windows 10 with Ubuntu WSL)

### ISSUE THREAD

**Issue by jgreth0** [isontheline/pro.webssh.net#600]
The app hangs every time I hit the 'eject' button.

**Comment by isontheline** [comment]
Does it crashes after some time?

**Comment by jgreth0** [comment]
> Does it crashes after some time?

No. I let it sit for a few minutes and it remains unresponsive.

I have since tried it a few more times and it sometimes does hang and sometimes does not hang. I can't determine a pattern. It happens with both windows and Linux targets.

**Comment by isontheline** [comment]
Are the hang happen when using WiFi or cellular?

Have you some time to extract logs?
In order to enable verbose logging you can follow the steps :
1. iOS Settings
2. WebSSH
3. Settings
4. Log Level > Verbose
5. Restart WebSSH
6. Reproduce your action
7. Find the log files inside iOS > Files > WebSSH

**Comment by jgreth0** [comment]
The relevant log section:
```
2022/04/23 11:39:55:606 [VERBOSE] Want to connect with a Private Key
2022/04/23 11:39:55:607 [DEBUG] Private Key is encrypted : 0
2022/04/23 11:39:55:607 [VERBOSE] Load Private Key in OpenSSH Format
2022/04/23 11:39:55:607 [VERBOSE] Launching connection...
2022/04/23 11:39:55:608 [VERBOSE] Connecting to SSH...
2022/04/23 11:39:55:608 [VERBOSE] Launching connection with block...
2022/04/23 11:39:55:609 [VERBOSE] Won't dismiss prompt because no one is displayed.
2022/04/23 11:39:55:624 [DEBUG] No SOCKS Tunnel launched. SSH connection will be established without any SOCKS hostname.
2022/04/23 11:39:55:817 [DEBUG] Connected to : *********
2022/04/23 11:39:55:821 [DEBUG] Authentication using login/privatekey
2022/04/23 11:39:55:883 [VERBOSE] Connecting with terminal type : xterm-color
2022/04/23 11:39:55:900 [VERBOSE] Launching check data notifier
2022/04/23 11:39:56:011 [DEBUG] Dismissing prompt...
2022/04/23 11:39:58:061 [VERBOSE] Is now connected to SSH, displaying terminal
2022/04/23 11:39:58:960 [VERBOSE] Did begin edit, will place accessory form
2022/04/23 11:39:59:508 [DEBUG] Keyboard is in attached mode.
2022/04/23 11:40:00:463 [VERBOSE] Closing connection...
2022/04/23 11:40:00:565 [DEBUG] Will end edit on scene F0533578-128F-4D66-993D-F1E1828BA1CB
```
The log file ends there.

**Comment by jgreth0** [comment]
Also, I have this issue on Wi-Fi. My server isn't exposed to the internet so I can't test the cellular path.

**Comment by jgreth0** [comment]
Also, I see the issue on iPad and iPhone.

**Comment by isontheline** [comment]
@jgreth0 Thank you a lot for your feedback!

That's strange. 

I'm not able to reproduce yet.

* Which build number are you using? (Press WebSSH Gear, build is at bottom)
* Which iOS version are you using?
* Have you purchased WebSSH Pro? (I don't want you to buy it, I just ask because there is a check when disconnect)

**Comment by jgreth0** [comment]
> Which build number are you using? (Press WebSSH Gear, build is at bottom)

17.4.887 @ Mar 23 2022 23:36:40 (same version on both iPhone and iPad).

> Which iOS version are you using?

iPad 8th gen is software version 15.4.1. iPhone SE is also 15.4.1.

> Have you purchased WebSSH Pro? (I don't want you to buy it, I just ask because there is a check when disconnect)

Yes :) The log has this after a successful disconnect:

```
2022/04/23 11:39:07:551 [DEBUG] Launch_APP_Count_17.4 : 9
2022/04/23 11:39:07:551 [DEBUG] Launch_APP_Count : 23
2022/04/23 11:39:07:572 [INFO] No prefered language. Use system language if available.
2022/04/23 11:39:07:582 [DEBUG] Locale Identifier : en_US
2022/04/23 11:39:07:582 [DEBUG] Device language : en
2022/04/23 11:39:07:582 [INFO] Language bundle is not loaded. Will load this bundle : en
2022/04/23 11:39:07:683 [DEBUG] Application did become active
2022/04/23 11:39:07:686 [DEBUG] No pin code set. WebSSH won't be locked.
2022/04/23 11:39:10:478 [VERBOSE] Want to connect with a Private Key
2022/04/23 11:39:10:494 [DEBUG] Private Key is encrypted : 0
2022/04/23 11:39:10:495 [VERBOSE] Load Private Key in OpenSSH Format
2022/04/23 11:39:10:495 [VERBOSE] Launching connection...
2022/04/23 11:39:10:495 [VERBOSE] Connecting to SSH...
2022/04/23 11:39:10:495 [VERBOSE] Launching connection with block...
2022/04/23 11:39:10:497 [VERBOSE] Won't dismiss prompt because no one is displayed.
2022/04/23 11:39:10:524 [DEBUG] No SOCKS Tunnel launched. SSH connection will be established without any SOCKS hostname.
2022/04/23 11:39:10:723 [DEBUG] Connected to : ******
2022/04/23 11:39:10:726 [DEBUG] Authentication using login/privatekey
2022/04/23 11:39:12:945 [VERBOSE] Connecting with terminal type : xterm-color
2022/04/23 11:39:12:961 [VERBOSE] Launching check data notifier
2022/04/23 11:39:13:071 [DEBUG] Dismissing prompt...
2022/04/23 11:39:15:159 [VERBOSE] Is now connected to SSH, displaying terminal
2022/04/23 11:39:16:236 [VERBOSE] Did begin edit, will place accessory form
2022/04/23 11:39:16:834 [DEBUG] Keyboard is in attached mode.
2022/04/23 11:39:17:988 [VERBOSE] Closing connection...
2022/04/23 11:39:18:026 [VERBOSE] Connection closed.
2022/04/23 11:39:18:089 [DEBUG] Will end edit on scene 3E004F30-8066-4BD1-A45E-29B10CE4FA63
2022/04/23 11:39:18:538 [VERBOSE] Saving (pushAllowed == 1) object 87F9D587-DED7-4619-91AE-4C8560DA273E to local database
2022/04/23 11:39:18:549 [VERBOSE] Won't push to cloud because iCloud is disabled
2022/04/23 11:39:18:551 [DEBUG] Launch_SSH_Count_17.4 : 8
2022/04/23 11:39:18:551 [DEBUG] Launch_SSH_Count : 24
2022/04/23 11:39:18:570 [VERBOSE] IAP already purchased : com.webssh.pro.unlimited
2022/04/23 11:39:18:571 [VERBOSE] Terminal view will disappear : remove all observers
```

My initial guess was that a TCP FIN/ACK got dropped at the end, but I can reproduce often enough that this seems unlikely (I would expect the packet drop rate to be very low within my home LAN). Also my omada controller isn't reporting any anomalies/alerts that would indicate that dropped packets are especially likely. My other guess is that there is something that changed in ios 15.4.1, since that was the most recent change. However, I suspect this would be a widespread issue if it were caused by the ios update.

**Comment by isontheline** [comment]
Thank you a lot for your strong feedback 👍
And thank you for your purchase 🙏

I'm also on 15.4.1 both iPhone / iPad.

If you don't press the disconnect HUD menu but use Ctrl-D, does the hang also happens at same rate?

**Comment by jgreth0** [comment]
Out of 10 tries on each device (to a mix of servers), ctrl-d has never failed.

I'm also now noticing that the eject button fails nearly every time when I'm connected to a windows server and almost never when I'm connected to a linux server.

On windows, I am using the built-in sshd server with bash (Ubuntu WSL) as my default shell (I followed this guide for setup: https://www.hanselman.com/blog/the-easy-way-how-to-ssh-into-bash-and-wsl2-on-windows-10-from-an-external-machine ). This would not be the first issue I've had with WSL :/ .

**Comment by isontheline** [comment]
Great feedback!

I will try to replicate the same setup as you in order to find and make a fix.

**Comment by isontheline** [comment]
Perhaps I should send always `Ctrl-D` before disconnecting the SSH session?

**Comment by isontheline** [comment]
@jgreth0 Do you think that `Ctrl-D` should be fired when using the eject button?

**Comment by jgreth0** [comment]
That sounds improper. It should work if there is nothing running. However, if you have a frozen application on the server and are using the eject button to kill the parent processes, ctrl-d wouldn't help.

My expectation is that when the eject button is pressed:
- The client sends SSH_MSG_CHANNEL_CLOSE.
- The client waits for SSH_MSG_CHANNEL_CLOSE back.
- The client sends TCP-FIN. (fclose?)
- The client returns to the main screen.

When ctrl-d is sent and there is no running application:
- The server sends SSH_MSG_CHANNEL_CLOSE.
- The client sends SSH_MSG_CHANNEL_CLOSE back.
- The client sends TCP-FIN. (fclose?)
- The client returns to the main screen.

I think that windows starts WSL on demand and terminates WSL immediately after it receives SSH_MSG_CHANNEL_CLOSE. My hypothesis is that the WSL process may be destroyed before there is time for a graceful disconnect process. The client is waiting for something that isn't sent before WSL is terminated.

If I can find some time I can try to take some traces with wireshark and see if there is any detectable pattern like this.

**Comment by isontheline** [comment]
@jgreth0 Does WebSSH 18.0 RC1 fixes the trouble?

https://testflight.apple.com/join/QSrBK59z

**Comment by jgreth0** [comment]
18.0 RC1 does not fix the issue. However...

I did use wireshark to capture packets this morning. In order to get a clean trace, I tried opening a connection, waiting five seconds, and then hitting the eject button. My idea was to isolate just what was happening in the disconnect phase. When I did this, I was not able to reproduce the issue. I am only able to reproduce the issue by hitting the eject button immediately after the prompt opens in the client.

Interestingly, I do see some encrypted packets being exchanged for a few seconds after the prompt opens in the client. Here is my new hypothesis: the client does not disconnect gracefully if it has not fully quiesced after the connection is established. For some reason, it takes longer to quiesce when connected to my windows machine (probably related to the WSL startup latency).

Unfortunately, wireshark doesn't (cant) support decrypting ssh traffic even with the client and server keys, so I can't see what is being exchanged in these few seconds after the prompt opens.

When I was attempting to reproduce the issue in the past, I was always hitting the eject button as fast as possible to get lots of trials. I probably originally hit this issue because I often hit the wrong server and immediately disconnect to get back to the menu and select the correct server.

**Comment by isontheline** [comment]
Thank you @jgreth0 for your strong feedback 👍

Disconnect should already be in a detached thread so "shouldn't" freeze the UI.
I will try another fix asap.

**Comment by jgreth0** [comment]
> Disconnect should already be in a detached thread so "shouldn't" freeze the UI.

That sounds backwards to me. If disconnect operates independently from the UI thread, it may send SSH_MSG_CHANNEL_CLOSE while the UI is in the middle of an operation. This would cause the server to disregard the second half of the operation in the UI thread. The UI thread would then hang waiting for the server.

**Comment by isontheline** [comment]
WebSSH 21.8.1069 should address this issue : https://testflight.apple.com/join/QSrBK59z
