### ISSUE TITLE
Ability to define scroll buffer size

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#605]
# Feature description
Please could you implement the ability to define how many lines of scroll buffer is retained (as a free number input field) in an SSH session.
Thanks.
(from https://github.com/isontheline/pro.webssh.net/issues/599#issuecomment-1106728568)

**Comment by isontheline** [comment]
No problem I will implement this feature 👍

**Comment by jarrah31** [comment]
Hi Arnaud, just thought I'd drop by to see if you have a rough eta for when a larger scroll buffer could be implemented please? The current buffer is quite limited on macOS - there are many times when tailing logs that I've been unable to go back further than a few pages, so I end up using iTerm more often than not unfortunately. 
Thanks.

**Comment by isontheline** [comment]
Hi @jarrah31 👋

Thank you for the reminder!

I will try to add the scroll buffer setting before July 21 (next week max).

**Comment by isontheline** [comment]
Beta will be available in a few hours.
Scrollback rows is a defined number yet (as I have some problems with iOS settings and free fields) :


![Image](https://user-images.githubusercontent.com/44212923/179370959-a34eaebc-0206-42f0-b7ed-0937c832a191.png)

**Comment by isontheline** [comment]
@jarrah31 The setting could be changed inside iOS > Settings > WebSSH > SSH > Scrollback Rows

Available inside the latest beta release

**Comment by jarrah31** [comment]
Fantastic, thank you Arnaud, I will test this later today.

**Comment by jarrah31** [comment]
It works great, thank you! (tested on macOS via WebSSH Menu -> Preferences. No restarted needed.) 

Just out of interest (related to the linked comment in this thread's first post), have you had any luck working out why the scroll bar doesn't work please? You thought it might be related to xterm.js?

**Comment by isontheline** [comment]
@jarrah31 I've just upped #599 and I will work on it soon

Sorry for the long delay resolution of your issues.

**Comment by jarrah31** [comment]
No problem at all, I know you have a day job too and that you can't spend all your spare time on this. I'm happy that they are done when you are able to.

**Comment by isontheline** [comment]
Thank you so much @jarrah31 🙏

But don't forget to reming me again if you see any too long delay 😉
