### ISSUE TITLE
SSH tunnel as a proxy server for a SOCKS client (equivalent of ssh -D)

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#607]
A great addition would be allowing opening the ssh tunnel as a proxy server for a SOCKS client (equivalent of ssh -D).

It would allow users to connect to and route all traffic through their home server when abroad to access local services blocked outside the country. Basically a free VPN!

I can't see this is possible on the current version, but please let me know if I've missed something.

Many thanks,

Paul.

_Originally posted by @blendexperts in https://github.com/isontheline/pro.webssh.net/discussions/606_

**Comment by rikhtehgaran** [comment]
Hi i have same problem thanks for adding this feature

**Comment by isontheline** [comment]
You can now enable the SOCKS server inside WebSSH.

How to do?
1. Allow WebSSH to accept external connections : iOS Settings > WebSSH > Tunnel > Incoming Connections Strategy > Accept both local and remote connections
2. (Optional) Enable VPN-Over-SSH (so you will be able to switch between apps on your iDevice)
3. (Optional) Enable WebSSH Settings > Keep Device Awake (in order to don't sleep your device)
4. Inside port forwarding use this : `*:1985` replace 1985 by the SOCKS port you want to listen to (it will be your SOCKS server port for your other devices)
5. Launch your tunnel
6. (Optional) If you know your device IP address skip this step. Launch mashREPL and get your local IP address with this command : `ifconfig`
7. On your other devices use a SOCKS configuration like this : `192.168.0.18:1985` where 192.168.0.18 is your iDevice and 1985 is your SOCKS server port

**Comment by rikhtehgaran** [comment]
I think these settings is for converting my IOS to an ssh server, and then I connect from another device to my IOS using socks. and 192.168.0.18 is the local IP of my IOS, and  1985 is the port of SOCK on my ios. am I right?
But I repeat again, I have a Linux server somewhere with an IP and port, so I ssh to my server. now I want to tunnel all traffic of ios over this ssh connection
So I put some port (4545) in port forwarding as you mentioned:
![image](https://user-images.githubusercontent.com/3824913/193218265-0616ab90-f29d-431a-863e-2a410b64e664.png)

I put this setting in telegram, for example as socks connection but no success and it still in connection:
![image](https://user-images.githubusercontent.com/3824913/193219660-f709c2b5-0272-4ad4-8c07-49a81f3a8866.png)

can you help me with more details if webssh support this feature?

**Comment by isontheline** [comment]
You're right WebSSH will act as a SOCKS proxy between telegram and your SSH server.

Please check that you allow outside connections on your Tunnel : 

Allow WebSSH to accept external connections : iOS Settings > WebSSH > Tunnel > Incoming Connections Strategy > Accept both local and remote connections

Outside connections are also from within your device from other apps.

Could you try?

**Comment by rikhtehgaran** [comment]
Hi i can find this: Allow WebSSH to accept external connections : iOS Settings > WebSSH > Tunnel > Incoming Connections Strategy > Accept both local and remote connections see here:
![AAcEQvcHFU](https://user-images.githubusercontent.com/3824913/193243941-8128e737-ab44-4980-9117-1f66a18f3d1a.jpg)

**Comment by isontheline** [comment]
You need to use the latest beta release :

https://testflight.apple.com/join/QSrBK59z

The option is on the bottom when done
