### ISSUE TITLE
RSA: Not a recognized key type 

### ISSUE THREAD

**Issue by dxniel7402** [isontheline/pro.webssh.net#61]
Hello,
I want to connect to my Server with an RSA Key, but the App can‘t. See at the screenshot below.

The key was generated in GitHubs Bash Tool. It‘s the same key like i use it in putty - just copy paste it.

iOS 14 Public Beta 7 - iPhone XS Max

![D90D3CBF-3EC5-4AE2-93AF-49D49E160B4A](https://user-images.githubusercontent.com/61451617/92304234-66543800-ef7c-11ea-98f6-230af07c6bec.jpeg)

**Comment by isontheline** [comment]
Hello @dxniel7402 

* Can you confirm me that you use the private key and not the public one?
* Can you share an **example** and **unused** private key? If not please provide here how you generate the private key (the full command line)

**Comment by isontheline** [comment]
@dxniel7402 I'm closing this issue 😕
Please reopen this issue as soon as you can share detailed reproduce steps.

☀️ Have a nice day

**Comment by cuongbn** [comment]
I got the same error as above. I have ppk putty file, how can I use the private key in the software.
Where can I get my rsa private key?

**Comment by isontheline** [comment]
Hello @cuongbn 👋

* Can you share an **example** and **unused** private key? If not please provide here how you generate the private key (the full command line)

Have a nice day ☀️

**Comment by nqnx** [comment]
Hello Arnaud @isontheline 

Attached you find a ed25519 test public / private key pair.

Thanks a lot for the work.

[public.txt](https://github.com/isontheline/pro.webssh.net/files/6351164/public.txt)
[private.txt](https://github.com/isontheline/pro.webssh.net/files/6351165/private.txt)

**Comment by isontheline** [comment]
Hello @nqnx 👋

That's perfect!

I will try this key pair and will fix this bug as soon as possible.

**Comment by isontheline** [comment]
@nqnx Could you test the latest beta please ?
https://testflight.apple.com/join/QSrBK59z

☀️ Have a nice day

**Comment by nqnx** [comment]
Hello @isontheline,
The latest beta version works with those keys. Thanks a lot!

Maybe an idea of improvement:
Remove "is encrypted" and rename "password" to "passphrase", automatically set the option "is encrypted" on in the background when "passphrase" is filled out.

**Comment by isontheline** [comment]
Hello @nqnx 👋

Thank you a lot for your feedback!

I'm creating a new issue for your idea :
