### ISSUE TITLE
Sidebar : show tags and groups

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#621]
# Request
Following on from [this reply](https://github.com/isontheline/pro.webssh.net/issues/617#issuecomment-1127007328) in another issue.

I would like to add my support for the introduction of a sidebar in the macOS and iPadOS versions of WebSSH please.

I think it would be a great place to list all the SSH, SFT, and Tunnel connections in a collapsable menu system, similar to how Photos works in macOS and iPadOS. 
Perhaps the inventory items (such as SSH, SFT, Tunnel) could be expandable like this? The first level expansion in SSH would show Group Names, with the next level showing Connections.
![image](https://user-images.githubusercontent.com/3072303/168655179-e0f2e9b7-80a0-473e-94b6-c1a5a01fc082.png)

Here is a quick mockup in Photos with albums representing Connections and folders as Group Names. 
<img width="244" alt="image" src="https://user-images.githubusercontent.com/3072303/168650659-75941d86-d9c1-403c-8534-6ff2bab45d42.png">

However I do see that the current layout is similar to how the Files app on the iPad works, with the main sections on the left such as "On My iPad", and all the folders and files in the main right-hand screen.

It's a tricky decision to make - either method seems to work well, though I would probably prefer the Photos method. :)

**Comment by jarrah31** [comment]
A global search field is a great idea! Though it feels better if it was perhaps visible all the time rather than only appearing when selecting sftp / ssh / tunnel, similar to the safari sidebar as shown below?

Is it possible to have the search field dynamically update / filter the list of Connections in the same way that Safari bookmarks works on the iPad? e.g.
<img width="320" alt="image" src="https://user-images.githubusercontent.com/3072303/168668823-2ec8aa49-33cd-45d7-b075-aef116791025.png">

**Comment by isontheline** [comment]
Great!

I was looking for the search field on Safari macOS but it's on iOS 😅

Yes could be great in that way

**Comment by jarrah31** [comment]
It may be worth including the New Connection button in the sidebar when all the connections are listed there too:
![image](https://user-images.githubusercontent.com/3072303/168670117-6e1ab201-8bd9-490b-9d06-313f2a315a30.png)

Also, is it possible to implement the ability to see what a button does when hovering the mouse over it? This would only be applicable to the macOS version though. e.g. this shows "Create a new tab". I thinking it could be used for "New Connection", mashREPL, Settings, Disconnect, Snippets, etc.
<img width="115" alt="image" src="https://user-images.githubusercontent.com/3072303/168670619-d7d2bde4-2b72-4e79-b4da-7d2002115891.png">
Just regarding the screenshot above, it seems the macOS version displays two sets of "+" to create a new tab.

**Comment by isontheline** [comment]
> It may be worth including the New Connection button in the sidebar when all the connections are listed there too

You're right

> Also, is it possible to implement the ability to see what a button does when hovering the mouse over it? This would only be applicable to the macOS version though. e.g. this shows "Create a new tab". I thinking it could be used for "New Connection", mashREPL, Settings, Disconnect, Snippets, etc. 

I have forgotten these tooltips, that's right

> Just regarding the screenshot above, it seems the macOS version displays two sets of "+" to create a new tab.

I need to disable the lower right "+" because I would like to be "same" as Safari :
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/44212923/168673473-ac545621-495a-4054-bb73-4b4a6b5651e8.png">

**Comment by jarrah31** [comment]
Thank you!

> I need to disable the lower right "+" because I would like to be "same" as Safari :

Yes good idea, makes sense to mimic the same method.

**Comment by isontheline** [comment]
An UI mockup idea from *Jorge* (by email) :

<img width="738" alt="image" src="https://user-images.githubusercontent.com/44212923/192369214-4e599054-00dd-4c17-b631-f892d123c325.png">

**Comment by isontheline** [comment]
Sidebar now displays groups and tags : https://testflight.apple.com/join/QSrBK59z
