### ISSUE TITLE
Map touch to mouse events in ssh

### ISSUE THREAD

**Issue by sgberman** [isontheline/pro.webssh.net#64]
**Describe the feature**
Can you make the touch screen emulate a mouse?  This feature would be useful when editing a file in VIM to allow you to move the cursor to the location you point at with your finger thereby allowing for faster text editing.

**Comment by isontheline** [comment]
Yes it should be possible to map touch to mouse events and it will be great I agree 👍

**Comment by isontheline** [comment]
Finally it's a duplicate of #59

I'm closing this issue and will do the work on #59

**Comment by isontheline** [comment]
Closing this in favor of https://github.com/isontheline/pro.webssh.net/issues/59
