### ISSUE TITLE
SFTP : File extention not recognized in 18.2

### ISSUE THREAD

**Issue by RealKindOne** [isontheline/pro.webssh.net#641]
# Bug description

iOS 15.5 / iPhone 11 

WebSSH 18.2 (Paid version)

WebSSH no longer recognizes files?

Previous version 18.0 I could select a file with the .mkv extension and I would have a option to download when I tap on it. Now I just get "Extension not recognized" when I tap on the file.

I now have to hold my finger on the file for the option to download it. I think this is a bug since the behavior is different.

I have uninstalled, restarted iPhone, installed, added back my server, and I still have this issue.

The icons are missing on the save section.

# Screenshots
Missing buttons.

test.mkv:
![IMG_0375](https://user-images.githubusercontent.com/20209685/171525771-108beddf-fef4-4bff-a97b-0095216b068a.PNG)

7z2107.exe (7-Zip):

![IMG_0376](https://user-images.githubusercontent.com/20209685/171525774-5a153044-d5ba-4868-9610-1a9b5e3143b4.PNG)

# Steps to reproduce
1. On a remote server  (I used Debian) ```touch test.mkv```.
2. SFTP into remote server.
3.  Select the test.mkv
4.  "Extension not recognized". -- This is supposed to show a option to download.
5. Click Cancel.
6. Click on the test.mkv and hold. 
7. Click Download.
9. Missing button when the download is finished for where to save the file.

Update 1: fixed filename for one of the images.

**Comment by isontheline** [comment]
Hello @RealKindOne 👋

OK I will make an improvement asap about the popup dialog to appear when simple tap on a file.

> Update 1: fixed filename for one of the images.

Does it fix `Missing button when the download is finished for where to save the file.`?

**Comment by RealKindOne** [comment]
> > Update 1: fixed filename for one of the images.
> 
> Does it fix `Missing button when the download is finished for where to save the file.`?

No. The "Update" was me editing the post to fix a typo I made. Its a old habit of mine to add a update note at the bottom of  a issue whenever I alter a comment.

**Comment by isontheline** [comment]
@RealKindOne Please find a fix for #652 : https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
@RealKindOne This issue is now fixed inside the latest beta release : 
https://testflight.apple.com/join/QSrBK59z

Have a nice day ☀️
