### ISSUE TITLE
German translation „paste“ —> „einfügen“

### ISSUE THREAD

**Issue by SeebM** [isontheline/pro.webssh.net#643]
# Bug description
The right german translation of „paste“ is „einfügen“ instead of „Kleister“

**Comment by isontheline** [comment]
Hello @SeebM 👋

Thank you so much 🙏

I will fix it asap.
If you want to update other translation strings youself, you can do it here : https://poeditor.com/join/project/KXbsLC7YZa

Have a nice day ☀️

**Comment by SeebM** [comment]
Hi @isontheline,
Wow, thanks for the quick response. I love your app! Will definitely have a look on the translation. Is there a trick to get acess? I can not see the project on my iphone.

**Comment by isontheline** [comment]
You're Welcome!

Ooops you're right I've made an config error.
You can now try to enroll : https://poeditor.com/join/project/KXbsLC7YZa

Thank you 🙏

**Comment by isontheline** [comment]
@SeebM It's now available on TestFlight : https://testflight.apple.com/join/QSrBK59z

Have a nice day ☀️
