### ISSUE TITLE
Google Web Fonts

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#657]
# Feature description
Allow user to choose from [Google Web fonts](https://fonts.google.com/). This would be really awesome and "fit" the "web" name. :) 

options: 
1. Allow user to add a URL for the Google Font they want (a little wonky)
2. Allow users to choose from 5-10 selected fonts. 
3. Use 2 for default values and allow user to use a URL to add "custom" choices. 

# Screenshots / Draws
_If applicable, add screenshots and/or draws to help explain your feature request_

**Comment by isontheline** [comment]
Yes you're right, and it will let to close https://github.com/isontheline/pro.webssh.net/issues/60 also

**Comment by mbierman** [comment]
Wonderful.apologies for the duplication.

**Comment by isontheline** [comment]
Some fonts will break the terminal columns alignment.
Does it matter?

**Comment by mbierman** [comment]
@isontheline As long as there are monospaced font options that don't break anything, it is fine to have some that do. People can choose if that matters. See macOS terminal 

![image](https://user-images.githubusercontent.com/1205471/185260689-f635a531-2aba-42b0-bd1d-5f5bc4f41ec9.png)

**Comment by isontheline** [comment]
You're right @mbierman 
Thank you a lot for your feedback 🙏

**Comment by isontheline** [comment]
Several Mono Nerd Fonts will be added soon :
* https://github.com/ryanoasis/nerd-fonts/releases

**Comment by isontheline** [comment]
I'm closing this issue.

Custom fonts can be imported by using an app on the App Store (iFont eg) :
1. Import the font on the device (must be MONO)
2. Use the font by creating a new theme inside WebSSH
