### ISSUE TITLE
Unwelcome Open connections... 

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#658]
# Bug description
My router detected thousands of connections to devices that it shouldn't be connecting to. Strange thing: I looked at the connections and they are all devices that are in my WebSSH servers. As soon as I exit webssh, the connections stopped. I've included some nettop for webSSH when no connections were supposed to be open. 

Thing is, I didn't have any open connections to those servers during the time. WebSSH is opening connections to devices for no apparent reason. 

This is deeply troubling for any number of reasons. No connection should ever be attempted unless the user asks for it. 

[test.txt](https://github.com/isontheline/pro.webssh.net/files/8934866/test.txt)

**Comment by isontheline** [comment]
@mbierman Just disable "monitor server availability".

WebSSH will never make any connection without user consent or enabling this feature on your side.

**Comment by mbierman** [comment]
Do you mean checking hosts availability? I do t remember turning that on. What is the default value? I strongly suggest adding a warning about what that means.

**Comment by isontheline** [comment]
Yes "checking hosts availability" one.

It's disabled by default since the begin.

**Comment by mbierman** [comment]
So it is off and yet it is still causing connections.

**Comment by isontheline** [comment]
Please post verbose logs of WebSSH.
All WebSSH tasks are logged.

In order to enable verbose logging you can follow the steps :
1. iOS Settings
2. WebSSH
3. Settings
4. Log Level > Verbose
5. Restart WebSSH
6. Reproduce your action
7. Find the log files inside iOS > Files > WebSSH

**Comment by isontheline** [comment]
@mbierman I've just tested nettop on my side and no open connection are there.

Perhaps you should enable then disable the option to try.

Nevertheless if the option is enabled (even if it would not) logs will tell you.

**Comment by mbierman** [comment]
Sorry for the delay. I'm still trying to reproduce. Here's an update so far: 

1. I have confirmed that all three devices I use WebSSH on have the setting disabled. Initially I thought maybe the issue was that one of the devices hadn't sync'd the setting with iCloud and so there was some interval before the iCloud sync happened and when those SSH attempts were done but now it has been long enough that the iCloud sync has to have completed and that doesn't explain why even as of a few hours ago I was seeing these SSH attempts. 
2. I notice that since that time, my router sill shows those connection attempts. 
3. When I reopen the WebSSH app and leave it for a while though, I'm not seeing those SSH attempts at the moment but as of this morning my router was showing them. 🤷🏻‍♂️ so I will continue to see if I can reproduce.

**Comment by isontheline** [comment]
Thanks for your update @mbierman 👍

Verbose logs could also be helpful to debug the trouble.

**Comment by mbierman** [comment]
I'm watching those as well. Nothing worth sharing as of now. I'll watch for a few days and if I can't reproduce will close.

**Comment by isontheline** [comment]
No problem. Thank you so much 🙏

**Comment by mbierman** [comment]
From my router: 

<img width="832" alt="image" src="https://user-images.githubusercontent.com/1205471/174708277-224cb306-bed9-4f16-8981-87be117a79f9.png">

[log-B9C534.txt](https://github.com/isontheline/pro.webssh.net/files/8945470/log-B9C534.txt)
[test2.txt](https://github.com/isontheline/pro.webssh.net/files/8945476/test2.txt)

**Comment by isontheline** [comment]
Thank you @mbierman 

Does test2.txt contains data related to WebSSH connections?
At first read I didn't see remote IP addresses.

Yes you're right, this WebSSH log file doesn't include port checks tries.

**Comment by mbierman** [comment]
@isontheline test2 is output from nettop. Again, I realize it wasn't running when router detected the connections, sorry. This is a difficult one to pin down!

**Comment by isontheline** [comment]
I'm also trying to find if there could be a bug inside the "open port" function on my side.

**Comment by mbierman** [comment]
Not seeing this anymore. I will close it and if anything ever happens we can deal with it. Thank you!

**Comment by isontheline** [comment]
Thank you @mbierman 🙏
