### ISSUE TITLE
Incorrect URL SFTP-error message

### ISSUE THREAD

**Issue by Lodan-Max** [isontheline/pro.webssh.net#660]
# Bug description
When receiving an error for sftp because of no ssh connection is made, URL for info is incorrect.

# Screenshots
![73640E58-40EC-4849-8B4A-FC8A341DC424](https://user-images.githubusercontent.com/83011549/174499413-71a81658-7bde-4481-b2cc-b96fdeec16a1.png)

# Steps to reproduce
1. Copy ssh connection from UDM Pro to SFTP
2. Try connecting
3. Receive error
4. Try to reach the webpage described on error (https://webssh.net/help/errors/ssh-sftp-error-must-first-connect-to-the-ssh-server/)
5. 404 - Not found

**Comment by Lodan-Max** [comment]
Found the error in the URL:
`https://webssh.net/documentation/help/errors/ssh-sftp-error-must-first-connect-to-the-ssh-server/`
the documentation-part went missing in the notification.

**Comment by isontheline** [comment]
Hello @Lodan-Max 👋

Thank you a lot for your issue!
You're right, I will fix the error link asap.

**Comment by isontheline** [comment]
@Lodan-Max Thank you so much for your support 🙏

![image](https://user-images.githubusercontent.com/44212923/174666267-225d1004-1084-41c1-94f9-2f6cc4c9d26a.png)
