### ISSUE TITLE
Icons in the header of an SFTP connection disapearing 

### ISSUE THREAD

**Issue by RK62** [isontheline/pro.webssh.net#670]
# Bug description
The icons in the header of an SFTP connection work, but are no longer visible when I select the connection from the sessions.
Version 19.2.924 on iPad

# Screenshots
Look at the Icons of the FTPS-Session Window on the right side:

[See attached video.](https://user-images.githubusercontent.com/39200469/177003045-27be41a5-174e-4026-8543-d8d8308dc517.mp4)

# Steps to reproduce
1. Open the SFTP session → everything works
2. Switch to an other session 
3. Switch back to SFT-Session 1. and there are no icons in the header

best regards, Ralf

**Comment by isontheline** [comment]
Hello @RK62 Ralf 👋

Thank you a lot for your feedback 🙏

I'm trying to reproduce this trouble.
I will make a fix in the next few hours.

Have a nice day ☀️

**Comment by isontheline** [comment]
I'm a bad guy :
<img width="365" alt="image" src="https://user-images.githubusercontent.com/44212923/177013958-9884328e-6004-4ba1-be26-76786ac59632.png">

Fix will be available in a few minutes

**Comment by isontheline** [comment]
@RK62 Please download the TestFlight builds here : 
https://testflight.apple.com/join/QSrBK59z

You will receive a notification when the new build will be ready

**Comment by RK62** [comment]
Works fine, have a nice weekend!
best regards, Ralf

Arnaud Mengus ***@***.***> schrieb am Sa. 2. Juli 2022 um
22:01:
