### ISSUE TITLE
Ping ICMPv6

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#674]
> i tried several ipv6 addresses, which are all ping-able via desktop, receiving errors with ping tool. Does anyone share the same issue?
> I can provide screen shots of mobile app:
![image](https://user-images.githubusercontent.com/81030/177302962-32cbe146-5a75-48f7-ab0e-584ef99b7899.png)
![image](https://user-images.githubusercontent.com/81030/177303150-1202f4ad-d47c-4997-88ff-b82393d0218b.png)

with the desktop result(within the same network):
```
ping 201:6b27:e4b8:de94:228c:d7f3:a313:a1e2

PING 201:6b27:e4b8:de94:228c:d7f3:a313:a1e2(201:6b27:e4b8:de94:228c:d7f3:a313:a1e2) 56 data bytes
64 bytes from 201:6b27:e4b8:de94:228c:d7f3:a313:a1e2: icmp_seq=2 ttl=64 time=1162 ms
64 bytes from 201:6b27:e4b8:de94:228c:d7f3:a313:a1e2: icmp_seq=3 ttl=64 time=494 ms
```

_Originally posted by @immartian in https://github.com/isontheline/pro.webssh.net/discussions/673#discussioncomment-3083663_

**Comment by isontheline** [comment]
Hello @immartian 👋

A fix should be available tomorrow.

**Comment by immartian** [comment]
fantastic, look forward

**Comment by isontheline** [comment]
@immartian Please find a fix on the latest beta release here :

**Comment by immartian** [comment]
it works like a charm. Thanks for the crafting. ![image](https://user-images.githubusercontent.com/81030/178541908-3215933c-b09a-47a2-9954-3c88f0359158.jpeg)

**Comment by isontheline** [comment]
Thank you so much @immartian for your feedback 🙏
