### ISSUE TITLE
Stage Manager on iPadOS : horizontal layout broken

### ISSUE THREAD

**Issue by maxgrass** [isontheline/pro.webssh.net#675]
# Bug description
ipados 15/16+stage manager, magic keyboard. Zsh/bash. midnight commander.
When screen is full - Input field is below the viewport.
App usage impossible.

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. ipados
2. magic keyboard
3. horizontal layout
4. open your ssh session
5. when screen is full with commands, the prompt is not visible anymore (below the viewport)

**Comment by isontheline** [comment]
@maxgrass Could you please add some screenshots / videos?

**Comment by isontheline** [comment]
Any update @maxgrass ?

**Comment by isontheline** [comment]
Waiting for new Xcode Beta as the current available Stage Manager inside the Simulator doesn't work as expected.

**Comment by isontheline** [comment]
Are you referring to the right prompt border?
<img width="719" alt="image" src="https://user-images.githubusercontent.com/44212923/179356222-cf79a454-f650-44f1-a6c8-b9bd9008a503.png">

**Comment by maxgrass** [comment]
When you have it, it's hard to overlook.
Note the cursor/prompt is below the view point.

![IMG_0131](https://user-images.githubusercontent.com/169885/179430499-ca8810e1-634c-44f9-bbaa-02bc28bbbd07.jpg)

**Comment by isontheline** [comment]
Thanks for your feedback @maxgrass 👍

I will try to find why stage manager causes these troubles

**Comment by isontheline** [comment]
I have found the problem
A fix will be available in a few hours

**Comment by isontheline** [comment]
Hello @maxgrass 👋

Should be fixed inside the latest beta release.

Could you give it a try?
