### ISSUE TITLE
Set a preference for initial window size in MacOS

### ISSUE THREAD

**Issue by sbrooke** [isontheline/pro.webssh.net#681]
When opening in MacOS the initial window is always relatively small and I always have to resize it. With the "Terminal" app I can save a preference for the window size.

**Comment by isontheline** [comment]
You're right!

Good issue @sbrooke

**Comment by isontheline** [comment]
> Hallo Arnoud,
> 
> First of all thank you for this nice and handy App. I use it very often and I love it.
> I just have two annoying problems maybe a bug. I describe what I do and what is the result.
> On my iMac I start WebSSH it appears in the middle of the screen. I move it to the right side of the screen to make some space for another App (Safari, …).
> If I close the WebSSH and open it again, it appears again in the middle of the screen. Every time I must move it to the right and adjust the width. 
> It cannot to save the previous positions and every time I must do this.
> 
> Also when I select Hide Sidebar, the next time I start de WebSSH it appears again.
> 
> Is it possible to solve these issue or should I wait for the next Update?
> I have the pro version and this happens also on my Macbook Pro. I always install the last version.
> 
> Thank you in advanced.
> 
> Best regards,
> 
> MO

**Comment by isontheline** [comment]
Hello Mo 👋

Thank you so much for your feedback and support about WebSSH 🙏

You're right these are two known issues that I need to address.
These aren't trivial because some features are unavailable inside Mac Catalyst framework. I will try to find how to resolve them.

Have a nice day ☀️

**Comment by isontheline** [comment]
For @isontheline work :
* https://stackoverflow.com/a/72352513
* https://gist.github.com/steipete/30c33740bf0ebc34a0da897cba52fefe
* https://stackoverflow.com/questions/62582967/how-to-fix-the-position-of-the-window-in-mac-catalyst

**Comment by isontheline** [comment]
@sbrooke Does the trouble need to be fixed only when WebSSH starts?

**Comment by sbrooke** [comment]
I haven't added a new comment on this issue in quite a while, but the Catalyst issues you listed above still exist. Notably, opening WebSSH always opens to a smallish window in the center of the screen, and tabbing between fields doesn't work. The tabbing is usually when I'm creating a new server and I'd like to tab through the entries for host, username, group, etc... Tabbing instead bounces from the entry fields to the "SSH" inventory item on the left and then down to the Private Key field in the new host entry. Just goes back and forth between those two after that. My only option is to shift my hands from the keyboard to the mouse/trackpad to get to the other required fields.

**Comment by isontheline** [comment]
@sbrooke Many thanks for your feedback

Tabbing issue is tracked here : https://github.com/isontheline/pro.webssh.net/issues/764
I don't have found yet how to tell the system to keep inside the fields instead of switching to other parts of the app

I will try to fix the window size / location as I've just found a snippet on Internet (which doesn't use any private API) that could do the job

**Comment by isontheline** [comment]
A first attempt is available on the latest beta release WebSSH 25.6.1300 : https://testflight.apple.com/join/QSrBK59z

You have to enable a custom setting :

![Image](https://github.com/isontheline/pro.webssh.net/assets/44212923/f8001dcb-d819-41ba-ab50-e6fceac5c7a3)
