### ISSUE TITLE
Vert. and Horiz. Lines Not Rendering Properly

### ISSUE THREAD

**Issue by AA7US** [isontheline/pro.webssh.net#682]
# Bug description
I'm using WebSSH to access a headless Raspberry Pi to run the GPS diagnostic utility called "cgps" ([https://gpsd.io/cgps.html](https://gpsd.io/cgps.html)).  In that utility, vertical and horizontal characters (symbols?) don't render properly in WebSSH.  The output renders correctly in Termius. 

# Screenshots
Here's a screen capture of the output in Termius:

![screenshot_836](https://user-images.githubusercontent.com/41341300/180670127-add9403c-27bf-4668-9819-c0a14b7b6c85.jpg)

Here's the same output in WebSSH:

![screenshot_838](https://user-images.githubusercontent.com/41341300/180670138-d1e153e2-e48f-4dde-a7f1-2aea2747cc77.jpg)

Thank you!

John L.

**Comment by isontheline** [comment]
Again, thank you so much @AA7US John for your feedback 🙏

I will work on it this week and I will try to reproduce and make a fix soon.

**Comment by isontheline** [comment]
Work In Progress

**Comment by isontheline** [comment]
Hello @AA7US 👋

Could you try WebSSH 19.5 latest beta ?
https://testflight.apple.com/join/QSrBK59z

**Comment by AA7US** [comment]
I just tested version 19.5 (953) on an iPad Air and a M1 MacBook Pro.  The vertical and horizontal lines are now rendering correctly and look beautiful!  Thank you Magnus!

**Comment by isontheline** [comment]
You're Welcome
Thank you too for your feedback @AA7US 🙏
