### ISSUE TITLE
Ability to launch a Tunnel Port Forwarding through a Dynamic Port Forwarding when available

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#683]
# Feature description
Now we can launch SSH and SFTP connections seamlessly through DPF tunnels but we can't launch Port Forwards over them.

So adding this ability will allow us to have a better WebSSH before having a full multi-jump feature.

**Comment by isontheline** [comment]
Available inside the latest beta release WebSSH 19.7

**Comment by jarrah31** [comment]
Hi Arnaud, do you have any examples or documentation on how this works, how to set it up, and what benefits it gives please? Thanks.

**Comment by isontheline** [comment]
@jarrah31 Yes documentation about DPF is here : https://webssh.net/documentation/help/networking/port-forwarding/#dynamic-port-forwarding

When you launch a "DPF" tunnel (with * wildcard char) WebSSH use it to launch any further SSH, SFTP or even TUNNEL connections through it.

So it "will act" as an "easy VPN" between your device and your trusted SSH server.

The next step is to implement "jump" : https://github.com/isontheline/pro.webssh.net/issues/577

**Comment by jarrah31** [comment]
> When you launch a "DPF" tunnel (with * wildcard char) WebSSH use it to launch any further SSH, SFTP or even TUNNEL connections through it.

I'm a little confused because I've been using the DPF tunnel with a wildcard char for a while now, so I was wondering what this particular issue fixes (so that I can test it out)? Sorry if I've misunderstood something. :)

**Comment by isontheline** [comment]
DPF has not been updated with this issue. 

The problem was that TUNNEL connections launched after a DPF weren't using the DPF so I was unable to forward a port on a bastion.

This could be considered as a "hack" before true jump feature implemented.

**Comment by isontheline** [comment]
Launching forwards through DPF let you to don't specify all port forwardings inside one TUNNEL but instead you can launch one or more forwards TUNNELs to do some things.

Perhaps this is only useful for me. I needed it last week under an IT incident.

**Comment by jarrah31** [comment]
Understood, thanks for the explanation Arnaud. :)
