### ISSUE TITLE
macOS : cursor focus is needed to make a clipboard paste (CMD + V)

### ISSUE THREAD

**Issue by gpsnail** [isontheline/pro.webssh.net#684]
# Bug description
Impossbile to use copy / paste on Mac OS .

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. Copy 
2. Paste (not available)

**Comment by isontheline** [comment]
Please add screenshots or videos.

It's already possible to copy and paste on macOS.

**Comment by isontheline** [comment]
* https://github.com/isontheline/pro.webssh.net/discussions/676
* https://github.com/isontheline/pro.webssh.net/issues/524
* https://github.com/isontheline/pro.webssh.net/discussions/666

**Comment by isontheline** [comment]
Does the other app is downloaded from the App Store?

Does all apps have the same behavior?

What's your computer uptime? Does a restart fixes the trouble?

Thank you for your feedback

**Comment by gpsnail** [comment]
Copy a command line from safari. 

Try to paste using cmd+V or pop up menu. 

The paste work in notes app.  

The popup menu appearing in webssh is grayed for paste and cut, only copy is available 


Computer up from the morning.

**Comment by isontheline** [comment]
Thank you.

Latest macOS release?
Does paste was working before?

**Comment by AA7US** [comment]
I can confirm copy and paste is working fine here with WebSSH v19.3 (927) on a 2018 MacBook Pro w/macOS v12.4 Monterey.

**Comment by isontheline** [comment]
You're right @AA7US => @gpsnail have you tried the latest beta release?
https://testflight.apple.com/join/QSrBK59z

**Comment by gpsnail** [comment]
Here is a screenshot on my second Mac with webssh 19.3, The popup menu is like this. 
I made a copy from a command line in Notes app. 
![image](https://user-images.githubusercontent.com/1072095/179839571-91007db5-8da8-4ef3-b3ab-d068bc52414b.jpeg)

**Comment by isontheline** [comment]
Menu bar is implemented yes

**Comment by isontheline** [comment]
@gpsnail Have you tried the latest beta release?
https://testflight.apple.com/join/QSrBK59z

**Comment by gpsnail** [comment]
I tried the release 19.4 updated from this morning 

And here the result of my search and try :
- if I copy thru the context menu of another app and tried to paste thru main menu and Cmd+v, it's not working 
- if I copy in the other app thru cmd+c and I can paste then with cmd+v 

But There is something not very natural is that you have to go on the cursor as it looks to not me selected by default. 

I'm not sure to be clear.

**Comment by isontheline** [comment]
> But There is something not very natural is that you have to go on the cursor as it looks to not me selected by default.
> I'm not sure to be clear.

You are talking about the cursor focus, isn't it?

**Comment by gpsnail** [comment]
Yes, you have to be on the cursor focus to make the cmd+v it's very strange.

**Comment by isontheline** [comment]
I will fix this bug

**Comment by isontheline** [comment]
Hello @gpsnail 👋

Does this issue is fixed?

**Comment by gpsnail** [comment]
Yes, fine now

**Comment by isontheline** [comment]
Thanks so much for your feedback @gpsnail 🙏
