### ISSUE TITLE
iOS WebSSH app asks for password even when the server doesn't

### ISSUE THREAD

**Issue by bradfitz** [isontheline/pro.webssh.net#685]
# Bug description

We (@Tailscale) have a custom SSH server that runs over Wireguard. Because we already know the user's identity from Wireguard, we skip all the SSH-level authentication. When the SSH client connects and requests auth type "none", usually the SSH server replies with a rejection and a list of which auth types can proceed. Our SSH server, on the other hand, accepts auth type none immediately. This confuses the WebSSH app which assumes that if you don't have a private key you must need a password.

Our workaround that we've told users is to set a fake password. The password is never used (never sent on the wire) but it makes the WebSSH app happy.

# Screenshots

![IMG_0091](https://user-images.githubusercontent.com/2621/179827431-7aaa4653-c2b5-4021-aee8-3bc0c896d3a1.png)
![IMG_0092](https://user-images.githubusercontent.com/2621/179827481-3e022a00-1bf4-4432-bef7-319d51ae44f0.png)

# Steps to reproduce
1. try to ssh to `188.166.70.128` on port `2222` (any username)
2. notice that WebSSH asks for a password, even though that test server never asks for any auth types
3. enter a dummy password to proceed (any password will make the app happy, even though it's never sent to the server)

/cc @maisem

**Comment by bradfitz** [comment]
With OpenSSH,

```
$ ssh -v -p 2222 188.166.70.128
...
debug1: Authentication succeeded (none).
...
It worked.
10 ...
9 ...
8 ...
7 ...
6 ...
5 ...
4 ...
3 ...
2 ...
1 ...
```

**Comment by isontheline** [comment]
Hello @bradfitz Brad 👋

Thank you a lot for your strong feedback (and your strong products too ;) 👍

May I use the 188.X.X.X IP address in order to make a fix in the next few hours?

**Comment by bradfitz** [comment]
> May I use the 188.X.X.X IP address in order to make a fix in the next few hours?

Yup! It exists specifically for testing. Test away. No rush. I'll keep it up as long as needed.

Thanks for looking into it!

**Comment by isontheline** [comment]
Thank you Brad 🙏

**Comment by isontheline** [comment]
It's almost done. A beta release will be available tomorrow, July 21.

**Comment by isontheline** [comment]
Please find a fix inside the latest beta release (19.5 build 949) : 
https://testflight.apple.com/join/QSrBK59z

When no password are set inside the connection form :
* If server accepts 'none' authentication : WebSSH won't ask user password
* If server don't accept 'none' authentication : WebSSH will require user to put password

**Comment by bradfitz** [comment]
@isontheline, it doesn't work for me. It looks like it's always sending username "test", regardless of what username I enter. Did you accidentally leave some debug code in the build?

**Comment by isontheline** [comment]
@bradfitz No hard coded credentials inside the build, even in beta releases.

And I'm able to connect to my own servers with usernames like 'apple', 'root' and many others.

So 'test' is not from my side.

**Comment by isontheline** [comment]
I don't find any string reference to "test" inside WebSSH code :/

That's strange.

Are you able to connect to a non Wireguard endpoint?

**Comment by isontheline** [comment]
Does build 19.4 #932 (July 10) sends bad username? (This build doesn't contains an update about SSH related things)

**Comment by bradfitz** [comment]
I ran our SSH server with a ton of debug logs. Other SSH clients send my actual username. 

* WebSSH build 932 sends the correct username
* WebSSH build 932 sends the correct username
* WebSSH build 941 sends the correct username
* WebSSH build 943 sends the correct username
* WebSSH build 949 sends "test" as the username

BTW, typo in all the TestFlight release notes: It should say "Its codename is ...." with the possessive rather than "It's" == "It is". :)

**Comment by isontheline** [comment]
> BTW, typo in all the TestFlight release notes: It should say "Its codename is ...." with the possessive rather than "It's" == "It is". :)

Thank you Brad 🙏
I'm fixing this typo.

Thank you a lot for your tests agains 932; 939, 941, 943 and 949!

In order to drive me in my searches : could you try to put a password inside the connection form? (even a bad password). When done, does the username is always 'test'?

I ask this because I have added some lines of code in order to check if server supports 'none' authentication and the kill switch of these lines is to set a password inside the connection form.

**Comment by bradfitz** [comment]
Yes, that's it:

* WebSSH build 949 with empty password sends "test" as the username
* WebSSH build 949 with dummy "foo" password sends the correct username

**Comment by isontheline** [comment]
That's crazy :/

It works on my side, isn't it?

<img width="264" alt="image" src="https://user-images.githubusercontent.com/44212923/180265279-0df1ccbd-59f7-4d82-847c-9fae764aad6f.png">

**Comment by bradfitz** [comment]
You seem to have a race.

The behavior depends on latency to the server. If the server is low latency, WebSSH sends "test". But if it's sufficiently "far away", something in the WebSSH code has time to initialize the username to the right one before it gets past the host key exchange phase of the SSH protocol and gets to auth.

If you have Go installed on your Mac, I can prepare a demo server you can run locally so you have a low latency SSH server to test against?

**Comment by isontheline** [comment]
@bradfitz 

> If you have Go installed on your Mac, I can prepare a demo server you can run locally so you have a low latency SSH server to test against?

Yes, it would be awesome!

Thank you a lot Brad for your help.

**Comment by bradfitz** [comment]
Oh, when there's no password saved in WebSSH, it makes two concurrent TCP connections to port 22. One has the right user ("foo" in my case) and  one has "test". Is that maybe for testing the host key or something?

This is me trying to hit my 10.0.0.52:2222 server running on the same wifi network:

```
$ go run tailscale.com/cmd/ssh-auth-none-demo@a3777f0dc8915f7aee7633747f56294268532936
2022/07/21 11:15:47 Running on :2222 ...
2022/07/21 11:15:50 Got connection from user "test", "SSH-2.0-PuTTY_Release_0.70" from 10.0.106.114:60621
2022/07/21 11:15:50 Got connection from user "foo", "SSH-2.0-PuTTY_Release_0.70" from 10.0.106.114:60622
2022/07/21 11:15:50 Started session from user "foo"
```

You should be able to run that server too using that `go run` command above.

Code's at https://github.com/tailscale/tailscale/pull/5115 if you're curious.

**Comment by bradfitz** [comment]
Also, why's there a ~3 second pause when connecting to the local LAN SSH server?

The 10 second countdown from that demo server's always at "7..." by the time the terminal shows up.

**Comment by isontheline** [comment]
> Also, why's there a ~3 second pause when connecting to the local LAN SSH server?

A legacy animation timer for old iOS devices. I'm opening an issue to check if it's still required : https://github.com/isontheline/pro.webssh.net/issues/688

> Oh, when there's no password saved in WebSSH, it makes two concurrent TCP connections to port 22. One has the right user ("foo" in my case) and one has "test". Is that maybe for testing the host key or something?

Yes I'm opening a connection in order to check server capabilities but I think I'm opening it wrongly.

> You should be able to run that server too using that go run command above.

Thank you, I'm trying it. It will help me to address the fix.

**Comment by isontheline** [comment]
@bradfitz I've done a fix : only one connection will be opened

Xcode Cloud pipeline is running.

I will release access to the binary tomorrow July 22 (morning Europe/Paris)

**Comment by isontheline** [comment]
Available build 950 should fix related issues : 
https://testflight.apple.com/join/QSrBK59z

**Comment by bradfitz** [comment]
Works for me now! 🙏

**Comment by isontheline** [comment]
Thank you a lot for your feedback Brad 👍
