### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by VermiIIi0n** [isontheline/pro.webssh.net#687]
# Add unicode support
Xterm.js supports unicode, yet in WebSSH I only see a bunch of '?'s
![52625374-4667-4FD4-937C-861157F44039](https://user-images.githubusercontent.com/104612478/180137937-dc27dde3-1a2d-489c-87bf-73a2614adbb7.jpeg)

As a non-English speaker, it's a major flaw for me.

BTW, maybe I shouldn't request two features at once, but having the ability to generate SSH key pairs will be sweet.

Other than these the app fits my appetite really well.

**Comment by isontheline** [comment]
Hello @VermiIIi0n 👋

Thank you a lot for your feedback!

I will fix unicode flaw asap.

Key generation is already planned

Have a nice day ☀️

**Comment by VermiIIi0n** [comment]
Thank you for your instant response!
Can't wait to see it, have a nice day👏

**Comment by isontheline** [comment]
Hello @VermiIIi0n 👋

Could you try WebSSH 19.5 latest beta ?
https://testflight.apple.com/join/QSrBK59z

**Comment by VermiIIi0n** [comment]
It now works perfectly, thank you for your efforts!

**Comment by isontheline** [comment]
You're Welcome
Thank you a lot for your feedback @VermiIIi0n 🙏
