### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#7]
WebSSH will be even better in dark :)

* [Designing a Dark Mode for your iOS app](https://blog.prototypr.io/designing-a-dark-mode-for-your-ios-app-the-ultimate-guide-6b043303b941)
* [Dark Mode on iOS 13](https://nshipster.com/dark-mode/)
* https://medium.com/ios-expert-series-or-interview-series/implementing-dark-mode-in-ios-13-54eb6775a1b7

# Need to
- [x] Remove all static colors coded
- [x] Use new system colors in order to be applied in both light/dark

* https://noahgilmore.com/blog/dark-mode-uicolor-compatibility/

**Comment by isontheline** [comment]
Disabling dark mode support (while fixing it for 14.0) in 13.16.8

**Comment by maravtdm** [comment]
Full white screen on ios 14 beta2
