### ISSUE TITLE
Label overlaps toggle in connection form

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#705]
# Bug description
The radio button displays poorly

# Screenshots
![image](https://user-images.githubusercontent.com/1205471/183243826-89e1b839-7da5-4375-9501-b227f9ce1398.png)

# Steps to reproduce
1.  Open Connection Settings. 
2. Note the Force Keyboard toggle alignment

**Comment by isontheline** [comment]
I will fix it soon.

Which device form factor are you using?

**Comment by mbierman** [comment]
iPhone 12 mini

**Comment by isontheline** [comment]
Fixed in the latest beta release available for download now.
