### ISSUE TITLE
Powershell snippets run in reverse order and do not complete

### ISSUE THREAD

**Issue by RichardBurt65** [isontheline/pro.webssh.net#708]
# Bug description
Powershell .ps1 snippets run in reverse order and do not complete

# Screenshots
<img width="1512" alt="Screenshot 2022-08-08 at 15 49 34" src="https://user-images.githubusercontent.com/110833650/183433966-9de9a7d5-b3b7-405b-8a95-2c47be4cb590.png">
<img width="1512" alt="Screenshot 2022-08-08 at 15 49 58" src="https://user-images.githubusercontent.com/110833650/183433981-a75e809c-54cf-47cb-b011-077a18dd464b.png">

# Steps to reproduce
1. Create any Powershell snippet
2. Run in SSH session on Microsoft machine
3. Error as in screenshot

**Comment by isontheline** [comment]
Hello @RichardBurt65 👋

Thank you a lot for your issue 👍

I will take a look at it in order to find and fix the trouble.

**Comment by isontheline** [comment]
Related to https://github.com/PowerShell/PSReadLine/issues/579

**Comment by isontheline** [comment]
Hello @RichardBurt65 

Have you some time to do a test?

Could you run this :
> Remove-PSReadlineKeyHandler Ctrl+Enter

=> Before running the snippet.

Does the snippet is pasted in good order?
If so I will be able to make a fix.

**Comment by RichardBurt65** [comment]
I'll try it in the morning and let you know.

**Comment by RichardBurt65** [comment]
Morning Arnaud,

Screenshot attached of results. Snippet still doesn’t run but at least it’s in the correct order (barring the excess >> signs) 

￼

**Comment by isontheline** [comment]
Good Morning ☀️

Thank you a lot for your feedback!
Screenshots seems not to be attached when sending them through email.

Good news if commands are now in correct order : seems to be a "bug" inside PowerShell due to carriage return characters between macOS and Windows.

I will implement a hack inside WebSSH.

**Comment by RichardBurt65** [comment]
Try again with attachment. 

￼

**Comment by isontheline** [comment]
I think attachments could only be put from GitHub.

**Comment by RichardBurt65** [comment]
<img width="1512" alt="Screenshot 2022-08-16 at 07 54 10" src="https://user-images.githubusercontent.com/110833650/184828322-67eb00c1-260c-4f4c-a4f3-5974b9d580f5.png">

**Comment by isontheline** [comment]
Does the snippet is executed when pressing ENTER after the last statement?

**Comment by RichardBurt65** [comment]
Yes

**Comment by isontheline** [comment]
If you add an empty line to the end of tour snippet does it execute it?

Snippets should not execute statements if they are no carriage return at the end because some users don't want to launch them automatically.

**Comment by RichardBurt65** [comment]
The snippet already has an empty end of line.

**Comment by isontheline** [comment]
Last question please : instead of executing the snippet => when you copy your statements and paste them to the terminal, does the paste works as expected?

**Comment by isontheline** [comment]
@RichardBurt65 Please also try out WebSSH 19.7 : 
https://testflight.apple.com/join/QSrBK59z

You will also need to change the default carriage return to "\r\n" :
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/44212923/184970178-59037d05-a501-4691-8ab5-9440ffdde23c.png">

**Comment by RichardBurt65** [comment]
Will do once I can get it installed (on the latest public Ventura beta) which won’t install apps via TestFlight)

**Comment by isontheline** [comment]
I will release WebSSH 19.7 in a few days so you will be able to test it through the App Store

**Comment by RichardBurt65** [comment]
Many thanks.

**Comment by RichardBurt65** [comment]
After installing todays Ventura latest beta and WebSSH beta I can now confirm that the powershell issue has been tested and fixed. 

Perfect and many thanks.

**Comment by isontheline** [comment]
Hello @RichardBurt65 👋

Great to hear that!
You're Welcome.

Many thanks for your feedback 🙏
