### ISSUE TITLE
connection != connexion

### ISSUE THREAD

**Issue by DexterLagan** [isontheline/pro.webssh.net#710]
Not really a bug, more of a typo I've seen all over the WebSSH docs. I know you're French. I'm French too. We have that habit of spelling connection 'connexion'. That's it!

**Comment by isontheline** [comment]
Oups 😅

You're right!

I'm planning to fix it soon.

Thank you again for your feedback

**Comment by isontheline** [comment]
Hello @DexterLagan 

Seems all terms have been fixed in the docs several weeks ago.

Could you confirm ?

**Comment by isontheline** [comment]
Thank you Dexter 🙏

Feel free to reopen if needed

Have a nice day ☀️
