### ISSUE TITLE
Tunnel function broken

### ISSUE THREAD

**Issue by melonsode** [isontheline/pro.webssh.net#711]
# Bug description
I can't connect ssh tunnel.

# Screenshots
![image](https://user-images.githubusercontent.com/3595109/184476719-4e40d8af-19bf-4a70-8d46-84af33a206ab.jpeg)

![image](https://user-images.githubusercontent.com/3595109/184476762-942b3cea-674d-4a7b-ad2c-750c0e7f2a10.jpeg)

# Steps to reproduce
1. tap Tunnel connection
2. Error is thrown

The setting of the connection should be valid because I haven't changed the settings. I could had connected to the server at least untill June. I guess such failure appeared the end of July.

**Comment by isontheline** [comment]
Hello @melonsode 👋

Thanks for your feedback 🙏

Please use this howto : https://webssh.net/documentation/help/howtos/Tunnel/NEVPNErrorDomain/

Have a nice day ☀️

**Comment by melonsode** [comment]
thank you. I have successed to connect again.
