### ISSUE TITLE
Renaming the "Export" menu

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#713]
Could the "Export" popup be renamed to make it more intuitive as to its purpose please? Something like "Export for copy/paste functionality", or "Open Copy/Paste Window"? I too was attempting to copy/paste lines of text today and because it behaves differently to the usual iOS/iPadOS behaviour (hold to select text), I initially thought Export just copied all text into the Copy buffer.

_Originally posted by @jarrah31 in https://github.com/isontheline/pro.webssh.net/discussions/609#discussioncomment-3416856_

**Comment by isontheline** [comment]
@jarrah31 Work In Progress :
* Removing the "Export" menu
* Adding ability to select text inside the terminal (hope everyone will enjoy this 😅)

**Comment by isontheline** [comment]
A first attempt will be issued in a few hours :

![Image](https://user-images.githubusercontent.com/44212923/186260848-d9bb7c0b-8319-402f-b610-30510954e72f.png)

* You will be able to switch between "Select Text Mode" and "Scroll Mode"
* New copy submenus will be created : copy selected / copy screen / copy all

**Comment by isontheline** [comment]
My own implementation of text selection is far from perfect but it's a first attempt : 
https://testflight.apple.com/join/QSrBK59z

All feedback is welcome 🙏

**Comment by AA7US** [comment]
Hi Arnaud,

I'm testing this new enhancement on an iPad.  Can you please explain what “Touch Mode” is and how to use it?

The regular copy and paste enhancements seem to work fine.

John L.

**Comment by mbierman** [comment]
The Touch Mode > Select Text needs work. It is far too hard to actually select text. Maybe use Long press to activate?

https://youtu.be/_Fkez5z2VNM

**Comment by isontheline** [comment]
Hi @AA7US John 👋

* Touch Mode : "normal" mode -> needed to move the rows by up / down gestures
* Select Mode : disable the move gestures in order to be able to select text inside the terminal

"Touch Mode" is by default when you launch a connection.

> The regular copy and paste enhancements seem to work fine.

Thank you for your feedback 🙏

**Comment by isontheline** [comment]
Hi @mbierman Michael 👋

Thank you a lot for your feedback and your video 🙏

> The Touch Mode > Select Text needs work. It is far too hard to actually select text. Maybe use Long press to activate?

I will try to enhance the UX in order to be user friendly

**Comment by isontheline** [comment]
I'm moving feedbacks about the text selection improvements here : [Improve iOS / iPadOS terminal text selection](#144)

**Comment by isontheline** [comment]
I'm closing this issue as the "Export" button has been renamed to "View Scrollback Buffer"

Any feedback is welcome on new issue threads

Have a nice day everyone ☀️
