### ISSUE TITLE
Since last not able to make selection to copy text

### ISSUE THREAD

**Issue by scotty92fr** [isontheline/pro.webssh.net#718]
# Bug description
I cannot select text to copy it

**Comment by isontheline** [comment]
Selection mode should be enabled before the use of text selection.

**Comment by scotty92fr** [comment]
Bonjour Arnaud, 

Comment est ce que je peux lancer le mode sélection ? 
Avant on avait une fenêtre texte qui apparaissait et on sélectionnait le texte, là je n’y arrive plus

Cordialement,
Michel Manceron

**Comment by isontheline** [comment]
Bonjour Michel 👋

Je vais rétablir la fenêtre texte dans la prochaine version beta (entre ce soir et demain) car mon implémentation actuelle n'est pas du tout optimale après quelques essais sur mes appareils.

Je m'excuse pour ce désagrément.

**Comment by scotty92fr** [comment]
Arnaud, 

il n’y a vraiment pas à t’excuser. Jamais déçu de l’app 🤣

Cordialement,
Michel Manceron

**Comment by isontheline** [comment]
Merci infiniment Michel pour ton soutien 🙏

**Comment by isontheline** [comment]
Le nouveau menu sera disponible dans quelques heures (build en cours) :


![Image](https://user-images.githubusercontent.com/44212923/186760743-83562004-3124-4199-8444-4a39bd514206.png)

**Comment by scotty92fr** [comment]
Arnaud, 

Quelle réactivité !! Je viens de tester 👍 

le « tampon de défilement » c’est un peu obscur mais une fois compris ça marche à merveille 

Merci beaucoup 

Cordialement,
Michel Manceron

**Comment by isontheline** [comment]
Merci infiniment Michel @scotty92fr 🙏

Oui la traduction est probablement à revoir (View Scrollback Buffer).
Je suis preneur pour toute proposition 😉

Je ferme cette issue, la livraison sur l'App Store devrait se faire dans les prochains jours.

A très bientôt ☀️

**Comment by scotty92fr** [comment]
Arnaud, même en anglais c’est pas clair 🤣, fenêtre de sélection me semblerait plus clair par exemple 

Cordialement,
Michel Manceron

**Comment by isontheline** [comment]
@scotty92fr Michel tu as totalement raison 😅

Je prévois la modification pour le prochain build

Merci !
