### ISSUE TITLE
App Crash on SSH-Tunnel Error

### ISSUE THREAD

**Issue by Wizzynik** [isontheline/pro.webssh.net#719]
# Bug description
On some occurrences the App crashes while trying to establish a SSH-Tunnel Connection. But only if at least the first try was unsuccessful.
I ran over this issue while testing my home proxy server. Sometimes it won't respond and any retry requires a app restart, which also closes every console window. 

# Device information
iPad Pro (11 Zoll, 3. Generation)
IOS Version: 15.6.1

# Steps to reproduce
1. Start the App
2. Try creating an SSH-Tunnel to a wrong (a not responding IP of a Server)
3. Click the error banner away and retry the connection
4. App closes / crashes

**Comment by isontheline** [comment]
Hello @Wizzynik 👋

Thank you so much for your feedback 🙏

I have encountered the same crashes today under the same circumstances as you.
I will release a fix in the following days.

Have a nice day ☀️

**Comment by isontheline** [comment]
Hello @Wizzynik 👋

Latest beta release should fix this issue :
