### ISSUE TITLE
Copy & Paste improvements

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#722]
Hi Arnaud, thank you for letting us test a new way of copy/pasting text within WebSSH.

As the other threads are now closed I thought I'd open a new one for us to provide feedback on this feature.

iOS
- If the keyboard is hidden and you hold-touch the screen, the menu hides behind the keyboard and the console drops down and leaves a white section at the top. It doesn't always do this but I can't work out the exact steps to reproduce.
- Touch mode -> Select text. Selecting text less then around 8 characters makes the keyboard appear / disappear. It's also really difficult to select text on iOS (not tested iPadOS), and could do with the OS' built-in method of text highlighting
- How do we copy text once highlighted? Tapping it just brings up the keyboard and highlight is lost. Touch holding brings up the menu, but selecting Copy -> Copy Selected doesn't make sense. What should happen here? Does it then copy any text I highlight? 

There's more but I've run out of time this evening. Will do more testing tomorrow. 👍

**Comment by isontheline** [comment]
Hi @jarrah31 👋

Thank you to open a new issue to track feedback improvements about copy / paste feature 👍

> If the keyboard is hidden and you hold-touch the screen, the menu hides behind the keyboard and the console drops down and leaves a white section at the top. It doesn't always do this but I can't work out the exact steps to reproduce.

I will check and fix

> Touch mode -> Select text. Selecting text less then around 8 characters makes the keyboard appear / disappear. It's also really difficult to select text on iOS (not tested iPadOS), and could do with the OS' built-in method of text highlighting

Yes my own implementation of text copy is far from user friendly you're right.
I need to improve it.
Right now you can still use "View Scrollback Buffer" in order to copy your content.

> How do we copy text once highlighted? Tapping it just brings up the keyboard and highlight is lost. Touch holding brings up the menu, but selecting Copy -> Copy Selected doesn't make sense. What should happen here? 

Once again you're right.

> Does it then copy any text I highlight?

Not yet (but yes it will) : https://github.com/isontheline/pro.webssh.net/issues/523

**Comment by jarrah31** [comment]
Thank you Arnaud!

macOS feedback:
- Using the right-click menu to copy and paste text causes the flashing cursor to loose focus. After selecting either copy or paste, I then need to click back on the screen to continue typing. 
- Looking forward to https://github.com/isontheline/pro.webssh.net/issues/523 where I can just highlight text and then press middle mouse button to paste. :)

**Comment by jarrah31** [comment]
I was curious to see how Termius handles copy/paste, so I launched the app and had a quick play. I must admit, their copy/paste method works really well, and it would be great if WebSSH could emulate it (I presume there's no trademark issues in doing so...)

Basically, you can scroll using touch by default. Touch-holding text causes a magnifying glass to appear to help you position the start of the cursor. An Apple-style "Select, Select All, Paste" menu then appears when you let go. If I press Select it highlights that word and presents draggable anchor points to highlight more text, with a "Copy, Select All, etc" menu appearing each time I stop touching the screen.
<img width="234" alt="image" src="https://user-images.githubusercontent.com/3072303/187149734-8faa71ed-4a36-404a-8e50-72b5ed1ab62a.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/3072303/187149966-53bd987b-8a65-4398-8ecb-e85ee839ed08.png">
<img width="285" alt="image" src="https://user-images.githubusercontent.com/3072303/187149575-1ff86117-9457-431d-9b1c-02e4d195f419.png">

**Comment by isontheline** [comment]
Yes Termius team have implemented a better text selection than me (they don't seem to use the native one though).

I will also implement a good one 😅

**Comment by isontheline** [comment]
> Copy Paste with the iPadOS is only doable by Scrollback Buffer, when there is no mouse in place.
But this is a real hazzle in my eyes, as the text in scrollback is really small and to copy text is really tough job to do. I would like to have a better way to copy and paste on the ipad.

From @MrFly72 on https://github.com/isontheline/pro.webssh.net/issues/762#issue-1438614240

**Comment by isontheline** [comment]
Some improvements of text selection are now available inside the latest beta release https://testflight.apple.com/join/QSrBK59z
