### ISSUE TITLE
Bug text lag/display

### ISSUE THREAD

**Issue by Suspectxyzz** [isontheline/pro.webssh.net#729]
# Bug description

1.Hello, if you have an iPhone x, up and turn the screen to the side, that bang from the iPhone enters the text and it is not understood.  I will come with a picture later

2.After long-term use, I noticed a lag in the terminal when writing, and on wifi/cellular data

3. If you try to delete a folder it is not deleted (empty or full) Suggestion: if you can add a bar or something like that to see how many files are left to delete
# Screenshots

**Comment by isontheline** [comment]
Hello @Suspectxyzz 👋

Thank you for your feedback!

1. Yes please post a screenshot
2. Are you using the default buffer size or a custom one?
3. You're right.

**Comment by Suspectxyzz** [comment]
thanks these are the pictures
![64E32434-2F8D-4C81-B47C-B05F56F3590C](https://user-images.githubusercontent.com/45514952/189422351-e73b6eea-5a0c-4640-a59b-f12e8a93b16c.jpeg)
![501C9F01-AE29-40AA-A424-88BA1769AFD8](https://user-images.githubusercontent.com/45514952/189422357-a94140c3-c310-4b4e-b5e0-f5e250bc7d4f.jpeg)
![94E960A5-F20F-4B91-98A1-267B96350D30](https://user-images.githubusercontent.com/45514952/189422361-3427f8bd-065a-4a3a-a085-84af619e2460.jpeg)

**Comment by isontheline** [comment]
I'm closing this issue in favor this existing one : https://github.com/isontheline/pro.webssh.net/issues/332
