### ISSUE TITLE
Port forward of 49152 no longer works on iOS 16

### ISSUE THREAD

**Issue by ksylvan** [isontheline/pro.webssh.net#731]
# Bug description

In the TUNNEL section, the following server settings used to work:

49152:localhost:49152

# Steps to reproduce
1. Create a TUNNEL configuration 
2. Add a port forward section like 49999:localhost:49999
3. Launch it
4. Error is thrown: “ Connection Failed
Port 49152 seems already opened by another forward or application”

![29D94FE5-A4C0-4A24-995C-46D9DAB681D9](https://user-images.githubusercontent.com/1226059/189499002-c4842d5d-27db-4c5d-95c3-a07c24d27f6e.jpeg)

**Comment by isontheline** [comment]
Hello @ksylvan 👋

Thanks for your bug report!

Does the error stills here when choosing another local port?

**Comment by ksylvan** [comment]
Yes, it happens with all sorts of local ports.
Yes, I’m sure no other port forwarding or app is listening on 49152.

This is what used to work:
```text
5555:localhost:5555
49152:localhost:49152
```

The setup has been working for months. I’ve been using the WebSSH port forwarding to facilitate using VSCode Web and TabNine as explained here:  https://github.com/ksylvan/remote-coding/blob/main/README.md

**Comment by ksylvan** [comment]
More info for you:

```text
mashREPL> curl -v localhost:5555
* Rebuilt URL to: localhost:5555/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 5555 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connection failed
* connect to 127.0.0.1 port 5555 failed: Connection refused
* Failed to connect to localhost port 5555: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 5555: Connection refused
```

And then when using 5555 only, I see some indication that it’s working:

```text
mashREPL> curl -v localhost:5555
* Rebuilt URL to: localhost:5555/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 5555 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5555 (#0)
> GET / HTTP/1.1
> Host: localhost:5555
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

**Comment by isontheline** [comment]
Yes your second try works because when one port forward is failing both are closed bu WebSSH.

Are there no ways to change 49152 on the local side?

I'm searching again but perhaps the port is already opened by the iOS or denied.

**Comment by ksylvan** [comment]
This used to work on iOS 15, so there ought to be a way to loosen whatever got tightened so we can do this type of thing on the upcoming iOS and iPadOS.

Device restart does not help.

**Comment by isontheline** [comment]
Thanks for your feedback @ksylvan 

I'm trying to reproduce

**Comment by isontheline** [comment]
I can confirm that port 49152 is already opened by an iOS process in background

**Comment by isontheline** [comment]
You will need to choose another local port for your forward

**Comment by isontheline** [comment]
I'm checking it again

**Comment by isontheline** [comment]
Found a first problem. Perhaps iOS 16 isn't the problem at all. You could try to downgrade WebSSH by using TestFlight :

**Comment by isontheline** [comment]
A bug is inside WebSSH 🐛
I will fix it in the next few hours

**Comment by isontheline** [comment]
Duplicated of #740

**Comment by isontheline** [comment]
Not a duplicates of #730

Sorry for the right / wrong answers

Port 49152 is opened under iOS 16 by a system process.

To check my words you can run under WebSSH mashREPL the command :

`curl -vv http://localhost:49152`

You will see that the port is open and it's not WebSSH that have opened the port.

**Comment by ksylvan** [comment]
Thanks and sorry for the extra work.
