### ISSUE TITLE
Tunneling doesn´t working on background

### ISSUE THREAD

**Issue by kukooo** [isontheline/pro.webssh.net#735]
# Bug description
When the tunnel connects it only works when it is in foreground, I've tried to connect using local port forwarding I need the app to be on side to side with safari.

# Steps to reproduce
1. Connect to a tunnel
2. Try to use that tunnel
3. It doesn't work
4. Set the app side by side with safari
5. use now the tunnel
6. It works now

**Comment by isontheline** [comment]
Hello @kukooo 👋

It's not a bug.

Please enable "VPN-Over-SSH" inside your connection settings in order to be able to use the forward outside WebSSH.

Have a nice day ☀️

**Comment by kukooo** [comment]
True, it work awesome.
Pro purchased :D

**Comment by isontheline** [comment]
> True, it work awesome.
> Pro purchased :D 

Thank you so much 🙏
