### ISSUE TITLE
iPhone web browser connect to localhost

### ISSUE THREAD

**Issue by 1kirmizi** [isontheline/pro.webssh.net#736]
`###` Discussed in https://github.com/isontheline/pro.webssh.net/discussions/701

<div type='discussions-op-text'>

<sup>Originally posted by **hypernice** August  3, 2022</sup>
I can connect over cellular Android firefox using simpleProxy [SOCKS5 127.0.0.1:2025] to my local network using ConnectBot as an SSH Tunnel host@xxx.xxx.xxx.xxx:2000 SOCKS5 source port 2025.

Is it possible to access my local network in the same manner using an iPhone? I can establish an SSH Tunnel using WebSSH, but I am not sure how to proceed using an iPhone browser since it doesn't look like any support adding a proxy configuration.
</div>

**Comment by isontheline** [comment]
Hello @1kirmizi 👋

Yet you can't because there is a mistake inside WebSSH.

Please upvote https://github.com/isontheline/pro.webssh.net/issues/607 in order to drive the roadmap.

**Comment by isontheline** [comment]
Perhaps I have misunderstood your need.

Could you explain more about your use case?
