### ISSUE TITLE
Change "Show Scrollback Buffer" translations

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#748]
Arnaud, même en anglais c’est pas clair 🤣, fenêtre de sélection me semblerait plus clair par exemple 

Cordialement,
Michel Manceron

_Originally posted by @scotty92fr in https://github.com/isontheline/pro.webssh.net/issues/718#issuecomment-1274310059_

**Comment by isontheline** [comment]
@scotty92fr Michel la traduction en français est désormais "Fenêtre de sélection"

Disponible sur la dernière beta 20.3

**Comment by scotty92fr** [comment]
Beaucoup plus compréhensible 👍Cordialement,Michel ManceronLe 3 nov. 2022 à 21:17, Arnaud Mengus ***@***.***> a écrit :﻿
@scotty92fr Michel la traduction en français est désormais "Fenêtre de sélection"
Disponible sur la dernière beta 20.3
