### ISSUE TITLE
Issue with server's Authentication method being both publickey and password, and SSH key gen request

### ISSUE THREAD

**Issue by philipt4** [isontheline/pro.webssh.net#749]
After plenty of failed attempts using online generated ssh keys online, i resorted to pulling out the Linux device to and using the good-old "ssh-keygen" and copy keys from there onto IOS. an embedded "ssh-keygen" would be fantastic.

I suggest support/recommendations on generating/importing keys be added to the app's online docs until this keygen feature is implemented.

Issue: 
Server ssh connection setting: AuthenticationMethods "publickey,password" gives error Connection_Established_But_Can_Not_Open_Session.
I get success if I add the server's password into the saved ssh configuration on the device and then attempt the connection.

Goal: 
To require a server password prompt after ssh keys are authorized, and not require the server password to be saved into the configuration.

**Comment by isontheline** [comment]
@philipt4 Key generation is planned here : #46

Almost all SSH keys should work out of the box.

Please post verbose logging for debugging.


In order to enable verbose logging you can follow the steps :
1. iOS Settings
2. WebSSH
3. Settings
4. Log Level > Verbose
5. Restart WebSSH
6. Reproduce your action
7. Find the log files inside iOS > Files > WebSSH

**Comment by isontheline** [comment]
Hello @philipt4 👋

Thank you a lot for your feedback 🙏

Could you try to change this setting please?

iOS Settings > WebSSH > None Authentication Strategy > Disallow

<img width="312" alt="image" src="https://user-images.githubusercontent.com/44212923/195437131-830eec51-dc34-4c62-be5f-a0d1e6e0d5b6.png">

Have a nice day ☀️

**Comment by isontheline** [comment]
@philipt4 Have you tried the suggestion above?

**Comment by isontheline** [comment]
@philipt4 Feel free to reopen this issue as soon as you need
