### ISSUE TITLE
Typing box thing misplacement

### ISSUE THREAD

**Issue by SabertoothWolf12** [isontheline/pro.webssh.net#756]
# Bug description
When I try to go into a file(and forgot to start with cd) the box that shows what place your typing will phase into the starting words of where you enter commands

# 

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by isontheline** [comment]
Sorry, I don't understand.

Could you please make a screenshot about your trouble?

**Comment by isontheline** [comment]
@SabertoothWolf12 Feel free to reopen this issue at any time
