### ISSUE TITLE
mashREPL : Implements history

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#76]
**Describe the feature**
- [x] Implements history
- [x] History can be browser through directional keys
- [x] History is saved and loaded from disk file ~/Documents/.mash_history
- [x] Command is not saved to history if command starts with a white space
- [x] Implements right and left cursor edit

**Comment by alex24072** [comment]
> **Describe the feature**
> 
> * [x]  Implements history
> * [x]  History can be browser through directional keys
> * [x]  History is saved and loaded from disk file ~/Documents/.mash_history
> * [x]  Command is not saved to history if command starts with a white space
> * [x]  Implements right and left cursor edit

**Comment by alex24072** [comment]
View
