### ISSUE TITLE
Copy Paset with iPadOS

### ISSUE THREAD

**Issue by MrFly72** [isontheline/pro.webssh.net#762]
# Feature description
Copy Paste with the iPadOS is only doable by Scrollback Buffer, when there is no mouse in place.
But this is a real hazzle in my eyes, as the text in scrollback is really small and to copy text is really tough job to do.
I would like to have a better way to copy and paste on the ipad.

**Comment by isontheline** [comment]
Thanks for your feedback @MrFly72 👍

You're right that text selection on WebSSH is so bad and need to be improved.

I'm moving your issue to this one : https://github.com/isontheline/pro.webssh.net/issues/722#issuecomment-1229903053
