### ISSUE TITLE
Broken terminal font in iOS Lockdown Mode

### ISSUE THREAD

**Issue by seborama** [isontheline/pro.webssh.net#769]
# Bug description
Broken terminal font and partly broken "Ctrl" handling in SSH session when using iOS / iPadOS Lockdown Mode (iOS > Settings > Privacy & Security > Lockdown Mode).

# Screenshots
<img width="1180" alt="PNG image" src="https://user-images.githubusercontent.com/8210110/201520352-448c24ae-088b-4477-bca3-08584a4a6a20.png">

# Steps to reproduce
1. Enable Lockdown Mode (this will reboot the device)
2. Start WebSSH
3. Start an SSH session
4. Font is not displayed correctly (proportional? with large white gaps) and "Ctrl" virtual key sometimes misbehaves (tendency to send Ctrl C without pressing C)

For now, the solution is to add an App exception to Lockdown Mode for WebSSH.

**Comment by isontheline** [comment]
Hello @seborama 👋

Thank you so much for your strong feedback 🙏

1) When using lockdown mode, please disable custom fonts :
* https://webssh.net/documentation/help/SSH/lockdown-mode-and-fonts/
* https://github.com/isontheline/pro.webssh.net/issues/734#issuecomment-1257271196

2) I think you are releasing your finger outside the "Ctrl" button which lead to enable "Ctrl-C" as default primary shortcut. Could you try again?

**Comment by seborama** [comment]
Excellent, you're quite right on both accounts.

I checked the in-app settings but it didn't occur to me to check the out-app iOS settings... Sorry about that!

Issue resolved.

Keep up the great work 👍

**Comment by isontheline** [comment]
> but it didn't occur to me to check the out-app iOS settings

Yes I'm currently moving settings in iOS, sorry for this trouble

> Keep up the great work 👍

Thank you so much for your support about WebSSH 🙏
