### ISSUE TITLE
Split screen keyboard

### ISSUE THREAD

**Issue by lublak** [isontheline/pro.webssh.net#791]
# Bug description

Currently if you are using split screen and web ssh and try to type something it it is not quit nice. You can not see what you are typing.

# Steps to reproduce
1. Open WebSSH
2. Open it in a split screen
3. open the keyboard

**Comment by isontheline** [comment]
Hello @lublak 👋

Thank you a lot for your issue 👍

Could you make a screenshot about the trouble you are encountering?

I'm not seeing your issue when splitting the screen :

![image](https://user-images.githubusercontent.com/44212923/205515592-8aab34a5-e36e-41d9-8539-9255908867ac.png)

**Comment by lublak** [comment]
@isontheline here :)

![image](https://user-images.githubusercontent.com/44057030/205516198-7afbacab-c56b-4ba2-bd45-800d62d1e80e.png)

![image](https://user-images.githubusercontent.com/44057030/205516204-5b378a63-e9e4-46e5-a14c-1c72fbcc1f95.png)

**Comment by lublak** [comment]
Some info: I have an iPad Pro 12,9

**Comment by isontheline** [comment]
Thank you @lublak 🙏
I was testing under iPad Air.

I will try under iPad Pro 12.9 so

**Comment by isontheline** [comment]
Text is behind the keyboard, the view doesn't resize properly.

I need to make a fix.
I'm adding this issue to the roadmap

**Comment by lublak** [comment]
@isontheline thanks :)

**Comment by lublak** [comment]
@isontheline any News? 😮
This issue is still present.

**Comment by isontheline** [comment]
@lublak Sorry I missed this issue

I will fix it in a few days 

My apologies

**Comment by lublak** [comment]
@isontheline All good. Basically, you can also work with it. Just not with a split screen.
Nevertheless, it would often be more convenient not to have to put your mobile phone next to it. xD

**Comment by isontheline** [comment]
@lublak I have a strange behaviour : 
* when WebSSH is on the right side keyboard overlaps
* when WebSSH is on the left all things right

Are you experiencing same?

**Comment by isontheline** [comment]
@lublak I think I have found the problem and I'll work on a fix in a few hours

**Comment by lublak** [comment]
@isontheline yes for me its the same. I've never tried that before. I've only ever had it on the right side xD

**Comment by isontheline** [comment]
For @isontheline work :
* https://developer.apple.com/documentation/uikit/uikeyboardframeenduserinfokey?language=objc

**Comment by isontheline** [comment]
A fix is now available : 
https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
Many thanks for your feedback @lublak 🙏
