### ISSUE TITLE
Slow Cursor on macOS

### ISSUE THREAD

**Issue by janwiesemann** [isontheline/pro.webssh.net#797]
# Bug description

I'm using quite a fast cursor speed speed on my Mac. Sadly, WebSSH does not seam follow or apply this setting. It's quite annoying if you quickly want to edit something at the beginning of a line.

# Steps to reproduce
1. Set fast cursor settings `System Preferences` -> `Keyboard` -> `Key repeat rate` and `Delay until repeat`
2. Connect to a server, move the cursor around without your arrow keys.

**Comment by isontheline** [comment]
Hello @janwiesemann 👋

Thank you a lot for your issue 🙏

You're right the cursor speed could be higher.

I don't know if I can use the macOS setting but I will try to get it or implement a cursor speed setting inside WebSSH.

Have a nice day ☀️

**Comment by isontheline** [comment]
Setting now available inside latest beta release : https://testflight.apple.com/join/QSrBK59z



![Image](https://user-images.githubusercontent.com/44212923/211096415-ccfc0dd5-ab85-429c-bd51-f936bd15775c.png)

**Comment by janwiesemann** [comment]
Thanks a lot. This was surprisingly fast.

I can see why you were using a ComboBox as selection but a Slider might be a better option. It would allow finer control over this feature.

Mit freundlichen Grüßen / kind regards

Jan Wiesemann


 <https://janwiesemann.de/>a human who takes pretty pictures and talks to computers 


\ KONTAKT‍@‍JANWIESEMANN‍.DE

 \ MARKT 22
  \ 35037 MARBURG

    \ +4‍9 (0)‍ 6‍4‍2‍1‍1‍6‍7‍7‍4‍4‍5
     \ +4‍9 (0)‍ 1‍7‍1‍8‍1‍8‍1‍0‍9‍7

       \ PGP-KEY: JANWIESEMANN.DE/#PGP

**Comment by isontheline** [comment]
Thanks for your feedback @janwiesemann 🙏

You're right about the slider but as I would like to retrieve the system settings in a future release (as you suggested before) I will close this issue as is.

I can however add two / three more values if needed in order to have a better speed control as implemented on the combobox.
