### ISSUE TITLE
NSLOOKUP Feature request

### ISSUE THREAD

**Issue by Zagrthos** [isontheline/pro.webssh.net#799]
# Feature description
Mostly the same like the ping feature, besides that it converts the IP-Addresses to DNS and vice versa.

# Screenshots / Draws
Use the ping UI as a reference and just change a few texts. The output could also be the same UI.

**Comment by isontheline** [comment]
Hello @Zagrthos 👋

Thank you so much for your request 🙏

I will plan it asap

**Comment by Zagrthos** [comment]
Hi,

thanks for the fast response.
Don't hurry, it's holidays. 🙂

**Comment by isontheline** [comment]
I'm merging this issue with this one : https://github.com/isontheline/pro.webssh.net/issues/1121
