### ISSUE TITLE
mashREPL : font-size through ssh_config

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#804]
# Feature description
> Is there a way to have a certain font size whenever one opens mashREPL? I’m aware one can pinch, and that will zoom in/out. But would love a way to have a bigger size whenever it’s open, and can’t find a way to set that. Thanks.

From *maique* on **Discord**

Thank you so much for using mashREPL 🙏

You’re right yet there isn’t any way to fix the font size like a standard ssh connection.

I will implement this enhancement asap. I will give you a link to the GitHub issue in order to track progress.

Have a nice day ☀️

> Thank you so much. I do use it a lot, daily, to ping a server, and it would be useful. Have a great day as well.

**Comment by isontheline** [comment]
Now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z

# How to enable it?
WebSSH > Settings (Gear) > Edit ssh_config > Then add this host setting :
```
Host mashREPL
    #!FontSize 30
```

The host must be named `mashREPL` and the `FontSize` parameter must be prefixed by `#!`. Then set the font size in pixels like `30`

**Comment by maique** [comment]
Brilliant, thank you.

**Comment by isontheline** [comment]
Thank you so much for your feedback @maique 🙏
