### ISSUE TITLE
Password authentication screen is delayed.

### ISSUE THREAD

**Issue by RealKindOne** [isontheline/pro.webssh.net#806]
# Bug description
The password authentication screen is delayed on startup.  I can my server ip addresses/ports/names/stuff for less than a second when I open the app.

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. Goto Settings
2. Enable "Password authentication". 
3.  Swip up to close the program.
4. Open program. 
5. **BUG** See Server ip addresses/ports/names/stuff for less than a second.
6. Lock screen takes over.

**Comment by isontheline** [comment]
Thank you so much for your feedback @RealKindOne 🙏

I will fix this in the next minor release 

Have a nice day ☀️

**Comment by isontheline** [comment]
The latest beta release should fixes this issue : 
https://testflight.apple.com/join/QSrBK59z

**Comment by RealKindOne** [comment]
It works. Thanks.
