### ISSUE TITLE
After some time..., keyboard not working.

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#812]
# Duplicates
- [x] https://github.com/isontheline/pro.webssh.net/issues/847
- [ ] https://github.com/isontheline/pro.webssh.net/issues/1025

# Bug description

> Hi!
> After some time..., keyboard not working.
> I need to unload the session and re-log in to fix the problem.
>  
> Please tell me how to fix it?)
> Thanks...

Hi 👋

Which keyboard are you using?

> MacBook Keyboard =D

I’m not aware about an issue with the onboard keyboard.

Does it occur every time ?

> I think this happens all the time during timeout. that is, I think that the application does not always report a break if the application has been minimized.
>  
> And, i don't know yet if this information will help, but I use biometrics to unlock the app. and I haven't tried using it without locking.

When you focus the terminal again, can you write again with your terminal?

> No. After unlocking, the terminal window does not respond. I have to unload the session and log in again. 

From a WebSSH user by email

**Comment by MKC-MKC** [comment]
video: https://yadi.sk/d/Q_k2OLIgJ8l38w

**Comment by frepke** [comment]
Same issue for me. It looks when pressing `command-v` the keyboard is working again but the you've to remove the pasted text.

**Comment by isontheline** [comment]
@frepke Does the trouble occur when you are typing or when you come back to WebSSH after app switch?

**Comment by frepke** [comment]
> @frepke Does the trouble occur when you are typing or when you come back to WebSSH after app switch?

It only occurs when coming back to the app.

**Comment by isontheline** [comment]
> It only occurs when coming back to the app. 

@frepke Thank you for your feedback 🙏

I will try to improve the app focus when switching

**Comment by isontheline** [comment]
Merging this one with #1025

**Comment by MKC-MKC** [comment]
I emailed that everything is fine, but in 1 case out of 10 it still stops working. Previously, I had to suffer longer with continuing to work in the terminal. now the problem disappears faster, in some cases the keyboard starts working only after switching between the via Mission Control screens again.

TestFlight.
Версия 27.2 (1382)

**Comment by isontheline** [comment]
Thanks @MKC-MKC for this information, I’ll continue to improve keyboard focus
