### ISSUE TITLE
[Docs] Typo in pricing-fr.md

### ISSUE THREAD

**Issue by fr3nchalp4a** [isontheline/pro.webssh.net#817]
In [documentation/src/docs/documentation/pricing-fr.md](https://github.com/isontheline/pro.webssh.net/blob/master/documentation/src/docs/documentation/pricing-fr.md),
there's a typo at "doûte" (last paragraph).
I'm on my phone now, so I can't 
PR, but this could be replaced by "doute".

**Comment by isontheline** [comment]
@fr3nchalp4a Toutes mes excuses !

The fix is beeing deployed
