### ISSUE TITLE
keyboard input stops working

### ISSUE THREAD

**Issue by daraHK-test** [isontheline/pro.webssh.net#822]
# Bug description
sometimes it's not responding to keyboard input. after selecting texts and press random keys, it starts working or I must quit the session and start it again.

# Screenshots
requires video

# Steps to reproduce
1. start a new session
2. switch between workspaces
3. sometimes it not respond to inputs from keyboard
4. no error at all. select texts with mouse and press random keys to fix the problem

**Comment by isontheline** [comment]
Hello @daraHK-test 👋

Thank you so much for your feedback 🙏

I'm merging your issue with this one : https://github.com/isontheline/pro.webssh.net/issues/812

I will work on it as soon as possible.

Have a nice day ☀️
