### ISSUE TITLE
Copy paste issues on iOS

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#826]
# Feature description
WebSSH is wonderful, but one area of weakness is copy/paste. It is ultra glitchy and cumbersome on iOS. Copy/paste is something that is routine and fundamental in shell usage and scripting. I see a lot of energy spent on what I would consider niche areas while this has not been addressed. Please make this a high priority. Copy paste must be 
- Easy to use 
- Easy to get to history and previous output
- Intuitive
- super reliable

nice to have
- keep last “n” copy buffers

# Screenshots / Draws
_If applicable, add screenshots and/or draws to help explain your feature request_

**Comment by isontheline** [comment]
@mbierman Under which OS the copy / paste is unreliable? 

On iOS there are two open issues about the glitches.

On macOS I'm not aware (or didn't remember sorry) of any issue big issue. Could you tell me more?

You're right about the fact to keep the last n history.

Thanks

**Comment by mbierman** [comment]
I updated the description. You are right, mostly an iOS issue.

**Comment by isontheline** [comment]
For @isontheline work : I'm linking to https://github.com/isontheline/pro.webssh.net/issues/722

**Comment by isontheline** [comment]
I'm merging this one with #722

A beta release will be available in a few hours now.
