### ISSUE TITLE
Share file SFTP connection

### ISSUE THREAD

**Issue by germankirichenko** [isontheline/pro.webssh.net#827]
# Feature description

First of all, thanks for a great tool! 
Bought immediately!

One function is missing for me, to share the file it must be downloaded. 

If you can make share a file directly from an SFTP connection and send it to messengers or applications, that would be just perfect!!!

**Comment by germankirichenko** [comment]
I saw a similar feature in the «Koder» app, you can check out how it's done there.

Perhaps when you send a file, it is downloaded automatically to a temporary folder and then deleted. This is imperceptible for small files and would be a great solution)

**Comment by isontheline** [comment]
@germankirichenko Nice I will take a look at it!

Are you needing this feature as a daily basis?

(I need to drive my roadmap)

Thank you!

**Comment by germankirichenko** [comment]
@isontheline 

> @germankirichenko Nice I will take a look at it!
> 
> Are you needing this feature as a daily basis?
> 
> (I need to drive my roadmap)
> 
> Thank you!

Yes, every day I send files that are generated on 30 servers and I have to download them to iCloud, and then send them to clients

**Comment by isontheline** [comment]
@germankirichenko So I will make my best efforts 😀

**Comment by germankirichenko** [comment]
@isontheline thank you, you are the best 🔥

**Comment by isontheline** [comment]
Being released in a few hours.
Will be available on TestFlight here : https://testflight.apple.com/join/QSrBK59z

You should receive a notification when available for download.

Have a nice day ☀️

**Comment by isontheline** [comment]
Now available on iOS : https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
@germankirichenko Thanks for your feedback 🙏

**Comment by Dag0d** [comment]
@isontheline Nice feature, but the German translation is wrong. The current German translation is "Aktie" which means "The Share" and not "to share". the right translation would be "Teilen"

Thanks for all your hard work

**Comment by isontheline** [comment]
Hello @Dag0d 👋

Excuse me for this translation mistake 😢
A fix have been pushed and will be available this afternoon.

Thank you so much for your feedback!

**Comment by isontheline** [comment]
Now available on TestFlight : 
https://testflight.apple.com/join/QSrBK59z

**Comment by germankirichenko** [comment]
@isontheline in translation for Russian is also an mistake)

It's better to write "Поделиться" instead of "Делиться"

**Comment by isontheline** [comment]
@germankirichenko Sorry for the mistake. I'm fixing it asap
