### ISSUE TITLE
Tunnel active for only a few moments after i switch from webssh to another app

### ISSUE THREAD

**Issue by atefsaleh** [isontheline/pro.webssh.net#83]
**Parent feature category**

- [*] Tunnel

**Describe the bug**
_A clear and concise description of what the bug is. Be warned : I will refuse reports with no or little informations_

**Informations**
 - Device : iPhone 11 Pro Max
 - OS : iOS 14.2 Public Beta
 - WebSSH free version

**Screenshots**
Unfortunately not applicable

**To Reproduce**
1.Add an ssh tunnel, mine is running on a custom port, authenticates using RSA key, port forwarding configured for Microsoft remote desktop to an internal machine as follows (without the quotes of course): "3389:x.y.z.w:3389" where x.y.z.w is the IP address of the internal machine
2.Install Microsoft RDP client from the app store https://apps.apple.com/us/app/remote-desktop-mobile/id714464092 add a connection with host IP address 127.0.0.1
3.try to connect to the newly added machine, if it fails to connect switch from the RDP app to webssh app, then switch back to the RDP app, when i do i am prompted for credentials, this is the normal behavior since i didn't enter or save any credentials in RDP connection, being prompted for credentials also makes me assume the tunnel is established (although i enabled "Show monitoring icon on servers list" in webssh settings and a the created shows a red circle when connected, usually red means not good or indicate a problem, but being prompted for credentials lets me assume the tunnel is up) successfully as it indicates i can communicate with the internal machine using the desired RDP port, from this point RDP app takes the credentials and doesn't come back with any response, until i switch to the webssh app and back to the RDP app, which after several "switches" logged me in to the target machine, but still the session either disconnects or freeze a few seconds after i switch back to the RDP app, if i may describe what i am experiencing i would say the tunnel is active as long as i have the webssh app in the foreground, i have to switch to another app to use the tunnel, once the webssh app is in the background, the tunnel is not working anymore after a few seconds, switching back to the webssh get the tunnel working again, when switching to the webssh app, the tunnel is still active and i don't have to reconnect it.
Sorry for the long second point, couldn't put it in several steps to implement.
Thanks in advance for your support.

**Comment by isontheline** [comment]
Hello @atefsaleh and thank you a lot for your report ❗ 

I'm aware about limitation about background operations and need to improve WebSSH.
Another issue has been opened here #25 but I think yours must be kept open too 👍 

This is not a bug from WebSSH but a limitation from Apple in order to prevent battery drain and privacy safe.
I will find a solution in the next days :muscle:

:sunny: Have a nice day!

**Comment by atefsaleh** [comment]
@isontheline many thanks for your prompt response, your explanation makes perfect sense, hope you will be able to find a way to get it working, again, merci beaucoup

**Comment by isontheline** [comment]
Hello @atefsaleh 👋

A beta release will be available soon on TestFlight : https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
Related to #25 VPN-Over-SSH

**Comment by isontheline** [comment]
@atefsaleh I will push a pre-beta-release in a few hours.

Have you already downloaded the TestFlight Beta Release?

**Comment by isontheline** [comment]
Now available for every beta tester through TestFlight

**Comment by atefsaleh** [comment]
@isontheline didn't yet but will do and feed back as soon as possible , many thanks.

**Comment by atefsaleh** [comment]
@isontheline downloaded the 14.6.2 from TestFlight, issue has been resolved, i was able to maintain a connection through the tunnel for 10 minutes (after which i disconnected gracefully) also the connection persists if the mobile is locked (i locked it manually), i can find my connection still up after unlocking the mobile. 
Thanks for your response and reaction, keep up the good work. 
Finally encore une fois, merci beaucoup.

**Comment by isontheline** [comment]
Thank you for your feedback @atefsaleh 👍
There are some glitches right now but it will work 😇

Merci à vous pour votre soutien et bonne continuation.

**Comment by jankkm** [comment]
I have exactly the same problem as described in the first post. Is the problem back or am I doing something wrong?

**Comment by isontheline** [comment]
@jankkm Please enable VPN-Over-SSH inside your connection settings

https://webssh.net/documentation/help/networking/vpn-over-ssh/

**Comment by jankkm** [comment]
> @jankkm Please enable VPN-Over-SSH inside your connection settings
> 
> https://webssh.net/documentation/help/networking/vpn-over-ssh/

I tried that but I actually need another VPN connection to reach the SSH server. Two VPN simultaneous connections are not possible on iOS as far as I know. Is it impossible then?

**Comment by isontheline** [comment]
@jankkm I understand your problem but there is no other workaround inside WebSSH as Apple prevents apps to run in background.

You may use Termius app which uses an hack : launching the GPS in order to force the tunnel to be always active.

**Comment by jankkm** [comment]
> @jankkm I understand your problem but there is no other workaround inside WebSSH as Apple prevents apps to run in background.
> 
> You may use Termius app which uses an hack : launching the GPS in order to force the tunnel to be always active.

Alright, thanks für the explanation! Have you considered using the GPS hack too? I don’t really like Termius so I‘ll try to find another way for now.

**Comment by isontheline** [comment]
@jankkm This hack isn't good at privacy and battery health.

The VPN-Over-SSH instead is using rules allowed by Apple. The GPS one isn't allowed to be used for another usage. 

Termius could suffer to functionality drop at any time by an upgrade to iOS.

So the GPS hack shouldn't be implemented inside WebSSH.

I hoper Apple will provide new ways to run some parts of apps in the background in a future iOS release.
