### ISSUE TITLE
macOS windows always new

### ISSUE THREAD

**Issue by mllr-mx** [isontheline/pro.webssh.net#835]
In macOS, unfortunately, it does not remember the position and size of the window. Also, it would be nice if when you restart the program, it would keep the closed bar closed as well.

many greetings

**Comment by isontheline** [comment]
Hello @mllr-mx 👋

Thank you so much for your feedback 🙏

I'm merging your issue these two ones :
* https://github.com/isontheline/pro.webssh.net/issues/681
* https://github.com/isontheline/pro.webssh.net/issues/585
