### ISSUE TITLE
Deep Links : Ability to use a Private Key

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#838]
# Feature description
Adding the ability to specify a Private Key when using deep links like this :
`ssh://user@host:port/?key=AWESOME`

* The `AWESOME` Private Key will used here.
* The `AWESOME` comes from the Private Key Name you have put
* Case ~~SENsitiVE!~~ insensitive!

- [x] Documentation

**Comment by isontheline** [comment]
@Thunderhawk2001 You can now use private keys on deep links : https://webssh.net/documentation/help/howtos/use-deep-linking/

**Comment by Thunderhawk2001** [comment]
Thank you so much! And sorry for answering this late. We just had our complete office moved(3 departments) to another location and I had to finally finish my own moving.

**Comment by isontheline** [comment]
No problem @Thunderhawk2001 you're Welcome!
