### ISSUE TITLE
Need larger fonts for iPhone 12 and above

### ISSUE THREAD

**Issue by ssb22** [isontheline/pro.webssh.net#840]
The iPhone 12 increased the screen DPI from 326 to 460.  So to get the same size font as "20px" on the iPhone 11 and below, it is now necessary to use 28 pixels.  Would it be possible to add fonts larger than 20 pixels so that people with limited eyesight can continue to use the app on newer versions of the iPhone?  Going up to 30 should be enough.  Thanks for maintaining this app.

**Comment by isontheline** [comment]
Hello @ssb22 👋

Thank you a lot for your issue 🙏

I will do my best to improve the ability to choose a bigger font size.

It should be available in few hours/days.

Have a nice day ☀️

**Comment by isontheline** [comment]
Now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z

Have a nice day ☀️

**Comment by isontheline** [comment]
@ssb22 You're Welcome
