### ISSUE TITLE
6+ open sessions in MacOS causes window refresh issues

### ISSUE THREAD

**Issue by sbrooke** [isontheline/pro.webssh.net#842]
# Bug description
This may be related to the other reported bug around memory issues and screen refreshes. I've noticed that when I have 6 or more open sessions in MacOS that the session windows will randomly clear and then return. Sometimes they return with a new line at the top. Other times they come back with the full text that was previously displayed, but the action of reading it in looks like the incorrect font size for a moment, before it fixes itself.

Ventura 13.2.1

I'll try to capture a video but it's transient.

**Comment by isontheline** [comment]
Hello @sbrooke 👋

Thank you a lot for your feedback 🙏

Yes it's same as #801 so I'm merging yours with theirs
