### ISSUE TITLE
unable to type and press enter after lose the focus on webSSH windows

### ISSUE THREAD

**Issue by daraHK88** [isontheline/pro.webssh.net#847]
# Bug description
after open a ssh window, everything works great until i go to my browser(i tried every browser) to copy something, when I come back to webSSH window I'm not able to copy nor type anything and if I press a lot of random keys, it starts typing again but whatever I copied has gone. I reported this bug before and you mentioned someone else also had this problem. but you didn't solve it after several month! really it's make me crazy. If you don't want to fix such a big bug please let me know I will find another program

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by isontheline** [comment]
> If you don't want to fix such a big bug please let me know I will find another program

1. I'm doing my best.
2. Perhaps not enough but my best
3. Everyone is free to stay within WebSSH or not
4. But I'm doing my best

> I reported this bug before and you mentioned someone else also had this problem. but you didn't solve it after several month!

Which issue are you referring about?

> really it's make me crazy

Me too. 
I'm using WebSSH height hours a day and there are a lot of glitches.
I do my best to fix them all.

**Comment by isontheline** [comment]
Hello @daraHK88 

Are you still encountering this issue under WebSSH 22?

**Comment by daraHK88** [comment]
Hello @isontheline
as you mentioned "Everyone is free to stay within WebSSH or not" I switched to Termius and I'm happy with it

**Comment by isontheline** [comment]
Thank you a lot for your feedback @daraHK88 🙏

No problem at all, I'm truly happy to hear that you have a tool that fulfill your SSH needs.
Feel free to reopen it as soon as you need.

Have a nice day ☀️
