### ISSUE TITLE
^H perform incorrectly in ssh

### ISSUE THREAD

**Issue by Mrxwise** [isontheline/pro.webssh.net#85]
**Describe the bug**
I redirected keras training output data-stream to a local file. When I cat these files, the backspace character ^H does not perform correctly.

**Informations**
 - Device : iPhone 6S, iPad 2018
 - OS : IOS 13
 - WebSSH Pro version : 14.5.11

**Comment by isontheline** [comment]
Hello @Mrxwise👋

* I need more reproducing steps
* What is "keras training output data-stream"?
* "^H does not perform correctly". OK but what's the intended behavior?

I will reopen this issue when you come back.

☀️ Have a nice day

**Comment by Mrxwise** [comment]
Hello Mr. Mengus👋Thanks for your reply.
I'm sorry for that I didn't explain the issue clearly, so I will add some screenshots.
I want to run the following code:

The <model_train.py&gt; is the code for model training using keras library.
The redirect file <model_train.log&gt; can be shown as:

There are many backspace characters. However, when I try to load the file with code:


It displays,

It looks like the character ^H does not backspace correctly.
I don't know why. I'll apologize for this, if it is just my fault.
☀️☀️&nbsp;Have a nice day☀️☀️




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arnaud Mengus"<notifications@github.com&gt;; 
发送时间: 2020年10月16日(星期五) 凌晨3:02
收件人: "isontheline/pro.webssh.net"<pro.webssh.net@noreply.github.com&gt;; 
抄送: "UyMA"<1192230855@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [isontheline/pro.webssh.net] ^H perform incorrectly in ssh (#85)





 
Hello @Mrxwise👋
  
I need more reproducing steps
 
What is "keras training output data-stream"?
 
"^H does not perform correctly". OK but what's the intended behavior?
  
I will reopen this issue when you come back.
 
☀️ Have a nice day

**Comment by isontheline** [comment]
Hello @Mrxwise 

I'm sorry but there is no screenshots attached to your comment :(

Could you check it?

Best Regards,

**Comment by Mrxwise** [comment]
Dear Mr. Mengus
Oh, that could be caused by network problems.


I will send my email to you again as a PDF file, as an attachment to this email. Hope you can receive it this time.


Best wishes,


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "isontheline/pro.webssh.net"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月16日(星期五) 晚上6:33
收件人:&nbsp;"isontheline/pro.webssh.net"<pro.webssh.net@noreply.github.com&gt;;
抄送:&nbsp;"UyMA"<1192230855@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [isontheline/pro.webssh.net] ^H perform incorrectly in ssh (#85)





 
Hello @Mrxwise
 
I'm sorry but there is no screenshots attached to your comment :(
 
Could you check it?
 
Best Regards,

**Comment by isontheline** [comment]
Instead you should use Github inside your web browser.

Emails may leaks sensitive data.

Best Regards,

**Comment by Mrxwise** [comment]
This is the third time I am doing the same thing :mask:. 

Well, here's my issues.

I want to run the following script in bash: 

`$ python -u model_train.py >./model_train.log 2>&1`

'model_train.py' is the source code for model training using keras library.

The redirect file `model_train.log` is shown as:
![1](https://user-images.githubusercontent.com/29838202/96254867-9addf980-0fe8-11eb-9a8a-cd4e7e4644fa.png)
There are many backspace characters. But when I try to load the file:

`tail model_train.log`

It displays,
![2](https://user-images.githubusercontent.com/29838202/96255049-ded0fe80-0fe8-11eb-8452-d6343e85f7bf.png)
It looks like that the character `^H` does not backspace correctly. 

I'll apologize for this, if it is just my fault. 

Yours ever,

**Comment by isontheline** [comment]
Thanks for your quick reply

Could you post a sample of your model_train.log?

☀️ Thank you a lot

**Comment by Mrxwise** [comment]
of course
[model_train.log](https://github.com/isontheline/pro.webssh.net/files/5391754/model_train.log)

**Comment by isontheline** [comment]
@Mrxwise 

I have run cat and tail (inside mashREPL) 
with your file and everything I think works :
- Each lines are displayed correctly without the ^H character

![simulator_screenshot_9414F70A-AF2A-4C5D-9AAF-A95341D46971](https://user-images.githubusercontent.com/44212923/96300247-83593d80-0ff5-11eb-8f64-90238e4022b0.png)

What behavior did you expect?
Did you expect string in place replacement?

**Comment by isontheline** [comment]
![Capture d’écran 2020-10-16 à 21 23 14](https://user-images.githubusercontent.com/44212923/96300434-d03d1400-0ff5-11eb-95a3-ac21642f555c.png)

You're right! Inside macOS terminal it works as you said.

**Comment by isontheline** [comment]
I have planned this issue

**Comment by Mrxwise** [comment]
:smiley::smiley:

**Comment by isontheline** [comment]
Hello @Mrxwise 

I think a fix will be available shortly :)

**Comment by isontheline** [comment]
Fixed inside 14.8.18 : https://testflight.apple.com/join/QSrBK59z

Could you try it?

☀️ Have a nice day

**Comment by Mrxwise** [comment]
Yes indeed, ^H can work well in 14.8.18 ;)

**Comment by isontheline** [comment]
This feature is enabled by default and cause some troubles : https://github.com/isontheline/pro.webssh.net/issues/161

So I will disable it by default.
You can enable "Reverse Wrap-Around" again inside terminal settings of your connection since 14.9.4
