### ISSUE TITLE
Stage Manager : Keyboard covers the terminal

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#851]
# Bug description
> When using stage manager the keyboard often covers the actual command line. There’s no way to scroll down to the command prompt either. This also happens with webssh in slide over & multi-window (non stage manager). I have additional screenshots if they’re helpful.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/44212923/227138933-e663ca9f-aef9-4089-b0c7-36c132e33f95.png">

**Comment by MrFly72** [comment]
I can confirm this.
Was trying to watch a YouTube and learn from it and with away use the terminal to check on it. Not possible currently, as stage Manager is not supported well at the moment. Any progress on this?

**Comment by isontheline** [comment]
No progress - yet - as I don't own any iPad capable for Stage Manager and the simulator is not yet well useful for Stage Manager Debugging

**Comment by MrFly72** [comment]
Oh, I know that you always do your best! 
It's a great tool, but a lot of work for you :-(

**Comment by isontheline** [comment]
You're right it's a lot of work but if you are already happy by using WebSSH I'm also happy to enhance it for you 😉

**Comment by MrFly72** [comment]
It's a small piece I can do

**Comment by isontheline** [comment]
A fix is ongoing

**Comment by isontheline** [comment]
A fix is now available : 
https://testflight.apple.com/join/QSrBK59z
