### ISSUE TITLE
Able to download a file through SFTP

### ISSUE THREAD

**Issue by lawsonav** [isontheline/pro.webssh.net#87]
**How to**
Forgive me if this is pedestrian, but I cannot figure out how I can save/download a file to my phone via SFTP. 

My use case: 

Setting up an OpenVPN server on a Pi - I want to save the client key .ovpn file. I assumed I can do this by long press, or swipe left/right on file. But I can’t find any save/transfer option at all?

**Comment by isontheline** [comment]
Hello @lawsonav 👋

You're right, WebSSH doesn't offer this feature yet.

It's now planned for 15.0

**Comment by lawsonav** [comment]
Ok. Super cool app still. Think I’ll end up going pro. 😅

Trying out a few ssh atm but this one is the best so far by a long way.

**Comment by isontheline** [comment]
Thank you a lot for your support! 👍 😇

**Comment by isontheline** [comment]
Similar to #113 

Need to implement SFTP transfers asap

**Comment by isontheline** [comment]
Hello 👋

I'm moving this issue to #114 in order to track all SFTP enhancements needed.

Have a nice day. ☀️

**Comment by isontheline** [comment]
I'm working on it since yesterday

Have a nice day ☀️

**Comment by isontheline** [comment]
- [ ] Having a menu to let user download a file
- [ ] Implement again folder renaming and folder deleting

**Comment by isontheline** [comment]
Hello @lawsonav  👋 

Please install _WebSSH Beta_ from TestFlight app : https://testflight.apple.com/join/QSrBK59z

You will then be able to download WebSSH 14.10.5 with download feature.

☀️ Have a nice day
