### ISSUE TITLE
the problem with the purchase

### ISSUE THREAD

**Issue by Suspectxyzz** [isontheline/pro.webssh.net#872]
# Bug description

Hello, I wanted to report this problem too, I don't think it's from you but I said I'd try it, as you can see I bought the premium version but I don't have access to the application on the new phone for a few months, is this the problem

if you want to see the uncensored picture, send a private message

I also made a ticket to Apple, I'm waiting for the answer in 48 hours
# Screenshots

![IMG_0255](https://user-images.githubusercontent.com/45514952/233749440-bbcd11c4-0af7-48c5-b681-970a9b13607e.jpeg)
![IMG_0256](https://user-images.githubusercontent.com/45514952/233749444-9e632917-a239-4c67-bf56-09eeba7366e3.jpeg)

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by isontheline** [comment]
Hello @Suspectxyzz 👋

Sorry for this trouble.

Have you tried this help?

https://webssh.net/documentation/help/restore-purchases/

Have a nice day ☀️
