### ISSUE TITLE
Prefer IPv4 over IPv6 protocol doesn't work anymore

### ISSUE THREAD

**Issue by AInteriorB** [isontheline/pro.webssh.net#876]
Hey @isontheline, how are you doing today?

# Bug description
Prefer IPv4 over IPv6 protocol doesn't work anymore on iPad Pro.

# Steps to reproduce
1. Go to WebSSH Settings, Internet Protocol Strategy, choose "Try IPv4 host address before IPv6"
2. Establish a connection to a host with both, IPv4 and IPv6 DNS entries
3. Connection is tried via IPv6

# Expected behavior
Connection is established via IPv4

**Comment by isontheline** [comment]
Hi @AInteriorB 👋

I'm fine thank you!
What about you?

I'm sorry for this trouble, I might have added a bug when refactoring the settings.

I will fix it this night (Europe/Paris) and I will ship it between today (April 25) and tomorrow (April 26) I think.

**Comment by isontheline** [comment]
I'm seeing a mistake, I'm fixing it

**Comment by AInteriorB** [comment]
You‘re the best, @isontheline 🎉

**Comment by isontheline** [comment]
@AInteriorB Hum I make mistakes not the best 🙃
I'm pushing WebSSH 21.9 to TestFlight, it should be available after being approved by Apple. I think tomorrow it should be available.

Sorry again for the trouble 😉

**Comment by isontheline** [comment]
@AInteriorB Now available on TestFlight

Could you give it a try?

Have a nice day ☀️

**Comment by isontheline** [comment]
If the fix doesn't work, feel free to reopen it.
