### ISSUE TITLE
Unable to paste content from some apps (rich metadata?)

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#877]
I am unable to copy / paste to a remote terminal. Clipboard strategy is set for allow read / write.

Any suggestions I can try?

_Originally posted by @RichardBurt65 in https://github.com/isontheline/pro.webssh.net/discussions/875_

**Comment by isontheline** [comment]
Hello @RichardBurt65 👋

Latest beta release should fix this issue : https://testflight.apple.com/join/QSrBK59z

Could you give it a try?

**Comment by RichardBurt65** [comment]
Works perfectly!

Many thanks for your prompt fix.

Now, to my list of improvements.... !
