### ISSUE TITLE
21.7 (1066) on MacOS having a variety of graphical errors.

### ISSUE THREAD

**Issue by sbrooke** [isontheline/pro.webssh.net#878]
I've noticed over the last week that I'm having multiple problems with graphics and sessions on MacOS. I'm on Ventura 13.3.1.

Quite often I come back to an open session and the window is non-responsive. Sometimes it shows content but most of the time it's blank. For the first time today I noticed that the content was frozen in the session but it had overlapped the top session ID bar. The bar that has the UP disconnect button on the left. The content had been repainted into that part of the window, and the session is unresponsive. I suspect it will come back to life at some point, as that's happened before, but I don't know how long that will take.

I've also had it "catch up" on some of the commands when it becomes responsive again, so it seems to be caching something in the session. I've tried typing "logout" to see if it's live and just not displaying and that has no effect. It's like the session is hung and it's causing graphical errors.

I can attach to the same system in other windows without trouble. It doesn't appear to be a problem on the system I'm connecting to.

**Comment by sbrooke** [comment]
As I was typing this, I returned to my hung window to find a blank screen with a blinking cursor at the bottom. Hit enter and the entire screen refreshed. It had not cached my keypresses. It now appears to be acting normally.

**Comment by isontheline** [comment]
The trouble is related to #801 
Since macOS Ventura, the Operating System is killing to often the WebSSH subprocesses (rendering engine) and WebSSH doesn't restore them properly.

I will work on this issue (very) soon

**Comment by isontheline** [comment]
Hello @sbrooke 

Could you try to run these steps in order to be sure that memory pressure is the root cause?
1. Launch WebSSH
2. Launch a SSH connection
3. Launch the macOS "Terminal" app (cover some parts of WebSSH)
4. Run this command : `sudo memory_pressure -S -l critical`

Are you seeing that WebSSH subprocess has been killed and the refresh happened?

**Comment by isontheline** [comment]
I'm merging this one with #801
