### ISSUE TITLE
OpenSSL 3.0.8 7 Feb 2023 not supported

### ISSUE THREAD

**Issue by qwertmax** [isontheline/pro.webssh.net#881]
### Discussed in https://github.com/isontheline/pro.webssh.net/discussions/880

<div type='discussions-op-text'>

<sup>Originally posted by **qwertmax** April 28, 2023</sup>
Is it possible to add support of `OpenSSH_8.7p1, OpenSSL 3.0.8 7 Feb 2023`

It looks like app is not supported it, because it keeps asking password when I provided .pem key. 

P.S. .pem key working perfectly for `OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1n  15 Mar 2022`</div>

**Comment by qwertmax** [comment]
2023/04/28 10:18:49:926 [WARN] User must check fingerprint because not know : ecdsa-sha2-nistp256 256 24:c4:50:f3:10:28:96:c6:a8:7f:d4:e8:84:94:ae:d1
2023/04/28 10:23:31:413 [WARN] Failed iCloud save : <CKError 0x280e69320: "Server Record Changed" (14/2004); server message = "record to insert already exists"; op = E8C2705B5F43BB0D; uuid = 22EEB0EE-477E-4E4C-9718-F49F168D47C9; container ID = "iCloud.com.itimeteo.webssh">
2023/04/28 10:36:47:283 [INFO] Thank you so much for using WebSSH 21.8.1078
2023/04/28 10:36:47:283 [DEBUG] WebSSH Setting Log Level : VERBOSE
2023/04/28 10:36:47:284 [INFO] Launching Data Migration...
2023/04/28 10:36:47:284 [INFO] Checking if settings need to be migrated...
2023/04/28 10:36:47:287 [INFO] Data Migration Done!
2023/04/28 10:36:47:288 [DEBUG] Launch_APP_Count_21.8 : 6
2023/04/28 10:36:47:288 [DEBUG] Launch_APP_Count : 18
2023/04/28 10:36:47:288 [DEBUG] Launching Vacuum on the local database...
2023/04/28 10:36:47:289 [DEBUG] 0 objects have been vacuumed
2023/04/28 10:36:47:298 [VERBOSE] Performing vacuum on old deleted iCloud objects...
2023/04/28 10:36:47:322 [DEBUG] Device language : en
2023/04/28 10:36:47:322 [INFO] Language bundle is not loaded. Will load this bundle : en
2023/04/28 10:36:47:348 [INFO] WebSSH should be locked after delay (secs) : 60
2023/04/28 10:36:47:841 [DEBUG] Application did become active
2023/04/28 10:36:47:846 [DEBUG] No pin code set. WebSSH won't be locked.
2023/04/28 10:36:48:296 [DEBUG] Fetching from iCloud with a change token
2023/04/28 10:36:48:338 [VERBOSE] No objects to be vacuumed on iCloud.
2023/04/28 10:36:48:721 [DEBUG] iCloud data fetched with success.
2023/04/28 10:36:57:354 [DEBUG] No custom SSH Config File will overwrite this connection settings
2023/04/28 10:36:57:354 [VERBOSE] Want to connect with a Private Key
2023/04/28 10:36:57:356 [VERBOSE] Private Key is not encrypted because we can load it without any passphrase.
2023/04/28 10:36:57:356 [DEBUG] Private Key is encrypted : 0
2023/04/28 10:36:57:356 [VERBOSE] Load Private Key in OpenSSH Format
2023/04/28 10:36:57:356 [VERBOSE] Launching connection (SSH)...
2023/04/28 10:36:57:357 [VERBOSE] Connecting to SSH...
2023/04/28 10:36:57:357 [VERBOSE] Launching connection with block...
2023/04/28 10:36:57:357 [VERBOSE] Won't dismiss prompt because no one is displayed.
2023/04/28 10:36:57:375 [DEBUG] No SOCKS Tunnel launched. SSH connection will be established without any SOCKS hostname.
2023/04/28 10:37:03:297 [DEBUG] Fetching from iCloud with a change token
2023/04/28 10:37:03:718 [DEBUG] iCloud data fetched with success.
2023/04/28 10:37:10:396 [VERBOSE] Cancelling connection...
2023/04/28 10:37:11:308 [DEBUG] No custom SSH Config File will overwrite this connection settings
2023/04/28 10:37:11:308 [VERBOSE] Want to connect with a Private Key
2023/04/28 10:37:11:309 [VERBOSE] Private Key is not encrypted because we can load it without any passphrase.
2023/04/28 10:37:11:309 [DEBUG] Private Key is encrypted : 0
2023/04/28 10:37:11:309 [VERBOSE] Load Private Key in OpenSSH Format
2023/04/28 10:37:11:309 [VERBOSE] Launching connection (SSH)...
2023/04/28 10:37:11:309 [VERBOSE] Connecting to SSH...
2023/04/28 10:37:11:309 [VERBOSE] Launching connection with block...
2023/04/28 10:37:11:310 [VERBOSE] Won't dismiss prompt because no one is displayed.
2023/04/28 10:37:11:323 [DEBUG] No SOCKS Tunnel launched. SSH connection will be established without any SOCKS hostname.
2023/04/28 10:37:13:000 [DEBUG] Connected to : 15.188.207.57
2023/04/28 10:37:13:004 [DEBUG] Authentication using login/privatekey
2023/04/28 10:37:13:235 [VERBOSE] <SSHLog>
  <AuthenticatePk>
    <SSHVersion>9.5.0.91</SSHVersion>
    <SshVersion>SSH-2.0-OpenSSH_8.7</SshVersion>
    <sshAuthenticatePk>
      <keyFingerprint>ssh-rsa 2048 b1:da:41:81:cc:6d:13:5c:ad:99:fe:46:1b:c9:af:93</keyFingerprint>
      <requestUserAuthService>
        <sendServiceRequest>
          <svcName>ssh-userauth</svcName>
          <SentServiceReq>ssh-userauth</SentServiceReq>
        </sendServiceRequest>
      </requestUserAuthService>
      <AuthList>publickey,gssapi-keyex,gssapi-with-mic</AuthList>
      <rsaSigLen>256</rsaSigLen>
      <error>Authentication failed or partial success. (4)</error>
      <PartialSuccess4>0</PartialSuccess4>
      <error>When partial success is 0, it means you are NOT using the correct private key that corresponds to the public key installed in the SSH user account.</error>
      <error>(less common) It can also mean that SSH tried to use rsa-sha2-256 for the authentication, because the server indicated it supports rsa-sha2-256, but does not actually support it for PK authentication.</error>
      <error>A workaround is to set the UncommonOptions property equal to "ForceUserAuthRsaSha1" and then re-try.</error>
      <AuthList>publickey,gssapi-keyex,gssapi-with-mic</AuthList>
      <error>Publickey authentication failed..</error>
    </sshAuthenticatePk>
    <error>Failed.</error>
  </AuthenticatePk>
</SSHLog>
2023/04/28 10:37:13:342 [DEBUG] Dismissing prompt...
2023/04/28 10:37:13:756 [VERBOSE] <SSHLog>
  <Connect_Ssh>
    <SSHVersion>9.5.0.91</SSHVersion>
    <connectInner>
      <hostname>13.38.108.239</hostname>
      <port>22</port>
      <sshConnect>
        <connectSocket>
          <connect_ipv6_or_ipv4>
            <error>timeout waiting for connect to complete;</error>
            <timeoutMs>15000</timeoutMs>
            <failedWaitToConnect>Socket operation timeout.</failedWaitToConnect>
          </connect_ipv6_or_ipv4>
        </connectSocket>
        <error>Failed to establish initial TCP/IP connection</error>
        <hostname>13.38.108.239</hostname>
        <port>22</port>
      </sshConnect>
    </connectInner>
    <error>Failed.</error>
  </Connect_Ssh>
</SSHLog>
2023/04/28 10:37:18:298 [DEBUG] Fetching from iCloud with a change token
2023/04/28 10:37:18:725 [DEBUG] iCloud data fetched with success.
2023/04/28 10:37:33:299 [DEBUG] Fetching from iCloud with a change token
2023/04/28 10:37:33:720 [DEBUG] iCloud data fetched with success.
2023/04/28 10:37:45:571 [DEBUG] No custom SSH Config File will overwrite this connection settings
2023/04/28 10:37:45:572 [VERBOSE] Want to connect with a Private Key
2023/04/28 10:37:45:572 [VERBOSE] Private Key is not encrypted because we can load it without any passphrase.
2023/04/28 10:37:45:572 [DEBUG] Private Key is encrypted : 0
2023/04/28 10:37:45:572 [VERBOSE] Load Private Key in OpenSSH Format
2023/04/28 10:37:45:572 [VERBOSE] Launching connection (SSH)...
2023/04/28 10:37:45:572 [VERBOSE] Connecting to SSH...
2023/04/28 10:37:45:572 [VERBOSE] Launching connection with block...
2023/04/28 10:37:45:574 [VERBOSE] Won't dismiss prompt because no one is displayed.
2023/04/28 10:37:45:587 [DEBUG] No SOCKS Tunnel launched. SSH connection will be established without any SOCKS hostname.
2023/04/28 10:37:46:038 [DEBUG] Connected to : 15.188.207.57
2023/04/28 10:37:46:042 [DEBUG] Authentication using login/privatekey
2023/04/28 10:37:46:275 [VERBOSE] <SSHLog>
  <AuthenticatePk>
    <SSHVersion>9.5.0.91</SSHVersion>
    <SshVersion>SSH-2.0-OpenSSH_8.7</SshVersion>
    <sshAuthenticatePk>
      <keyFingerprint>ssh-rsa 2048 b1:da:41:81:cc:6d:13:5c:ad:99:fe:46:1b:c9:af:93</keyFingerprint>
      <requestUserAuthService>
        <sendServiceRequest>
          <svcName>ssh-userauth</svcName>
          <SentServiceReq>ssh-userauth</SentServiceReq>
        </sendServiceRequest>
      </requestUserAuthService>
      <AuthList>publickey,gssapi-keyex,gssapi-with-mic</AuthList>
      <rsaSigLen>256</rsaSigLen>
      <error>Authentication failed or partial success. (4)</error>
      <PartialSuccess4>0</PartialSuccess4>
      <error>When partial success is 0, it means you are NOT using the correct private key that corresponds to the public key installed in the SSH user account.</error>
      <error>(less common) It can also mean that SSH tried to use rsa-sha2-256 for the authentication, because the server indicated it supports rsa-sha2-256, but does not actually support it for PK authentication.</error>
      <error>A workaround is to set the UncommonOptions property equal to "ForceUserAuthRsaSha1" and then re-try.</error>
      <AuthList>publickey,gssapi-keyex,gssapi-with-mic</AuthList>
      <error>Publickey authentication failed..</error>
    </sshAuthenticatePk>
    <error>Failed.</error>
  </AuthenticatePk>
</SSHLog>
2023/04/28 10:37:46:382 [DEBUG] Dismissing prompt...
2023/04/28 10:37:48:300 [DEBUG] Fetching from iCloud with a change token
2023/04/28 10:37:48:720 [DEBUG] iCloud data fetched with success.
2023/04/28 10:37:51:985 [INFO] Opening embedded browser on : https://webssh.net/support/?ts=1682671071
2023/04/28 10:38:03:301 [DEBUG] Fetching from iCloud with a change token
2023/04/28 10:38:03:761 [DEBUG] iCloud data fetched with success.
2023/04/28 10:38:04:160 [VERBOSE] IAP already purchased (iCloud) : com.webssh.pro.unlimited
2023/04/28 10:38:11:838 [DEBUG] No custom SSH Config File will overwrite this connection settings
2023/04/28 10:38:11:838 [VERBOSE] Want to connect with a Private Key
2023/04/28 10:38:11:838 [VERBOSE] Private Key is not encrypted because we can load it without any passphrase.
2023/04/28 10:38:11:838 [DEBUG] Private Key is encrypted : 0
2023/04/28 10:38:11:838 [VERBOSE] Load Private Key in OpenSSH Format
2023/04/28 10:38:11:838 [VERBOSE] Launching connection (SSH)...
2023/04/28 10:38:11:839 [VERBOSE] Connecting to SSH...
2023/04/28 10:38:11:839 [VERBOSE] Launching connection with block...
2023/04/28 10:38:11:840 [VERBOSE] Won't dismiss prompt because no one is displayed.
2023/04/28 10:38:11:852 [DEBUG] No SOCKS Tunnel launched. SSH connection will be established without any SOCKS hostname.
2023/04/28 10:38:12:137 [DEBUG] Connected to : 15.188.207.57
2023/04/28 10:38:12:140 [DEBUG] Authentication using login/privatekey
2023/04/28 10:38:12:368 [VERBOSE] <SSHLog>
  <AuthenticatePk>
    <SSHVersion>9.5.0.91</SSHVersion>
    <SshVersion>SSH-2.0-OpenSSH_8.7</SshVersion>
    <sshAuthenticatePk>
      <keyFingerprint>ssh-rsa 2048 b1:da:41:81:cc:6d:13:5c:ad:99:fe:46:1b:c9:af:93</keyFingerprint>
      <requestUserAuthService>
        <sendServiceRequest>
          <svcName>ssh-userauth</svcName>
          <SentServiceReq>ssh-userauth</SentServiceReq>
        </sendServiceRequest>
      </requestUserAuthService>
      <AuthList>publickey,gssapi-keyex,gssapi-with-mic</AuthList>
      <rsaSigLen>256</rsaSigLen>
      <error>Authentication failed or partial success. (4)</error>
      <PartialSuccess4>0</PartialSuccess4>
      <error>When partial success is 0, it means you are NOT using the correct private key that corresponds to the public key installed in the SSH user account.</error>
      <error>(less common) It can also mean that SSH tried to use rsa-sha2-256 for the authentication, because the server indicated it supports rsa-sha2-256, but does not actually support it for PK authentication.</error>
      <error>A workaround is to set the UncommonOptions property equal to "ForceUserAuthRsaSha1" and then re-try.</error>
      <AuthList>publickey,gssapi-keyex,gssapi-with-mic</AuthList>
      <error>Publickey authentication failed..</error>
    </sshAuthenticatePk>
    <error>Failed.</error>
  </AuthenticatePk>
</SSHLog>
2023/04/28 10:38:12:474 [DEBUG] Dismissing prompt...
2023/04/28 10:38:18:302 [DEBUG] Fetching from iCloud with a change token
2023/04/28 10:38:18:701 [DEBUG] iCloud data fetched with success.
2023/04/28 10:38:26:370 [DEBUG] Application will resign active
2023/04/28 10:40:06:679 [DEBUG] Fetching from iCloud with a change token
2023/04/28 10:40:06:987 [DEBUG] Application did become active
2023/04/28 10:40:06:994 [DEBUG] No pin code set. WebSSH won't be locked.
2023/04/28 10:40:07:139 [DEBUG] iCloud data fetched with success.
2023/04/28 10:40:08:572 [VERBOSE] IAP already purchased (iCloud) : com.webssh.pro.unlimited
2023/04/28 10:40:09:968 [DEBUG] Application will resign active

**Comment by isontheline** [comment]
Thank you @qwertmax 🙏

I will try to reproduce tonight and will come back to you

**Comment by isontheline** [comment]
Which Linux Distribution are you using with `OpenSSH_8.7p1, OpenSSL 3.0.8 7 Feb 2023`?

**Comment by qwertmax** [comment]
Amazon Linux 2

**Comment by isontheline** [comment]
Thank you @qwertmax 🙏

I'm trying to reproduce on my side with the same OpenSSH version.
I will come back to you asap.

**Comment by qwertmax** [comment]
@isontheline Did you replicate this issue ?

**Comment by isontheline** [comment]
@qwertmax Not yet sorry
I was busy these last days

But be sure, I didn't have forget you

I'm doing my best to come back to you in a timely manner

**Comment by isontheline** [comment]
I'm able to connect :


![Image](https://user-images.githubusercontent.com/44212923/236924441-fdaebb64-77b7-4edb-a452-c5ef5c44ed1f.png)

**Comment by qwertmax** [comment]
Did you use pem key for auth ? @isontheline

**Comment by isontheline** [comment]
@qwertmax Yes ssh-rsa one in PEM format :
<img width="376" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/664fd8ac-1994-4ad1-864f-edb08eeca876">

**Comment by isontheline** [comment]
@qwertmax Could you try to generate a new Private / Public Key and publish it on your server?

**Comment by qwertmax** [comment]
@isontheline generated and added new SSH key, added id_rda PK to iOS app, but still asking password when I'm trying to connect to machine.

**Comment by qwertmax** [comment]
@qwertmax where can I download that version ?

**Comment by qwertmax** [comment]
@isontheline where can I download that version ?

**Comment by isontheline** [comment]
@qwertmax 
https://testflight.apple.com/join/QSrBK59z

**Comment by qwertmax** [comment]
@isontheline tested, same issue, I have popup with password input.

**Comment by qwertmax** [comment]
@isontheline 
`2023/05/16 14:32:25:469 [INFO] Thank you so much for using WebSSH 22.0.1086
2023/05/16 14:32:25:469 [DEBUG] WebSSH Setting Log Level : VERBOSE
2023/05/16 14:32:25:469 [INFO] Launching Data Migration...
2023/05/16 14:32:25:469 [INFO] Checking if settings need to be migrated...
2023/05/16 14:32:25:472 [INFO] Data Migration Done!
2023/05/16 14:32:25:472 [DEBUG] Launch_APP_Count_22.0 : 3
2023/05/16 14:32:25:472 [DEBUG] Launch_APP_Count : 33
2023/05/16 14:32:25:472 [DEBUG] Launching Vacuum on the local database...
2023/05/16 14:32:25:473 [DEBUG] 0 objects have been vacuumed
2023/05/16 14:32:25:479 [VERBOSE] Performing vacuum on old deleted iCloud objects...
2023/05/16 14:32:25:499 [DEBUG] Device language : en
2023/05/16 14:32:25:499 [INFO] Language bundle is not loaded. Will load this bundle : en
2023/05/16 14:32:25:523 [INFO] WebSSH should be locked after delay (secs) : 60
2023/05/16 14:32:25:675 [DEBUG] Application did become active
2023/05/16 14:32:25:677 [DEBUG] No pin code set. WebSSH won't be locked.
2023/05/16 14:32:25:945 [VERBOSE] No objects to be vacuumed on iCloud.
2023/05/16 14:32:26:479 [DEBUG] Fetching from iCloud with a change token
2023/05/16 14:32:26:830 [DEBUG] iCloud data fetched with success.
2023/05/16 14:32:30:702 [DEBUG] No custom SSH Config File will overwrite this connection settings
2023/05/16 14:32:30:702 [VERBOSE] Want to connect with a Private Key
2023/05/16 14:32:30:705 [VERBOSE] Private Key is not encrypted because we can load it without any passphrase.
2023/05/16 14:32:30:705 [DEBUG] Private Key is encrypted : 0
2023/05/16 14:32:30:705 [VERBOSE] Load Private Key in OpenSSH Format
2023/05/16 14:32:30:706 [VERBOSE] Launching connection (SSH)...
2023/05/16 14:32:30:706 [VERBOSE] Connecting to SSH...
2023/05/16 14:32:30:706 [VERBOSE] Launching connection with block...
2023/05/16 14:32:30:707 [VERBOSE] Won't dismiss prompt because no one is displayed.
2023/05/16 14:32:30:722 [INFO] IP Strategy is set to 'ipv4'. Does IPv6 is prefered over IPv4? => 0
2023/05/16 14:32:30:722 [DEBUG] No SOCKS Tunnel launched. SSH connection will be established without any SOCKS hostname.
2023/05/16 14:32:30:936 [DEBUG] Connected to : 13.38.250.251
2023/05/16 14:32:30:940 [DEBUG] Authentication using login/privatekey
2023/05/16 14:32:31:116 [DEBUG] Authentication has failed
2023/05/16 14:32:31:120 [VERBOSE] <SSHLog>
  <AuthenticatePk>
    <SSHVersion>9.5.0.94</SSHVersion>
    <UnlockStatus>2</UnlockStatus>
    <SshVersion>SSH-2.0-OpenSSH_8.7</SshVersion>
    <sshAuthenticatePk>
      <keyFingerprint>ssh-rsa 3072 02:66:3d:df:e3:8f:d4:92:01:7b:46:0a:b0:aa:13:14</keyFingerprint>
      <requestUserAuthService>
        <sendServiceRequest>
          <svcName>ssh-userauth</svcName>
          <SentServiceReq>ssh-userauth</SentServiceReq>
        </sendServiceRequest>
      </requestUserAuthService>
      <AuthList>publickey,gssapi-keyex,gssapi-with-mic</AuthList>
      <rsaSigLen>384</rsaSigLen>
      <hostKeyAlg>3</hostKeyAlg>
      <error>Authentication failed or partial success. (4)</error>
      <PartialSuccess4>0</PartialSuccess4>
      <error>When partial success is 0, it means you are not using the correct private key that corresponds to the public key installed in the SSH user account.</error>
      <error>(less common) It can also mean that SSH tried to use rsa-sha2-256 for the authentication, because the server indicated it supports rsa-sha2-256, but does not actually support it for PK authentication.</error>
      <error>A workaround is to set the UncommonOptions property equal to "ForceUserAuthRsaSha1" and then re-try.</error>
      <error>Also, to force SSH to continue with password authentication even if the public-key authentication fails, set UncommonOptions = "PubkeyOrPassword".</error>
      <AuthList>publickey,gssapi-keyex,gssapi-with-mic</AuthList>
      <error>Publickey authentication failed..</error>
    </sshAuthenticatePk>
    <error>Failed.</error>
  </AuthenticatePk>
</SSHLog>
2023/05/16 14:32:31:227 [DEBUG] Dismissing prompt...
2023/05/16 14:32:37:443 [DEBUG] Application will resign active
`

**Comment by isontheline** [comment]
@qwertmax Have you tried to generate an ED25519 private key from WebSSH?

**Comment by qwertmax** [comment]
@isontheline no, I didn’t try it. Should I ?

**Comment by isontheline** [comment]
@qwertmax If you have some time, yes please

**Comment by qwertmax** [comment]
@isontheline tried - working.

**Comment by isontheline** [comment]
@isontheline So your server want to exclude RSA keys (because now weak) and WebSSH doesn't enforce it
I think

**Comment by qwertmax** [comment]
@isontheline but from laptop I can connect via RSA.

**Comment by isontheline** [comment]
From terminal app not WebSSH ?

**Comment by qwertmax** [comment]
@isontheline yes from terminal. Not from WebSSH.

**Comment by isontheline** [comment]
> The RSA SHA-1 hash algorithm is being quickly deprecated across operating systems and SSH clients because of various security vulnerabilities, with many of these technologies now outright denying the use of this algorithm.

https://askubuntu.com/a/1409528
