### ISSUE TITLE
New copy Paste on iOS will drop spaces

### ISSUE THREAD

**Issue by MrFly72** [isontheline/pro.webssh.net#896]
# Bug description
If you select text which has spaces inside, the spaces are missing when pasted into the same window.

# Screenshots
https://github.com/isontheline/pro.webssh.net/assets/65505278/f6a6743d-394b-4265-b810-1d930b731616

# Steps to reproduce
1. copy text from the same screen
2. paste

**Comment by isontheline** [comment]
Ouch 😢

OK will be fixed in the upcoming minor release.

Thank you so much for your feedback @MrFly72 🙏

**Comment by isontheline** [comment]
WebSSH 22.1.1098 is now available : https://testflight.apple.com/join/QSrBK59z
