### ISSUE TITLE
Changing fontsize

### ISSUE THREAD

**Issue by mare333** [isontheline/pro.webssh.net#897]
# Bug description
Changing the fontsize doesn't work. Neither cmd+/- nor menu. On MacOS.

# Steps to reproduce
1. cmd-+ or cmd--.
2. Menu Darstellung-Vergrößern/Verkleinern
3. No Error is thrown

**Comment by isontheline** [comment]
Hello @mare333 👋

Thank you a lot for your feedback 🙏

I'm checking the trouble and will come back to you shortly.

**Comment by isontheline** [comment]
A fix will be available in a few hours on the testflight beta release : https://testflight.apple.com/join/QSrBK59z

**Comment by mare333** [comment]
Version 22.1 (1095)? Still not working.

**Comment by isontheline** [comment]
<img width="262" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/bbd10874-373e-4559-b470-58905e2aff7f">

**Comment by mare333** [comment]
Ok. Sorry. Too fast.

**Comment by mare333** [comment]
After testing Build 1096: Changing the fontsize acts different to previous versions. The fontsize doesn't change, only the space between the characters differs.

**Comment by isontheline** [comment]
You're right I'm fixing it.
Sorry for the mistake

**Comment by isontheline** [comment]
Related to https://github.com/xtermjs/xterm.js/issues/4474
I'm fixing it with the patch provided

**Comment by isontheline** [comment]
WebSSH 22.1.1098 is now available : https://testflight.apple.com/join/QSrBK59z

**Comment by mare333** [comment]
Now it works fine. Thank you very much.

**Comment by isontheline** [comment]
You're Welcome @mare333
