### ISSUE TITLE
Minor UI issue with arrow button

### ISSUE THREAD

**Issue by Prodigio** [isontheline/pro.webssh.net#902]
# Bug description
Minor UI issue of arrow button on iOS 16.5. Corners look different, not rounded.

# Screenshots
![image](https://github.com/isontheline/pro.webssh.net/assets/18284425/dcd50d6f-1381-4365-a99d-197941e72806)

# Steps to reproduce
Open the terminal view to see keyboard.

**Comment by isontheline** [comment]
Hello @Prodigio 👋

Thank you so much for your feedback 🙏

I've just updated to 16.6 but I didn't understand your UI issue.

Could you explain me further?

Have a nice day ☀️

**Comment by isontheline** [comment]
I now see on your screenshot what you are referring about, thank you @Prodigio  🙏

I will reproduce and this it in the next minor release.

**Comment by isontheline** [comment]
Hello @Prodigio 👋

Could you please try WebSSH 22.3.1111 ?
https://testflight.apple.com/join/QSrBK59z
