### ISSUE TITLE
iOS / iPadOS : Make the Menu bar/Header automatically hide

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#904]
# Feature description

> Hey! Great works! Webssh is by far the best ssh client on iOS I have tried. But I want to share some improvement ideas with you.
> 
> 3. Make the Menu bar/Header automatically hide. Screen space is precarious on mobile device. It will give me more space if I can toggle the header.
> 
>  Thanks you!

**Comment by AInteriorB** [comment]
like #630 ;)

**Comment by isontheline** [comment]
Thank you so much @AInteriorB 🙏
