### ISSUE TITLE
SSH Cloud Syncing not working

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#911]
# Bug description
I added an SSH connection on my iPad and it is not showing up on my macOS device. I also added a connection on the mac side and it didn't sync to iPad. I tried toggling the Cloud setting on and off on both to get a refresh going. 

# Screenshots

# Steps to reproduce
1. Add SSH to iPad
2. Go to macOS and try to open the connection
4. Connection doesn't exist.

**Comment by isontheline** [comment]
I've tried on my own and it seems to work.

Could you check that you are running the same flavour (App Store / TestFlight) on both devices?

If it's same flavour, please post verbose logs for both devices.

Thank you.

**Comment by mbierman** [comment]
All devices are using the latest. Which logs do you need?

**Comment by mbierman** [comment]
ping @isontheline

**Comment by isontheline** [comment]
The WebSSH logs please :

# iOS
1. iOS Settings
2. WebSSH
3. Settings
4. Log Level > Verbose
5. Restart WebSSH
6. Reproduce your action
7. Find the log files inside iOS > Files > WebSSH

# macOS
1. Launch WebSSH
2. WebSSH menu (top bar)
3. Settings
4. Log Level > Verbose
5. Restart WebSSH
6. Reproduce your action
7. Launch mashREPL (inside WebSSH)
8. Type `pwd`
9. Go to the folder printed
10. Find WebSSH logs there

I'm looking for errors inside the logs

**Comment by mbierman** [comment]
[ipad.txt](https://github.com/isontheline/pro.webssh.net/files/11715786/ipad.txt)
What setting is it talking about?

**Comment by isontheline** [comment]
`71DCFA31C955 to local database
2023/06/11 14:37:49:455 [WARN] Unable to save record zone : <CKError 0x282057a50: "Not Authenticated" (9/1002); "CloudKit access was denied by user settings">`

In your iOS settings > iCloud > Allow WebSSH to use the iCloud storage

**Comment by mbierman** [comment]
@isontheline Actually it is not working on my mac. I have checked macOS > System Settings > [Name] > iCloud > iCloud Drive > Apps syncing > webSSH is on and iCloud Drive is active. 

In WebSSH > Settings > Enable iCloud is on.

**Comment by isontheline** [comment]
@mbierman Could you extract the error log as you did it on your iPad?

**Comment by mbierman** [comment]
So the "action" is Connections aren't syncing. Opening it I get the following: 

```
michaels:Documents michaelbierman$ cat log-385ED3.txt 
2023/06/13 17:10:59:808 [INFO] Thank you so much for using WebSSH 22.3.1112
2023/06/13 17:10:59:810 [DEBUG] WebSSH Setting Log Level : VERBOSE
2023/06/13 17:10:59:810 [INFO] Launching Data Migration...
2023/06/13 17:10:59:810 [INFO] Checking if settings need to be migrated...
2023/06/13 17:10:59:836 [INFO] Data Migration Done!
2023/06/13 17:10:59:838 [DEBUG] Launch_APP_Count_22.3 : 9
2023/06/13 17:10:59:839 [DEBUG] Launch_APP_Count : 101
2023/06/13 17:10:59:839 [DEBUG] Launching Vacuum on the local database...
2023/06/13 17:10:59:840 [DEBUG] 0 objects have been vacuumed
2023/06/13 17:10:59:867 [VERBOSE] Performing vacuum on old deleted iCloud objects...
2023/06/13 17:11:00:384 [DEBUG] Application did become active
2023/06/13 17:11:00:387 [DEBUG] WebSSH scenes must be locked
2023/06/13 17:11:00:387 [VERBOSE] Received scene lock notification
2023/06/13 17:11:00:494 [DEBUG] Device language : en
2023/06/13 17:11:00:494 [INFO] Language bundle is not loaded. Will load this bundle : en
2023/06/13 17:11:00:615 [VERBOSE] No objects to be vacuumed on iCloud.
2023/06/13 17:11:00:788 [INFO] WebSSH should be locked after delay (secs) : 600
2023/06/13 17:11:00:855 [DEBUG] Fetching from iCloud with a change token
2023/06/13 17:11:01:381 [DEBUG] iCloud data fetched with success.
2023/06/13 17:11:03:072 [VERBOSE] Received scene lock notification
```
