### ISSUE TITLE
"Can you still not support bastion host login?"

### ISSUE THREAD

**Issue by jaychoubaby** [isontheline/pro.webssh.net#914]
"I want to know why bastion host login cannot be achieved due to what reasons?"

**Comment by isontheline** [comment]
Jump hosting is already planned here : https://github.com/isontheline/pro.webssh.net/issues/577

You can however use a workaround before this feature is implemented : launch a dynamic port forwarding inside WebSSH -> https://webssh.net/documentation/help/networking/dynamic-port-forwarding/
