### ISSUE TITLE
SSH Cloud Syncing still not working with iCloud enabled

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#916]
# Bug description
[bug 911](https://github.com/isontheline/pro.webssh.net/issues/911) is not resolved.

Apps using iCloud includes WebSSH.

# Screenshots
![IMG_5543](https://github.com/isontheline/pro.webssh.net/assets/1205471/c4fc0a16-571d-4a9a-b4e5-67d7669bac19)

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by mbierman** [comment]
Yes, there are too many places to look in iOS settings which have gotten a bit out of hand. Thank you.

**Comment by mbierman** [comment]
@isontheline sorry I am still having trouble with the mac side afterall. iCloud seems to be enabled—what am I missing?

**Comment by mbierman** [comment]
@isontheline looks like that did it! Thank you. 🙏🏻

**Comment by isontheline** [comment]
Thanks for your feedback @mbierman 🙏
