### ISSUE TITLE
Automatically send ‘q’ when exiting terminal

### ISSUE THREAD

**Issue by jedis00** [isontheline/pro.webssh.net#918]
# Feature description
Please add a configurable option to automatically send ‘q’ when exiting terminal to exit back to connection list. I never need to reconnect and if I did, I’d simply tap the connection again at the main list.

**Comment by isontheline** [comment]
Hello @jedis00 👋

Already there :
<img width="401" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/6cb89c36-8fcd-48e1-9580-5334a8b508d9">

Could give it a try?

**Comment by jedis00** [comment]
@isontheline Thanks, that worked! What is the difference between those settings in the app vs when it opens the Settings in the system settings app? It's odd to have to go in two places.

To make these settings in the app easier to find, can you add a right caret > at the end of the row on the right, to mirror how iOS does additional menu options?

**Comment by isontheline** [comment]
> What is the difference between those settings in the app vs when it opens the Settings in the system settings app? It's odd to have to go in two places.

I'm migrating these old settings into the iOS' settings place. These are the last to migrate.
Sorry for the trouble :/

> To make these settings in the app easier to find, can you add a right caret > at the end of the row on the right, to mirror how iOS does additional menu options?

I will remove them so them won't hurt anymore
