### ISSUE TITLE
Connection locks up

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#922]
# Bug description
Similar to 777, if I navigate away (e.g. a different space on macOS) I cannot use the open terminal connection in webssh. This makes it very difficult to use WebSSH in any practical way. 

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by isontheline** [comment]
Michael I need more information to fix troubles you are encountering.

By « locks up » what do you mean?

Do you have any logs filled by errors?

**Comment by mbierman** [comment]
So if I'm in a session and I go to another space to work and come back the session will take no input for a long time, if ever. 

Since Spaces are a critical part of daily workflow this makes WebSSH difficult to use and in hoping it can be fixed. 

I will grab some logs when I'm back at one of my macs.

**Comment by isontheline** [comment]
Thank you Michael.

If the trouble comes again -> please try to reload the rendering engine by using Cmd + R or :
<img width="462" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/818def14-15d0-4602-9112-f9253c347937">

I would like to find if all WebSSH is locked or only the rendering engine.

**Comment by mbierman** [comment]
I will definitely try to reprise and see if that solves the issue! Thank you.

**Comment by isontheline** [comment]
@mbierman Feel free to reopen this issue if needed
