### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by jonasinberlin** [isontheline/pro.webssh.net#923]
I am not able to open keyboard after touching screen for scroll. 
can’t edit file’s at this way.

**Comment by isontheline** [comment]
Which version are you using?

**Comment by jonasinberlin** [comment]
Hi
Thanks for the fast response 
I use 22.2.1101 on iPhone 7plus
It worked earlier but now I’m not able to open the keyboard with touching the screen anymore.

**Comment by isontheline** [comment]
Thanks @jonasinberlin 🙏

Please upgrade WebSSH to 22.3 on the App Store

A new button keyboard is now at top

**Comment by jonasinberlin** [comment]
Thank you very much, that solved the problem. 
I’m so thankful for this great app. 
I’m using the app every day and I love the snippets. 
Thanks 
Jonas

**Comment by isontheline** [comment]
You're welcome Jonas 

Thank you so much for your strong support about WebSSH 🙏
I hope you will enjoy the upcoming releases.

Have a nice day ☀️
