### ISSUE TITLE
no background app refresh (ssh local port forwarding problem)

### ISSUE THREAD

**Issue by urosch** [isontheline/pro.webssh.net#924]
The ssh tunnel (with LPF) only works when Webssh app is side by side with Safari (webssh app in foreground). I'm forwarding some port to remote server for security reasons and for testing of a certain webapp.
After the Webssh app goes to background the tunnel is instantly nonfunctional.
I have a video of this that I can share with you somewhere if you need me to, but there is a size limit here.

In the screenshot you will see that Webssh app has no Background refresh as compared with Termius app for example. The tunnel in Termius stays open no matter where the app is  (foreground or background).

I also tried Webssh vpn port f. option.
The vpn port forwarding option is not a good alternative as there is only one port limitation and I believe the ssh tunnel can be fixed by enabling / adding the background app refresh option.
 
![IMG_7481](https://github.com/isontheline/pro.webssh.net/assets/15800755/f6a5181c-817e-4fbf-a618-b5d21ce0e2ee)

Thanks for your efforts and thank you for your help!

**Comment by isontheline** [comment]
Hello @urosch 👋

> The vpn port forwarding option is not a good alternative as there is only one port limitation

You can setup multiple ports on the same tunnel

> I believe the ssh tunnel can be fixed by enabling / adding the background app refresh option.

I'm sorry, background app refresh can't be used for this.
Background app refresh is triggered by the operating system when it want to be.

Termius doesn't use BAR to persist connections => they use your GPS location to do so

**Comment by urosch** [comment]
thank you @isontheline for the quick reply! 
I read your Documentation for VPN that said ”One drawback of VPN-Over-SSH is that only one port forwarding connection could be launched at a time” and thought ther was a limit on number of connections...

That makes this feature very useful. I much much rather use vpn config than some app using gps location tracking feature for this.
Have a nice day/night!

**Comment by isontheline** [comment]
Thank you @urosch for your feedback 🙏

Don't hesitate to come back to me if you notice any trouble or bug around the port forwarding.
