### ISSUE TITLE
Snippets code text always dark blue even in dark mode

### ISSUE THREAD

**Issue by RichardBurt65** [isontheline/pro.webssh.net#925]
The icons in WebSSH always takes the colour from System Settings -> Appearance -> Accent Colour. I'm quite happy with this as it makes things easier to see when the Mac is in dark mode.

Unfortunately the online indicator also takes the colour from Accent Colour so setting Accent Colour to red makes everything appear to be offline when they are not. 

The text for code in Snippets is always dark blue which is difficult to read when there is a dark background. 

Can the snippet text colour be set to follow the Accent colour AND set the offline / online indicator to NOT follow Accent Colour (ie hardcode for red / green only)?

(Sorry, two issues rather than one).

**Comment by isontheline** [comment]
Good catch!

I'm planing it for the next minor release 👍

**Comment by isontheline** [comment]
Hello @RichardBurt65 👋

It's now available on the latest beta release : https://testflight.apple.com/join/QSrBK59z
