### ISSUE TITLE
Provide support for Meta-key 

### ISSUE THREAD

**Issue by nutilius** [isontheline/pro.webssh.net#939]
# Feature description
Many programs in Unix use the Meta key, which is mapped mostly as Alt key in PC or Option key in Mac. For example Emacs editor and emacs mode in bash/zsh use Meta in may shortcuts. On iPad with external keyboard, WebSSH don't provide such functionality and working with emacs is very hard.  Meta is simulated by pressing Esc (on the screen) and key (on the keyboard).

**Comment by isontheline** [comment]
Meta should already works on supported keyboards.

Which keyboard are you using on your iPad?

**Comment by nutilius** [comment]
I use Logitech ComboTouch. I've checked - doesn't work.

**Comment by isontheline** [comment]
> Meta is simulated by pressing Esc (on the screen) and key (on the keyboard).

Does it's a workaround you are currently using on WebSSH?

On other apps which combo-keys are you using to emulate the Meta key under your Logitech keyboard?

Thank you so much for your feedback 🙏

**Comment by nutilius** [comment]
I use also LaTerminal app, where Option key works as Meta.
In WebSSH Option selects Internional characters (even in US keyboard layout). The ideal world - Left Option - standard Meta, Right Option - select international character. But I'm not sure is it possible in apps like WebSSH (with JavaScript engine embedded).

**Comment by isontheline** [comment]
Thanks for your feedback, I will try some improvement as soon as possible

I'm coming back to you

**Comment by isontheline** [comment]
@nutilius On your keyboard please press both ctrl + alt when wanting an "alt" :


![Image](https://github.com/isontheline/pro.webssh.net/assets/44212923/8ef67493-fa2f-46d8-92ea-4b72715b834f)
