### ISSUE TITLE
ssh-ed25519

### ISSUE THREAD

**Issue by abirfo1** [isontheline/pro.webssh.net#940]
# Bug description
_Put here a clear and concise description of what the bug is_

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by isontheline** [comment]
Hello @abirfo1  👋 
Thanks for your issue! 
But...

Please edit your issue description to better describe your encountering trouble.

Have a nice day ☀️
