### ISSUE TITLE
Sidebar shows "SFTP" instead of the connection name

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#943]
# Bug description
<img width="835" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/44212923/779e6b38-10b9-4e14-92cb-c0cad944772a">

> I like the app very much. It's just funny that SSH shows which server to connect to and SFTP only says "SFTP". Otherwise well done.

**Comment by isontheline** [comment]
Will be available in the upcoming beta release

**Comment by Stl31** [comment]
I'm trying to use the app on my phone but it's not working

**Comment by isontheline** [comment]
@Stl31 This issue is related to iPad and Mac
