### ISSUE TITLE
IPv6 : Unable to show host availability

### ISSUE THREAD

**Issue by DorianCoding** [isontheline/pro.webssh.net#945]
# Bug description
_Put here a clear and concise description of what the bug is_
Hello,

I always get a red flag when connecting to my servers whereas the connection is possible. I don’t if it is a ping or something that may be blocked by the server?
# Screenshots
_If applicable, add screenshots to help explain your problem_
![IMG_5819](https://github.com/isontheline/pro.webssh.net/assets/108593662/e57d7975-0c5d-4327-b35f-e4caffd14808)

# Steps to reproduce
1. Try to connect to a server
2. Error is thrown

**Comment by isontheline** [comment]
Thanks for your feedback @DorianCoding 🙏

Availability is done yet by checking the SSH port is opened or not. Ping availability checkup is not yet implemented.

Red flag but connecting is possible or not at all?
If not : could you post the root cause from the logs?

**Comment by DorianCoding** [comment]
> Availability is done yet by checking the SSH port is opened or not. Ping availability checkup is not yet implemented.



> Availability is done yet by checking the SSH port is opened or not. Ping availability checkup is not yet implemented.
> 
> Red flag but connecting is possible or not at all?

Yes connection is perfectly possible, this is why I am kinda skeptical as the port is definitely open and there is no port knocking.

**Comment by isontheline** [comment]
Thanks @DorianCoding 

Any firewall or application filter on the server side?

On your computer what about : 
`nmap -p22 yourhost`

If 22 is your port

**Comment by isontheline** [comment]
Good spot @DorianCoding !

You seems right about IPv4/6 I think I'm not doing the good job.

I will fix it so 😉

**Comment by isontheline** [comment]
Latest WebSSH beta release should fix this issue : https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
Not (yet) available :(
Build error

**Comment by isontheline** [comment]
Now ready : https://testflight.apple.com/join/QSrBK59z
