### ISSUE TITLE
Remove SFTP non-text-file warning on .json files

### ISSUE THREAD

**Issue by F0x1d** [isontheline/pro.webssh.net#957]
It's really annoying to tap "Yes" every time. Maybe just register .json as a text file extension?

Sorry, screenshot is in Russian, but i think you can understand what i'm talking about
<img width="417" alt="image" src="https://github.com/isontheline/pro.webssh.net/assets/39910552/6a9e07ad-9025-4530-8591-ccd6ce1ef1e5">

**Comment by isontheline** [comment]
Hello @F0x1d 👋

Sorry for the inconvenience, I will fix it in the next minor release.

Have a nice day ☀️

**Comment by isontheline** [comment]
Now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z

Have a nice day ☀️
