### ISSUE TITLE
Font Support P10K

### ISSUE THREAD

**Issue by g4challenge** [isontheline/pro.webssh.net#97]
For users with ZSH and themes like p10k it would be great to include compatible shell fonts like meslo, patched for fontawesome.

https://github.com/romkatv/powerlevel10k/blob/master/font.md

![IMG_126C032D9EC2-1](https://user-images.githubusercontent.com/7804472/97958481-8f8f1a00-1dad-11eb-84b0-45e1a5d2caa7.jpeg)

**Comment by isontheline** [comment]
Hello @g4challenge 👋

Thank you a lot for your issue.

I'm referencing issue #60 to track progress.

**Comment by isontheline** [comment]
I'm now working on additional font support

**Comment by isontheline** [comment]
Hello @g4challenge 👋

Please try the latest WebSSH 15.0 Beta Release : 
https://testflight.apple.com/join/QSrBK59z

P10K font have been included.

Have a nice day ☀️

**Comment by g4challenge** [comment]
Many Thanks @isontheline  - works like a charm!
![IMG_25A59F83F022-1](https://user-images.githubusercontent.com/7804472/125600339-4c9bfb45-cfc0-439b-b890-594b3cebce29.jpeg)

**Comment by isontheline** [comment]
Hello @g4challenge 👋

Happy to hear that 😉

Thank you a lot for your feedback!
