### ISSUE TITLE
Tunnel by ip forwording?

### ISSUE THREAD

**Issue by fredmo** [isontheline/pro.webssh.net#970]
Hello,
it seems to have regression :

I am able to do a connexion ssh.

When I open the tunnel with ip forwarding 
xxx:127.0.0.1:xxx it s showing « green » , 
But previously ( maybe 3 or 6 months ago ) I was able to open a vnc client on 127.0.0.1:xxx and now it s no more working.

ios 16.6
And I even rechecked by rebooting the iPhone 

Is it working on your side?

Regards

**Comment by isontheline** [comment]
Hello @fredmo 👋

Yes it's works on my side.
Does any error is thrown?
Or just you can't use the tunnel?

Moreover have you enable the VPN-Over-SSH toggle in order to use it outside WebSSH?

Have a nice day ☀️

**Comment by fredmo** [comment]
Exactly, Thank you!

by enabling « VPN over ssh » , save and retry, it s working .

**Comment by isontheline** [comment]
You're Welcome
