### ISSUE TITLE
Keeps cycling in iso update 

### ISSUE THREAD

**Issue by mark4russell** [isontheline/pro.webssh.net#971]
# Bug 
Click update on iso install ok looks good but refresh iso update and your app comes back wanting to update stoped trying after third time
mark4russell@hotmail.com if you want me to poke stuff for you

if you already know all this just ignore me hate to waste your time

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. 
2. 
3. 
4. Error is thrown

**Comment by philippelt** [comment]
Hello,

I have the same problem. I am currently on 22.4.xxx and trying to update to 23.0 seems to fail. Once the update is supposed to be done, the update button is back and the version check confirm that no update was done.

Any way to get some trace of what's happening ?

**Comment by philippelt** [comment]
Behavior has changed. Appstore app no longer propose the update but a  open button as if the upgrade has been done.

After control, the installed app is still 22.4.x where the appstore shows 23.0

**Comment by isontheline** [comment]
Perhaps an App Store issue?
Are you using the App Store or TestFlight?

**Comment by philippelt** [comment]
I just have retried now (regular upgrade using appstore) and this time the upgrade was quick and fine. I am now on 23.0.1145

May be as you said an appstore issue ! Sorry for the inconvenience

By the way, MANY THANKS for giving us the ability to manage manually display/hide of the keyboard, I found it was switching frequently in undesired way. Nice usability improvement ! 😄

**Comment by isontheline** [comment]
Thank you so much @philippelt for your feedback 🙏

Glad to hear that the App Store issue is over 😅

If you think that more improvements could be done about the keyboard doesn't hesitate to tell me.

Have a nice day ☀️
