### ISSUE TITLE
Can't hide the keyboard on iPadOS anymore

### ISSUE THREAD

**Issue by 12inchpianist** [isontheline/pro.webssh.net#973]
# Bug description
Since one of the recent releases, it's no longer possible to hide the keyboard with the button in the bottom right corner on the iPad keyboard. Pushing this button just does nothing in webSSH. 

# Screenshots

![IMG_1779](https://github.com/isontheline/pro.webssh.net/assets/13376524/e7ac2f16-a879-4ef5-8562-aeb0662d5953)

# Steps to reproduce
1. open webSSH 
2. connect to any machine via SSH
3. push the button to hide the keyboard 
4. nothing happens

**Comment by isontheline** [comment]
Hello @12inchpianist 👋

Thank you a lot for your report 🙏

I will try to make my best to revert this behaviour.

Have a nice day ☀️

**Comment by victor7376** [comment]
Has this issue been fixed as I can’t hide the keyboard even after yesterday’s update.

gr8 app btw

**Comment by isontheline** [comment]
@victor7376 Not yet fixed 'cause I was busy on other fixes. Should be soon.

> gr8 app btw

Many thanks 🙏

**Comment by isontheline** [comment]
On iOS 17 and the "Keyboard Visibility Swap Method" value set to "both" will let us to use the hide button :


![Image](https://github.com/isontheline/pro.webssh.net/assets/44212923/45c5575d-da9e-461d-991f-1d26945e5f83)

**Comment by isontheline** [comment]
But not the first time 😓

If you dismiss the keyboard by tapping on screen and then showing it again => the hide button seems to works

**Comment by isontheline** [comment]
A fix should be available in a few hours

**Comment by victor7376** [comment]
Yeh, if you tap the keyboard icon at the top it hides and shows the keyboard, but strange how the ‘hide keyboard’ just doesn’t work for me.

**Comment by isontheline** [comment]
Please try WebSSH 23.5.1172 : https://testflight.apple.com/join/QSrBK59z
