### ISSUE TITLE
How do I edit or delete an ssh connection?

### ISSUE THREAD

**Issue by ahs3** [isontheline/pro.webssh.net#98]
**How to**
_A clear and concise question about the use of any WebSSH feature. Be warned : I will refuse requests with useless questions_

**Comment by isontheline** [comment]
Hello @ahs3 👋

I've just written a how-to here :
https://webssh.net/documentation/help/howtos/edit-delete-connection/

Does it help you?

Have a nice day ☀️

**Comment by ahs3** [comment]
Perfect! That's exactly what I needed.

**Comment by isontheline** [comment]
You're Welcome
