### ISSUE TITLE
“Paste” and “paste special” in keyboard accessory view layout

### ISSUE THREAD

**Issue by necrevistonnezr** [isontheline/pro.webssh.net#986]
# Feature description
It'd be awesome if we had the possibility to have “paste” or “paste special” buttons (currently in the three-dot-menu at the top right) in the row above the keyboard, either to be configured by the user her-/himself, or as a default option.

**Comment by isontheline** [comment]
Hello @necrevistonnezr 👋

Many thanks for your feedback 🙏


If I add two new tokens to [Keyboard Accessory Vies Customisation](https://webssh.net/documentation/help/howtos/SSH/customise-keyboard-accessory-view-layout/), would it be OK for you?

For example I would implement these tokens :
* {PASTE}
* {PASTE_PASSWORD}

**Comment by isontheline** [comment]
So I'm planning it 😉

**Comment by isontheline** [comment]
Will be released in a few hours on the beta release.
I will come back to you shortly

**Comment by isontheline** [comment]
Thank you so much @necrevistonnezr for your support about my work 🙏
