### ISSUE TITLE
Keep Keyboard active on ssh reconnect

### ISSUE THREAD

**Issue by ftneek** [isontheline/pro.webssh.net#99]
**Describe the feature**
Hello, when returning to the app and reconnecting to an ssh session that was closed due to leaving the app in the background, I have to press the little keyboard icon to use a bluetooth keyboard. It would be awesome if I didn’t have to press the little keyboard icon every time when reconnecting, thanks!

**Screenshots**
![image](https://user-images.githubusercontent.com/34530420/98457021-3d951e00-2138-11eb-8bb6-b8adfd0f7b02.jpeg)

**Comment by isontheline** [comment]
Hello @ftneek 👋

Thank you a lot for your issue!

I have now planned it inside #37 

Have a nice day ☀️

**Comment by isontheline** [comment]
Hello 👋

Don't worry about this issue closing : I'm merging this issue into #37 in order to track all Virtual Keyboard Enhancements needed. I will work on it soon.

Have a nice day. ☀️

**Comment by isontheline** [comment]
Should be fixed in 14.8 (available in a few hours on TestFlight)

**Comment by isontheline** [comment]
Hello @ftneek  👋 

Could you try _WebSSH Beta_ from TestFlight app : https://testflight.apple.com/join/QSrBK59z
In order to check if your issue is fixed or not.

☀️ Have a nice day

**Comment by ftneek** [comment]
The testflight build has addressed this issue, cheers! ✅

**Comment by isontheline** [comment]
Hello @ftneek 👋

Can I add your nickname to "WebSSH Contributors" page ?

**Comment by ftneek** [comment]
Sure no problem, that would actually be pretty cool. Thanks 😁
