### ISSUE TITLE
Things that can be improved.

### ISSUE THREAD

**Issue by spenya** [isontheline/pro.webssh.net#990]
Hi! Great work. I really like it, but there a few things I think could be improved.

I don't see the point in having separate list of hosts and cloning them ... I think it would be better one hosts and enable services on it ... with specific properties if needed.

Maybe I need use to it, but I get messed with tabs, and sessions on the left pane, I don't know where some tab goes time to time, or what I have already opened. 

two sided sftp, so you can move things server to server or to local ... 

Bye, Good Job!!

**Comment by isontheline** [comment]
Hi @spenya 👋

Thank you so much for your feedback 🙏

> I don't see the point in having separate list of hosts and cloning them ... I think it would be better one hosts and enable services on it ... with specific properties if needed.

I will do on future release : https://github.com/isontheline/pro.webssh.net/issues/202

> Maybe I need use to it, but I get messed with tabs, and sessions on the left pane, I don't know where some tab goes time to time, or what I have already opened.

Could you tell me more about this statement?

> two sided sftp, so you can move things server to server or to local ...

I'm opening an issue to track your request.

Have a nice day ☀️

**Comment by nrvcnnhxtn-ctrl** [comment]
import SwiftUI

@main
struct SecureClipboardAppApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

**Comment by nrvcnnhxtn-ctrl** [comment]
import Foundation
import CryptoKit
import SwiftUI

let clipboardExpiry: TimeInterval = 300
var sessionKey = SymmetricKey(size: .bits256)
var secureClipboardStore: [String: SecureClipboardEntry] = [:]

struct SecureClipboardEntry {
    let id: String
    let encryptedData: Data
    let token: String
    let timestamp: Date
    let hmac: Data
}

func generateHMAC(data: Data, key: SymmetricKey) -> Data {
    let mac = HMAC<SHA256>.authenticationCode(for: data, using: key)
    return Data(mac)
}

func verifyHMAC(data: Data, hmac: Data, key: SymmetricKey) -> Bool {
    return HMAC<SHA256>.isValidAuthenticationCode(hmac, authenticating: data, using: key)
}

func storeClipboard(_ text: String) -> String? {
    let id = UUID().uuidString
    let token = UUID().uuidString
    let textData = Data(text.utf8)
    
    do {
        let sealedBox = try AES.GCM.seal(textData, using: sessionKey)
        let encryptedData = sealedBox.combined!
        let hmac = generateHMAC(data: encryptedData, key: sessionKey)
        
        let entry = SecureClipboardEntry(id: id, encryptedData: encryptedData, token: token, timestamp: Date(), hmac: hmac)
        secureClipboardStore[id] = entry
        return "gpt://secure_clipboard/\(id)?token=\(token)"
    } catch {
        print("AES encryption failed: \(error)")
        return nil
    }
}

func retrieveClipboard(id: String, token: String) -> String? {
    guard let entry = secureClipboardStore[id],
          entry.token == token,
          Date().timeIntervalSince(entry.timestamp) < clipboardExpiry,
          verifyHMAC(data: entry.encryptedData, hmac: entry.hmac, key: sessionKey)
    else { return nil }
    
    do {
        let sealedBox = try AES.GCM.SealedBox(combined: entry.encryptedData)
        let text = String(decoding: try AES.GCM.open(sealedBox, using: sessionKey), as: UTF8.self)
        secureClipboardStore.removeValue(forKey: id)
        return text
    } catch {
        print("AES decryption failed: \(error)")
        return nil
    }
}

// Auto-clean timer
Timer.scheduledTimer(withTimeInterval: 60, repeats: true) { _ in
    let now = Date()
    secureClipboardStore = secureClipboardStore.filter {
        now.timeIntervalSince($0.value.timestamp) < clipboardExpiry
    }
}
